### PR TITLE
fix budget view with consumable costs

### LINKED ISSUE #23496: [11.0.6] SQL Syntax Error in Budget -> Main tab (Budget::showValuesByEntity)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description
When navigating to the "Main" tab of a Budget (`front/budget.form.php`), a fatal SQL syntax error occurs. The page fails to load the financial summary. 

The issue seems to be caused by a malformed mathematical query built inside `src/Budget.php` (specifically in the `showValuesByEntity()` function around line 547). The SQL query string is missing a value (like `0`) before the first `+` sign when summing up `cost_fixed` and `cost_material` for tickets, problems, and changes.

**Error snippet:**
`MySQL query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' + \`glpi_ticketcosts\`.\`cost_fixed\` + \`glpi_ticketcosts\`.\`cost_material\`) AS \`value\`...'`

### Expected behavior
The "Main" tab should correctly display the financial summary of the budget without throwing a MariaDB syntax error.

### Logs / Stack trace
```text
MySQL query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' + `glpi_ticketcosts`.`cost_fixed` 
+ `glpi_ticketcosts`.`cost_material`) AS `value` FROM `glpi_ticketcosts` INNER JOIN `glpi_tickets`...
In ./src/DBmysql.php(416)
#0 ./src/DBmysqlIterator.php(129): DBmysql->doQuery()
#1 ./src/DBmysql.php(1088): DBmysqlIterator->execute()
#2 ./src/Budget.php(547): DBmysql->request()
#3 ./src/Budget.php(118): Budget->showValuesByEntity()
#4 ./src/CommonGLPI.php(738): Budget::displayTabContentForItem()

<img width="1083" height="442" alt="Image" src="https://github.com/user-attachments/assets/8d962192-8d3f-4217-9b76-00f19fd6fa3a" />

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Enable Debug mode in GLPI.
2. Create a new Budget.
3. Go to Assets -> Consumables and link some items/costs to this budget.
4. Go to Management -> Budgets and open the created budget.
5. Click on the "Main" or "Items" tab on the left menu.
6. See the Fatal Error (SQL syntax) and backtrace immediately on the screen.

### Your GLPI setup information

###GLPI information
GLPI: 11.0.6 ( => /var/www/glpi)
Installation mode: DOCKER
Current language: en_GB
Source Integrity: OK

### User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0

###Database:
Server Software: mariadb.org binary distribution
Server Version: 10.11.16-MariaDB-ubu2204
Server SQL Mode: 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

fixes #23496

### CODE REVIEW

**Review by trasher — APPROVED** [review]

File: tests/functional/BudgetTest.php [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+{
+    public function testGetItemListCriteria(): void
+    {
+        global $DB;
+
+        $this->login();
+
+        $rc = new \ReflectionClass(Budget::class);
+        $method = $rc->getMethod('getItemListCriteria');
+        $method->setAccessible(true);
```
Comment (trasher) [inline tests/functional/BudgetTest.php]:
```suggestion
```

**Review by AdrienClairembault — DISMISSED** [review]
The `budget.cy.js` test is red.

**Comment by cconard96** [comment]
> The `budget.cy.js` test is red.

~I'll try blind fixing, but all local test methods for playwright are broken for me as are PHPUnit tests but at least in the latter case it is easy to make a fix locally to unblock them.~

Nevermind. Thankfully they are still Cypress. I don't think those are broken too.

**Review by cedric-anne — APPROVED** [review]
