### PR TITLE
Fix printer model dictionary replay 

### LINKED ISSUE #18987: Printer model dictionnary rule execution fails - SQL error
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.18 & main branch

### Bug description

Replay the dictionnary rules fails with an sql error.

`
SQL Error "1062": Duplicate entry '3' for key 'PRIMARY' in query "INSERT INTO `glpi_printermodels` (`name`, `comment`, `id`, `date_creation`, `date_mod`) VALUES ('modified name', '', '3', '2025-02-14 15:23:17', '2025-02-14 15:23:17')"
`

### Relevant log output

```shell

```

### Page URL

./front/ruledictionnaryprintermodel.php?replay_rule=replay_rule

### Steps To reproduce

1. Create a printer, assign a model 'MyModel'
2. On dictionary page, Create a Printer model rule
- criteria 'Model' /  is / "MyModel"
- action 'Model' / assign / 'Fixed Model'
3. On Dictionaries / Printer model page : clic the "Replay the dictionary rule"

Error displayed : 
SQL Error "1062": Duplicate entry '4' for key 'PRIMARY' in query "INSERT INTO `glpi_printermodels` (`name`, `comment`, `id`, `date_creation`, `date_mod`) VALUES ('fixedModel', '', '4', '2025-02-14 15:53:50', '2025-02-14 15:53:50')"

Then 
- the printer is not associated with any model `printermodels_id` is 0. 
- the model is removed from `glpi_printermodels` database

### Your GLPI setup information

Fresh install, reproduced with glpi 10.0.18 and glpi main branch.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
closes #18987

To be reviewed per commit; first one only fix CS, phpdoc and typos; while seocnd one fix the issues and add tests.

### CODE REVIEW

File: phpunit/functional/RuleDictionnaryPrinterModelCollectionTest.php [hunk 1]
```diff
@@ -0,0 +1,222 @@
...
+    }
+
+    public function testIgnoreImport()
+    {
+        $rule       = new \Rule();
+        $criteria   = new \RuleCriteria();
+        $action     = new \RuleAction();
+        $collection = new \RuleDictionnaryPrinterModelCollection();
+
+        $rules_id = $rule->add([
```
Comment (SebSept) [inline phpunit/functional/RuleDictionnaryPrinterModelCollectionTest.php]: you should use $this->createItem() it ensure object is created as expected and make the next assertion useless.

File: phpunit/functional/RuleDictionnaryPrinterModelCollectionTest.php [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+            'is_active'   => 1,
+            'entities_id' => 0,
+            'sub_type'    => \RuleDictionnaryPrinterModel::class,
+            'match'       => \Rule::AND_MATCHING,
+            'condition'   => 0,
+            'description' => '',
+        ]);
+        $this->assertGreaterThan(0, $rules_id);
+
+        $this->assertGreaterThan(
```
Comment (SebSept) [inline phpunit/functional/RuleDictionnaryPrinterModelCollectionTest.php]: same remark here and below, use $this->createItem()

**Review by SebSept — CHANGES_REQUESTED** [review]
✅ Bug fixed.

**Review by SebSept — APPROVED** [review]
bug fixed (tested before 2 last commits) -> lgtm
