### PR TITLE
catch sql errors when checking replica status

### LINKED ISSUE #23522: Uncaught Exception: Access denied; BINLOG MONITOR privilege required for SHOW BINLOG STATUS in SQL Replicas tab
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

When enabling the "SQL Replicas" switch and navigating to the "SQL Replicas" tab, the page fails to load (there's no replica setup), and a critical uncaught RuntimeException is thrown in `php-errors.log`.

The error occurs because `DBmysql->doQuery()` attempts to run `SHOW BINLOG STATUS`, which requires the `BINLOG MONITOR` privilege on newer versions of MySQL/MariaDB. Because the standard GLPI database user lacks this privilege, it throws a fatal SQL error.

### Relevant log output

```shell
glpi.CRITICAL:   *** Uncaught PHP Exception RuntimeException: "MySQL query error: Access denied; you need (at least one of) the BINLOG MONITOR privilege(s) for this operation (1227) in SQL query "SHOW BINLOG STATUS"." at DBmysql.php line 416
  Backtrace :
  ./src/DBmysql.php:416                              
  ./src/DBConnection.php:590                         DBmysql->doQuery()
  ./src/Config.php:570                               DBConnection::getReplicationStatus()
  ./src/Config.php:1089                              Config->showFormDBSlave()
  ./src/CommonGLPI.php:738                           Config::displayTabContentForItem()
  ./ajax/common.tabs.php:108                         CommonGLPI::displayStandardTab()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:208        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:71                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

/front/config.form.php

### Steps To reproduce

1. Log in as a Super-Admin.
2. Go to **Setup** > **General** > **System** tab.
3. Enable the "SQL Replicas" configuration.
4. Attempt to access the newly available "SQL Replicas" tab.
5. Observe the UI failure and check `/files/_log/php-errors.log` to see the uncaught exception.

### Your GLPI setup information

<details><summary>
         GLPI information
      </summary><pre>
GLPI: 11.0.6 ( =&gt; /var/www/glpi)
Installation mode: DOCKER
Current language: pt_BR
Source Integrity: 4 files changed
  M: css/legacy/includes/_planning.scss
  M: public/css_compiled/css_glpi.min.css
  M: templates/components/form/fields_macros.html.twig
  M: templates/pages/admin/user/user.html.twig
</pre></details><details><summary>
         Server
      </summary><pre>
Operating system: Linux 27c02f5c2439 6.8.0-101-generic #​101-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb  9 10:15:05 UTC 2026 x86_64

PHP: 8.5.3 apache2handler

PHP extensions: Core, date, lexbor, openssl, pcre, sqlite3, zlib, ctype, curl, uri, json, fileinfo, filter, hash, iconv, SPL, mbstring, Zend OPcache, session, standard, PDO, pdo_sqlite, bz2, posix, random, Reflection, libxml, SimpleXML, tokenizer, dom, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, Phar, exif, gd, intl, ldap, mysqli, redis, soap, sodium, zip

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;512M&quot; post_max_size=&quot;8M&quot; session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;Strict&quot; session.save_handler=&quot;files&quot; upload_max_filesize=&quot;2M&quot; 

Web server: Apache ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 11.8.6-MariaDB-ubu2404
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@mariadb:3306/glpi
   
Host info: mariadb via TCP/IP

Requirements:
PHP version (8.5.3) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader, xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (11.8.6) is supported.
The log file has been created successfully.
Write access to /var/glpi/files/_cache has been validated.
Write access to /var/glpi/files/_cron has been validated.
Write access to /var/glpi/files has been validated.
Write access to /var/glpi/files/_graphs has been validated.
Write access to /var/glpi/files/_lock has been validated.
Write access to /var/glpi/files/_pictures has been validated.
Write access to /var/glpi/files/_plugins has been validated.
Write access to /var/glpi/files/_rss has been validated.
Write access to /var/glpi/files/_sessions has been validated.
Write access to /var/glpi/files/_tmp has been validated.
Write access to /var/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed
Following extensions are installed: ctype, iconv, sodium.
Write access to /var/glpi/marketplace has been validated.
Timezones seems loaded in database.
</pre></details><details><summary>
         GLPI constants
      </summary><pre>
GLPI_ROOT: &quot;/var/www/glpi&quot;
GLPI_VERSION: &quot;11.0.6&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.6@84160e91f70f353b33495a7928e5b1476d4b6d98&quot;
GLPI_FILES_VERSION: &quot;11.0.6-b89c5af8&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2026&quot;
GLPI_I18N_DIR: &quot;/var/www/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/var/glpi/config&quot;
GLPI_VAR_DIR: &quot;/var/glpi/files&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/glpi/marketplace&quot;
GLPI_LOG_DIR: &quot;/var/glpi/logs&quot;
GLPI_INSTALL_MODE: &quot;DOCKER&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                                # protocol\n                        (\n                            (?:\n                                (?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                    |\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain name\n                                    |\n                                [a-z0-9\\-\\_]++                                              # a single-level domain name\n                            )\\.?\n                                |                                                           # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}                              # an IP address\n                                |                                                           # or\n                            \\[\n                                (?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n                            \\]                                                              # an IPv6 address\n                        )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n                        (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n                    $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/var/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/glpi/files/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/glpi/marketplace&quot;,&quot;/var/www/glpi/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;
</pre></details><details><summary>
         LDAP directories
      </summary><pre>
Server: none, 
	Port: &#39;389&#39;, 
	BaseDN: none, 
	Connection filter: none, 
	RootDN: none, 
	Use TLS: none

Server: none, 
	Port: &#39;389&#39;, 
	BaseDN: none, 
	Connection filter: none, 
	RootDN: none, 
	Use TLS: none

Server: none, 
	Port: &#39;389&#39;, 
	BaseDN: none, 
	Connection filter: none, 
	RootDN: none, 
	Use TLS: none
</pre></details><details><summary>
         SQL replicas
      </summary><pre>
Active
SQL Server: localhost - não foi possível conectar ao banco de dados&lt;br&gt;
</pre></details><details><summary>
         Notifications
      </summary><pre>
Way of sending emails: PHP
</pre></details><details><summary>
         Plugins list
      </summary><pre>
gantt                Name: Gantt                          Version: 1.3.2        State: Enabled                                  Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.5        State: Enabled                                  Install Method: Marketplace
mreporting           Name: More Reporting                 Version: 1.9.3        State: Enabled                                  Install Method: Marketplace
pdf                  Name: PDF                            Version: 4.1.2        State: Enabled                                  Install Method: Marketplace
singlesignon         Name: Single Sign-on                 Version: 1.6.1        State: Enabled                                  Install Method: Manual
</pre></details>

### Anything else?

This is likely related to recent privilege changes in MySQL 8+ or MariaDB 10.5+. If granting `BINLOG MONITOR` is now a strict requirement for the GLPI user when using replicas, it would be helpful to explicitly add this to the official documentation alongside catching the exception in `DBConnection::getReplicationStatus()`.

To get your tab working again in the meantime, you can grant the missing privilege to your GLPI database user by running this directly in your MySQL/MariaDB console as root:

```sql
GRANT BINLOG MONITOR ON *.* TO 'your_glpi_user'@'localhost';
FLUSH PRIVILEGES;
```

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

fixes #23522

### CODE REVIEW

File: src/DBConnection.php [hunk 1]
```diff
@@ -586,14 +586,19 @@ public static function getReplicationStatus(): array
...
+                    foreach (['File', 'Position'] as $var_name) {
+                        $data['source'][strtolower($var_name)] = $db_main->result($result, 0, $var_name);
+                    }
+                } else {
+                    $data['source']['error'] = $db_main->error();
                 }
-            } else {
-                $data['source']['error'] = $db_main->error();
+            } catch (Exception) {
+                $data['source']['error'] = 'Unable to get binary log status. Check if the binary log is enabled on the database server and the database user has the necessary permissions for your specific database to access it (REPLICATION CLIENT, BINLOG MONITOR, etc).';
```
Comment (trasher) [inline src/DBConnection.php:606]: Since we catch a global Exception, maybe should we keep a trace in logs of the original one; in case this would not be related to described error? Would ease debugging.

File: src/DBConnection.php [hunk 2]
```diff
@@ -617,16 +622,20 @@ public static function getReplicationStatus(): array
...
+                        foreach ($replica_vars as $var_name => $var_key) {
+                            $data['replica'][$num][$var_name] = $db_replica->result($result, 0, $var_key);
+                        }
+                    } else {
+                        $data['replica'][$num]['error'] = $db_replica->error();
                     }
-                } else {
-                    $data['replica'][$num]['error'] = $db_replica->error();
+                } catch (Exception) {
+                    $data['replica'][$num]['error'] = 'Unable to get replica status. Check if the database user has the necessary permissions for your specific database to access it (REPLICATION CLIENT, REPLICA MONITOR, etc).';
```
Comment (trasher) [inline src/DBConnection.php:648]: Same Exception remark here

**Review by trasher — COMMENTED** [review]
LGTM, see comments

**Review by cedric-anne — APPROVED** [review]
