### PR TITLE
Fix service catalog tile right check

### LINKED ISSUE #22039: [GLPI 11.0.2] Helpdesk : Service Catalog not displayed
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.2

### Bug description

Hello,
In the Helpdesk tile configuration at the root entity level, I want to configure a tile that redirects to the Service Catalog.
I have configured it as follows:
Image
Image

However, when I access the Helpdesk with a test user (from the root entity), the Service Catalog tile does not appear. The other tiles (ticket list, external links) display correctly.
I don't have any tile configurations in the profiles that could override this setting.
Image

### Relevant log output

```shell
Nothing appears in php-errors.log, sql-errors.log or access-errors.log
```

### Page URL

https://glpi.domain.com/Helpdesk

### Steps To reproduce

1. Create a tile in the Helpdesk configuration at the root entity level that redirects to a GLPI page: Service Catalog
2. Log in with a user in this entity (simplified interface)

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.2 ( =&gt; /var/www/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: 4 files changed
  A: css/palettes/cmb.scss
  A: css/palettes/previews/cmb.png
  A: inc/downstream.php
  D: install/install.php</pre></details><details><summary>Server</summary><pre>Operating system: Linux APP-GLPI-TEST 6.8.0-85-generic #​85-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep 18 15:26:59 UTC 2025 x86_64

PHP: 8.3.6 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv,
intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer,
xmlreader, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;3000&quot; memory_limit=&quot;128M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;Lax&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache/2.4.58 (Ubuntu) (Apache/2.4.58 (Ubuntu) Server at glpi-test.domain.com Port 80)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36

Database:
   
Server Software: (Ubuntu)
   
Server Version: 8.0.44-0ubuntu0.24.04.1
   
Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
   
Parameters: user@localhost/glpi_db
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.3.6) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (8.0.44) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/glpi&quot;
GLPI_VERSION: &quot;11.0.2&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.2@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.2-52505ef9&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/etc/glpi/&quot;
GLPI_VAR_DIR: &quot;/var/lib/glpi&quot;
GLPI_LOG_DIR: &quot;/var/log/glpi&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/lib/glpi&quot;
GLPI_CACHE_DIR: &quot;/var/lib/glpi/_cache&quot;
GLPI_CRON_DIR: &quot;/var/lib/glpi/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/lib/glpi/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/lib/glpi/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/lib/glpi/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/lib/glpi/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/lib/glpi/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/lib/glpi/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/lib/glpi/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/lib/glpi/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/lib/glpi/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/lib/glpi/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/lib/glpi/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/glpi/marketplace&quot;,&quot;/var/www/glpi/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>LDAP directories</summary><pre>Server: &#39;ad.local&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;OU=Utilisateurs,DC=ad,DC=local&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;ldap@ad.local&#39;, 
	Use TLS: none</pre></details><details><summary>SQL replicas</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://noreply%40tenant.onmicrosoft.com:********@smtp.office365.com:587)</pre></details><details><summary>Plugins list</summary><pre>advancedplanning     Name: advancedplanning               Version: 1.1.1      State: Not installed                           
Install Method: Marketplace
news                 Name: Alertes                        Version: 1.13.0     State: Enabled                                 
Install Method: Marketplace
carbon               Name: Carbon                         Version: 1.1.1      State: Enabled                                 
Install Method: Marketplace
fields               Name: Champs supplémentaires         Version: 1.23.1     State: Enabled                                 
Install Method: Marketplace
datainjection        Name: Data Injection                 Version: 2.15.1     State: Enabled                                 
Install Method: Marketplace
useditemsexport      Name: Export des éléments utilisés   Version: 2.6.0      State: Enabled                                 
Install Method: Marketplace
footer               Name: Footer                         Version: 1.1.1      State: Installed / not activated               
Install Method: Marketplace
gantt                Name: gantt                          Version: 1.2.0      State: Enabled                                 
Install Method: Marketplace
gappessentials       Name: Gapp Essentials                Version: 2.3.0      State: Installed / not activated               
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.2      State: Enabled                                 
Install Method: Marketplace
manufacturersimports Name: Imports fabricants             Version: 3.1.1      State: Enabled                                 
Install Method: Marketplace
jamf                 Name: Plugin Jamf pour GLPI          Version: 3.1.2      State: Installed / not activated               
Install Method: Marketplace</pre></details>

### Anything else?

Thansk for help !

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

The service catalog tile was checking for the "create ticket" right, when it should instead check if the service catalog is enabled.

## References

Fix #22039.

### CODE REVIEW

File: tests/DbTestCase.php [hunk 1]
```diff
@@ -168,7 +168,7 @@ protected function checkInput(CommonDBTM $object, $id = 0, $input = [])
                 $this->assertArrayHasKey(
                     $k,
                     $object->fields,
-                    "Object not created as expected, field '$k' not found in object " . get_class($object),
+                    "Object not created or updated as expected, field '$k' not found in object " . get_class($object),
```
Comment (AdrienClairembault) [inline tests/DbTestCase.php:171]: Unrelated but I noticed the message was incorrect.

**Review by trasher — APPROVED** [review]
