### PR TITLE
Fix ambiguous column counting itil relations; closes #22635

### LINKED ISSUE #22635: Fail to get computer page
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

After upgrading to GLPI 11.0.4, we can't open certain computer's pages with error : 
```
An unexpected error occurred
Return to previous page
```

This error occur with "super-admin" profile and not on all computers. 
We have other custom profile without this bug (this profile has not rights on Tickets) 

According to the stack trace, I tried to execute SQL request in database with the same error. After little modification (table specification in WHERE clause), there is no more bug : 
```
SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` 
INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) 

WHERE `glpi_items_tickets`.`itemtype` = 'Monitor' AND `glpi_items_tickets`.`items_id` IN ('49') AND `is_deleted` = '0'
```

### Relevant log output

```shell
[2026-01-12 16:37:26] glpi.CRITICAL:   *** Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("MySQL query error: Column 'itemtype' in WHERE is ambiguous (1052) in SQL query "SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) WHERE `itemtype` = 'Peripheral' AND `items_id` IN ('5574', '6834', '4974', '6113', '6835', '3763') AND `is_deleted` = '0'".") in "pages/generic_form.html.twig" at line 33." at generic_form.html.twig line 33
  Backtrace :
  ./templates/pages/generic_form.html.twig:33
  ./vendor/twig/twig/src/Template.php:358            Twig\Template->yield()
  ./vendor/twig/twig/src/Template.php:373            Twig\Template->display()
  ./vendor/twig/twig/src/TemplateWrapper.php:51      Twig\Template->render()
  .../Glpi/Application/View/TemplateRenderer.php:170 Twig\TemplateWrapper->render()
  ./src/Glpi/Controller/AbstractController.php:68    Glpi\Application\View\TemplateRenderer->render()
  ...c/Glpi/Controller/GenericFormController.php:208 Glpi\Controller\AbstractController->render()
  ...c/Glpi/Controller/GenericFormController.php:121 Glpi\Controller\GenericFormController->displayForm()
  ./src/Glpi/Controller/GenericFormController.php:83 Glpi\Controller\GenericFormController->handleFormAction()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\GenericFormController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
  Previous: MySQL query error: Column 'itemtype' in WHERE is ambiguous (1052) in SQL query "SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) WHERE `itemtype` = 'Peripheral' AND `items_id` IN ('5574', '6834', '4974', '6113', '6835', '3763') AND `is_deleted` = '0'".
  ./src/DBmysql.php:392
  ./src/DBmysqlIterator.php:125                      DBmysql->doQuery()
  ./src/DBmysql.php:1061                             DBmysqlIterator->execute()
  ./src/DbUtils.php:607                              DBmysql->request()
  ./src/autoload/dbutils-aliases.php:214             DbUtils->countElementsInTable()
  ./src/CommonItilObject_Item.php:604                countElementsInTable()
  ./src/CommonItilObject_Item.php:556                CommonItilObject_Item::countForItemAndLinked()
  ./src/CommonGLPI.php:357                           CommonItilObject_Item->getTabNameForItem()
  ./src/Computer.php:160                             CommonGLPI->addStandardTab()
  ./src/CommonGLPI.php:319                           Computer->defineTabs()
  ./src/CommonGLPI.php:948                           CommonGLPI->defineAllTabs()
  ./src/CommonGLPI.php:1288                          CommonGLPI->showTabsContent()
  ./src/CommonDBTM.php:6565                          CommonGLPI->display()
  :                                                  CommonDBTM::displayFullPageForItem()
  ...Application/View/Extension/PhpExtension.php:105 call_user_func_array()
  ...ates/fc/fc25133b450e3c854fe967b7fa41d941.php:45 Glpi\Application\View\Extension\PhpExtension->call()
  ./vendor/twig/twig/src/Template.php:402            __TwigTemplate_f55a98b7f26f33b0b32f20a23439b550->doDisplay()
  ./vendor/twig/twig/src/Template.php:358            Twig\Template->yield()
  ./vendor/twig/twig/src/Template.php:373            Twig\Template->display()
  ./vendor/twig/twig/src/TemplateWrapper.php:51      Twig\Template->render()
  .../Glpi/Application/View/TemplateRenderer.php:170 Twig\TemplateWrapper->render()
  ./src/Glpi/Controller/AbstractController.php:68    Glpi\Application\View\TemplateRenderer->render()
  ...c/Glpi/Controller/GenericFormController.php:208 Glpi\Controller\AbstractController->render()
  ...c/Glpi/Controller/GenericFormController.php:121 Glpi\Controller\GenericFormController->displayForm()
  ./src/Glpi/Controller/GenericFormController.php:83 Glpi\Controller\GenericFormController->handleFormAction()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\GenericFormController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

https://glpi.local/front/computer.form.php?id=4339

### Steps To reproduce

_No response_

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.4 ( =&gt; /var/www/html/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: OK</pre></details><details><summary>Server</summary><pre>Operating system: Linux srv-glpi.xxx.com 5.10.0-37-amd64 #​1 SMP Debian 5.10.247-1 (2025-12-11) x86_64

PHP: 8.2.30 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext,
gmp, iconv, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem,
sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;600&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;512M&quot; post_max_size=&quot;25M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;20M&quot; 

Web server: Apache/2.4.65 (Debian) (Apache/2.4.65 (Debian) Server at glpi.xxx.com Port 80)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:146.0) Gecko/20100101 Firefox/146.0

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 10.11.15-MariaDB-deb11
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpiuser@localhost/glpidb
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.2.30) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.15) is
supported.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/html/glpi&quot;
GLPI_VERSION: &quot;11.0.4&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.4@9065df1ff6b8ff1d77b519d1c4856507d18258b0&quot;
GLPI_FILES_VERSION: &quot;11.0.4-1d4fbe9a&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi/locales&quot;
GLPI_VAR_DIR: &quot;/var/lib/glpi&quot;
GLPI_DOC_DIR: &quot;/var/lib/glpi&quot;
GLPI_CRON_DIR: &quot;/var/lib/glpi/_cron&quot;
GLPI_DUMP_DIR: &quot;/var/lib/glpi/_dumps&quot;
GLPI_GRAPH_DIR: &quot;/var/lib/glpi/_graphs&quot;
GLPI_LOCK_DIR: &quot;/var/lib/glpi/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/lib/glpi/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/lib/glpi/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/lib/glpi/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/lib/glpi/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/lib/glpi/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/lib/glpi/_uploads&quot;
GLPI_CACHE_DIR: &quot;/var/lib/glpi/_cache&quot;
GLPI_LOG_DIR: &quot;/var/log/glpi&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_CONFIG_DIR: &quot;/var/www/html/glpi/config&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/lib/glpi/_locales&quot;
GLPI_INVENTORY_DIR: &quot;/var/lib/glpi/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/lib/glpi/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi/marketplace&quot;,&quot;/var/www/html/glpi/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>LDAP directories</summary><pre>Server: &#39;ldaps://srvxxx.xxx.priv&#39;, 
	Port: &#39;636&#39;, 
	BaseDN: &#39;DC=xxx,DC=xxx,DC=priv&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;s-ad@xxx.xxx.priv&#39;, 
	Use TLS: none

Server: &#39;ldaps://srvxxx.xxx.priv&#39;, 
	Port: &#39;636&#39;, 
	BaseDN: &#39;DC=xxx,DC=xxx,DC=priv&#39;, 
	Connection filter: none, 
	RootDN: &#39;s-ad@xxx.xxx.priv&#39;, 
	Use TLS: none</pre></details><details><summary>SQL replicas</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://relay.xxx.com:587)</pre></details><details><summary>Plugins list</summary><pre>news                 Name: Alertes                        Version: 1.13.0     State: Enabled                                 
Install Method: Marketplace
webapplications      Name: Applications Web               Version: 5.1.3      State: Enabled                                 
Install Method: Marketplace
datainjection        Name: Data Injection                 Version: 2.15.3     State: Enabled                                 
Install Method: Marketplace
useditemsexport      Name: Export des éléments utilisés   Version: 2.6.1      State: Enabled                                 
Install Method: Marketplace
geninventorynumber   Name: Génération de numéros d&#39;invent Version: 2.10.0     State: Enabled                                 
Install Method: Marketplace
genericobject        Name: Gestion d&#39;objets               Version: 3.0.2      State: Enabled                                 
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.4      State: Enabled                                 
Install Method: Marketplace
manufacturersimports Name: Imports fabricants             Version: 3.1.2      State: Enabled                                 
Install Method: Marketplace
mreporting           Name: Plus de rapports               Version: 1.9.2      State: Enabled                                 
Install Method: Marketplace
tag                  Name: Tag Management                 Version: 2.14.3     State: Enabled                                 
Install Method: Marketplace</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

File: src/CommonItilObject_Item.php [hunk 1]
```diff
@@ -594,12 +594,12 @@ public static function countForItemAndLinked(CommonDBTM $item)
...
                 'WHERE' => [
-                    static::$itemtype_2 => $type,
-                    static::$items_id_2 => $ids,
+                    static::getTable() . '.' . static::$itemtype_2 => $type,
+                    static::getTable() . '.' . static::$items_id_2 => $ids,
                 ],
             ];
             if ($type_item->maybeDeleted()) {
-                $criteria['WHERE']['is_deleted'] = 0;
+                $criteria['WHERE'][static::getTable() . '.' . 'is_deleted'] = 0;
```
Comment (trasher) [inline src/CommonItilObject_Item.php]:
```suggestion
                $criteria['WHERE'][type_item . '.' . 'is_deleted'] = 0;
```

**Review by AdrienClairembault — APPROVED** [review]

File: src/CommonItilObject_Item.php [hunk 2]
```diff
@@ -594,12 +594,12 @@ public static function countForItemAndLinked(CommonDBTM $item)
...
                 'WHERE' => [
-                    static::$itemtype_2 => $type,
-                    static::$items_id_2 => $ids,
+                    static::getTable() . '.' . static::$itemtype_2 => $type,
+                    static::getTable() . '.' . static::$items_id_2 => $ids,
                 ],
             ];
             if ($type_item->maybeDeleted()) {
-                $criteria['WHERE']['is_deleted'] = 0;
+                $criteria['WHERE'][type_item . '.' . 'is_deleted'] = 0;
```
Comment (trasher) [inline src/CommonItilObject_Item.php]:
```suggestion
                $criteria['WHERE'][$type_item . '.' . 'is_deleted'] = 0;
```

File: src/CommonItilObject_Item.php [hunk 3]
```diff
@@ -594,12 +594,12 @@ public static function countForItemAndLinked(CommonDBTM $item)
...
                 'WHERE' => [
-                    static::$itemtype_2 => $type,
-                    static::$items_id_2 => $ids,
+                    static::getTable() . '.' . static::$itemtype_2 => $type,
+                    static::getTable() . '.' . static::$items_id_2 => $ids,
                 ],
             ];
             if ($type_item->maybeDeleted()) {
-                $criteria['WHERE']['is_deleted'] = 0;
+                $criteria['WHERE'][$type . '.' . 'is_deleted'] = 0;
```
Comment (cedric-anne) [inline src/CommonItilObject_Item.php]:
```suggestion
                $criteria['WHERE'][$type::getTable() . '.' . 'is_deleted'] = 0;
```

Comment (trasher) [reply src/CommonItilObject_Item.php]: I wonder why it's been so complicated for me not to fix that correctly...

File: src/CommonItilObject_Item.php [hunk 4]
```diff
@@ -594,12 +594,12 @@ public static function countForItemAndLinked(CommonDBTM $item)
...
                 'WHERE' => [
-                    static::$itemtype_2 => $type,
-                    static::$items_id_2 => $ids,
+                    static::getTable() . '.' . static::$itemtype_2 => $type,
+                    static::getTable() . '.' . static::$items_id_2 => $ids,
                 ],
             ];
             if ($type_item->maybeDeleted()) {
-                $criteria['WHERE']['is_deleted'] = 0;
+                $criteria['WHERE'][$type::getTable() . '.' . 'is_deleted'] = 0;
```
Comment (trasher) [inline src/CommonItilObject_Item.php]: Reporter tell it still is an issue. I should not have changed that, problem was not there.
```suggestion
                $criteria['WHERE']['is_deleted'] = 0;
```

**Review by cedric-anne — APPROVED** [review]
