### PR TITLE
Fix dropdown conditions

### LINKED ISSUE #21604: Unable to Select Status for "If the asset status is" and "Status to apply"  under Agent Cleanup
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11.0.1

### Bug description

Under Administration -> Inventory 

Both Dropdowns unable to filter for existing statuses:
Image

### Relevant log output

```shell

```

### Page URL

/front/inventory.conf.php

### Steps To reproduce

1. Click on Administration
2. Click on Inventory
3. Select unter Agent Cleanup - Action -> Change the status
4. Try to select a status under "if the asset status is:" or "Status to apply:"

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.1 ( =&gt; /var/www/html/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: N/A</pre></details><details><summary>Server</summary><pre>Operating system: Linux  5.14.0-570.51.1.0.1.el9_6.x86_64 #​1 SMP PREEMPT_DYNAMIC Tue Oct 7 05:02:48 PDT 2025 x86_64

PHP: 8.2.29 fpm-fcgi

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard,
cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, ldap, exif, mysqlnd, PDO,
Phar, SimpleXML, soap, sockets, sodium, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip,
Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;120&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;512M&quot; post_max_size=&quot;100M&quot;
session.cookie_secure=&quot;1&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;100M&quot; 

Web server: Apache/2.4.62 (Oracle Linux Server) OpenSSL/3.2.2 ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36
Edg/141.0.0.0

Database:
   
Server Software: MariaDB Server
   
Server Version: 10.11.14-MariaDB
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@127.0.0.1/glpi_prod
   
Host info: 127.0.0.1 via TCP/IP

Requirements:
PHP version (8.2.29) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.14) is
supported.
The log file has been created successfully.
Write access to
/srv/glpi_files/_cache has been validated.
Write access to /srv/glpi_files/_cron has been validated.
Write access to /srv/glpi_files has been validated.
Write access to /srv/glpi_files/_graphs has been validated.
Write access to /srv/glpi_files/_lock has been validated.
Write access to /srv/glpi_files/_pictures has been validated.
Write access to /srv/glpi_files/_plugins has been validated.
Write access to /srv/glpi_files/_rss has been validated.
Write access to /srv/glpi_files/_sessions has been validated.
Write access to /srv/glpi_files/_tmp has been validated.
Write access to /srv/glpi_files/_uploads has been validated.
SELinux configuration is OK.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/html/glpi&quot;
GLPI_VERSION: &quot;11.0.1&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.1&quot;
GLPI_FILES_VERSION: &quot;11.0.1-3a9929cf&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/srv/glpi_config/&quot;
GLPI_VAR_DIR: &quot;/srv/glpi_files&quot;
GLPI_DOC_DIR: &quot;/srv/glpi_files&quot;
GLPI_CACHE_DIR: &quot;/srv/glpi_files/_cache&quot;
GLPI_CRON_DIR: &quot;/srv/glpi_files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/srv/glpi_files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/srv/glpi_files/_locales&quot;
GLPI_LOCK_DIR: &quot;/srv/glpi_files/_lock&quot;
GLPI_PICTURE_DIR: &quot;/srv/glpi_files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/srv/glpi_files/_plugins&quot;
GLPI_RSS_DIR: &quot;/srv/glpi_files/_rss&quot;
GLPI_SESSION_DIR: &quot;/srv/glpi_files/_sessions&quot;
GLPI_TMP_DIR: &quot;/srv/glpi_files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/srv/glpi_files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/srv/glpi_files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/srv/glpi_files/_themes&quot;
GLPI_LOG_DIR: &quot;/srv/glpi_files/_logs&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi/marketplace&quot;,&quot;/var/www/html/glpi/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>LDAP directories</summary><pre>Server: &#39;&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;DC=test,DC=de&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;CN=glpi-svc,OU=Funktionsaccounts,OU=Administration,DC=,DC=&#39;, 
	Use TLS: none</pre></details><details><summary>SQL replicas</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: PHP</pre></details><details><summary>Plugins list</summary><pre>accounts             Name: Accounts                       Version: 3.1.1      State: Not installed                           
Install Method: Marketplace
activity             Name: Activities                     Version: 3.2.2      State: Not installed                           
Install Method: Marketplace
fields               Name: Additional fields              Version: 1.22.1     State: Enabled                                 
Install Method: Marketplace
datainjection        Name: Data injection                 Version: 2.15.1     State: Enabled                                 
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.0      State: Enabled                                 
Install Method: Marketplace
addressing           Name: IP Addressing                  Version: 3.1.0      State: Not installed                           
Install Method: Marketplace
order                Name: Orders management              Version: 2.12.1     State: Installed / not activated               
Install Method: Marketplace
manufacturersimports Name: Suppliers imports              Version: 3.1.1      State: Enabled                                 
Install Method: Marketplace</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
fix #21604

I'm not sure the way condition is passed here is correct; but I guess it's better to handle that (specific? or not...) case rather than trying to fix; it's quite hard to review all possible cases in existing source code (and plugins).

### CODE REVIEW

**Comment by trasher** [comment]
> Hard to validate but looks OK if it doesn't break any existing tests.

I doubt "condition" system can really and correctly be tested - not from phpunit :-/

> Maybe you could add another test for the related issue?

Hum... I'll take a look.

File: src/Dropdown.php [hunk 1]
```diff
@@ -2898,16 +2898,6 @@ public static function getDropdownValue($post, $json = true)
             $post['permit_select_parent'] = false;
         }
 
-        if (isset($post['condition']) && !empty($post['condition']) && !is_array($post['condition'])) {
```
Comment (trasher) [inline src/Dropdown.php:2901]: Moved to group conditions code inside method

**Review by AdrienClairembault — APPROVED** [review]
