### PR TITLE
fix: [10.0] Default locale wasn't correctly loaded when the browser only sent a part of  the language like pl

### LINKED ISSUE #22321: Wrong language selected for login panel
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.18

### Bug description

When trying to log in to a main panel i encountered weird issue. When i have more than 1 language in web browser, it selects by default english. I have to delete all other languages to make it select my actual language.

It appears despite having default language Polish on my web browser and system. I'm using Windows 11 and 10 OS.

I also tested it from a CMD level by a curl command and it didn't have to select correct language to display - Polish. On a Linux Ubuntu and Windows it both displayed polish for a login panel - It is a good behavior.

Please let me know if it was fixed because i didn't find solutions in changelogs and glpi forum 

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

v10.0.18 GLPI
extra plugins: ActualTime, GroupCategory, taskList

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by froozeify**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description
fixes #22321

In some case the browser was only sending a the first letter of language and GLPI won't find the match.
i.e: `pl` was sent and glpi mapping is `pl_PL` so in that case the fallback `en_GB` was displayed to the user.

### CODE REVIEW

File: src/Session.php [hunk 1]
```diff
@@ -862,10 +862,30 @@ public static function getPreferredLanguage(): string
...
+                }
+
+                // Otherwise fallback to the first matching locale
+                // e.g., 'en' -> 'en_GB' (since en_EN doesn't exist)
+                $prefix = $language . '_';
+                foreach ($supported_locales as $locale_key) {
+                    if (str_starts_with($locale_key, $prefix)) {
+                        return $locale_key;
+                    }
+                }
```
Comment (cedric-anne) [inline src/Session.php]: This may produce unexpected results. For instance, it will use `es_419` but users from Europe would probably expect `es_SP` to be used.
Still, there are many languages, like `ca_ES`, `cs_CZ`, `el_GR`, ... that should be served when the requested locale is `ca`, `cz`, `el`, ...

I guess the proposal is better than the current behavior, so if no one has a better idea, it is OK for me.

Comment (froozeify) [reply src/Session.php]: Indeed didn´t though of those specific case, we could either reorder in the `$CFG_GLPI['languages']` or remove that fallback case and it will them return the default GLPI language (few lines after)

image

File: src/Session.php [hunk 2]
```diff
@@ -862,10 +862,30 @@ public static function getPreferredLanguage(): string
         }
         arsort($accepted_languages); // sort by qfactor
 
+        $supported_locales = array_keys($CFG_GLPI['languages'] ?? []);
```
Comment (trasher) [inline src/Session.php]: Is it possible there is no `$CFG_GLPI['languages']`? I guess no

**Comment by trasher** [comment]
Instead of trying to guess, what about adding the short form (optional) in the configuration? This would permit some locales not to have a bad default.

**Comment by cedric-anne** [comment]
> Instead of trying to guess, what about adding the short form (optional) in the configuration? This would permit some locales not to have a bad default.

We could have a `$CFG_GLPI['main_languages'] = ['es' => 'es_SP', ...]`. It requires to do it manually, but it is probalby the safer solution.

**Comment by trasher** [comment]
> > Instead of trying to guess, what about adding the short form (optional) in the configuration? This would permit some locales not to have a bad default.
> 
> We could have a `$CFG_GLPI['main_languages'] = ['es' => 'es_SP', ...]`. It requires to do it manually, but it is probalby the safer solution.

I'd vote for that. For sure, we have to maintain it, but only when adding new languages mainly (that's not so often).

**Comment by froozeify** [comment]
I'm updating the code and creating a mapping with $CFG_GLPI['main_languages'] so

File: inc/define.php [hunk 3]
```diff
@@ -138,6 +138,58 @@
...
+    'hi' => 'hi_IN',
+    'hr' => 'hr_HR',
+    'hu' => 'hu_HU',
+    'it' => 'it_IT',
+    'km' => 'km_KH',
+    'lv' => 'lv_LV',
+    'lt' => 'lt_LT',
+    'mn' => 'mn_MN',
+    'nl' => 'nl_NL',
+    'no' => 'nb_NO',
```
Comment (cedric-anne) [inline inc/define.php]:
```suggestion
    'nb' => 'nb_NO',
```

File: inc/define.php [hunk 4]
```diff
@@ -138,6 +138,58 @@
     'es_CL'  => ['Español chileno',           'es_CL.mo',       'es',    'es', 'spanish chilean',      2],
 ];
 
+// Mapping of short language codes to their main locale
+$CFG_GLPI['main_languages'] = [
+    'ar' => 'ar_SA',
```
Comment (trasher) [inline inc/define.php]: I'm not sure for this one, maybe should we have no default for `ar`?

File: inc/define.php (hunk 3 above)
Comment (froozeify) [reply inc/define.php]: Maye we should have both ? I see on the comment also `no_NB, no_NN`
image

Comment (cedric-anne) [reply inc/define.php]: I thought it was a typo.
Honestly, I am not able to know what should be declared right now, and I will not spend too much time on this. If you are sure of what you are doing, this is fine for me.

Comment (froozeify) [reply inc/define.php]: I've added the aliases because some country like ukraine the iso code is UA

Comment (cedric-anne) [reply inc/define.php]: It seems that `nb`, `nn` and `no` are valid ISO-639-1 codes (see https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes).

Comment (cedric-anne) [reply inc/define.php]: > I've added the aliases because some country like ukraine the iso code is UA

UA is the alpha 2 country code, but is not a valid language code, so it will probably never be sent by browsers.

Comment (froozeify) [reply inc/define.php]: Indeed, I was checking with the wrong ISO https://fr.wikipedia.org/wiki/ISO_3166-2 , I'll rollback that commit

Comment (trasher) [reply inc/define.php]: `nb` is the correct one; see https://www.localeplanet.com/icu/nb-NO/index.html and https://www.localeplanet.com/icu/iso639.html#nb

No idea where this `no_*` is from, you maybe can delete that comment.

File: inc/define.php (hunk 4 above)
Comment (cedric-anne) [reply inc/define.php]: Unless we have a documented source, I cannot tell if it is a good or a bad idea to assign a default region for the arabic language.

File: inc/define.php (hunk 3 above)
Comment (trasher) [reply inc/define.php]: Seems like `no_` was wrongly used in GLPI a long time ago. This has been changed in a1a689f27171ad48d676b5195f83b05329ea89ac
So, please remove all that comments, it's really useless.

File: inc/define.php (hunk 4 above)
Comment (trasher) [reply inc/define.php]: In doubt, we should not have this default.

File: inc/define.php (hunk 3 above)
Comment (trasher) [reply inc/define.php]: > It seems that `nb`, `nn` and `no` are valid ISO-639-1 codes (see https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes).

Well, `no` is referenced as a "macro language", so not a primary language, rather a specific one.

Comment (trasher) [inline inc/define.php]:
```suggestion
    'nb' => 'nb_NO',
```

File: inc/define.php [hunk 5]
```diff
@@ -138,6 +138,58 @@
...
+    'hi' => 'hi_IN',
+    'hr' => 'hr_HR',
+    'hu' => 'hu_HU',
+    'it' => 'it_IT',
+    'km' => 'km_KH',
+    'lv' => 'lv_LV',
+    'lt' => 'lt_LT',
+    'mn' => 'mn_MN',
+    'nl' => 'nl_NL',
+    'nb' => 'nb_NO',
```
Comment (cedric-anne) [inline inc/define.php:170]:
```suggestion
    'nb' => 'nb_NO',
    'nn' => 'nn_NO',
```

File: inc/define.php (hunk 4 above)
Comment (froozeify) [reply inc/define.php]: I've commented it and if an user in the future have the proposal for it we'll be able to update it quickly
