### PR TITLE
Fix "My devices" dropdown when group devices are shown

### LINKED ISSUE #21953: GLPI 11 - Error when assigning items to a ticket
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11

### Bug description

When trying to assign a item with a ticket, I get the message "Results cant be loaded"
Investigating the log file I get this error

`[2025-11-17 10:32:10] glpi.CRITICAL:   *** Uncaught PHP Exception RuntimeException: "MySQL query error: Unknown column 'groups_id' in 'WHERE' (1054) in SQL query "SELECT * FROM `glpi_computers` WHERE `groups_id` IN ('38') AND ((`glpi_computers`.`entities_id` = '0' OR (`glpi_computers`.`is_recursive` = '1' AND `glpi_computers`.`entities_id` IN ('0')))) AND `is_deleted` = '0' AND `is_template` = '0' ORDER BY `name`"." at DBmysql.php line 371
  Backtrace :
  ./src/DBmysql.php:371
  ./src/DBmysqlIterator.php:123                      DBmysql->doQuery()
  ./src/DBmysql.php:1040                             DBmysqlIterator->execute()
  ./src/Dropdown.php:4312                            DBmysql->request()
  ./ajax/getDropdownMyDevices.php:42                 Dropdown::getDropdownMyDevices()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()`

The column groups_id doesn't exist in glpi_computers table

### Relevant log output

```shell
[2025-11-17 10:32:10] glpi.CRITICAL:   *** Uncaught PHP Exception RuntimeException: "MySQL query error: Unknown column 'groups_id' in 'WHERE' (1054) in SQL query "SELECT * FROM `glpi_computers` WHERE `groups_id` IN ('38') AND ((`glpi_computers`.`entities_id` = '0' OR (`glpi_computers`.`is_recursive` = '1' AND `glpi_computers`.`entities_id` IN ('0')))) AND `is_deleted` = '0' AND `is_template` = '0' ORDER BY `name`"." at DBmysql.php line 371
  Backtrace :
  ./src/DBmysql.php:371
  ./src/DBmysqlIterator.php:123                      DBmysql->doQuery()
  ./src/DBmysql.php:1040                             DBmysqlIterator->execute()
  ./src/Dropdown.php:4312                            DBmysql->request()
  ./ajax/getDropdownMyDevices.php:42                 Dropdown::getDropdownMyDevices()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

1. Open a ticket
2. got to Items
3. Try to add an item assigned with requester

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.2 ( =&gt; /var/www/html/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: 2 files changed
  A: public/logo-GLPI-250-black.png
  A: public/toyota.pac</pre></details><details><summary>Server</summary><pre>Operating system: Linux vmlinux20-01 6.1.0-41-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.158-1 (2025-11-09) x86_64

PHP: 8.2.29 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv,
igbinary, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm,
tokenizer, xmlreader, xmlwriter, xsl, zip, redis, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;600&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;1024M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;1&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache/2.4.65 (Debian) (Apache/2.4.65 (Debian) Server at helpdesk.mcoutinho.pt Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
Edg/142.0.0.0

Database:
   
Server Software: Debian 12
   
Server Version: 10.11.14-MariaDB-0+deb12u2-log
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@127.0.0.1/glpi
   
Host info: 127.0.0.1 via TCP/IP

Requirements:
PHP version (8.2.29) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.14) is
supported.
The log file has been created successfully.
Write access to
/srv/glpi/files/_cache has been validated.
Write access to /srv/glpi/files/_cron has been validated.
Write access to /srv/glpi/files has been validated.
Write access to /srv/glpi/files/_graphs has been validated.
Write access to /srv/glpi/files/_lock has been validated.
Write access to /srv/glpi/files/_pictures has been validated.
Write access to /srv/glpi/files/_plugins has been validated.
Write access to /srv/glpi/files/_rss has been validated.
Write access to /srv/glpi/files/_sessions has been validated.
Write access to /srv/glpi/files/_tmp has been validated.
Write access to /srv/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/html/glpi&quot;
GLPI_VERSION: &quot;11.0.2&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.2@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.2-52505ef9&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi/locales&quot;
GLPI_LOG_DIR: &quot;/var/log/glpi&quot;
GLPI_VAR_DIR: &quot;/srv/glpi/files&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_CONFIG_DIR: &quot;/var/www/html/glpi/config&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/srv/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/srv/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/srv/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/srv/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/srv/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/srv/glpi/files/_lock&quot;
GLPI_PICTURE_DIR: &quot;/srv/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/srv/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/srv/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/srv/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/srv/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/srv/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/srv/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/srv/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi/marketplace&quot;,&quot;/var/www/html/glpi/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>LDAP directories</summary><pre>Server: &#39;10.1.1.212&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;OU=Users,OU=MCoutinho,DC=mcoutinho,DC=local&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;mcoutinho\ad_sync_glpi&#39;, 
	Use TLS: none

Server: &#39;10.1.19.2&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;OU=Users,OU=MultiAuto,DC=multiauto,DC=local&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;multiauto\ad_sync_glpi&#39;, 
	Use TLS: none</pre></details><details><summary>SQL replicas</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://helpdesk%40mcoutinho.pt:********@smtp.office365.com:587?verify_peer=0)
Name: &#39;helpdesk@mcoutinho.pt&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com/imap-oauth-1/ssl}&#39;
	Login: &#39;helpdesk@mcoutinho.pt&#39;
	Password: No</pre></details><details><summary>Plugins list</summary><pre>actualtime           Name: ActualTime                     Version: 3.2.0      State: Installed / not activated               
Install Method: Marketplace
advancedplanning     Name: advancedplanning               Version: 1.1.1      State: Installed / not activated               
Install Method: Marketplace
behaviors            Name: Behaviours                     Version: 3.0.1      State: Enabled                                 
Install Method: Marketplace
fields               Name: Campos adicionais              Version: 1.23.0     State: Enabled                                 
Install Method: Marketplace
uninstall            Name: Ciclo de vida do item (desinst Version: 2.9.4      State: Installed / not activated               
Install Method: Marketplace
accounts             Name: Contas                         Version: 3.0.4      State: Installed / not activated               
Install Method: Marketplace
gantt                Name: gantt                          Version: 1.2.0      State: Enabled                                 
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.2      State: Enabled                                 
Install Method: Marketplace
addressing           Name: IP Addressing                  Version: 3.0.3      State: Installed / not activated               
Install Method: Marketplace
itremote             Name: IT Remote                      Version: 2.0        State: Installed / not activated               
Install Method: Manual
mailanalyzer         Name: Mail Analyzer                  Version: 3.2.2      State: Installed / not activated               
Install Method: Marketplace
mouvements           Name: Movements                      Version: 1.3.0      State: Enabled                                 
Install Method: Manual
mydashboard          Name: O meu Painel                   Version: 2.2.2      State: Enabled                                 
Install Method: Marketplace
oauthimap            Name: Oauth IMAP                     Version: 1.5.0      State: Enabled                                 
Install Method: Marketplace
protocolsmanager     Name: Protocols manager              Version: 1.6.0.2    State: Enabled                                 
Install Method: Manual
taskdrop             Name: TaskDrop                       Version: 2.1.0      State: Installed / not activated               
Install Method: Marketplace
tasklists            Name: Tasks list                     Version: 2.1.1      State: Installed / not activated               
Install Method: Marketplace
timelineticket       Name: Timeline of tickets            Version: 10.0+1.2   State: Installed / not activated               
Install Method: Marketplace
treeview             Name: Vista em árvore                Version: 1.20.0     State: Enabled                                 
Install Method: Marketplace</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cedric-anne**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

It fixes #21953

### CODE REVIEW

File: tests/functional/DropdownTest.php [hunk 1]
```diff
@@ -2228,7 +2231,7 @@ public static function assignableAssetsProvider()
     {
         return [
             [\CartridgeItem::class], [Computer::class], [\ConsumableItem::class], [Monitor::class], [\NetworkEquipment::class],
-            [\Peripheral::class], [\Phone::class], [\Printer::class], [\Software::class],
+            [\Peripheral::class], [\Phone::class], [Printer::class], [\Software::class],
```
Comment (trasher) [inline tests/functional/DropdownTest.php]: Why not import every class?

File: tests/functional/DropdownTest.php [hunk 2]
```diff
@@ -2653,124 +2656,220 @@ public function testGetDropdownMyDevices()
...
+        $this->createItem(
+            Group_User::class,
+            [
+                'groups_id' => $group_id,
+                'users_id'  => $user_id,
+            ]
+        );
+
+        // Create test equipment owned by user/group using GLPI's createItem helper
+        $computer_1 = $this->createItem('Computer', [
```
Comment (trasher) [inline tests/functional/DropdownTest.php]:
```suggestion
        $computer_1 = $this->createItem(Computer::class, [
```

(for all hardcoded itemtypes)

**Review by trasher — APPROVED** [review]
