### PR TITLE
[HLAPI] Skip cookie auth if session already started

### LINKED ISSUE #21165: Possible inconsistency in the New GLPI 11 API session
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11 Rc5

### Bug description

Today, when using the API in several requests, there were times when, for example, when opening a new ticket, it did not respond, so I had to request it again for it to work. The logs showed the following messages below. I am leaving them here in case it is some kind of bug related to the API session: 

### Relevant log output

```shell
glpi.WARNING:   *** Warning: ini_set(): Session ini settings cannot be changed when a session is active at info.php line 428
  Backtrace :
  ...hecodingmachine/safe/generated/8.2/info.php:428 
  ...i/Api/HL/Middleware/CookieAuthMiddleware.php:48 Safe\ini_set()
  ...lpi/Api/HL/Middleware/AbstractMiddleware.php:48 Glpi\Api\HL\Middleware\CookieAuthMiddleware->process()
  ./src/Glpi/Api/HL/Router.php:547                   Glpi\Api\HL\Middleware\AbstractMiddleware->__invoke()
  ./src/Glpi/Api/HL/Router.php:549                   Glpi\Api\HL\Router::Glpi\Api\HL\{closure}()
  ./src/Glpi/Api/HL/Router.php:663                   Glpi\Api\HL\Router->doAuthMiddleware()
  ./src/Glpi/Controller/ApiController.php:98         Glpi\Api\HL\Router->handleRequest()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\ApiController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()

__________

glpi.ERROR:   *** Caught Safe\Exceptions\InfoException: An error occurred
  Backtrace :
  ...e/safe/generated/Exceptions/InfoException.php:9 
  ...hecodingmachine/safe/generated/8.2/info.php:430 Safe\Exceptions\InfoException::createFromPhpError()
  ...i/Api/HL/Middleware/CookieAuthMiddleware.php:48 Safe\ini_set()
  ...lpi/Api/HL/Middleware/AbstractMiddleware.php:48 Glpi\Api\HL\Middleware\CookieAuthMiddleware->process()
  ./src/Glpi/Api/HL/Router.php:547                   Glpi\Api\HL\Middleware\AbstractMiddleware->__invoke()
  ./src/Glpi/Api/HL/Router.php:549                   Glpi\Api\HL\Router::Glpi\Api\HL\{closure}()
  ./src/Glpi/Api/HL/Router.php:663                   Glpi\Api\HL\Router->doAuthMiddleware()
  ./src/Glpi/Controller/ApiController.php:98         Glpi\Api\HL\Router->handleRequest()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\ApiController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Ran into issue working on a web app that uses GLPI authorization code flow. May fix #21165.
In some cases, it seems like a PHP session can already be started and that causes the `ini_set` to fail, not so silently anymore.

### CODE REVIEW

**Comment by orthagh** [comment]
Could we just skip the session_start, no ?
What about stateless API ? I saw you mentioning that recently

File: src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php [hunk 1]
```diff
@@ -43,6 +43,11 @@ class CookieAuthMiddleware extends AbstractMiddleware implements AuthMiddlewareI
 {
     public function process(MiddlewareInput $input, callable $next): void
     {
+        if (session_status() === PHP_SESSION_ACTIVE) {
+            // session already started
+            $next($input);
+            return;
+        }
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php:50]: Is this normal to have this middleware executed while the session is already loaded ?
For instance, it may be due to internal requests from the API itself, and I guess it should ignore authentication middlewares in this case.

**Comment by cconard96** [comment]
> Could we just skip the session_start, no ?

Maybe. I thought there was an unexpected issue initially with it but it may be OK now.

> What about stateless API ? I saw you mentioning that recently

From the user POV at least, it is. A session may be started but it doesn't get reused between requests except in the case of the endpoints using CookieAuthMiddleware like "/authorize" for authorization code flow, documentation, etc. In those cases, it is here because they are likely to be used from a browser and it should try reusing the existing GLPI login.

File: src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php (hunk 1 above)
Comment (cconard96) [reply src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php:50]: There isn't really an overlap of the two auth middlewares. Internal auth middleware is only loaded prior to an internal feature making an API call. Cookie auth middleware is always loaded but the condition is set to always return false, so it only runs if it is explicitly attached to a route.

The only routes with cookie auth are:
- Authorization code grant "/authorize"
- Documentation "/doc" and "/doc.json"
- Index "/"
- Getting started documentation "/getting-started"

There are no current or foreseen uses for internal features to access these endpoints.

This also doesn't seem specific to authorization code flows. It seems consistent when using password grant in an external web application (not that I would want to use that for anything important) and then trying to get the OpenAPI schema "/doc.json".
