### PR TITLE
Fix dashboard fake provider random numbers generation

### LINKED ISSUE #22116: Dashboard fake data fatal error with PHP 8.5
When displaying a dashboard with fake data; following error appears iwhen running PHP 8.5:
```
[2025-12-01 06:48:57] glpi.WARNING:   *** Warning: The float 1.376962357852134E+19 is not representable as an int, cast occurred at FakeProvider.php line 54
  Backtrace :
  ./src/Glpi/Dashboard/FakeProvider.php:54           
  ./src/Glpi/Dashboard/FakeProvider.php:304          Glpi\Dashboard\FakeProvider::getObscureNumberForString()
  ./src/Glpi/Dashboard/Provider.php:207              Glpi\Dashboard\FakeProvider::nbItemByFk()
  :                                                  Glpi\Dashboard\Provider::__callStatic()
  ./src/Glpi/Dashboard/Grid.php:1036                 call_user_func_array()
  ./ajax/dashboard.php:215                           Glpi\Dashboard\Grid->getCardHtml()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### PR DESCRIPTION
**Pull request by cedric-anne**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

`xxh3` produces a 16 bytes strings, with a maximum hexadecimal value of `double(1.8446744073709552E+19)`, that is higher than `PHP_INT_MAX`.
`xxh32` produces a 8 bytes string, with a maximum hexadecimal value of `int(4294967295)`, that is lower than `PHP_INT_MAX` .
Therefore, using `xxh32` instead of `xxh3` permits to ensure that the random number generation will not fail with a `float xxx is not representable as an int`.

It fixes #22116.

### CODE REVIEW

File: src/Glpi/Dashboard/FakeProvider.php [hunk 1]
```diff
@@ -50,8 +50,9 @@ final class FakeProvider extends Provider
 {
     private static function getObscureNumberForString(string $string, int $max = 100): int
     {
-        // xxh3 should be the fastest hashing algorithm in PHP as of 8.1
-        return (int) abs((int) hexdec(hash('xxh3', $string)) % $max);
+        // xxh32 is pretty fast and produces a 8 bytes string that has an hexadecimal integer representation lower than `PHP_INT_MAX`
+        return (int) abs((int) hexdec(hash('xxh32', $string)) % $max);
+
```
Comment (trasher) [inline src/Glpi/Dashboard/FakeProvider.php]:
```suggestion
```
