### PR TITLE
Do not create SLA Level for new ticket created in Pending status

### LINKED ISSUE #23356: Ticket SLA Levels unicity issues
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

There is problem handing of SLA Level assignment to the Tickets in special case: if ticket is created not as new but as Pending.
This can happen due to BR or if user intentionally assigns SLA and Pending in one step.

My opinion to fix is adding check here:
https://github.com/glpi-project/glpi/blob/5d5cbea6a4561b553df81a6778d531afb474e99e/src/Ticket.php#L1279-L1289

To:
```
if ($sla->getFromDB($slas_id) 
&& in_array($this->fields['status'], array_merge($this->getNewStatusArray(), $this->getProcessStatusArray()))
) {
```

This issue exists also in GLPI 10.x but does not throw exception but silently fails with SQL error

### Relevant log output

```shell
[2026-03-04 07:58:56] glpi.CRITICAL:   *** Uncaught PHP Exception RuntimeException: "MySQL query error: Duplicate entry '31563-2443' for key 'unicity' (1062) in SQL query "INSERT INTO `glpi_slalevels_tickets` (`date`, `slalevels_id`, `tickets_id`) VALUES ('2026-03-05 09:00:00', '2443', '31563')"." at DBmysql.php line 405
  Backtrace :
  ./src/DBmysql.php:405
  ./src/DBmysql.php:1360                             DBmysql->doQuery()
  ./src/CommonDBTM.php:777                           DBmysql->insert()
  ./src/CommonDBTM.php:1382                          CommonDBTM->addToDB()
  ./src/LevelAgreement.php:970                       CommonDBTM->add()
  ./src/CommonITILObject.php:2678                    LevelAgreement->addLevelToDo()
  ./src/Ticket.php:1346                              CommonITILObject->pre_updateInDB()
  ./src/CommonDBTM.php:1757                          Ticket->pre_updateInDB()
  ./src/Glpi/Features/ParentStatus.php:174           CommonDBTM->update()
  ./src/ITILFollowup.php:320                         ITILFollowup->updateParentStatus()
  ./src/CommonDBTM.php:1398                          ITILFollowup->post_addItem()
  ./front/itilfollowup.form.php:58                   CommonDBTM->add()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:71                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

1. Create SLA with escalation levels
2. Create new ticket with that SLA in Pending status
3. Save ticket
4. Either solve ticket or return it back to working status
5. It fails with exception as in CommonITILObject::pre_updateInDB() it tries to create same record

### Your GLPI setup information

Clean 11.0.6 install without plugins

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by VladoTTX**
## Checklist before requesting a review

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.

## Description

- It fixes #23356 
- Ticket SLA Levels unicity issues in case if ticket is created with SLA escalation level and in Pending status

### CODE REVIEW

**Review by trasher — COMMENTED** [review]
Looks good to me; please add a tests

File: src/Ticket.php [hunk 1]
```diff
@@ -1276,7 +1276,10 @@ public function manageSlaLevel($slas_id)
         $slalevels_id = SlaLevel::getFirstSlaLevel($slas_id);
 
         $sla = new SLA();
-        if ($sla->getFromDB($slas_id)) {
+        if (
+            $sla->getFromDB($slas_id)
+            && in_array($this->fields['status'], array_merge(static::getNewStatusArray(), static::getProcessStatusArray()))
```
Comment (AdrienClairembault) [inline src/Ticket.php]: Shouldn't this also take into account the approval status?

File: src/Ticket.php
Comment (AdrienClairembault) [inline src/Ticket.php:1]: What about the `manageOlaLevel` method? It probably has the same issue.

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]

File: src/Ticket.php (hunk 1 above)
Comment (VladoTTX) [reply src/Ticket.php]: Approval status does not affect SLA, what counts here is that SLA Level should be applied just in case SLA is running. It was assumed previously, that while Adding ticket, it always will be New or Processing state. Which is not always true... (due to BR for example)

File: src/Ticket.php
Comment (VladoTTX) [reply src/Ticket.php:1]: You are right also OLA needs same approach. I've just added it

File: src/Ticket.php (hunk 1 above)
Comment (AdrienClairembault) [reply src/Ticket.php]: Just to be sure, I meant this status specifically (not the "Approval" which is another dedicated field):

image

Comment (VladoTTX) [reply src/Ticket.php]: Waw, I didn't know about the status APPROVAL until now.. I am not sure about the intention of adding this status and whether SLA should be running in this status (IMHO no, but probably author who added it should explain..)
But current code anywhere in GLPI counts with APPROVAL like normal status where clocks are ticking.. 
So you are right, in current situation also APPROVAL should be added to the check...

**Review by AdrienClairembault — APPROVED** [review]

File: src/Ticket.php [hunk 2]
```diff
@@ -1276,7 +1276,10 @@ public function manageSlaLevel($slas_id)
         $slalevels_id = SlaLevel::getFirstSlaLevel($slas_id);
 
         $sla = new SLA();
-        if ($sla->getFromDB($slas_id)) {
+        if (
+            $sla->getFromDB($slas_id)
+            && !in_array($this->fields['status'], static::getReopenableStatusArray())
```
Comment (cedric-anne) [inline src/Ticket.php]: It will prevent a useless query.

```suggestion
            !in_array($this->fields['status'], static::getReopenableStatusArray())
            && $sla->getFromDB($slas_id)
```

File: src/Ticket.php [hunk 3]
```diff
@@ -1306,7 +1309,10 @@ public function manageOlaLevel($slas_id)
         $olalevels_id = OlaLevel::getFirstOlaLevel($slas_id);
 
         $ola = new OLA();
-        if ($ola->getFromDB($slas_id)) {
+        if (
+            $ola->getFromDB($slas_id)
+            && !in_array($this->fields['status'], static::getReopenableStatusArray())
```
Comment (cedric-anne) [inline src/Ticket.php]:
```suggestion
            !in_array($this->fields['status'], static::getReopenableStatusArray())
            && $ola->getFromDB($slas_id)
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Please add a test case. The SLA feature in GLPI is pretty complex.

**Comment by cedric-anne** [comment]
@SebSept Since you worked on this part recently, are you able to add a test case for this?

**Comment by SebSept** [comment]
I'll write a test tomorrow

File: src/Ticket.php
Comment (SebSept) [inline src/Ticket.php:1295]: $sla may not be set at this point, which will cause an error (mysql error).

```patch
diff --git a/src/Ticket.php b/src/Ticket.php
@@ -1276,9 +1276,9 @@
         $slalevels_id = SlaLevel::getFirstSlaLevel($slas_id);
 
         $sla = new SLA();
+        $in_db = $sla->getFromDB($slas_id);
         if (
-            !in_array($this->fields['status'], static::getReopenableStatusArray())
-            && $sla->getFromDB($slas_id)
+            $in_db && !in_array($this->fields['status'], static::getReopenableStatusArray())
         ) {
             $sla->clearInvalidLevels($this->fields['id']);
             $calendars_id = Entity::getUsedConfig(
@@ -1290,7 +1290,10 @@
             $sla->setTicketCalendar($calendars_id);
             $sla->addLevelToDo($this, $slalevels_id);
         }
-        SlaLevel_Ticket::replayForTicket($this->getID(), $sla->getField('type'));
+
+        if ($in_db) {
+            SlaLevel_Ticket::replayForTicket($this->getID(), $sla->fields['type']);
+        }
     }
 
     /**
```

Or Maybe an early return can be done if sla is not in db.

```php
        if(!$in_db) {
            return;
        }
```

+ do the same in `manageOlaLevel()`

**Review by SebSept — CHANGES_REQUESTED** [review]

File: src/Ticket.php
Comment (SebSept) [reply src/Ticket.php:1295]: this is why ci tests fails.

**Comment by Maximjke** [comment]
Hello
Any updates?
Thanks in advance!

File: src/Ticket.php
Comment (VladoTTX) [reply src/Ticket.php:1295]: Thanks, should be fixed in latest commit

**Review by SebSept — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
