### PR TITLE
Fix unhandled curl exceptions from Toolbox::callCurl()

### LINKED ISSUE #20389: Uncaught PHP Exception Safe\Exceptions\CurlException
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11.0.0.Beta7

### Bug description

Hello,

I'm getting the following error when I try to access the section where there should be a space to enter the glpi network key.

Image

### Relevant log output

```shell
[2025-07-23 10:25:39] glpi.CRITICAL:   *** Uncaught PHP Exception Safe\Exceptions\CurlException: "Connection timed out after 5001 milliseconds" at CurlException.php line 12
  Backtrace :
  ...achine/safe/lib/Exceptions/CurlException.php:12 
  ...thecodingmachine/safe/generated/8.2/curl.php:67 Safe\Exceptions\CurlException::createFromPhpError()
  ./src/Toolbox.php:1435                             Safe\curl_exec()
  ./src/GLPINetwork.php:166                          Toolbox::callCurl()
  ./src/GLPINetwork.php:75                           GLPINetwork::getRegistrationInformations()
  ./src/GLPINetwork.php:57                           GLPINetwork::showForConfig()
  ./src/CommonGLPI.php:683                           GLPINetwork::displayTabContentForItem()
  ./ajax/common.tabs.php:111                         CommonGLPI::displayStandardTab()
  ...Glpi/Controller/LegacyFileLoadController.php:63 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.

## Description

Fix #20389.

### CODE REVIEW

File: src/Toolbox.php [hunk 1]
```diff
@@ -1371,6 +1373,57 @@ public static function callCurl(
         /** @var array $CFG_GLPI */
         global $CFG_GLPI;
 
+        try {
+            return self::doCallCurl($url, $eopts, $msgerr, $curl_error, $check_url_safeness, $curl_info);
+        } catch (CurlException $e) {
+            ErrorHandler::logCaughtException($e);
```
Comment (cedric-anne) [inline src/Toolbox.php]: In the future, I would like to remove usages of `ErrorHandler::logCaughtException()` that requires to maintain static usage of the error handler.

```suggestion
            /** @var LoggerInterface $PHPLOGGER */
            global $PHPLOGGER;
            $PHPLOGGER->error(
                $e->getMessage(),
                ['exception' => $e]
            );
```

File: src/EmptyCurlContentException.php [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <https://www.gnu.org/licenses/>.
+ *
+ * ---------------------------------------------------------------------
+ */
+
+/**
+ * Planning Class
+ **/
```
Comment (cedric-anne) [inline src/EmptyCurlContentException.php]:
```suggestion
```

File: src/EmptyCurlContentException.php [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+final class EmptyCurlContentException extends Exception {}
```
Comment (cedric-anne) [inline src/EmptyCurlContentException.php]: May be moved in `Glpi\Exception` namespace.

File: src/Toolbox.php [hunk 4]
```diff
@@ -1371,6 +1373,57 @@ public static function callCurl(
...
+            } else {
+                $msgerr = sprintf(
+                    __('Failed to connect to the proxy server (%s)'),
+                    $curl_error
+                );
+            }
+
+            return "";
+        } catch (EmptyCurlContentException $e) {
+            ErrorHandler::logCaughtException($e);
```
Comment (cedric-anne) [inline src/Toolbox.php]:
```suggestion
            /** @var LoggerInterface $PHPLOGGER */
            global $PHPLOGGER;
            $PHPLOGGER->error(
                $e->getMessage(),
                ['exception' => $e]
            );
```

File: src/Toolbox.php [hunk 5]
```diff
@@ -1371,6 +1373,57 @@ public static function callCurl(
...
+     * @throws EmptyCurlContentException
+     */
+    private static function doCallCurl(
+        $url,
+        array $eopts = [],
+        &$msgerr = null,
+        &$curl_error = null,
+        bool $check_url_safeness = false,
+        ?array &$curl_info = null
+    ) {
```
Comment (cedric-anne) [inline src/Toolbox.php]:
```suggestion
    ): string {
```

**Review by cedric-anne — APPROVED** [review]
