### PR TITLE
0 was not handled; fixes #13995

### LINKED ISSUE #13995: Personal View on Home page when Results to display on home page = 0
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

When an user configure: Results to display on home page = 0 

Personal View on Home page show all tickets in GLPI 9.4.11 

When the number of tickets is very hight the browser is colapsed

imagen

but  on GLPI 9.4.6 only show a head with the number of tickets and a link

imagen

Has this functionality been changed on purpose or is it a bug in this version?

### Relevant log output

_No response_

### Page URL

glpi/front/central.php

### Steps To reproduce

start glpi
Show Personal View 

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #13995

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

File: src/Change.php [hunk 1]
```diff
@@ -1128,7 +1128,7 @@ public static function showCentralList($start, $status = "process", $showgroupch
         $iterator = $DB->request($criteria);
 
         $total_row_count = count($iterator);
-        $displayed_row_count = (int)$_SESSION['glpidisplay_count_on_home'] > 0
+        $displayed_row_count = (int)$_SESSION['glpidisplay_count_on_home'] >= 0
```
Comment (cedric-anne) [inline src/Change.php:1131]: When `$_SESSION['glpidisplay_count_on_home']`, we still want to display the component to have the table head (i.e. the title/link/counter), without having table rows.

With proposed fix, nothing will be displayed.

Comment (trasher) [reply src/Change.php:1131]: OK, I did not has that in mind

**Review by cedric-anne — APPROVED** [review]
