### PR TITLE
Make sure DropdownTranslation::getTranslatedValue() do not returns null

### LINKED ISSUE #21838: [GLPI 11] Error page when displaying service catalogue with translation for a category description translated in "French"
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11.0.2

### Bug description

My default language is English, and I am trying to translate a category that contains several forms. 

Image

There is no problem with the title and comment fields, but when I want to translate the description, I get the following error message :

> Une erreur est survenue
Revenir à la page précédente
An exception has been thrown during the rendering of a template ("Glpi\Form\Category::getServiceCatalogItemDescription(): Return value must be of type string, null returned") in "components/helpdesk_forms/service_catalog_item.html.twig" at line 72.
In ./templates/components/helpdesk_forms/service_catalog_item.html.twig(72)
0 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
1 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
2 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
3 ./vendor/twig/twig/src/Extension/CoreExtension.php(1520): Twig\TemplateWrapper->render()
4 ./files/_cache/11.0.2-52505ef9-production/templates/93/93ebe2e9edfd7da7e33581f1c5039e2d.php(136): Twig\Extension\CoreExtension::include()
5 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_0455b8eeaaca551336ba3a5e81731baf->doDisplay()
6 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
7 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
8 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
9 ./vendor/twig/twig/src/Extension/CoreExtension.php(1520): Twig\TemplateWrapper->render()
10 ./files/_cache/11.0.2-52505ef9-production/templates/1b/1b3b128b3dc88bee58d67011eb515b5c.php(140): Twig\Extension\CoreExtension::include()
11 ./vendor/twig/twig/src/Template.php(446): __TwigTemplate_c9da388d8014a00e0b57dc1ae4c32be6->block_content_body()
12 ./files/_cache/11.0.2-52505ef9-production/templates/59/5980a5fa29e6fb8da46ffc7a775532f9.php(80): Twig\Template->yieldBlock()
13 ./vendor/twig/twig/src/Template.php(446): __TwigTemplate_74676ad001615867624bff4d58631167->block_content()
14 ./files/_cache/11.0.2-52505ef9-production/templates/b9/b9d261b3a8dcc4775238b3c9c67c2cd1.php(62): Twig\Template->yieldBlock()
15 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_8427efc2b0eca407d2122875d596750b->doDisplay()
16 ./files/_cache/11.0.2-52505ef9-production/templates/59/5980a5fa29e6fb8da46ffc7a775532f9.php(49): Twig\Template->yield()
17 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_74676ad001615867624bff4d58631167->doDisplay()
18 ./files/_cache/11.0.2-52505ef9-production/templates/1b/1b3b128b3dc88bee58d67011eb515b5c.php(55): Twig\Template->yield()
19 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_c9da388d8014a00e0b57dc1ae4c32be6->doDisplay()
20 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
21 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
22 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
23 ./src/Glpi/Application/View/TemplateRenderer.php(170): Twig\TemplateWrapper->render()
24 ./src/Glpi/Controller/AbstractController.php(68): Glpi\Application\View\TemplateRenderer->render()
25 ./src/Glpi/Controller/ServiceCatalog/IndexController.php(98): Glpi\Controller\AbstractController->render()
26 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\ServiceCatalog\IndexController->__invoke()
27 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
28 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
29 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle()
30 {main}

> Previous: Glpi\Form\Category::getServiceCatalogItemDescription(): Return value must be of type string, null returned
In ./src/Glpi/Form/Category.php(129)
0 ./vendor/twig/twig/src/Extension/CoreExtension.php(1913): Glpi\Form\Category->getServiceCatalogItemDescription()
1 ./files/_cache/11.0.2-52505ef9-production/templates/53/53ecaad0a5c594d4589caca622f004d6.php(122): Twig\Extension\CoreExtension::getAttribute()
2 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_dbbaa7269a853a486c37a336c899c065->doDisplay()
3 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
4 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
5 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
6 ./vendor/twig/twig/src/Extension/CoreExtension.php(1520): Twig\TemplateWrapper->render()
7 ./files/_cache/11.0.2-52505ef9-production/templates/93/93ebe2e9edfd7da7e33581f1c5039e2d.php(136): Twig\Extension\CoreExtension::include()
8 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_0455b8eeaaca551336ba3a5e81731baf->doDisplay()
9 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
10 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
11 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
12 ./vendor/twig/twig/src/Extension/CoreExtension.php(1520): Twig\TemplateWrapper->render()
13 ./files/_cache/11.0.2-52505ef9-production/templates/1b/1b3b128b3dc88bee58d67011eb515b5c.php(140): Twig\Extension\CoreExtension::include()
14 ./vendor/twig/twig/src/Template.php(446): __TwigTemplate_c9da388d8014a00e0b57dc1ae4c32be6->block_content_body()
15 ./files/_cache/11.0.2-52505ef9-production/templates/59/5980a5fa29e6fb8da46ffc7a775532f9.php(80): Twig\Template->yieldBlock()
16 ./vendor/twig/twig/src/Template.php(446): __TwigTemplate_74676ad001615867624bff4d58631167->block_content()
17 ./files/_cache/11.0.2-52505ef9-production/templates/b9/b9d261b3a8dcc4775238b3c9c67c2cd1.php(62): Twig\Template->yieldBlock()
18 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_8427efc2b0eca407d2122875d596750b->doDisplay()
19 ./files/_cache/11.0.2-52505ef9-production/templates/59/5980a5fa29e6fb8da46ffc7a775532f9.php(49): Twig\Template->yield()
20 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_74676ad001615867624bff4d58631167->doDisplay()
21 ./files/_cache/11.0.2-52505ef9-production/templates/1b/1b3b128b3dc88bee58d67011eb515b5c.php(55): Twig\Template->yield()
22 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_c9da388d8014a00e0b57dc1ae4c32be6->doDisplay()
23 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
24 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
25 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
26 ./src/Glpi/Application/View/TemplateRenderer.php(170): Twig\TemplateWrapper->render()
27 ./src/Glpi/Controller/AbstractController.php(68): Glpi\Application\View\TemplateRenderer->render()
28 ./src/Glpi/Controller/ServiceCatalog/IndexController.php(98): Glpi\Controller\AbstractController->render()
29 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\ServiceCatalog\IndexController->__invoke()
30 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
31 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
32 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle()
33 {main}
Retour en haut de page

### Relevant log output

```shell

```

### Page URL

https://glpi.domain.com/ServiceCatalog

### Steps To reproduce

1. Set english as default language for user
2. Create a service catalog category
3. Translate in french the description of this category
4. Go on : https://glpi.domain.com/ServiceCatalog
5. See the error message

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.2 ( =&gt; /var/www/html/glpi)
Installation mode: TARBALL
Current language: fr_FR
Source Integrity: 7 files changed
  D: install/install.php
  A: public/pics/logos/emptyPx.png
  M: public/pics/logos/logo-G-100-white.png
  M: public/pics/logos/logo-GLPI-100-white.png
  M: public/pics/logos/logo-GLPI-250-black.png
  A: src/Glpi/Search/Provider/OLD-SQLProvider.php
  M: src/Glpi/Search/Provider/SQLProvider.php</pre></details><details><summary>Server</summary><pre>Operating system: Linux LIN-DIN006-Z 6.12.48+deb13-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.12.48-1 (2025-09-20) x86_64

PHP: 8.4.11 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext,
iconv, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm,
tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;128M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache/2.4.65 (Debian) (Apache/2.4.65 (Debian) Server at itsm.cordongroup.com Port 80)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
Edg/142.0.0.0

Database:
   
Server Software: -- Please help get to 10k stars at https://github.com/MariaDB/Server
   
Server Version: 11.8.3-MariaDB-0+deb13u1 from Debian
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@172.16.10.15/itsm
   
Host info: 172.16.10.15 via TCP/IP

Requirements:
PHP version (8.4.11) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (11.8.3) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/html/glpi&quot;
GLPI_VERSION: &quot;11.0.2&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.2@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.2-52505ef9&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi/locales&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_CONFIG_DIR: &quot;/var/www/html/glpi/config&quot;
GLPI_VAR_DIR: &quot;/var/www/html/glpi/files&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/www/html/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/var/www/html/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/www/html/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/www/html/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/www/html/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/www/html/glpi/files/_lock&quot;
GLPI_LOG_DIR: &quot;/var/www/html/glpi/files/_log&quot;
GLPI_PICTURE_DIR: &quot;/var/www/html/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/www/html/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/www/html/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/www/html/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/www/html/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/www/html/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/www/html/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/www/html/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi/marketplace&quot;,&quot;/var/www/html/glpi/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>Annuaires LDAP</summary><pre>Server: &#39;ldap://172.16.10.1&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;OU=CordonGroup,DC=corp,DC=cordongroup,DC=com&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(mail=*@*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;CN=svc_ldap,OU=Infra,DC=corp,DC=cordongroup,DC=com&#39;, 
	Use TLS: none

Server: &#39;ldap://10.22.2.1:3268&#39;, 
	Port: none, 
	BaseDN: &#39;DC=cordon,DC=cordonweb,DC=com&#39;, 
	Connection filter:
&#39;(&amp;(objectClass=user)(objectCategory=person)(extensionAttribute10=*@*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;CN=LDAP Connector,CN=Users,DC=cordon,DC=cordonweb,DC=com&#39;, 
	Use TLS: none</pre></details><details><summary>Réplicats SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://fortimail.cordongroup.com:25)
Name: &#39;itsm@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm@cordongroup.com&#39;
	Password: No
Name: &#39;itsm.infra@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.infra@cordongroup.com&#39;
	Password: Yes
Name: &#39;itsm.ssi@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.ssi@cordongroup.com&#39;
	Password: No
Name: &#39;itsm.mwp@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.mwp@cordongroup.com&#39;
	Password: No
Name: &#39;itsm.sysnet@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.sysnet@cordongroup.com&#39;
	Password: No</pre></details><details><summary>Plugins list</summary><pre>fields               Name: Additional fields              Version: 1.23.0     State: Activé                                 
Install Method: Marketplace
news                 Name: Alerts                         Version: 1.13.0     State: Activé                                 
Install Method: Marketplace
behaviors            Name: Behaviours                     Version: 3.0.1      State: Erreur / à nettoyer                    
Install Method: Manual
mydashboard          Name: Dashboard                      Version: 2.2.2      State: Non installé                           
Install Method: Marketplace
webapplications      Name: Dashboard applicatif           Version: 5.1.2      State: Non installé                           
Install Method: Marketplace
datainjection        Name: Data injection                 Version: 2.15.1     State: Activé                                 
Install Method: Marketplace
escalade             Name: Escalation                     Version: 2.10.0     State: Activé                                 
Install Method: Marketplace
formcreator          Name: Form Creator                   Version: 3.0.0      State: Installé / non activé                 
Install Method: Marketplace
tag                  Name: Gestion des tags               Version: 2.13.0     State: Non installé                           
Install Method: Marketplace
uninstall            Name: Item&#39;s Lifecycle (uninstall)   Version: 2.10.2     State: Non installé                           
Install Method: Marketplace
oauthimap            Name: Oauth IMAP                     Version: 1.5.0      State: Activé                                 
Install Method: Marketplace
samlsso              Name: samlsso                        Version: 1.2.2      State: Activé                                 
Install Method: Marketplace
manufacturersimports Name: Suppliers imports              Version: 3.1.1      State: Activé                                 
Install Method: Marketplace</pre></details><details><summary>Locales overrides</summary><pre>/var/www/html/glpi/files/_locales/formcreator/form_11_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_11_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_13_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_14_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_14_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_15_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_16_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_16_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_17_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_18_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_18_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_19_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_19_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_1_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_20_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_20_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_21_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_21_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_22_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_22_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_23_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_23_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_24_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_24_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_25_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_25_fr_FR.php
/var/www/html/glpi/files/_locales/formcreator/form_3_en_US.php
/var/www/html/glpi/files/_locales/formcreator/form_3_fr_FR.php</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

PHPDoc from `DropdownTranslationgetTranslatedValue()` says it return a string but it is not true as the translation itself can be null in the database:

image

This create some issues as code calling this method don't expect a null value here, leading to fatal errors:

> An exception has been thrown during the rendering of a template ("Glpi\Form\Category::getServiceCatalogItemDescription(): Return value must be of type string, null returned") in "components/helpdesk_forms/service_catalog_item.html.twig" at line 72.

I've fixed it by making sure we do not null return null value, as indicated by the PHPDoc return hint.

## References

Fix #21838.

### CODE REVIEW

File: src/DropdownTranslation.php [hunk 1]
```diff
@@ -571,7 +571,7 @@ public static function getTranslatedValue($ID, $itemtype, $field = 'name', $lang
                 // The field is already translated in this language
                 if (count($iterator)) {
                     $current = $iterator->current();
-                    return $current['value'];
+                    return $current['value'] ?? "";
```
Comment (cedric-anne) [inline src/DropdownTranslation.php]: IMHO, you should not return an empty string here, as a null value should probably be considered identical as "no tranlation". Maybe a `['NOT' => ['value' => null]]` criteria should be added to the previous query.

File: src/DropdownTranslation.php [hunk 2]
```diff
@@ -582,7 +582,7 @@ public static function getTranslatedValue($ID, $itemtype, $field = 'name', $lang
             ]);
             if (count($iterator)) {
                 $current = $iterator->current();
-                return $current[$field];
+                return $current[$field] ?? "";
```
Comment (cedric-anne) [inline src/DropdownTranslation.php]: Same here.

File: src/DropdownTranslation.php (hunk 1 above)
Comment (trasher) [reply src/DropdownTranslation.php]: Looking at the code, it seems the value is just used as is (in GLPI core at least).

Comment (trasher) [reply src/DropdownTranslation.php]: I submit before I finished :D
So behavior is from a code pov the same.

From a logical point of view, having null or an empty string in a translated value both means "no translation".

**Review by trasher — APPROVED** [review]

File: src/DropdownTranslation.php [hunk 3]
```diff
@@ -571,7 +571,7 @@ public static function getTranslatedValue($ID, $itemtype, $field = 'name', $lang
                 // The field is already translated in this language
                 if (count($iterator)) {
                     $current = $iterator->current();
-                    return $current['value'];
+                    return $current['value'] ?? $value;
```
Comment (cedric-anne) [inline src/DropdownTranslation.php]: To fallback to `// Get the value coming from the dropdown table`.
```suggestion
                    if (!empty($current['value'])) {
                        return $current['value'];
                    }
```

File: src/DropdownTranslation.php [hunk 4]
```diff
@@ -582,7 +582,7 @@ public static function getTranslatedValue($ID, $itemtype, $field = 'name', $lang
             ]);
             if (count($iterator)) {
                 $current = $iterator->current();
-                return $current[$field];
+                return $current[$field] ?? $value;
```
Comment (cedric-anne) [inline src/DropdownTranslation.php]:
```suggestion
                if (!empty($current[$field])) {
                    return $current[$field];
                }
```

File: src/DropdownTranslation.php [hunk 5]
```diff
@@ -582,7 +582,7 @@ public static function getTranslatedValue($ID, $itemtype, $field = 'name', $lang
...
             }
         }
```
Comment (cedric-anne) [inline src/DropdownTranslation.php:592]: on next line `return $value;`

File: src/KnowbaseItemTranslation.php [hunk 6]
```diff
@@ -291,9 +291,9 @@ public static function getTranslatedValue(KnowbaseItem $item, $field = "name")
             && in_array($field, ['name', 'answer'])
         ) {
             $first = array_shift($found);
-            return $first[$field];
+            return $first[$field] ?? "";
```
Comment (cedric-anne) [inline src/KnowbaseItemTranslation.php]:
```suggestion
            if (!empty($first[$field])) {
                return $first[$field];
            }
```

File: src/ReminderTranslation.php [hunk 7]
```diff
@@ -243,9 +243,9 @@ public static function getTranslatedValue(Reminder $item, $field = "name")
             && in_array($field, ['name', 'text'])
         ) {
             $first = array_shift($found);
-            return $first[$field];
+            return $first[$field] ?? "";
```
Comment (cedric-anne) [inline src/ReminderTranslation.php]:
```suggestion
            if (!empty($first[$field])) {
                return $first[$field] ?? "";
            }
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/DropdownTranslation.php (hunk 3 above)
Comment (AdrienClairembault) [reply src/DropdownTranslation.php]: I'll use a strict comparison as empty would return true for "0", which could possibly be a valid translation.

File: tests/functional/DropdownTranslationTest.php [hunk 8]
```diff
@@ -200,4 +202,36 @@ public function testgetTranslatedCompletename(): void
             }
         }
     }
+
+    /**
+     * Regression test to make sure getTranslatedValue return a string even if
+     * the translation value is null.
+     */
+    public function testNullValue(): void
```
Comment (cedric-anne) [inline tests/functional/DropdownTranslationTest.php]:
```suggestion
    public function testGetTanslatedValueFallbackToDropdownValue(): void
```

File: tests/functional/DropdownTranslationTest.php [hunk 9]
```diff
@@ -200,4 +202,36 @@ public function testgetTranslatedCompletename(): void
...
+        // Act: get translation
+        $translation = DropdownTranslation::getTranslatedValue(
+            $category->getID(),
+            Category::class,
+            'description',
+            'fr_FR',
+            'my fallback value'
+        );
+
+        // Assert: translation should not be null
```
Comment (cedric-anne) [inline tests/functional/DropdownTranslationTest.php]:
```suggestion
        // Assert: translation should correspond to the untranslated value
```

File: tests/functional/DropdownTranslationTest.php [hunk 10]
```diff
@@ -200,4 +202,36 @@ public function testgetTranslatedCompletename(): void
...
+        $this->assertEquals('My description', $translation);
+    }
```
Comment (cedric-anne) [inline tests/functional/DropdownTranslationTest.php:236]:
```suggestion
    }

    /**
     * Regression test to make sure getTranslatedValue return a string even if
     * the translation value is null.
     */
    public function testGetTanslatedValueFallbackToDefaultValue(): void
    {
        // Arrange: create a null translation
        $category = $this->createItem(Category::class, [
            'name'        => 'My category',
            'description' => '',
        ]);
        $this->createItem(DropdownTranslation::class, [
            'items_id' => $category->getID(),
            'itemtype' => Category::class,
            'language' => 'fr_FR',
            'field'    => 'description',
            'value'    => null,
        ]);

        // Act: get translation
        $translation = DropdownTranslation::getTranslatedValue(
            $category->getID(),
            Category::class,
            'description',
            'fr_FR',
            'my fallback value'
        );

        // Assert: translation should correspond to the given fallback value parameter
        $this->assertEquals('my fallback value', $translation);
    }
```

File: tests/functional/DropdownTranslationTest.php [hunk 11]
```diff
@@ -200,4 +202,68 @@ public function testgetTranslatedCompletename(): void
...
+            'my fallback value'
+        );
+
+        // Assert: translation should correspond to the untranslated value
+        $this->assertEquals('My description', $translation);
+    }
+
+    /**
+     * Regression test to make sure getTranslatedValue return a string even if
+     * the translation value is null.
```
Comment (cedric-anne) [inline tests/functional/DropdownTranslationTest.php]:
```suggestion
     * the translation value is null and the untranslated value is empty.
```

**Review by trasher — APPROVED** [review]
