### PR TITLE
Fix unset kb category

### LINKED ISSUE #21873: Crash when trying to save a knowledge article with no category
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.2

### Bug description

When I try to save a knowledge base article with no category - such that it shows up under the 'without category' section in Self-Service -, I get an unexpected error message. When looking up in the logs I get this error:

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create a new knowledge article leaving the 'knowledgebase category' empty.
2. Hit Save.
3. The unexpected error pops up and the item is not saved.

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

Fixes #21873

### CODE REVIEW

File: tests/functional/KnowbaseItemTest.php [hunk 1]
```diff
@@ -1665,4 +1665,46 @@ public function testClone()
...
+            1,
+            countElementsInTable(
+                \KnowbaseItem_KnowbaseItemCategory::getTable(),
+                ['knowbaseitems_id' => $kbi->getID()]
+            )
+        );
+        $kbi->update([
+            'id' => $kbi->getID(),
+            '_categories' => '',
+            '__categories_defined' => 1
```
Comment (trasher) [inline tests/functional/KnowbaseItemTest.php]:
```suggestion
            '__categories_defined' => 1,
```

File: tests/functional/KnowbaseItemTest.php [hunk 2]
```diff
@@ -1665,4 +1665,46 @@ public function testClone()
...
+            'name' => __FUNCTION__,
+            'entities_id' => $this->getTestRootEntity(true),
+            'is_recursive' => 1,
+            'knowbaseitemcategories_id' => 0,
+        ]);
+
+        $kbi->update([
+            'id' => $kbi->getID(),
+            '_categories' => [$category->getID()],
+            '__categories_defined' => 1
```
Comment (trasher) [inline tests/functional/KnowbaseItemTest.php]:
```suggestion
            '__categories_defined' => 1,
```
