### PR TITLE
Fix : Category and Type unavailable in Ticket Template selectable fields

### LINKED ISSUE #21313: GLPI 11.0.0 ticket templates (predefined fields)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0

### Bug description

When creating a template in the "Predefined Fields" tab, the "Category" option is not displayed:

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Lainow**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #21313
- Here is a brief description of what this PR does
In the list of fields that can be selected as Predefined/Mandatory and Hidden Fields for a Ticket Template, the category and type were no longer visible. (Whereas they were visible in version 10.)

### CODE REVIEW

**Review by trasher — APPROVED** [review]

**Comment by cconard96** [comment]
Not sure. In GLPI 10, the behavior was:

- Predefined: Showed category and type
https://github.com/glpi-project/glpi/blob/9fa7b535022f5f8c97922246dbf78f724d14aa0a/src/ITILTemplatePredefinedField.php#L288

- Hidden: Did not show category and type
https://github.com/glpi-project/glpi/blob/9fa7b535022f5f8c97922246dbf78f724d14aa0a/src/ITILTemplateHiddenField.php#L175

- Mandatory: Showed category and type
https://github.com/glpi-project/glpi/blob/9fa7b535022f5f8c97922246dbf78f724d14aa0a/src/ITILTemplateMandatoryField.php#L175
https://github.com/glpi-project/glpi/blob/9fa7b535022f5f8c97922246dbf78f724d14aa0a/src/ITILTemplateField.php#L74

File: src/ITILTemplateField.php [hunk 1]
```diff
@@ -131,7 +131,7 @@ abstract public static function getExcludedFields();
      *
      * @return bool
      **/
-    public static function showForITILTemplate(ITILTemplate $tt, $withtemplate = 0): bool
+    public static function showForITILTemplate(ITILTemplate $tt, $withtemplate = 0, $withtypeandcategory = true): bool
```
Comment (Rom1-B) [inline src/ITILTemplateField.php]: I’m not sure modifying this function is necessary, as it is only called once and with `$withtypeandcategory` set to `false`. So, on line 144, the code remains `$fields = $tt->getAllowedFieldsNames(false);` as in the original version.

```suggestion
    public static function showForITILTemplate(ITILTemplate $tt, $withtemplate = 0): bool
```

Comment (Lainow) [reply src/ITILTemplateField.php]: It is called in ITILTemplateField and ITILTemplatePredefinedField where it is set to True, and it is only in ITILTemplateHiddenFIeld that it must be set to false.

Comment (Rom1-B) [reply src/ITILTemplateField.php]: In this case, it would seem more consistent to set `$withtypeandcategory = false` by default, as in the `getAllowedFieldsNames()` function used immediately afterwards, and to modify the other two calls with `$withtypeandcategory = true`.
