### PR TITLE
fix: use friendly name for User objects in QuestionTypeItem

### LINKED ISSUE #22856: [Forms] User selection in native Forms displays Login instead of Full Name (GLPI 11)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [ ] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

Hello,

In the new native Forms module of GLPI 11, there is a display issue when selecting User objects.

**Environment:**

GLPI version: 11.0.4

PHP version: 8.4

**Steps to reproduce:**

Image

Use the native Forms feature (not the old plugin).

Add a question of type GLPI Object.

Select Administration > Users as the target object.

Fill out the form and select a user.

View the submitted response/answer.

Expected behavior: The answer should display the user's Full Name.

Actual behavior: The answer displays only the Login/Logon name (the name field in the database).

Additional information: This issue seems to be related to how the new native Forms module handles the getFriendlyName or the display parameters for the User class in the transition to GLPI 11. Given that I am using PHP 8.4, there might also be a compatibility nuance in how object strings are rendered.

Thank you for looking into this!

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by husisusi**
## Summary
This PR improves how User objects are displayed within `QuestionTypeItem`. It adds a specific check to use the `getFriendlyName()` method when the item is a `User` instance, rather than defaulting to the raw `name` field.

## Related Issue
Fixes #22856

## Solution
- Added a check `if ($item instanceof \User)`.
- Implemented `getFriendlyName()` for User objects to ensure the proper display name (e.g., Firstname Lastname) is returned.
- Retained the fallback to `$item->fields['name']` for non-user objects.

## Technical Details
Modified `src/Glpi/Form/QuestionType/QuestionTypeItem.php` to handle the `\User` class specifically before returning the label.

### CODE REVIEW

**Review by AdrienClairembault — APPROVED** [review]
Thanks for the contribution, looks good 👍

**Review by ccailly — APPROVED** [review]

File: src/Glpi/Form/QuestionType/QuestionTypeItem.php [hunk 1]
```diff
@@ -407,6 +407,11 @@ public function formatRawAnswer(mixed $answer, Question $question): string
             return '';
         }
 
+        // If the object is a user, use getFriendlyName()
+        if ($item instanceof \User) {
```
Comment (trasher) [inline src/Glpi/Form/QuestionType/QuestionTypeItem.php]:
```suggestion
        if ($item instanceof User) {
```
