### PR TITLE
deduplicate my devices dropdown

### LINKED ISSUE #22914: items duplicated for requester in ticket
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.5

### Bug description

in the de device list apears duplicated items

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

fixes #22914

### CODE REVIEW

File: tests/functional/DropdownTest.php [hunk 1]
```diff
@@ -2779,6 +2788,12 @@ public function testGetDropdownMyDevices()
                             'itemtype' => Computer::class,
                             'items_id' => $computer_1->getID(),
                         ],
+                        [
+                            'id'       => Computer::class . '_' . $computer_3->getID(),
+                            'text'     => 'Test user and group Laptop - LAP789 - INV999',
+                            'itemtype' => Computer::class,
+                            'items_id' => $computer_3->getID(),
+                        ]
```
Comment (trasher) [inline tests/functional/DropdownTest.php]:
```suggestion
                        ],
```

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
