### PR TITLE
Fix image paste on tickets on IE

### LINKED ISSUE #3866: [9.2.1 to 9.3] Cannot paste images in tinyMCE on Internet Explorer
Problem only on IExplorer 11
Works on Firefox or Chrome

* Steps to reproduce (which actions have you made) :
Make a screenshot (png or jpg) and paste it in the ticket (tinyMCE)

* Expected result :
Image uploaded and included in the text of ticket

* Actual result :
Image refused and an error about the format of file.
"Type de fichier non autorisé"

* URL of the page :
http://GLPI/front/ticket.form.php

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.3-dev ( => /var/www/html)
Installation mode: TARBALL

Operating system: Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64
PHP 5.6.33 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring,
	mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.33 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Server Software: MariaDB Server
	Server Version: 5.5.56-MariaDB
	Server SQL Mode: 
	Parameters: glpiuser@127.0.0.1/glpidb
	Host info: 127.0.0.1 via TCP/IP

Thank you ;) !

### PR DESCRIPTION
**Pull request by AnaelMobilia**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3866

  - Fix error "Filetype not allowed" on pasting image (ctrl + v) on tinymce on a ticket with IE11
  - Fix undefined or null reference when right click-> paste on IE11 => display error message
Fix #3866

### CODE REVIEW

File: js/fileupload.js [hunk 1]
```diff
@@ -385,7 +396,7 @@ if (typeof tinymce != 'undefined') {
                   var file  = new Blob([this.response], {type: 'image/png'});
                   file.name = 'image_paste'+ Math.floor((Math.random() * 10000000) + 1)+".png";
 
-                  uploaded = insertImageInTinyMCE(editor, file);
+                    uploaded = insertImageInTinyMCE(editor, file);
```
Comment (orthagh) [inline js/fileupload.js]: remove this change (CS break)

File: js/fileupload.js [hunk 2]
```diff
@@ -64,7 +64,13 @@ function uploadFile(file, editor, input_name) {
       },
 
       error: function (request) {
-         alert(request.responseText);
+         // If this is an error on the return
+         if (request.responseText !== undefined) {
+            alert(request.responseText);
+         } else {
+            // Error before sending request #3866
+            alert(request.statusText);
```
Comment (orthagh) [inline js/fileupload.js]: i don't have in mind what text this could return, but i think alert (sending status to final user) it is a bad idea.
Doing a `console.error(...)` could be better

File: inc/html.class.php [hunk 3]
```diff
@@ -5322,7 +5322,10 @@ static function redefineAlert() {
       echo self::scriptBlock("
       window.old_alert = window.alert;
       window.alert = function(message, caption) {
-         message = message.replace('\\n', '<br>');
+         // Don't apply methods on undefined objects... ;-) #3866
+         if(message !== undefined) {
```
Comment (orthagh) [inline inc/html.class.php]: i think this test could be better with: `message.length > 0` or `typeof message == "String"`
Test it !

File: js/fileupload.js [hunk 4]
```diff
@@ -64,7 +64,13 @@ function uploadFile(file, editor, input_name) {
       },
 
       error: function (request) {
-         alert(request.responseText);
+         // If this is an error on the return
+         if (request.responseText !== undefined) {
```
Comment (orthagh) [inline js/fileupload.js]: better test:
```javascript
if ("responseText" in request
    && request.responseText.length > 0) {
```

File: js/fileupload.js (hunk 2 above)
Comment (AnaelMobilia) [reply js/fileupload.js]: @orthagh In case of css error (as in this case for IE), the user have an empty pop-up that is showing.
Imho, it's better to have a "technical" error message than a empty box.

For example, if you test on IE11, you will have "Error : Access Refused" that is showing

Regards

File: inc/html.class.php (hunk 3 above)
Comment (AnaelMobilia) [reply inc/html.class.php]: @orthagh undefined.anything is never a great idea ;-)
I update for the typeof comparision !

File: js/fileupload.js [hunk 5]
```diff
@@ -368,6 +374,11 @@ if (typeof tinymce != 'undefined') {
             //transform to blob and insert into editor
             if (base64.length) {
                var file = dataURItoBlob(base64);
+               // Fix #3866 - undefined file name
+               if (file.name === undefined) {
```
Comment (orthagh) [inline js/fileupload.js]: another candidate for `typeof` test :)

After that, it should be ok for merge

**Comment by trasher** [comment]
Should target 9.2/bf branch. I'll rebase.

**Comment by trasher** [comment]
Finally, I rebase on 9.3/bf; there are lots of conflicts to deal with on 9.2. If you want to get this one fixed on 9.2.x; I guess this should be done in another PR.
