### PR TITLE
Fix custom asset permissions in cloned profiles

### LINKED ISSUE #20007: Cloning profiles doesn't sync custom object rights
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

main

### Bug description

Cloning a profile also clones the profile rights. In the case of custom assets and custom dropdowns the rights are properly set from the Profile side, but when looking at the permission tab for the asset/dropdown definition the rights are missing.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create profile with permissions for a custom asset
2. Clone the profile
3. Check the Profiles tab for the custom asset

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

Fixes #20007
This PR makes profiles sync rights with the custom asset definition when profiles are created/cloned, not just when they are updated.

### CODE REVIEW

File: phpunit/functional/ProfileTest.php [hunk 1]
```diff
@@ -200,8 +201,20 @@ public function testClone()
 
         // Get default "Admin" profile
         $profile = new \Profile();
+        // TODO Test sync of custom asset permissions
```
Comment (trasher) [inline phpunit/functional/ProfileTest.php]: If it's done, this should be removed.

File: .phpstan-baseline.php [hunk 2]
```diff
@@ -7186,7 +7186,7 @@
 $ignoreErrors[] = [
 	'message' => '#^Property Profile\\:\\:\\$profileRight \\(array\\) does not accept null\\.$#',
 	'identifier' => 'assign.propertyType',
-	'count' => 2,
+	'count' => 1,
```
Comment (trasher) [inline .phpstan-baseline.php]: There should be ne new entries in phpstan baseline. Either issues have to be fixed; or properly ignored in code for false positives.

Comment (cconard96) [reply .phpstan-baseline.php]: This is a removal of one instance of the error, not an addition.

Comment (trasher) [reply .phpstan-baseline.php]: Sorry, I misread

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Tests are failing.

**Comment by cconard96** [comment]
Test never fails for me locally/in test docker env.

**Comment by trasher** [comment]
I reproduce fail on my local instance

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
