### PR TITLE
fix path used by icon dropdown

### LINKED ISSUE #19585: [main] Document type : icons path error (is not a directory)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

main

### Bug description

In the document type forms (new, or editing an existing one), the "Icon" field is in error, it cannot find the directory.

Image

### Relevant log output

```shell
no log
```

### Page URL

https://glpimain/front/documenttype.form.php

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Fixes #19585

This specific icon dropdown is only used to show icons from `/pics/icones` and even if another location was specified, the actual images always assumed to be served from the '/pics/icones` web URL. I changed the dropdown method to not have a configurable store path, fixed the path to point to the new location in the public folder, and cleaned up the error reporting.

### CODE REVIEW

File: src/Dropdown.php [hunk 1]
```diff
@@ -959,7 +959,7 @@ public static function dropdownUsedItemTypes($name, $itemtype_ref, $options = []
      *
      * @param string  $myname      the name of the HTML select
      * @param mixed   $value       the preselected value we want
-     * @param string  $store_path  path where icons are stored
+     * @param string  $store_path  path where icons are stored (No longer used)
```
Comment (trasher) [inline src/Dropdown.php:962]: If store_path is passed; it should trhow a depreciation message.

**Comment by flegastelois** [comment]
Related to #19585

File: src/Dropdown.php [hunk 2]
```diff
@@ -959,79 +959,85 @@ public static function dropdownUsedItemTypes($name, $itemtype_ref, $options = []
...
+            $error_msg = __('Error reading icon directory');
+            echo <<<HTML
+            <div class="alert alert-danger">
+                <span class="fs-4 alert-title">
+                    $error_msg
+                </span>
+            </div>
+HTML;
+
+            trigger_error(sprintf(__('Error reading directory %s'), $icon_path), E_USER_WARNING);
```
Comment (cedric-anne) [inline src/Dropdown.php:1040]: Logged messages should not be translated. We want to have untranslated log messages when someone report a bug.

```suggestion
            trigger_error(sprintf('Error reading directory %s', $icon_path), E_USER_WARNING);
```

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]
