### PR TITLE
filter aggregate metadata in Printer_CartridgeInfo

### LINKED ISSUE #21512: GLPI 11.0.1 - Error when displaying front/printed.php page
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

When navigate to Assets > Printers gets these error:
```
An exception has been thrown during the rendering of a template ("Printer_CartridgeInfo::createCartridgeInformationBadge(): Argument #1 ($data) must be of type array, int given, called in ./src/Printer_CartridgeInfo.php on line 247") in "pages/generic_list.html.twig" at line 37.
In ./templates/pages/generic_list.html.twig(37)
#0 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
#1 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
#2 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
#3 ./src/Glpi/Application/View/TemplateRenderer.php(170): Twig\TemplateWrapper->render()
#4 ./src/Glpi/Controller/AbstractController.php(68): Glpi\Application\View\TemplateRenderer->render()
#5 ./src/Glpi/Controller/GenericListController.php(51): Glpi\Controller\AbstractController->render()
#6 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\GenericListController->__invoke()
#7 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#8 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#9 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle()
#10 {main}

Previous: Printer_CartridgeInfo::createCartridgeInformationBadge(): Argument #1 ($data) must be of type array, int given, called in ./src/Printer_CartridgeInfo.php on line 247
In ./src/Printer_CartridgeInfo.php(211)
#0 ./src/Printer_CartridgeInfo.php(247): Printer_CartridgeInfo::createCartridgeInformationBadge()
#1 [internal function]: Printer_CartridgeInfo::{closure}()
#2 ./src/Printer_CartridgeInfo.php(246): array_map()
#3 ./src/Glpi/Search/Provider/SQLProvider.php(6755): Printer_CartridgeInfo::getSpecificValueToDisplay()
#4 ./src/Glpi/Search/Provider/SQLProvider.php(5187): Glpi\Search\Provider\SQLProvider::giveItem()
#5 ./src/Glpi/Search/SearchEngine.php(655): Glpi\Search\Provider\SQLProvider::constructData()
#6 ./src/Glpi/Search/SearchEngine.php(670): Glpi\Search\SearchEngine::getData()
#7 ./src/Glpi/Search/SearchEngine.php(627): Glpi\Search\SearchEngine::showOutput()
#8 [internal function]: Glpi\Search\SearchEngine::show()
#9 ./src/Glpi/Application/View/Extension/PhpExtension.php(93): call_user_func_array()
#10 /home/itsp/var/glpi/_cache/11.0.1-3a9929cf-production/templates/a7/a73879c82b08ddcc5dbc021bf36198ae.php(55): Glpi\Application\View\Extension\PhpExtension->call()
#11 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_0e83943f97e9d2a632162b0d53820427->doDisplay()
#12 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
#13 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
#14 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
#15 ./src/Glpi/Application/View/TemplateRenderer.php(170): Twig\TemplateWrapper->render()
#16 ./src/Glpi/Controller/AbstractController.php(68): Glpi\Application\View\TemplateRenderer->render()
#17 ./src/Glpi/Controller/GenericListController.php(51): Glpi\Controller\AbstractController->render()
#18 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\GenericListController->__invoke()
#19 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#20 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#21 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle()
#22 {main}
```

### Relevant log output

```shell

```

### Page URL

front/printer.php

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
## Description

- It fixes #21512
- Here is a brief description of what this PR does

Handle behavior on printer cartridges info

### CODE REVIEW

File: tests/functional/Printer_CartridgeInfoTest.php [hunk 1]
```diff
@@ -0,0 +1,227 @@
...
+{
+    public function testGetSpecificValueToDisplayWithAggregateData()
+    {
+        // Create printer
+        $printer = new \Printer();
+        $printers_id = $printer->add([
+            'name' => 'Test Printer CMYK',
+            'entities_id' => $this->getTestRootEntity(true),
+        ]);
+        $this->assertGreaterThan(0, $printers_id);
```
Comment (cedric-anne) [inline tests/functional/Printer_CartridgeInfoTest.php]: Prefer the usage of the `createItem()` method when creating items in your tests. It validates that the item is created correctly, and that actuel fields values are identical to the creation input.

```suggestion
        $printer = $this->createItem(
            Printer::class,
            [
                'name' => 'Test Printer CMYK',
                'entities_id' => $this->getTestRootEntity(true),
            ]
        );
        $printers_id = $printer->getID();
```

File: tests/functional/Printer_CartridgeInfoTest.php [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+        );
+
+        // Verify badges are displayed
+        $this->assertNotEmpty($result);
+        $this->assertStringContainsString('Black', $result);
+        $this->assertStringContainsString('Cyan', $result);
+        $this->assertStringContainsString('71%', $result);
+        $this->assertStringContainsString('85%', $result);
+        $this->assertStringContainsString('d-flex flex-wrap', $result);
+        $this->assertStringContainsString('badge', $result);
```
Comment (cedric-anne) [inline tests/functional/Printer_CartridgeInfoTest.php:94]: Your test seems correct, but an additional functionnal test for this would permit to ensure that the whole search results display execution chain is working as expected. You can test the result of `\Search::getDatas()`, like in #21348 for instance.

File: tests/functional/Printer_CartridgeInfoTest.php [hunk 3]
```diff
@@ -0,0 +1,227 @@
...
+
+        $result = \Printer_CartridgeInfo::getSpecificValueToDisplay(
+            '_virtual_toner_percent',
+            [],
+            $options
+        );
+
+        $this->assertTrue(
+            empty($result) || $result === \CommonDBTM::getSpecificValueToDisplay('_virtual_toner_percent', [], $options)
+        );
```
Comment (cedric-anne) [inline tests/functional/Printer_CartridgeInfoTest.php]: We want an empty result in this case. If we get something else, it is probably an issue.

```suggestion
        $this->assertTrue(empty($result));
```

File: tests/functional/Printer_CartridgeInfoTest.php [hunk 4]
```diff
@@ -0,0 +1,227 @@
...
+    {
+        $options = [];
+
+        $result = \Printer_CartridgeInfo::getSpecificValueToDisplay(
+            '_virtual_toner_percent',
+            [],
+            $options
+        );
+
+        $this->assertTrue(empty($result) || is_string($result));
```
Comment (cedric-anne) [inline tests/functional/Printer_CartridgeInfoTest.php]:
```suggestion
        $this->assertTrue(empty($result));
```

**Review by cedric-anne — COMMENTED** [review]
The fix seems OK.

**Review by trasher — CHANGES_REQUESTED** [review]
LGTM, but it seems like you miss a requested change from Cédric.

**Comment by trasher** [comment]
Also, please fix lint ;)

File: tests/functional/Printer_CartridgeInfoTest.php (hunk 2 above)
Comment (f2cmb) [reply tests/functional/Printer_CartridgeInfoTest.php:94]: New test added https://github.com/glpi-project/glpi/pull/21523/commits/e9243d0fa13ecf32da0854c0a3d157a40931163c

**Review by trasher — APPROVED** [review]
