### PR TITLE
fix exclusion notification + tests

### LINKED ISSUE #22309: v11.0.4: Adding "Profile: Utilisateur" to notification exclusions has the opposite effect
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

When adding "Profile: Utilisateur" to the Exclusions field in a notification rule, GLPI does not exclude this profile. Instead, it unexpectedly adds the profile as a recipient of the notification. This results in users receiving notifications they should be excluded from.

#### Expected Behavior
Users with the "Utilisateur" profile should be excluded from the notification.

#### Actual Behavior
Users with the Utilisateur profile receive the notification as if they were explicitly added as recipients. In our case, this caused every employee who had ever logged into GLPI (except IT staff with higher profiles such as Technician) to receive the ticket notification.

#### Screenshot
Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Navigate to:
   `Setup > Notifications > [any notification] > Recipients`
2. Add a standard recipient (e.g., **Requester**).
3. In the **Exclusions** field, add:
   `Profile: Utilisateur`
4. Save the notification configuration.
5. Trigger the conditions for the notification.

### Your GLPI setup information

_No response_

### Anything else?

We have the OAuth IMAP and samlsso plugins enabled.

### PR DESCRIPTION
**Pull request by Herafia**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !41459

When a profile or group was placed in the exclusions for a notification, it was incorrectly included as a recipient; now the exclusion is correctly applied and users linked to the excluded profile/group no longer receive the notification.

A test has been added to verify that a profile marked is_exclusion (in this case, Technician) does not appear in the list of recipients after calling getTargets().

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by stonebuzz** [comment]
- Should also fix: https://github.com/glpi-project/glpi/issues/22309

**Review by stonebuzz — APPROVED** [review]
seem's good for me

File: src/NotificationTarget.php [hunk 1]
```diff
@@ -1497,7 +1497,6 @@ private function removeExcludedTargets(array $target_list): array
             ],
         ]));
         if ($exclusions === []) {
-            // No exclusion, no need to filter
```
Comment (trasher) [inline src/NotificationTarget.php:1500]: Why removing this comment? It seem still accurate.

File: src/NotificationTarget.php [hunk 2]
```diff
@@ -1507,46 +1506,59 @@ private function removeExcludedTargets(array $target_list): array
             }
         }
         if ($user_ids === []) {
-            // Cannot filter targets without a user id
```
Comment (trasher) [inline src/NotificationTarget.php:1510]: Why removing this comment? It seem still accurate.

**Review by trasher — APPROVED** [review]

File: src/NotificationTarget.php
Comment (Rom1-B) [inline src/NotificationTarget.php:1490]: I think that if `$target_list` is empty, we can exit directly at the beginning of the function:
```suggestion
        global $DB;

        if ($target_list === []) {
            return $target_list;
        }
```

**Review by Rom1-B — APPROVED** [review]

**Review by stonebuzz — APPROVED** [review]
