### PR TITLE
fix: return 401 instead of 500 for AJAX requests with expired session

### LINKED ISSUE #21557: Requests to /ajax/notifications_ajax.php return a 500 error when session is expired
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

When a user session expires, but the user left the tab opened, the browser still send regular (1/min) GET requests on /ajax/notifications_ajax.php. Those requests gets a 500 error (instead of 401 or 403). This can trigger alerts when you monitor the 5XX error rate

### Relevant log output

```shell
in php-error.log, I can see this

[2025-10-20 16:26:42] glpi.CRITICAL:   *** Uncaught PHP Exception Glpi\Exception\SessionExpiredException: "" at Session.php line 1068
  Backtrace :
  ./src/Session.php:1068                             
  ./src/Session.php:1182                             Session::checkValidSessionId()
  ./src/Glpi/Http/Firewall.php:144                   Session::checkLoginUser()
  ...trollerListener/FirewallStrategyListener.php:82 Glpi\Http\Firewall->applyStrategy()
  ...ymfony/event-dispatcher/EventDispatcher.php:260 Glpi\Kernel\Listener\ControllerListener\FirewallStrategyListener->onKernelController()
  ...ymfony/event-dispatcher/EventDispatcher.php:220 Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()
  ...symfony/event-dispatcher/EventDispatcher.php:56 Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
  ./vendor/symfony/http-kernel/HttpKernel.php:169    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

1. Log into GLPI, and open for example the main ticket page (/front/ticket.php)
2. Leave the tab open
3. Wait for the session to expire
4. See that requests to /ajax/notifications_ajax.php now gets a 500 error

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.1 ( =&gt; /app)
Installation mode: TARBALL
Current language: fr_FR
Source Integrity: 4 files changed
  A: bin/init-db
  A: inc/downstream.php
  D: install/install.php
  A: public/sso.php</pre></details><details><summary>Server</summary><pre>Operating system: Linux 24485edd080a 5.14.0-570.44.1.el9_6.x86_64 #​1 SMP PREEMPT_DYNAMIC Wed Sep 17 10:32:11 EDT 2025 x86_64

PHP: 8.3.26 fpm-fcgi

PHP extensions: Core, date, libxml, pcre, zlib, filter, hash, json, random, readline, Reflection, SPL, session, cgi-fcgi,
bcmath, bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, ldap, mbstring, openssl, PDO, posix, standard, SimpleXML, sockets,
sodium, tokenizer, xml, xmlwriter, zip, exif, mysqlnd, Phar, xmlreader, mysqli, pdo_mysql, igbinary, msgpack, redis, Zend
OPcache

Setup: disable_functions=&quot;system, show_source, symlink, exec, dl, shell_exec, passthru, phpinfo, escapeshellcmd&quot;
max_execution_time=&quot;180&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;384M&quot; post_max_size=&quot;8M&quot; session.cookie_secure=&quot;0&quot;
session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;redis&quot; upload_max_filesize=&quot;100M&quot; 

Web server: nginx/1.28.0 ()

User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36

Database:
   
Server Software: Alpine Linux
   
Server Version: 11.4.8-MariaDB
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: v-679f8f6e-3f79-8-glpi-gkAtSqeQA0-1760708100@127.0.0.1:3306/glpi
   
Host info: 127.0.0.1 via TCP/IP

Requirements:
PHP version (8.3.26) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (11.4.8) is supported.
The log file has been created successfully.
Write access to
/data/app/_cache has been validated.
Write access to /data/app/_cron has been validated.
Write access to /data/app/_files has been validated.
Write access to /data/app/_graphs has been validated.
Write access to /data/app/_lock has been validated.
Write access to /data/app/_pictures has been validated.
Write access to /data/app/_plugins has been validated.
Write access to /data/app/_rss has been validated.
Write access to /data/sessions has been validated.
Write access to /data/tmp has been validated.
Write access to /data/tmp has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/data/app/marketplace has been validated.
Timezones seems not loaded, see
https://glpi-install.readthedocs.io/en/latest/timezones.html.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/app&quot;
GLPI_VERSION: &quot;11.0.1&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.1@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.1-3a9929cf&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/app/locales&quot;
GLPI_VAR_DIR: &quot;/data/app&quot;
GLPI_MARKETPLACE_DIR: &quot;/data/app/marketplace&quot;
GLPI_DOC_DIR: &quot;/data/app/_files&quot;
GLPI_SESSION_DIR: &quot;/data/sessions&quot;
GLPI_TMP_DIR: &quot;/data/tmp&quot;
GLPI_UPLOAD_DIR: &quot;/data/tmp&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_CONFIG_DIR: &quot;/app/config&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_CACHE_DIR: &quot;/data/app/_cache&quot;
GLPI_CRON_DIR: &quot;/data/app/_cron&quot;
GLPI_GRAPH_DIR: &quot;/data/app/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/data/app/_locales&quot;
GLPI_LOCK_DIR: &quot;/data/app/_lock&quot;
GLPI_LOG_DIR: &quot;/data/app/_log&quot;
GLPI_PICTURE_DIR: &quot;/data/app/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/data/app/_plugins&quot;
GLPI_RSS_DIR: &quot;/data/app/_rss&quot;
GLPI_INVENTORY_DIR: &quot;/data/app/_inventories&quot;
GLPI_THEMES_DIR: &quot;/data/app/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/data/app/marketplace&quot;,&quot;/app/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>Annuaires LDAP</summary><pre>Server: &#39;127.0.0.1&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;DC=lapiole,DC=org&#39;, 
	Connection filter:
&#39;(&amp;(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=Role_Support_User,OU=Roles,DC=lapiole,DC=org)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;,

	RootDN: &#39;glpi@lapiole.org&#39;, 
	Use TLS: none

Server: &#39;office.lapiole.org&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;DC=lapiole,DC=org&#39;, 
	Connection filter: &#39;(&amp;(objectClass=inetOrgPerson)(|(posixMemberOf=admins)(posixMemberOf=equipe)))&#39;, 
	RootDN: none, 
	Use TLS: &#39;1&#39;</pre></details><details><summary>Réplicats SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://localhost:25?verify_peer=0)
Name: &#39;Support (Zimbra)&#39;
	Active: Yes
	Server: &#39;{127.0.0.1:143/imap/notls}INBOX&#39;
	Login: &#39;glpi@lapiole.org&#39;
	Password: Yes</pre></details><details><summary>Plugins list</summary><pre>behaviors            Name: Behaviours                     Version: 3.0.1      State: Activé                                 
Install Method: Manual
fields               Name: Champs supplémentaires         Version: 1.21.22    State: Installé / non activé                 
Install Method: Manual
pdf                  Name: Print to pdf                   Version: 4.1.0      State: Activé                                 
Install Method: Manual
manufacturersimports Name: Suppliers imports              Version: 3.1.1      State: Activé                                 
Install Method: Manual
tag                  Name: Tag Management                 Version: 2.13.0     State: Activé                                 
Install Method: Manual</pre></details>

### Anything else?

I'm using redis for session storage, but I don't think it's related

### PR DESCRIPTION
**Pull request by f2cmb**
- It fixes #21557
- Here is a brief description of what this PR does :

Fix AJAX requests returning HTTP 500 instead of 401 when session expires.

The AccessErrorListener had an early return for AJAX requests that prevented handling of SessionExpiredException. This has been fixed by processing SessionExpiredException before the
  AJAX check.

For AJAX requests with expired sessions, the listener now returns a proper JSON 401 response:
  
```
  {
    "error": "Your session has expired",
    "message": "Please log in again",
    "code": "ERROR_SESSION_EXPIRED"
  }
```

 HTML requests continue to redirect to the login page as before. Other exception handling remains unchanged.

 Warning : This fix applies to all 122 AJAX endpoints in the application. Low risk of impact, though frontend handling of 401 responses should be monitored after deployment.

### CODE REVIEW

**Comment by f2cmb** [comment]
No tests added for the moment as i am not sure about potential impact : need pre-review first.

**Comment by trasher** [comment]
I'm not confident enough with new routiong system, I'll wait for @cedric-anne review.

File: src/Glpi/Kernel/Listener/ExceptionListener/AccessErrorListener.php [hunk 1]
```diff
@@ -79,18 +74,39 @@ public function onKernelException(ExceptionEvent $event): void
...
-            );
-        } elseif (
-            $throwable instanceof AccessDeniedHttpException
+            if ($request->isXmlHttpRequest() || $request->getPreferredFormat() !== 'html') {
+                // For AJAX/JSON requests, return a JSON response with 401 status
+                $response = new JsonResponse([
+                    'error'   => __('Your session has expired'),
+                    'message' => __('Please log in again'),
+                    'code'    => 'ERROR_SESSION_EXPIRED',
+                ], 401);
```
Comment (cedric-anne) [inline src/Glpi/Kernel/Listener/ExceptionListener/AccessErrorListener.php]: Throwing back a `HttpException` should permit to have it correctly handled by the `ErrorController`.

```suggestion
                // For AJAX/JSON requests, convert the error into a HttpException
                $http_exception = new \Glpi\Exception\Http\HttpException(403, 'Session expired.');
                $http_exception->setMessageToDisplay(__('Your session has expired. Please log in again.'));
                throw $http_exception;
```

Comment (f2cmb) [reply src/Glpi/Kernel/Listener/ExceptionListener/AccessErrorListener.php]: Response code shouldn't be 401 instead of 403 ? https://stackoverflow.com/questions/1653493/what-http-status-code-is-supposed-to-be-used-to-tell-the-client-the-session-has

Comment (f2cmb) [reply src/Glpi/Kernel/Listener/ExceptionListener/AccessErrorListener.php]: Changed here https://github.com/glpi-project/glpi/pull/21599/commits/2d6d33bf1ced6c3fbfdb01780bb8a1da95d508c1 but i kept 401 Response Code.

**Comment by trasher** [comment]
> Seems like the `$event->setResponse($response);` is wrongly conditionned

Nevermind, it's OK
