### PR TITLE
Fix display of timeline items; fixes #10961

### LINKED ISSUE #10961: Attachment missing on ticket timeline
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc2

### Bug description

I noticed that when I create a ticket and attach a file, the file won't show in the ticket timeline.
It uploads normally in the server path.
I've also noticed that the date and time of this field in the ticket timeline is wrong (ex: i opened the ticket today and the date of where the attachment was supposed to be shows 6 days past).
glpi

This problem does not occur in 10.0.0-rc1 version.

I've tested clean install of both versions with nothing configured, rc1 works normally and rc2 behaves like reported. 

**The problem does not occur when I add an attachment in a followup on the ticket.**

### Relevant log output

```shell
I don't know if this error logs are useful for this but here it goes.

php-errors
[2022-03-10 20:34:25] glpiphplog.WARNING: Test logger  
[2022-03-10 20:36:22] glpiphplog.DEBUG: Html::compileScss() in C:\xampp\htdocs\glpi\src\Html.php line 6771
Compile css/palettes/auror.scss  {"user":"@4130-TI"} 
[2022-03-11 15:35:05] glpiphplog.WARNING: Test logger  

sql-errors
[2022-03-11 15:29:01] glpisqllog.ERROR: DBmysql::query() in C:\xampp\htdocs\glpi\src\DBmysql.php line 367
  *** MySQL query error:
  SQL: INSERT INTO `glpi_logs` (`items_id`, `itemtype`, `itemtype_link`, `linked_action`, `user_name`, `date_mod`, `id_search_option`, `old_value`, `new_value`) VALUES ('1', 'Config', '', '0', 'glpi (2)', '2022-03-11 15:29:01', '1', 'priority_matrix {\"1\":{\"1\":\"1\",\"2\":\"1\",\"3\":\"2\",\"4\":\"2\",\"5\":\"2\"},\"2\":{\"1\":\"1\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"3\"},\"3\":{\"1\":\"2\",\"2\":\"2\",\"3\":\"3\",\"4\":\"4\",\"5\":\"4\"},\"4\":{\"1\":\"2\",\"2\":\"3\', '{\"1\":{\"1\":\"1\",\"2\":\"1\",\"3\":\"2\",\"4\":\"2\",\"5\":\"2\"},\"2\":{\"1\":\"1\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"3\"},\"3\":{\"1\":\"2\",\"2\":\"2\",\"3\":\"3\",\"4\":\"4\",\"5\":\"4\"},\"4\":{\"1\":\"2\",\"2\":\"3\",\"3\":\"4\",\"')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '{\"1\":{\"1\":\"1\",\"2\":\"1\",\"3\":\"2\",\"4\":\"2\",\"5\":\"2\"},\"2\":{\...' at line 1
  Backtrace :
  src\DBmysql.php:1295                               
  src\Log.php:261                                    DBmysql->insert()
  src\Log.php:188                                    Log::history()
  src\Config.php:3717                                Log::constructHistory()
  src\Config.php:3690                                Config->logConfigChange()
  src\CommonDBTM.php:1642                            Config->post_updateItem()
  src\Config.php:3048                                CommonDBTM->update()
  src\Config.php:280                                 Config::setConfigurationValues()
  src\CommonDBTM.php:1512                            Config->prepareInputForUpdate()
  front\config.form.php:63                           CommonDBTM->update()
  {"user":"2@4130-TI"}
```

### Page URL

_No response_

### Steps To reproduce

Open a ticket and insert an attachment with it.

### Your GLPI setup information

GLPI 10.0.0-rc2 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:pt_BR

Operating system: Windows NT 4130-TI 10.0 build 19044 (Windows 10) AMD64
PHP 8.1.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2 (Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2 Server at 127.0.0.1
	Port 8081
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.22-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.1.2) is supported.PHP version (8.1.2) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.22) is supported.Database engine version (10.4.22) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated. Write access to C:\xampp\htdocs\glpi/config has been validated. Write access to C:\xampp\htdocs\glpi/files/_cron has been validated. Write access to C:\xampp\htdocs\glpi/files has been validated. Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated. Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated. Write access to C:\xampp\htdocs\glpi/files/_lock has been validated. Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated. Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated. Write access to C:\xampp\htdocs\glpi/files/_rss has been validated. Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated. Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated. Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10961 #10912

Since #10647, `CommonITILObject::getTimelineItemtypes()` is used to define the template used to display timeline items, so all entries should be defined even when user has no rights to add/edit corresponding items, in order to display timeline items using the right template.

### CODE REVIEW

File: src/CommonITILObject.php [hunk 1]
```diff
@@ -7130,7 +7121,7 @@ class_exists($validation_class) && $params['with_validations']
 
                 $item['timeline_position'] = $document_item['timeline_position'];
                 $item['_can_edit'] = $can_view_documents && $document_obj->canUpdateItem();
-                $item['_can_delete'] = $can_view_documents && $document_obj->canDeleteItem();
+                $item['_can_delete'] = $can_view_documents && $document_obj->canDeleteItem() && $canupdate_parent;
```
Comment (cedric-anne) [inline src/CommonITILObject.php:7124]: This ensure that `delete` button on a document is not available when ticket is closed.

**Review by cconard96 — APPROVED** [review]

**Comment by cedric-anne** [comment]
Would fix #10912 too.

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]
