### PR TITLE
Network inventory fixes for Extreme Network equipments

### LINKED ISSUE #20140: Management switch interface is created for each inventory
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.18

### Bug description

Hi,
When I do a Extreme Network  switch inventory, a management interface is added every time. 
I've opened an issue in glpi-agent https://github.com/glpi-project/glpi-agent/issues/962 , but apparently the problem comes from the server.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

[5420f-stack.zip](https://github.com/user-attachments/files/20994256/5420f-stack.zip)

### Your GLPI setup information

GLPI Agent version
v1.15

GLPIInventory plugin 
GLPI Inventory v1.5.3

Operating system
Linux

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
Closes #20140; see also https://github.com/glpi-project/glpi-agent/issues/962

Te be reviewed per commit

### CODE REVIEW

**Comment by trasher** [comment]
Note: for the management port issue; I choose the solution with less impact. I'm not 100% sure where the problem comes from, but solving another way would require more code changes, and this could impact existing inventories.

**Comment by stonebuzz** [comment]
After testing, everything looks good on my end.

I also tried to simplify the code on my side, and I got the same result using the following patch.

```diff
diff --git a/src/Inventory/Asset/NetworkEquipment.php b/src/Inventory/Asset/NetworkEquipment.php
index 3348285297..2182b734cf 100644
--- a/src/Inventory/Asset/NetworkEquipment.php
+++ b/src/Inventory/Asset/NetworkEquipment.php
@@ -307,6 +307,7 @@ class NetworkEquipment extends MainAsset
                     }
                     break;
                 case 'chassis':
+                case 'module':
                     if (property_exists($component, 'serial')) {
                         ++$elt_count;
                     }
@@ -334,6 +335,7 @@ class NetworkEquipment extends MainAsset
         foreach ($components as $component) {
             switch ($component->type) {
                 case 'chassis':
+                case 'module':
                     if (property_exists($component, 'serial')) {
                         if (property_exists($component, 'stack_number')) {
                             $stack_number = $component->stack_number;
diff --git a/src/Inventory/Asset/NetworkPort.php b/src/Inventory/Asset/NetworkPort.php
index d01d93054c..9e1afea35c 100644
--- a/src/Inventory/Asset/NetworkPort.php
+++ b/src/Inventory/Asset/NetworkPort.php
@@ -146,6 +146,10 @@ class NetworkPort extends InventoryAsset
             }
         }
 
+        if (property_exists($val, 'name') && $val->name === 'Management') {
+            $val->name .= ' port';
+        }
+
         $this->ports += $this->data;
 
         return $this->data;
@@ -806,7 +810,7 @@ class NetworkPort extends InventoryAsset
             foreach ($this->ports as $k => $val) {
                 $matches = [];
                 if (
-                    preg_match('@[\w\s+]*(\d+)/[\w]@', $val->name, $matches)
+                    preg_match('@[\w\s+]*(\d+)[/:][\w]@', $val->name, $matches)
                 ) {
                     //reset increment when name lenght differ
                     //Gi0/0 then Gi0/0/1, Gi0/0/2, Gi0/0/3

```
The main simplification is in the stack management logic.

From this, I conclude that the module type should be handled similarly to the chassis type,
and that a port named "Management" should indeed be treated differently, as it is used internally by GLPI.

You'll notice the check using `property_exists($val, 'name')` here:

```php
if (property_exists($val, 'name') && $val->name === 'Management') {
    $val->name .= ' port';
}
```

**Comment by g-bougard** [comment]
I'm fine too with the actual PR.

@stonebuzz said:
> 
> You'll notice the check using `property_exists($val, 'name')` here:
> 
> ```
> if (property_exists($val, 'name') && $val->name === 'Management') {
>     $val->name .= ' port';
> }
> ```

I guess adding this property check should fix the actual unittests issue.

**Comment by trasher** [comment]
> ```diff
> diff --git a/src/Inventory/Asset/NetworkEquipment.php b/src/Inventory/Asset/NetworkEquipment.php
> index 3348285297..2182b734cf 100644
> --- a/src/Inventory/Asset/NetworkEquipment.php
> +++ b/src/Inventory/Asset/NetworkEquipment.php
> @@ -307,6 +307,7 @@ class NetworkEquipment extends MainAsset
>                      }
>                      break;
>                  case 'chassis':
> +                case 'module':
> ```

It seems some equipments both chassis and module with a serial number; this proposal will cause serial number change to existing equipments - that's why is made a method to choose one.

File: src/Inventory/Asset/NetworkPort.php [hunk 1]
```diff
@@ -144,6 +144,11 @@ public function prepare(): array
             if (!property_exists($val, 'trunk')) {
                 $val->trunk = 0;
             }
+
+            //Port name "Management" is reserved
+            if ($val->name === 'Management') {
```
Comment (trasher) [inline src/Inventory/Asset/NetworkPort.php]:
```suggestion
            if (property_exists($val, 'name') && $val->name === 'Management') {
```

**Review by stonebuzz — APPROVED** [review]
