### PR TITLE
Fix AllAsset exports

### LINKED ISSUE #22035: Blank export (PDF/CSV) from “Assets → All assets” (GLPI 11.0.2)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.2

### Bug description

Symptoms:

Export works fine from individual asset types (Computers, Monitors, etc.): PDF / CSV / XML / ODT.

Export from All assets does not work — after clicking export I get a blank page / no file downloaded.

Environment:

GLPI: 11.0.2 (stable)

PHP: 8.4.13

Browsers tested: Firefox and Edge/Chrome (same behavior)

What I checked:

No errors in GLPI logs at export time:
files/_logs/php-errors.log, glpi.log, sql-errors.log.

No errors in web server logs either.

In DevTools → Network, I can see the export request:

/glpi/public/front/report.dynamic.php?item_type=AllAssets ... &display_type=2

Response headers:

Status Code: 200 OK

Content-Type: text/html; charset=UTF-8

Content-Length: 0

So the endpoint runs but returns an empty HTML response instead of a file.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

assets --> all assets > export 

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
closes #22035

Reverts https://github.com/glpi-project/glpi/pull/20428/files#diff-fddc2770c1d35659f0f234f634611059929b024a59195e5abfd3ed24b97ef951: `$item` is already set when required; and in that case `AllAsset` is a valid item type.

### CODE REVIEW

File: src/Search.php [hunk 1]
```diff
@@ -168,9 +168,9 @@ public static function show($itemtype)
 
 
     /**
-     * Display result table for search engine for an type
+     * Display result table for search engine for a type
      *
-     * @param class-string<CommonDBTM> $itemtype Item type to manage
+     * @param class-string<CommonGLPI> $itemtype Item type to manage
```
Comment (trasher) [inline src/Search.php]: I would expect something like that to work:
```suggestion
     * @param class-string<AllAssets|CommonDBTM> $itemtype Item type to manage
```


But phpstan keeps complaining. `CommonGLPI` is not expected here, only specific `AllAssets` case is valid. I do not know how to make phptsan happy :/

Comment (AdrienClairembault) [reply src/Search.php]: `class-string<AllAssets>|class-string<CommonDBTM>` maybe?

Comment (trasher) [reply src/Search.php]: Nope, that does not work :/
```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   report.dynamic.php                                                                                                                                    
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------ 
  117    Parameter #1 $itemtype of static method Search::showList() expects class-string<AllAssets>|class-string<CommonDBTM>, class-string<CommonGLPI> given.  
         🪪  argument.type                                                                                                                                     
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------ 
```

Comment (trasher) [reply src/Search.php]: I've forced `$itemtype` variable type on the front file side, seems that works that way.

Comment (AdrienClairembault) [reply src/Search.php]: I think this is because getItemForItemtype may return any CommonGLPI item, not just AllAssets or CommonDBTM.

So phpstan warns that you may send an incorrect type and trigger an error.

File: front/report.dynamic.php [hunk 2]
```diff
@@ -42,11 +42,12 @@
     return;
 }
 
+/** @var class-string<AllAssets|CommonDBTM> $itemtype */
 $itemtype = $_GET['item_type'];
```
Comment (AdrienClairembault) [inline front/report.dynamic.php:46]: This seems unsafe to assume as $_GET can contains anything.

Comment (trasher) [reply front/report.dynamic.php:46]: Probably, but that's not related to current PR
