### PR TITLE
fix(migration): handle unsupported value operators in form migration conditions

### LINKED ISSUE #20205: GLPI 11 Beta 7 - Operators unavailable (when importing forms via CLI)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-beta7

### Bug description

When using migration:formcreator_plugin_to_core, forms with "≤" | "≥" | "regular expression matches" broke, changing the operator to "is equal to" and not allowing to preview/use the imported form. I've noticed that these operators does not exist in GLPI11-beta7 version

Example

V10:

Image

When imported to V11:

Image

Trying to preview/use the form (/Form/Render/<ID>):

Image

### Relevant log output

```shell
glpi.CRITICAL:   *** Uncaught PHP Exception LogicException: "Condition handler not found for item "Dropdown" and operator "greater_than"" at Engine.php line 294
  Backtrace :
  ./src/Glpi/Form/Condition/Engine.php:294
  ./src/Glpi/Form/Condition/Engine.php:224           Glpi\Form\Condition\Engine->computeCondition()
  ./src/Glpi/Form/Condition/Engine.php:155           Glpi\Form\Condition\Engine->computeConditions()
  ./src/Glpi/Form/Condition/Engine.php:74            Glpi\Form\Condition\Engine->computeItemVisibility()
  .../Glpi/Controller/Form/RendererController.php:96 Glpi\Form\Condition\Engine->computeVisibility()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\Form\RendererController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()


(Same error for imports that contains "match_regex"/"regular expression matches" and "less than"/"≤" operators)
```

### Page URL

yourglpi.com/Form/Render/<ID>

### Steps To reproduce

1. Import forms via CLI using migration:formcreator_plugin_to_core
2. Try to Preview or use the imported form

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0-dev ( => /usr/share/glpi11)
Installation mode: TARBALL
Current language: en_US</pre></details><details><summary>Server</summary><pre>Operating system: Linux 5.14.0-427.40.1.el9_4.x86_64 #​1 SMP PREEMPT_DYNAMIC Wed Oct 16 07:08:17 EDT 2024 x86_64

PHP: 8.3.13 fpm-fcgi

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard,
sockets, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, ldap, exif,
mysqlnd, PDO, Phar, SimpleXML, soap, sodium, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader,
xmlrpc, zip, apcu, selinux, Zend OPcache

Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
upload_max_filesize="20M" disable_functions="" 

Web server: Apache/2.4.57 (AlmaLinux) OpenSSL/3.0.7 ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
Edg/137.0.0.0

Database:
   
Server Software: Percona Server (GPL), Release 30, Revision 41ebc5d9
   
Server Version: 8.0.39-30
   
Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@127.0.0.1/glpi11
   
Host info: 127.0.0.1 via TCP/IP

Requirements:
PHP version (8.3.13) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (8.0.39) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi11/files/_cache has been validated.
Write access to /var/lib/glpi11/files/_cron has been validated.
Write access to /var/lib/glpi11/files has been validated.
Write access to /var/lib/glpi11/files/_graphs has been validated.
Write access to /var/lib/glpi11/files/_lock has been validated.
Write access to /var/lib/glpi11/files/_pictures has been validated.
Write access to /var/lib/glpi11/files/_plugins has been validated.
Write access to /var/lib/glpi11/files/_rss has been validated.
Write access to /var/lib/glpi11/files/_sessions has been validated.
Write access to /var/lib/glpi11/files/_tmp has been validated.
Write access to /var/lib/glpi11/files/_uploads has been validated.
For security reasons, SELinux
mode should be Enforcing.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/usr/share/glpi11/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: "/usr/share/glpi11"
GLPI_VERSION: "11.0.0-dev"
GLPI_SCHEMA_VERSION: "11.0.0-dev@3625b5fec3b12824545d9777d46d72fa99584d03"
GLPI_FILES_VERSION: "11.0.0-dev-ae8cbfd4"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.4"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/usr/share/glpi11/locales"
GLPI_CONFIG_DIR: "/etc/glpi11"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: false
GLPI_VAR_DIR: "/var/lib/glpi11/files"
GLPI_LOG_DIR: "/var/log/glpi11"
GLPI_SYSTEM_CRON: true
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_MARKETPLACE_DIR: "/usr/share/glpi11/marketplace"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST:
["#^http://[^@:]+(:80)?(/.*)?$#","#^https://[^@:]+(:443)?(/.*)?$#","#^feed://[^@:]+(/.*)?$#"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_LOG_LVL: "warning"
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_DOC_DIR: "/var/lib/glpi11/files"
GLPI_CACHE_DIR: "/var/lib/glpi11/files/_cache"
GLPI_CRON_DIR: "/var/lib/glpi11/files/_cron"
GLPI_GRAPH_DIR: "/var/lib/glpi11/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi11/files/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi11/files/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi11/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi11/files/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi11/files/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi11/files/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi11/files/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi11/files/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi11/files/_inventories"
GLPI_THEMES_DIR: "/var/lib/glpi11/files/_themes"
GLPI_PLUGINS_DIRECTORIES: ["/usr/share/glpi11/marketplace","/usr/share/glpi11/plugins"]
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"</pre></details><details>
Install Method: Manual</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ccailly**
## Checklist before requesting a review

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

- It partially fixes #20205

Check whether the operator is supported by the question type when migrating conditions on questions.
Some operators are not supported by the new form integration.

Warning displayed if conditions are not imported.

### CODE REVIEW

**Comment by cedric-anne** [comment]
I put it back to draft to prevent it from being merged right now. I am merging 10.0 into 11.0 and I wait for test to being fixed to push it to the upstream.

File: src/Glpi/Form/Migration/FormMigration.php [hunk 1]
```diff
@@ -1380,29 +1380,52 @@ private function processMigrationOfVisibilityConditions(): void
...
+                    /** @var Question|Comment|Section|FormDestination $item */
+                    $item = getItemForItemtype($target_item['itemtype']);
+                    if ($item->getFromDB($target_item['items_id']) === false) {
+                        throw new LogicException(
+                            sprintf(
+                                'Target item %s with ID %d not found for visibility condition.',
+                                $target_item['itemtype'],
+                                $target_item['items_id']
+                            )
+                        );
```
Comment (cedric-anne) [inline src/Glpi/Form/Migration/FormMigration.php]: This condition will be skipped anyway, I think it is preferable to not block the migration with an exception in this case. For instance, you can use fallback values:
```php
                        sprintf(
                            __('A visibility condition used in "%s" "%s" (Form "%s") with value operator "%s" is not supported by the question type. It will be ignored.'),
                            $item->getTypeName(1) ?? $target_item['itemtype'],
                            $item->getName() ?? $target_item['items_id'],
                            $item->getForm()->getName() ?? NOT_AVAILABLE,
                            $value_operator->getLabel()
                        )
```

File: src/Glpi/Form/Migration/FormMigration.php [hunk 2]
```diff
@@ -1380,29 +1380,46 @@ private function processMigrationOfVisibilityConditions(): void
...
+                    )
+                ));
+
+                // If no condition handler is found for the value operator, we skip this condition
+                if ($condition_handler === false) {
+                    /** @var Question|Comment|Section|FormDestination $item */
+                    $item = getItemForItemtype($target_item['itemtype']);
+                    if ($item->getFromDB($target_item['items_id']) !== false) {
+                        $form = $item->getForm();
+                    }
```
Comment (cedric-anne) [inline src/Glpi/Form/Migration/FormMigration.php]: 1. If you do not set `$item` to `null`, `$item->getTypeName(1) ?? $target_item['itemtype']` will result in an error because it will try to execute a method on `false`;
2. `$form` should always be set (even with a `null` value).

```suggestion
                    if ($item !== false && $item->getFromDB($target_item['items_id']) !== false) {
                        $form = $item->getForm();
                    } else {
                        $item = null
                        $form = null;
                    }
```

File: src/Glpi/Form/Migration/FormMigration.php [hunk 3]
```diff
@@ -1380,29 +1380,46 @@ private function processMigrationOfVisibilityConditions(): void
...
+
+                    $this->result->addMessage(
+                        MessageType::Warning,
+                        sprintf(
+                            __('A visibility condition used in "%s" "%s" (Form "%s") with value operator "%s" is not supported by the question type. It will be ignored.'),
+                            $item->getTypeName(1) ?? $target_item['itemtype'],
+                            $item->getName() ?? $target_item['items_id'],
+                            $form?->getName() ?? NOT_AVAILABLE,
```
Comment (cedric-anne) [inline src/Glpi/Form/Migration/FormMigration.php]: I think it is not required.

```suggestion
                            $form->getName() ?? NOT_AVAILABLE,
```

File: src/Glpi/Form/Migration/FormMigration.php [hunk 4]
```diff
@@ -1380,29 +1380,49 @@ private function processMigrationOfVisibilityConditions(): void
...
+                ));
+
+                // If no condition handler is found for the value operator, we skip this condition
+                if ($condition_handler === false) {
+                    /** @var Question|Comment|Section|FormDestination $item */
+                    $item = getItemForItemtype($target_item['itemtype']);
+                    if ($item !== false && $item->getFromDB($target_item['items_id']) !== false) {
+                        $form = $item->getForm();
+                    } else {
+                        $item = null
```
Comment (cedric-anne) [inline src/Glpi/Form/Migration/FormMigration.php]:
```suggestion
                        $item = null;
```

**Review by trasher — APPROVED** [review]
