### PR TITLE
Fix helpdesk forms actors dropdowns

### LINKED ISSUE #21243: Search text and pagination issue with form actor questions
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0

### Bug description

From [community forum post](https://forum.glpi-project.org/post.php?tid=293155).

> I'm trying migration tests before going live with v11.
> 
> The problem I will describe here is there in both migrated forms (formcreator) and also on a brand new form that I start from scratch.
> 
> If I add a question of type "Actors" -> "Requesters", there are 2 bugs :
> 
> 1. The combobox is populated but only the first 50 users are displayed.
> (previously on FormCreator, all active users were available.)
> 
> 2. Impossible to search for a particular user because when I type letters, nothing happens.
> (again it was working great on v10 with FormCreator)

I have confirmed both issues. The search text parameter does not seem implemented (`\Glpi\Controller\Form\QuestionActorsDropdownController`) for the dropdown and pagination doesn't appear to be triggering or implemented on the server-side (`\Glpi\Form\Dropdown\FormActorsDropdown::getUsers`).

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Fix multiple issues with the helpdesk actors dropdown.

## References

Fix #21243

### CODE REVIEW

File: src/Glpi/Controller/Form/QuestionActorsDropdownController.php [hunk 1]
```diff
@@ -66,9 +66,16 @@ public function __invoke(Request $request): Response
             'allowed_types'    => $request->request->all('allowed_types'),
             'right_for_users'  => $request->request->getString('right_for_users', 'all'),
             'group_conditions' => $request->request->all('group_conditions'),
+            'page'             => $request->request->getInt('page'),
+            'page_size'        => $request->request->getInt('page_limit'),
```
Comment (cedric-anne) [inline src/Glpi/Controller/Form/QuestionActorsDropdownController.php]:
```suggestion
            'page'             => $request->request->getInt('page', 1),
            'page_size'        => $request->request->getInt('page_limit', -1),
```

**Comment by slingky78** [comment]
I tested and seems to work well now. Thank you very much.
