### PR TITLE
Make sure itemtype is found before calling getFromDB; closes #22821

### LINKED ISSUE #22821: infocom automatic job not running - Caught Error: Call to a member function getFromDB() on false
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

Hi,

every time the infocom job (that sends the email) tries to run, it fails with an error. And I receive an email telling me that a job couldn't be executed and that I need to check it.

### Relevant log output

```shell
[2026-01-25 21:37:49] glpi.ERROR:   *** Caught Error: Call to a member function getFromDB() on false
  Backtrace :
  ./src/Item_Devices.php:97                          
  ./src/CommonDBTM.php:5932                          Item_Devices->computeFriendlyName()
  ./src/CommonDBTM.php:3739                          CommonDBTM->getFriendlyName()
  ./src/Infocom.php:704                              CommonDBTM->getName()
  ./src/CronTask.php:897                             Infocom::cronInfocom()
  ./front/crontask.form.php:55                       CronTask::launch()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

Running on a Synology NAS with latest DSM in Web Station.

Operating system: Linux ds1823 4.4.302+ #​86009 SMP Wed Nov 26 18:19:20 CST 2025 x86_64

PHP: 8.4.14 fpm-fcgi

PHP extensions: Core, date, libxml, pcre, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, session, PDO, random,
readline, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, bz2, calendar,
curl, dba, exif, ftp, gd, gettext, gmp, iconv, intl, mysqli, openssl, pdo_dblib, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, zlib,
posix, shmop, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, zip, Phar, Zend OPcache

Setup: disable_functions="" max_execution_time="240" max_input_vars="1000" memory_limit="256M" post_max_size="80M"
session.cookie_secure="1" session.cookie_httponly="1" session.cookie_samesite="" session.save_handler="files"
upload_max_filesize="80M" 

Web server: Apache/2.4.63 (Unix) ()

User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0
Safari/537.36

Database:
   
Server Software: Source distribution
   
Server Version: 10.11.11-MariaDB
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi_user@127.0.0.1:3307/glpi
   
Host info: 127.0.0.1 via TCP/IP

Requirements:
PHP version (8.4.14) is supported.PHP version (8.4.14) is supported.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer,
xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installedmysqli extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
intl extension is installedintl extension is installed
mbstring extension is installedmbstring extension is installed
zlib extension is installedzlib extension is installed
bcmath extension is installedbcmath extension is installed
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installedopenssl extension is installed
Database engine version (10.11.11) is supported.Database engine version (10.11.11) is
supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /volume1/web/glpi/files/_cache has been validated. Write access to
/volume1/web/glpi/files/_cron has been validated. Write access to /volume1/web/glpi/files has been validated. Write access to
/volume1/web/glpi/files/_graphs has been validated. Write access to /volume1/web/glpi/files/_lock has been validated. Write
access to /volume1/web/glpi/files/_pictures has been validated. Write access to /volume1/web/glpi/files/_plugins has been
validated. Write access to /volume1/web/glpi/files/_rss has been validated. Write access to /volume1/web/glpi/files/_sessions
has been validated. Write access to /volume1/web/glpi/files/_tmp has been validated. Write access to
/volume1/web/glpi/files/_uploads has been validated.Write access to /volume1/web/glpi/files/_cache has been validated.
Write access to /volume1/web/glpi/files/_cron has been validated.
Write access to /volume1/web/glpi/files has been validated.
Write access to /volume1/web/glpi/files/_graphs has been validated.
Write access to /volume1/web/glpi/files/_lock has been validated.
Write access to /volume1/web/glpi/files/_pictures has been validated.
Write access to /volume1/web/glpi/files/_plugins has been validated.
Write access to /volume1/web/glpi/files/_rss has been validated.
Write access to /volume1/web/glpi/files/_sessions has been validated.
Write access to /volume1/web/glpi/files/_tmp has been validated.
Write access to /volume1/web/glpi/files/_uploads has been validated.

Sessions configuration is secured.Sessions configuration is secured.
exif extension is installedexif extension is installed
ldap extension is not presentldap extension is not present
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installedZend OPcache extension is installed
Following extensions are installed: ctype, iconv, sodium.Following extensions are installed:
ctype, iconv, sodium.
Write access to /volume1/web/glpi/marketplace has been validated.Write access to
/volume1/web/glpi/marketplace has been validated.
Timezones seems not loaded, see
https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see
https://glpi-install.readthedocs.io/en/latest/timezones.html.

### Anything else?

I'm not 100% sure, but it seems that it appeared after the update of php 8.3 to 8.4.

Any idea how to debug would be highly appreciated!

Thanks,
Viktor

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

File: src/Item_Devices.php [hunk 1]
```diff
@@ -93,8 +93,7 @@ public function getCloneRelations(): array
     protected function computeFriendlyName()
     {
         $itemtype = static::$itemtype_2;
-        if (!empty($this->fields[static::$itemtype_1])) {
-            $item = getItemForItemtype($this->fields[static::$itemtype_1]);
+        if (!empty($this->fields[static::$itemtype_1]) && $item = getItemForItemtype($this->fields[static::$itemtype_1])) {
```
Comment (cedric-anne) [inline src/Item_Devices.php]: `getFromDB` return value could also be added in the check.
```php
        if (
            !empty($this->fields[static::$itemtype_1])
            && $item = getItemForItemtype($this->fields[static::$itemtype_1])
            && $item->getFromDB($this->fields[static::$items_id_1]);
        ) {
```

Comment (trasher) [reply src/Item_Devices.php]: done

**Comment by trasher** [comment]
There are certainly hundreds of issues of that kind... At least this one is now solved.

**Review by cedric-anne — APPROVED** [review]
