### PR TITLE
Ensure tag is removed from Agent when not present

### LINKED ISSUE #23721: Agent tag not reset when no more set
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [ ] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

After a submitted inventory with tag set has been submitted, the tag is kept if tag is removed from the following inventory.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Import an inventory with tag set: [tag-issue-with-tag.json](https://github.com/user-attachments/files/26400655/tag-issue-with-tag.json)
2. Check the asset in glpi and see it has a tag
3. Import an inventory from the same asset and with the same deviceid but this time with no tag: [tag-issue-no-tag.json](https://github.com/user-attachments/files/26400679/tag-issue-no-tag.json)
4. Check the asset in glpi and see the previous tag has been kept

This is also the case with xml inventory: [tag-issue-with-tag.xml](https://github.com/user-attachments/files/26400713/tag-issue-with-tag.xml) vs [tag-issue-no-tag.xml](https://github.com/user-attachments/files/26400724/tag-issue-no-tag.xml)

### Your GLPI setup information

_No response_

### Anything else?

This only happens when deviceid remains the same. The use case is when you reconfigure an agent on a computer to remove the previously tag and after it submitted at least one inventory.

### PR DESCRIPTION
**Pull request by trasher**
Add test
closes #23721

### CODE REVIEW

File: src/Glpi/Inventory/Inventory.php [hunk 1]
```diff
@@ -848,6 +850,15 @@ public function handleItem()
             $this->mainasset->setExtraData($this->data);
             $this->mainasset->setAssets($this->assets);
             $item_start = microtime(true);
+            //cleanup tag
+            if (
+                ($agent = $this->mainasset?->getAgent()) instanceof Agent
+                && !$this->mainasset->isPartial()
```
Comment (g-bougard) [inline src/Glpi/Inventory/Inventory.php]: I don't see the purpose of the "not isPartial" test part: when partial, inventory is json and in json format "tag" field is part of the json root. I mean a partial inventory has always "tag" set if tag is defined in agent config. This means if "tag" field is not set in partial inventory json it has to be removed in glpi.

Anyway, I tested with and without this "if" test part and I can confirm "tag" is reset in glpi when a partial inventory without tag set is submitted. My guess is "tag" field in code is defined, even empty, elsewhere in glpi code.

I suggest just to remove this test part.
```suggestion
```

**Review by SebSept — APPROVED** [review]
I don't have the full picture of the spec. I'm not qualified to review the business logic.

Probably some tests can be written to describe the uses cases (when should tag be removed, preserved, etc). Then it can be used for documentation.

From the perspective of code analysis, lgtm -> approve.

File: src/Glpi/Inventory/Inventory.php (hunk 1 above)
Comment (g-bougard) [reply src/Glpi/Inventory/Inventory.php]: oups, my mistake... I generated inventory locally and so my test was wrong.

So I updated my test files to use same deviceid. And then it appears this line is a problem and have to be removed: the tag is not reset on partial inventory.

So you can also add a test for this case:
 * tag must be reset if not present in json even if partial

Comment (trasher) [reply src/Glpi/Inventory/Inventory.php]: I did not knwow tag was always present in partial mode.

**Review by g-bougard — CHANGES_REQUESTED** [review]
As I said in my previous comment, the tag has to be reset also in the case of a partial inventory.

**Review by g-bougard — APPROVED** [review]
Lol, your commit was submitted just I submit my review.

**Comment by trasher** [comment]
> Probably some tests can be written to describe the uses cases (when should tag be removed, preserved, etc). Then it can be used for documentation.

Well, I guess all cases are tested. Only computers can have tags (agent adds tag only for computers).
Other cases were already tested; the only problem when tag was not blanked; this is now fixed.

BTW, I realized I put tests in the wrong place, I'll move them.
