### PR TITLE
Fix unexpected warnings in TestUpdatedDataCommand

### LINKED ISSUE #18907: Unexpected SQL warning in `tests/bin/test-updated-data` command
They should be fixed and the test script should fail if any warning is triggerred.

```
+ tests/bin/test-updated-data --host=db --user=root --fresh-db=glpi --updated-db=glpitest-9.5 --ansi --no-interaction
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_accesscontrols_formaccesscontrols` WHERE `forms_forms_id` = '1' AND `strategy` = 'Glpi\\Form\\AccessControl\\ControlType\\AllowList' AND `config` = CAST(`config` AS CHAR) = '{\"user_ids\": [\"all\"], \"group_ids\": [], \"profile_ids\": []}' AND `is_active` = '1'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '{"user_ids": ["all"], "group_ids": [], "profile_ids": []}' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_accesscontrols_formaccesscontrols` WHERE `forms_forms_id` = '2' AND `strategy` = 'Glpi\\Form\\AccessControl\\ControlType\\AllowList' AND `config` = CAST(`config` AS CHAR) = '{\"user_ids\": [\"all\"], \"group_ids\": [], \"profile_ids\": []}' AND `is_active` = '1'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '{"user_ids": ["all"], "group_ids": [], "profile_ids": []}' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_destinations_formdestinations` WHERE `forms_forms_id` = '1' AND `itemtype` = 'Glpi\\Form\\Destination\\FormDestinationTicket' AND `name` = 'Ticket' AND `config` = CAST(`config` AS CHAR) = '{\"glpi-form-destination-commonitilfield-titlefield\": {\"value\": \"<span contenteditable=\\\"false\\\" data-form-tag=\\\"true\\\" data-form-tag-value=\\\"6\\\" data-form-tag-provider=\\\"Glpi\\\\Form\\\\Tag\\\\AnswerTagProvider\\\" class=\\\"border-teal border-start border-3 bg-dark-lt\\\">Answer: Title</span>\"}, \"glpi-form-destination-commonitilfield-contentfield\": {\"value\": \"<span contenteditable=\\\"false\\\" data-form-tag=\\\"true\\\" data-form-tag-value=\\\"7\\\" data-form-tag-provider=\\\"Glpi\\\\Form\\\\Tag\\\\AnswerTagProvider\\\" class=\\\"border-teal border-start border-3 bg-dark-lt\\\">Answer: Description</span>\"}, \"glpi-form-destination-commonitilfield-observerfield\": {\"strategies\": [\"last_valid_answer\"], \"specific_question_ids\": [], \"specific_itilactors_ids\": []}, \"glpi-form-destination-commonitilfield-requesttypefield\": {\"strategy\": \"specific_value\", \"specific_question_id\": null, \"specific_request_type\": 1}, \"glpi-form-destination-commonitilfield-contentfield_auto\": false}'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '{"glpi-form-destination-commonitilfield-titlefield": {"value": "<span contenteditable=\"false\" data-form-tag=\"true\" data-form' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_destinations_formdestinations` WHERE `forms_forms_id` = '2' AND `itemtype` = 'Glpi\\Form\\Destination\\FormDestinationTicket' AND `name` = 'Ticket' AND `config` = CAST(`config` AS CHAR) = '{\"glpi-form-destination-commonitilfield-titlefield\": {\"value\": \"<span contenteditable=\\\"false\\\" data-form-tag=\\\"true\\\" data-form-tag-value=\\\"13\\\" data-form-tag-provider=\\\"Glpi\\\\Form\\\\Tag\\\\AnswerTagProvider\\\" class=\\\"border-teal border-start border-3 bg-dark-lt\\\">Answer: Title</span>\"}, \"glpi-form-destination-commonitilfield-contentfield\": {\"value\": \"<span contenteditable=\\\"false\\\" data-form-tag=\\\"true\\\" data-form-tag-value=\\\"14\\\" data-form-tag-provider=\\\"Glpi\\\\Form\\\\Tag\\\\AnswerTagProvider\\\" class=\\\"border-teal border-start border-3 bg-dark-lt\\\">Answer: Description</span>\"}, \"glpi-form-destination-commonitilfield-observerfield\": {\"strategies\": [\"last_valid_answer\"], \"specific_question_ids\": [], \"specific_itilactors_ids\": []}, \"glpi-form-destination-commonitilfield-requesttypefield\": {\"strategy\": \"specific_value\", \"specific_question_id\": null, \"specific_request_type\": 2}, \"glpi-form-destination-commonitilfield-contentfield_auto\": false}'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '{"glpi-form-destination-commonitilfield-titlefield": {"value": "<span contenteditable=\"false\" data-form-tag=\"true\" data-form' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '1' AND `name` = 'Urgency' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeUrgency' AND `is_mandatory` = '0' AND `vertical_rank` = '0' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND (((`extra_data` = '') OR (`extra_data` IS NULL))) AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '1' AND `name` = 'Category' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeItemDropdown' AND `is_mandatory` = '0' AND `vertical_rank` = '1' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND `default_value` = '{\"items_id\":0}' AND `extra_data` = '{\"itemtype\":\"ITILCategory\"}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '1' AND `name` = 'User devices' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeUserDevice' AND `is_mandatory` = '0' AND `vertical_rank` = '2' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND `default_value` = '0' AND `extra_data` = '{\"is_multiple_devices\":false}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '1' AND `name` = 'Watchers' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeObserver' AND `is_mandatory` = '0' AND `vertical_rank` = '3' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND `extra_data` = '{\"is_multiple_actors\":true}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '1' AND `name` = 'Location' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeItemDropdown' AND `is_mandatory` = '0' AND `vertical_rank` = '4' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND `default_value` = '{\"items_id\":0}' AND `extra_data` = '{\"itemtype\":\"Location\"}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '1' AND `name` = 'Title' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeShortText' AND `is_mandatory` = '0' AND `vertical_rank` = '5' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND (((`extra_data` = '') OR (`extra_data` IS NULL))) AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '1' AND `name` = 'Description' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeLongText' AND `is_mandatory` = '1' AND `vertical_rank` = '6' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND (((`extra_data` = '') OR (`extra_data` IS NULL))) AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '2' AND `name` = 'Urgency' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeUrgency' AND `is_mandatory` = '0' AND `vertical_rank` = '0' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND (((`extra_data` = '') OR (`extra_data` IS NULL))) AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '2' AND `name` = 'Category' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeItemDropdown' AND `is_mandatory` = '0' AND `vertical_rank` = '1' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND `default_value` = '{\"items_id\":0}' AND `extra_data` = '{\"itemtype\":\"ITILCategory\"}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '2' AND `name` = 'User devices' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeUserDevice' AND `is_mandatory` = '0' AND `vertical_rank` = '2' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND `default_value` = '0' AND `extra_data` = '{\"is_multiple_devices\":false}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '2' AND `name` = 'Watchers' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeObserver' AND `is_mandatory` = '0' AND `vertical_rank` = '3' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND `extra_data` = '{\"is_multiple_actors\":true}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '2' AND `name` = 'Location' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeItemDropdown' AND `is_mandatory` = '0' AND `vertical_rank` = '4' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND `default_value` = '{\"items_id\":0}' AND `extra_data` = '{\"itemtype\":\"Location\"}' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '2' AND `name` = 'Title' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeShortText' AND `is_mandatory` = '0' AND `vertical_rank` = '5' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND (((`extra_data` = '') OR (`extra_data` IS NULL))) AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_questions` WHERE `forms_sections_id` = '2' AND `name` = 'Description' AND `type` = 'Glpi\\Form\\QuestionType\\QuestionTypeLongText' AND `is_mandatory` = '1' AND `vertical_rank` = '6' AND (((`horizontal_rank` = '') OR (`horizontal_rank` IS NULL))) AND (((`description` = '') OR (`description` IS NULL))) AND (((`default_value` = '') OR (`default_value` IS NULL))) AND (((`extra_data` = '') OR (`extra_data` IS NULL))) AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_sections` WHERE `forms_forms_id` = '1' AND `name` = 'First section' AND (((`description` = '') OR (`description` IS NULL))) AND `rank` = '0' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
PHP User Warning (512): MySQL query warnings:
  SQL: SELECT * FROM `glpi_forms_sections` WHERE `forms_forms_id` = '2' AND `name` = 'First section' AND (((`description` = '') OR (`description` IS NULL))) AND `rank` = '0' AND `visibility_strategy` = '' AND `conditions` = CAST(`conditions` AS CHAR) = '[]'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '[]' at DBmysql.php line 399 in /var/www/glpi/src/DBmysql.php at line 399
```

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Fix #18907.

### CODE REVIEW

File: tests/src/Command/TestUpdatedDataCommand.php [hunk 1]
```diff
@@ -178,21 +178,25 @@ public function __construct($dbhost, $dbuser, $dbpassword, $dbdefault)
...
                         $criteria[] = [
                             'OR' => [
-                                [$key => ''],
+                                [$key => $empty_value],
                                 [$key => null],
                             ]
                         ];
                     } elseif ($field_type === 'json') {
-                        // Compare JSON fields using they CHAR representation
+                        // Compare JSON fields using their CHAR representation
```
Comment (cedric-anne) [inline tests/src/Command/TestUpdatedDataCommand.php:194]:
```suggestion
```

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]
