### PR TITLE
Fix tree browse not selecting initial category from URL parameter

### LINKED ISSUE #23360: Clicking KB category in article shows articles without a category
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0/bugfixes

### Bug description

Clicking a category in an article redirects the user to the KB browse view with the default category selection, which is "Without category".

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #23360 
- Here is a brief description of what this PR does : The `knowbaseitemcategories_id` parameter present in the URL after clicking a KB article's category badge was never read by the fancytree JavaScript `code. tree.activateKey(-1) `was hardcoded, always selecting "Without Category". This fix extracts the category ID from the request parameters and passes it as the initial node to `activateKey()`.

**Note about PHPStan** : Ideally, the `$itemtype` parameter should be typed as `class-string<CommonDBTM>` across the trait and interface, but that would also fix errors currently tracked in the PHPStan baseline (`getTreeCategoryList()`, `Search::getDatas()`), requiring baseline cleanup outside the scope of this PR.

A targeted `@phpstan-ignore` keeps the fix minimal.

### CODE REVIEW

**Comment by f2cmb** [comment]
An e2e test could be produced, but since we are working on KB on another projetc i'm not sure it's worth it on this PR.

**Comment by cconard96** [comment]
I tested the changes, but it doesn't seem to have changed anything. I added a console log and the activeNode is not null, so the initial category is never used.

> An e2e test could be produced, but since we are working on KB on another projetc i'm not sure it's worth it on this PR.

That would be for the next major version though which is *undisclosed amount of time* away and GLPI 11 will be supported for a time after that. Given that and the fact we have occasionally had bug fixes break other things, it would be safer to add a test now even if the entire KB feature is being rewritten.

**Comment by f2cmb** [comment]
@cconard96 did you clear the localStorage on your browser after the fix is applied ? I had to, to see the fix working.

About e2e, you're right, i'll comit this soon.

**Comment by cconard96** [comment]
> @cconard96 did you clear the localStorage on your browser after the fix is applied ? I had to, to see the fix working.

That let it work once, but it still isn't completely working. Once you load a category, it is no longer null so clicking on a different category in an article doesn't change it.

**Comment by f2cmb** [comment]
> > @cconard96 did you clear the localStorage on your browser after the fix is applied ? I had to, to see the fix working.
> 
> That let it work once, but it still isn't completely working. Once you load a category, it is no longer null so clicking on a different category in an article doesn't change it.

@cconard96 I fixed it : the URL parameter now takes precedence over persisted state. An e2e test has been added covering both cases. Could you give it another try?

**Comment by cconard96** [comment]
Seems OK now

**Review by cconard96 — APPROVED** [review]

File: src/Glpi/Features/TreeBrowse.php [hunk 1]
```diff
@@ -77,6 +77,10 @@ public static function showBrowseView(string $itemtype, array $params, $update =
                             ? (int) $params['unpublished']
                             : 1;
 
+        $cat_item = static::getCategoryItem($itemtype); // @phpstan-ignore argument.type
```
Comment (trasher) [inline src/Glpi/Features/TreeBrowse.php]: Is the phpstan error really expected? 
If not, it have to be fixed if possible, or added to the baseline. Inline comments must target only issues that cannot be fixed.

Comment (f2cmb) [reply src/Glpi/Features/TreeBrowse.php]: Yes without this (as mentioned) i have errors ont src core files, and if i want to manage everything i have to edit the phpstan rules of the project. This seems to be the best thing to do imho if i want to not produce a fix without editing files outside of the scope of this issue. But i am open to suggestions.

Comment (trasher) [reply src/Glpi/Features/TreeBrowse.php]: I have no idea how to fix that specific issue; phpstan does not like traits as far as I know.

So this should be added to the phpstan baseline; but still not as a local comment.

Comment (trasher) [reply src/Glpi/Features/TreeBrowse.php]: I've added a commit

**Review by trasher — APPROVED** [review]
