### PR TITLE
Fix multiple groups handling in search results

### LINKED ISSUE #21727: Completename handling in search results broken
Remaining values (in cases there are multiple) are not processed and the `itemlink` handling isn't either.

Maybe related to #21510

 _Originally posted by @cconard96 in [#21486](https://github.com/glpi-project/glpi/issues/21486#issuecomment-3461021376)_

### PR DESCRIPTION
**Pull request by cedric-anne**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

It fixes #21727.

### CODE REVIEW

**Review by trasher — APPROVED** [review]

File: tests/functional/SearchTest.php [hunk 1]
```diff
@@ -6230,37 +6231,8 @@ public function testCompletenameColumnRenderingInSearchResults(): void
...
-        $expected = [
-            'FR - _cat_1',
-            'FR - _cat_1 &gt; FR - _subcat_1',
-            'FR - _cat_1 &gt; R&amp;D',
-        ];
-
-        foreach ($expected as $key => $displayname) {
-            $this->assertTrue(isset($result['data']['rows'][$key]['TaskCategory_1']['displayname']));
-            $this->assertEquals($displayname, $result['data']['rows'][$key]['TaskCategory_1']['displayname']);
-        }
```
Comment (cedric-anne) [inline tests/functional/SearchTest.php:6260]: This was already tested in `testCompletenameColumnTranslationsInSearchResults`
