### PR TITLE
Fix solutions; closes #4173

### LINKED ISSUE #4173: Fatal error when adding solution on duplicated ticket
last 9.3/bugfixes (june 13 2018)

```
2018/06/13 08:50:24 [error] 2023#2023: *191 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in .../inc/itilsolution.class.php:266
Stack trace:
#0 .../inc/commondbtm.class.php(928): ITILSolution->prepareInputForAdd(Array)
#1 .../inc/ticket_ticket.class.php(389): CommonDBTM->add(Array)
#2 .../inc/itilsolution.class.php(325): Ticket_Ticket::manageLinkedTicketsOnSolved('3094', Object(ITILSolution))
#3 .../inc/commondbtm.class.php(966): ITILSolution->post_addItem()
#4 .../front/itilsolution.form.php(57): CommonDBTM->add(Array)
#5 {main}
  thrown in .../inc/itilsolution.class.php on line 266" while reading response header from upstream, client: ::1, server: _, request: "POST .../front/itilsolution.form.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost", referrer: "http://localhost.../front/ticket.form.php?id=3094"
```

### PR DESCRIPTION
**Pull request by trasher**
Fix undefined index
Add tests on solutions for duplicated tickets
Make sure there is no loop
Create new empty solution for add

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4173

### CODE REVIEW

File: tests/functionnal/ITILSolution.php [hunk 1]
```diff
@@ -136,4 +136,53 @@ public function testTicketSolution() {
          )
       )->isIdenticalTo(2);
    }
+
+   public function testSoluitionOnDuplicate() {
```
Comment (orthagh) [inline tests/functionnal/ITILSolution.php]: typo
