### PR TITLE
legacy api add_keys_names polymorphic support

### LINKED ISSUE #22842: GLPI 11 API getFriendlyNames() fails for items_id_target fields
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

The `getFriendlyNames()` method in GLPI API fails when `add_keys_names` includes `items_id_target` because `getItemtypeForForeignKeyField('items_id_target')` returns null.

### Relevant log output

```shell
Event: Ticket
error:
DbUtils::getClassForItemtype(): Argument #1 ($itemtype) must be of type string, null given, called in .\src\DbUtils.php on line 554
```

### Page URL

_No response_

### Steps To reproduce

Make an API request to get TicketValidation items with add_keys_names parameter
Include status field in the add_keys_names array

Example API call:

bashGET /apirest.php/TicketValidation?add_keys_names[]=status&add_keys_names[]=items_id_target
4. Observe the error in logs and API response issues

## **Page URL**
API endpoint: /apirest.php/TicketValidation
Affected file: src/Glpi/Api/API.php (getFriendlyNames method)

### Your GLPI setup information

GLPI Version: 11.0.4
Database: MariaDB
PHP Version: 8.3

### Anything else?

Affected Tables:

glpi_ticketvalidations

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

fixes #22842

Filters out non-foreign keys.
Adds support for polymorphic foreign keys like "items_id" and "items_id_target".

### CODE REVIEW

File: src/Glpi/Api/API.php [hunk 1]
```diff
@@ -2911,20 +2911,29 @@ protected function getFriendlyNames(
...
+            if (!isset($data[$kn_fkey])) {
+                trigger_error(sprintf('Invalid value: "%s" doesn\'t exist.', $kn_fkey), E_USER_WARNING);
+                continue;
+            }
+            $kn_id = $data[$kn_fkey];
+
+            if ($kn_fkey === "id") {
                 // Get friendlyname for current item
                 $kn_itemtype = $self_itemtype;
                 $kn_id = $data[$kn_itemtype::getIndexName()];
```
Comment (cedric-anne) [inline src/Glpi/Api/API.php:2926]: If `$kn_itemtype::getIndexName()` is different than `id` and if the `id` field does not exist, a warning will now be triggered. Previously, `id` was correctly replaced by `$kn_itemtype::getIndexName()` without any warning.
The behaviour changed since the warning has been moved outside the `else` block.

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by cedric-anne — APPROVED** [review]
