### PR TITLE
Fix links to ITIL items inside plugin item impact tab; fixes #7301

### LINKED ISSUE #7301: [9.5] Impact analysis - problem with linked tickets
On my cmdb plugin, i display for example a server.

When i click on linked ticket

image

i am redirected to http://localhost/glpi95/plugins/xxx/front/ticket.form.php?id=64945

& not to http://localhost/glpi95/front/ticket.form.php?id=64945

in impact.js you do not use root_doc parameter : 

```
listElements: function(title, elements, url) {
      var html = "";

      if (elements.length > 0) {
         html += "<h3>" + title + "</h3>";
         html += "<ul>";

         elements.forEach(function(element) {
            var link = "./" + url + ".form.php?id=" + element.id;
            html += '<li><a target="_blank" href="' + link + '">' + element.name
               + '</a></li>';
         });
         html += "</ul>";
      }

      return html;
   },
```

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #7301

### CODE REVIEW

File: js/impact.js [hunk 1]
```diff
@@ -2458,7 +2458,7 @@ var GLPIImpact = {
          html += "<ul>";
 
          elements.forEach(function(element) {
-            var link = "./" + url + ".form.php?id=" + element.id;
+            var link = CFG_GLPI.root_doc + "/front/" + url + ".form.php?id=" + element.id;
```
Comment (orthagh) [inline js/impact.js:2461]: This may broke plugins item, no ?

Comment (cedric-anne) [reply js/impact.js:2461]: This method is used to generate URLs for tickets/problems/changes and is called only from `buildOngoingDialogContent`.
