### PR TITLE
Fix assets dropdowns visibility from self service

### LINKED ISSUE #21509: User forms simplified mode: the user cannot enter the computer name in a form.
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

When I’m in form creation mode, the computer names are displayed correctly. However, when the user tries to use this form, they can’t enter the computer name. traduit

1. **form creation mode**

Image

Image

2. **User forms  mode simplifield : the user cannot enter the computer name in a form.**

Image

### Relevant log output

```shell
no log
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

On GLPI 10, ajax request to /getDropdownValue would return their own assets for self service users.

See on formcreator, logged in as 'post-only':

image

image

image

This seems to have changed in GLPI 11, possibly by accident while introducing the generic "AssignableItem" trait.
This PR rectify this behavior by:
* Creating two dedicated `getAssignableVisiblityCriteriaForCentral` and `getAssignableVisiblityCriteriaForHelpdesk` methods.
* The original `getAssignableVisiblityCriteria` method will call the correct submethod depending on the current interface
* The `getAssignableVisiblityCriteriaForHelpdesk` method will return a criteria that will allow the user to see his own items, without right checks as such rights are not available for helpdesk profiles
* A `getOwnAssetsCriteria` method was introduced to share logic without duplication between the two new methods.

## References

Fix #21509, #21566 and #21502.

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
Back to draft, I think I need to take this setting into account too:

image

File: src/Glpi/Features/AssignableItem.php [hunk 1]
```diff
@@ -105,8 +106,22 @@ public function canUpdateItem(): bool
      * @return array[]|QueryExpression[]
      * @see AssignableItemInterface::getAssignableVisiblityCriteria()
      */
-    public static function getAssignableVisiblityCriteria(?string $item_table_reference = null): array
-    {
+    public static function getAssignableVisiblityCriteria(
+        ?string $item_table_reference = null
+    ): array {
+        return Session::getCurrentInterface() === "central"
```
Comment (cedric-anne) [inline src/Glpi/Features/AssignableItem.php]: The `$criteria = [crc32(serialize($criteria)) => $criteria];` encapsulation should be done here.
