### PR TITLE
do not leak full path (logs and display)

### LINKED ISSUE #18895: Do not leak full path of file in error logs
Currently in some _log files, we leak the full path to the impacted files.

Example in php-errors.log:
```
[2024-04-09 17:33:34] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to bind to LDAP server `veve.geg.efe.:389` anonymously
error: Can't contact LDAP server (-1) in /home/francois/www/glpi-core/10bf/htdocs/src/AuthLDAP.php at line 3194
  Backtrace :
  src/AuthLDAP.php:3194                              trigger_error()
  src/AuthLDAP.php:1666                              AuthLDAP::connectToServer()
  front/authldap.form.php:67                         AuthLDAP::testLDAPConnection()
  public/index.php:82                                require()
```

In certain security contexts (at our customers, in the cloud, etc.), given that we can consult/download these files directly in the GLPI 11 interface, we should only see the end of the path to the file (example: "src/AuthLDAP.php").

And yes, this information can also be found in the "System" tab of the general configuration of GLPI, customers/partners have already asked us for patches to hide this information: perhaps take advantage of this to add a variable like (simple example to think about) if installation mode "CLOUD", do not display the system information.

The full paths are also available, in debug mode, when an exception occurs, but they should not.

### PR DESCRIPTION
**Pull request by SebSept**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

- It fixes #18895

Root files path is replaced by '.' in logs and display.
Work for errors and exceptions.
Paths are still leak if the problem happend before kernel is booted, but not a big deal since these problem require to modify core source code.

### CODE REVIEW

File: src/Toolbox.php [hunk 1]
```diff
@@ -3309,4 +3313,14 @@ final public static function getNormalizedItemtype(string $itemtype)
     {
         return strtolower(str_replace('\\', '', $itemtype));
     }
+
+    /**
+     * @param string $msg
+     * @return array|string|string[]
+     */
+    public static function cleanPaths(string $msg): string|array
```
Comment (trasher) [inline src/Toolbox.php:3321]: I guess we can just keep this one (since it's static and eays to call anywhere in GLPI), drop the other one in log line formatter (replaced with TOolbox one call), and also use this one for each sanitizing instead of hardcoded replacements in ErroHandler/ErrorController.

Comment (cedric-anne) [reply src/Toolbox.php:3321]: You may create a `Glpi\Error\ErrorUtils` class that contains a static `cleanPaths` method to not depend on the whole `Toolbox` class.

Comment (trasher) [reply src/Toolbox.php:3321]: The point is we should onlyç have one method that does the replacement, and rely on it elsewhere. Cedric's proposal seems good to me.

File: phpunit/functional/ToolboxTest.php [hunk 2]
```diff
@@ -1637,4 +1639,52 @@ public function testComputeRedirect(string $interface, string $where, ?string $r
 
         $this->assertSame($result, $instance->computeRedirect($where));
     }
+
+
+    private function setUpLogFiles(): void
+    {
+        // remove the log file if it exists
+        assert(!file_exists($this->getCustomLogFilePath()) || unlink($this->getCustomLogFilePath()));
+        assert(!file_exists($this->getDefaultFilePath()) || unlink($this->getDefaultFilePath()));
```
Comment (cedric-anne) [inline phpunit/functional/ToolboxTest.php:1648]: It does not seems usefull for the added tests.

```suggestion
```

File: src/Glpi/Error/ErrorUtils.php [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+
+namespace Glpi\Error;
+
+class ErrorUtils
+{
+    /**
+     * @param string $message
+     *
+     * Replace GLPI_ROOT path by '.' in $message
+     * @return string
```
Comment (cedric-anne) [inline src/Glpi/Error/ErrorUtils.php:43]: We may want to clean more paths in the future. No need to be too precise in the method description.

```suggestion
     * Rewrite file paths to not expose their full filesystem path, as it can be considered as a sensitive information.
     *
     * @param string $message
     * @return string
```

File: phpunit/functional/Glpi/Error/ErrorUtilsTest.php [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+
+    public static function unsafeContentsProvider(): array
+    {
+        return [
+            [\GLPI_ROOT . 'bla bla'],
+            ['bla bla' . \GLPI_ROOT],
+            [\GLPI_ROOT],
+            ['/path/' . \GLPI_ROOT . '/path'],
+        ];
+    }
```
Comment (cedric-anne) [inline phpunit/functional/Glpi/Error/ErrorUtilsTest.php:82]: IMHO, a unique test that verifies the whole returned value would be more relevant, e.g. `'a string with ' . \GLPI_ROOT . '/test.php and other content'` should return `'a string with ./test.php and other content'`.

File: phpunit/functional/Glpi/Log/ErrorLogHandlerTest.php [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+        $this->logger->error($message);
+
+        $this->assertStringContainsString($message, file_get_contents($this->getDefaultFilePath()));
+    }
+
+    public function test_Log_FilterRootPathInLogFile(): void
+    {
+        $PHPLOGGER = new Logger('glpi_test');
+        $PHPLOGGER->pushHandler(new ErrorLogHandler());
+
```
Comment (cedric-anne) [inline phpunit/functional/Glpi/Log/ErrorLogHandlerTest.php:75]: This logger is not used here.

```suggestion
```

File: src/Toolbox.php [hunk 6]
```diff
@@ -311,9 +312,12 @@ private static function log($level = LogLevel::WARNING, $args = null)
         $tps = microtime(true);
 
         try {
+            $msg = self::cleanPaths($msg);
```
Comment (cedric-anne) [inline src/Toolbox.php:315]: I think it is not required. The `$PHPLOGGER` uses the `ErrorLogLineFormatter/AbstractLogLineFormatter` that already handle this clean.

```suggestion
```

File: phpunit/functional/ToolboxTest.php (hunk 2 above)
Comment (SebSept) [reply phpunit/functional/ToolboxTest.php:1648]: nop, it was the previous init in setUp()

File: phpunit/functional/Glpi/Error/ErrorUtilsTest.php (hunk 4 above)
Comment (SebSept) [reply phpunit/functional/Glpi/Error/ErrorUtilsTest.php:82]: testing edge cases is important and should not be missed IMHO.

File: phpunit/functional/Glpi/Log/ErrorLogHandlerTest.php (hunk 5 above)
Comment (SebSept) [reply phpunit/functional/Glpi/Log/ErrorLogHandlerTest.php:75]: correct.

File: phpunit/functional/Glpi/Error/ErrorUtilsTest.php (hunk 4 above)
Comment (cedric-anne) [reply phpunit/functional/Glpi/Error/ErrorUtilsTest.php:82]: I agree, my point is that you should validate the complete returned string. You can still use a provider to provide many edge cases.

File: src/Toolbox.php (hunk 6 above)
Comment (SebSept) [reply src/Toolbox.php:315]: path cleaning is made in the LineFormatter attached to the ErrorLogHandler.
At the moment, the error handler is pushed in the logger. 
But **it may not be the case in the future**.
By doing it, we avoid a future regression.
Cleaning both times has no downside.

So you're right, **at the moment, with the current configuration** cleaning happens 2 times.
But it's future-proof to keep this filtering.

Comment (cedric-anne) [reply src/Toolbox.php:315]: OK.

File: phpunit/functional/Glpi/Error/ErrorUtilsTest.php (hunk 4 above)
Comment (SebSept) [reply phpunit/functional/Glpi/Error/ErrorUtilsTest.php]: done

File: src/Toolbox.php [hunk 7]
```diff
@@ -3309,4 +3314,13 @@ final public static function getNormalizedItemtype(string $itemtype)
     {
         return strtolower(str_replace('\\', '', $itemtype));
     }
+
+    /**
+     * @param string $message
+     * @return string
+     */
+    public static function cleanPaths(string $message): string
```
Comment (trasher) [inline src/Toolbox.php:3322]: Is this new method really needed? I do not think we expect it does more one day than just calling `ErrorUtils::cleanPaths()` - which can be done directly as far as I see.

File: phpunit/functional/Glpi/Error/ErrorUtilsTest.php [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+    {
+        return [
+            ['input' => \GLPI_ROOT . '/files/ is not writtable.', 'expected' => './files/ is not writtable.'],
+            ['input' => 'Base dir is writtable, fix rights in ' . \GLPI_ROOT, 'expected' => 'Base dir is writtable, fix rights in .'],
+            ['input' => \GLPI_ROOT, 'expected' => '.'],
+            ['input' => 'error in ' . \GLPI_ROOT . '/path : content not readable', 'expected' => 'error in ./path : content not readable'],
+        ];
+    }
+
+    public static function safeContentsProvider(): array
```
Comment (trasher) [inline phpunit/functional/Glpi/Error/ErrorUtilsTest.php:66]: This one is not used

File: src/Toolbox.php (hunk 7 above)
Comment (trasher) [reply src/Toolbox.php:3322]: I see no reason having now or in the future a `Toolbox::cleanPaths` that does something else than `ErrorUtil::cleanPaths`
I also do not see how it's less error prone; it may even be confusing having 2 distinct method that does exactly the same.

File: phpunit/functional/Glpi/Error/ErrorUtilsTest.php [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+
+use PHPUnit\Framework\Attributes\DataProvider;
+
+class ErrorUtilsTest extends \DbTestCase
+{
+    #[DataProvider('safeContentsProvider')]
+    public function testcleanPathsOnSafeContent($input, $expected)
+    {
+        assert(is_string(\GLPI_ROOT) && strlen(\GLPI_ROOT) > 0);
+        $this->assertEquals($expected, ErrorUtils::cleanPaths($input));
```
[the remark this answers is not in the document]
Comment (SebSept) [reply phpunit/functional/Glpi/Error/ErrorUtilsTest.php]: good catch!

File: src/Toolbox.php (hunk 7 above)
Comment (SebSept) [reply src/Toolbox.php:3322]: did you notice Toolbox::cleanPaths() calls ErrorUtil::cleanPaths() ? There is only one concrete function.
In my experience, it's always a good thing to isolate that kind of things.
It doesn't deserve a long discussion as you said.

**Review by cedric-anne — APPROVED** [review]

File: src/Toolbox.php (hunk 7 above)
Comment (cedric-anne) [reply src/Toolbox.php:3322]: When we will be able to "inject" dependencies in the constructor, the `ErrorUtil::cleanPaths()` calls may be replaced by `$this->errorUtils->cleanPaths()` calls. The way it is done currently may indeed require less changes. Anyway, this kind of changes is pretty easy to made with IDEs and error would probably be detected by PHPStan or the test suite.

Both way to do are valid to me.

**Review by AdrienClairembault — APPROVED** [review]

**Review by trasher — APPROVED** [review]
