### PR TITLE
Fix solve ticket massive action

### LINKED ISSUE #19564: Solving tickets from change or problem = habilitation error - 11.0.0-beta2
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-beta2

### Bug description

The "resolve tickets" feature from a change or issue via the massive action does not work. Returns an "habilitations error"
Profile used: Super-admin
Regardless of whether the change or issue is resolved or not, it is impossible to use this feature to resolve the tickets associated with the issue/change.

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Fix #19564.

Not sure why but the original code is looking for a `tickets_id` field on a `Ticket` object.
My theory is that at some point in the past `$item` was a `Change_Ticket/Problem_Ticket` item and it was changed by some unrelated PR to a `Ticket`, breaking this code.

Added a test to avoid it breaking again in the future.

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
`CFG_GLPI` is undefined for the `/front/massive_action.php` in the vue js app file, only on the CI.
[9ac3798](https://github.com/glpi-project/glpi/pull/19606/commits/9ac3798a983487a3b47c70ccfa517d37ae066dd8) should fix it but there is probably an underlying issue.

**Comment by AdrienClairembault** [comment]
Nvm, won't work since this is computed at build time so the condition will always be true.

File: js/src/vue/app.js [hunk 1]
```diff
@@ -69,9 +69,12 @@ const component_context = import.meta.webpackContext('.', {
     chunkName: '/vue-sfc/[request]'
 });
 
-/* global __webpack_public_path__ */
-// eslint-disable-next-line no-global-assign
-__webpack_public_path__ = CFG_GLPI.root_doc + __webpack_public_path__;
+// TODO: CFG_GLPI is undefined sometimes, find out why.
+if (typeof CFG_GLPI !== "undefined") {
```
Comment (cedric-anne) [inline js/src/vue/app.js:73]: This is not a good idea. We have to find why E2E test fails here.

@cconard96 Do you have an idea ?

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: js/src/vue/app.js (hunk 1 above)
Comment (AdrienClairembault) [reply js/src/vue/app.js:73]: Yes but it is not related to the fix from this PR, it should be looked at independently.

**Comment by AdrienClairembault** [comment]
Up

**Comment by AdrienClairembault** [comment]
Rebased to solve conflicts.

**Comment by AdrienClairembault** [comment]
Rebased to fix tests.

File: js/src/vue/app.js (hunk 1 above)
Comment (cedric-anne) [reply js/src/vue/app.js:73]: Fixed in https://github.com/glpi-project/glpi/pull/19721

**Review by trasher — APPROVED** [review]

**Comment by AdrienClairembault** [comment]
I'll look into on monday, wanted to fix it but encountered other errors on the way that needed to also be fixed.

**Review by cedric-anne — APPROVED** [review]
