### PR TITLE
fix(forms): Ensure that translations of default forms are visible in the list

### LINKED ISSUE #21002: Form translations do not always show in list
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0/bugfixes

### Bug description

Originally noted in #20496.

If question translations exist but not form name translations, the language doesn't show in the Form translations tab until you "Add" the language.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ccailly**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #21002

Currently, translations for default forms are not necessarily initialized (which means that there is at least one empty translation for the form name).
This fix initializes translations for all languages so that all translations are visible in the form's translations tab.

### CODE REVIEW

File: src/Glpi/Helpdesk/DefaultDataManager.php [hunk 1]
```diff
@@ -165,6 +165,17 @@ private function addFormTranslations(int $forms_id, string $name, string $descri
...
+            $DB->insert(
+                ItemTranslation::getTable(),
+                [
+                    'itemtype'     => Form::class,
+                    'items_id'     => $forms_id,
+                    'language'     => $lang,
+                    'key'          => Form::TRANSLATION_KEY_NAME,
+                    'translations' => '{}',
+                ]
+            );
```
Comment (cedric-anne) [inline src/Glpi/Helpdesk/DefaultDataManager.php]: Maybe I miss something, but as far as there is a unique key `unique_item_key` (`items_id`, `itemtype`, `key`, `language`), adding this entry should make the `$form_stmt->execute([Form::TRANSLATION_KEY_NAME, $lang, json_encode(['one' => $translated_name]), $name_hash]);` query fail.

File: src/Glpi/Helpdesk/DefaultDataManager.php [hunk 2]
```diff
@@ -169,6 +169,17 @@ private function addFormTranslations(int $forms_id, string $name, string $descri
...
+                $DB->insert(
+                    ItemTranslation::getTable(),
+                    [
+                        'itemtype'     => Form::class,
+                        'items_id'     => $forms_id,
+                        'language'     => $lang,
+                        'key'          => Form::TRANSLATION_KEY_NAME,
+                        'translations' => '{}',
+                    ]
+                );
```
Comment (cedric-anne) [inline src/Glpi/Helpdesk/DefaultDataManager.php]: 1. The statement should be used here.
2. I guess the name hash must be properly defined.

```suggestion
                $form_stmt->execute([Form::TRANSLATION_KEY_NAME, $lang, '{}',  $name_hash]);
```
