### PR TITLE
fix(form): Forms with many destinations may overload the browser

### LINKED ISSUE #21310: GLPI11 - Forms with many destinations
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0

### Bug description

Hello,

I have a form with 89 destinations that does not load (in the ‘Destinations’ submenu of the form). When I go to the form's destinations, the page remains loading and then displays an error. I do not have any errors on the GLPI side or in the browser tools.

If you wish, I can email you an export of the form in JSON format.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by froozeify**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

- It fixes #21310
- Switching to ajax request on destination page so forms with a lot of destinations don't overload the browser (with 89 destination was getting more than 250 requests on the page load)

### CODE REVIEW

File: js/modules/Forms/DestinationAccordionController.js [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        const accordionWrapper = document.querySelector('#glpi-destinations-accordion');
+
+        accordionWrapper.addEventListener('show.bs.collapse', async (e) => {
+            const accordionItem = e.target;
+            const accordionItemContent = accordionItem.querySelector('.accordion-body');
+            if (accordionItemContent.innerHTML.trim() !== '') {
+                return;
+            }
+
+            accordionItemContent.innerHTML = '<div class="text-center"><div class="spinner-border text-primary" role="status"></div></div>';
```
Comment (AdrienClairembault) [inline js/modules/Forms/DestinationAccordionController.js]: Looks better with a small margin at the end :)

```suggestion
            accordionItemContent.innerHTML = '<div class="text-center"><div class="spinner-border text-primary mb-3" role="status"></div></div>';
```

File: src/Glpi/Controller/Form/Destination/GetDestinationFormController.php [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+                    {% endif %}
+                </div>
+
+                {# Hidden values #}
+                <input type="hidden" name="id" value="{{ destination.getID() }}"/>
+                <input type="hidden" name="_glpi_csrf_token" value="{{ csrf_token() }}"/>
+            </form>
+        TWIG,
+            $twig_params
+        );
```
Comment (AdrienClairembault) [inline src/Glpi/Controller/Form/Destination/GetDestinationFormController.php]: We try to avoid using inline templates

File: js/modules/Forms/DestinationAccordionController.js [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <https://www.gnu.org/licenses/>.
+ *
+ * ---------------------------------------------------------------------
+ */
+import { GlpiFormDestinationAutoConfigController } from "./DestinationAutoConfigController.js";
+import {GlpiFormDestinationConditionController} from "./DestinationConditionController.js";
```
Comment (AdrienClairembault) [inline js/modules/Forms/DestinationAccordionController.js]:
```suggestion
import { GlpiFormDestinationConditionController } from "./DestinationConditionController.js";
```

To keep it similar to the previous line

File: templates/pages/admin/form/form_destination.html.twig [hunk 4]
```diff
@@ -173,11 +156,11 @@
...
+    import("/js/modules/Forms/DestinationAccordionController.js").then(function (module) {
+        new module.GlpiFormDestinationAccordionController();
 
-    import("/js/modules/Forms/DestinationConditionController.js").then((m) => {
-        new m.GlpiFormDestinationConditionController();
-    });
+        {% if active_destination %}
+            document.querySelector('.destination-{{ active_destination }} .accordion-button').click();
+        {% endif %}
+    })
```
Comment (AdrienClairembault) [inline templates/pages/admin/form/form_destination.html.twig:170]: It would be better for the UX if the active destination was already loaded in the main request.

File: src/Glpi/Controller/Form/Destination/GetDestinationFormController.php [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+        // Right check
+        if (!$destination->can($destination_id, READ)) {
+            throw new AccessDeniedHttpException();
+        }
+
+        $twig = TemplateRenderer::getInstance()->render('pages/admin/form/form_destination_form.html.twig', [
+            'destination' => $destination,
+            'form' => $destination->getForm(),
+            'can_update' => FormDestination::canUpdate(),
```
Comment (AdrienClairembault) [inline src/Glpi/Controller/Form/Destination/GetDestinationFormController.php]:
```suggestion
            'can_update' => FormDestination::canUpdate() && $destination->canUpdateItem(),
```

File: templates/pages/admin/form/form_destination.html.twig [hunk 6]
```diff
@@ -37,6 +37,10 @@
 {# @var int|null                                       active_destination #}
 {# @var boolean                                        can_update #}
 
+{% if destinations|length == 1 %}
+    {% set active_destination = (destinations|first).getID() %}
+{% endif %}
+
```
Comment (cedric-anne) [inline templates/pages/admin/form/form_destination.html.twig]: IMHO, this fallback should be done on the controller side.

**Review by cedric-anne — APPROVED** [review]
