### PR TITLE
fix double encrypt of snmp passwords

### LINKED ISSUE #23843: SNMP v3 credentials edit
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

When I create an SNMP v3 credentials, all is good.
When I want to edit (and make no change, but click "Save") the credentials, the first time, I get no error but the authentication stops working. The second time, I get
Image

It looks like the pass field are replaced by a placeholder to display all the dots but the place holder is written in the DB.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

fixes #23843

UX of password fields isn't standardized in GLPI, so if this isn't how it is desired to handle them in this specific case, please let me know. The encrypted values were used in the form and saving the form caused them to get encrypted again. By the second save, the encrypted data becomes too long to store.

### CODE REVIEW

File: src/SNMPCredential.php [hunk 1]
```diff
@@ -204,6 +209,18 @@ public function getEncryption(): string
...
+        parent::post_getFromDB();
+        $key = new GLPIKey();
+        if (isset($this->fields['auth_passphrase'])) {
+            $this->fields['auth_passphrase'] = $key->decrypt($this->fields['auth_passphrase']);
+        }
+        if (isset($this->fields['priv_passphrase'])) {
+            $this->fields['priv_passphrase'] = $key->decrypt($this->fields['priv_passphrase']);
+        }
+    }
+
```
Comment (cedric-anne) [inline src/SNMPCredential.php]: It is preferable to not decrypt values automatically here, but only when it is necessary. The `|decrypt` filter can be used in the `/templates/components/form/snmpcredential.html.twig` template.

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/SNMPCredential.php (hunk 1 above)
Comment (cconard96) [reply src/SNMPCredential.php]: This is done currently for OAuthClient and Webhook. Should they be changed for 11.0/bugfixes too?

Comment (cedric-anne) [reply src/SNMPCredential.php]: Yes, since it could prevent unexpected leaks of sensitive data (e.g. with a var dump).

**Review by cedric-anne — APPROVED** [review]

**Comment by trasher** [comment]
Lint issue is unrelated, we're looking into it.

**Review by trasher — APPROVED** [review]
