### PR TITLE
Fix dropdown conditions

### LINKED ISSUE #19456: Forms conditional visibility not working
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-beta

### Bug description

Testing "Conditional Visibility" from forms

- Works with "Always Visible" (Default)
- Does not work with "Visible if..."
- Does not work with "Hidden if..."

Image

Image

### Relevant log output

```shell
(No logs created during creation + tests)
```

### Page URL

http://glpi.url/Form/Render/<Form ID>

### Steps To reproduce

1. Click "Create a Ticket" in user glpi.url/Helpdesk or preview your form in Administration > Forms
2. Select the form that you've created / Preview your form
3. Try to select a dropdown who has any visibility rule set

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0-dev ( => /usr/share/glpi11)
Installation mode: TARBALL
Current language: en_US</pre></details><details><summary>Server</summary><pre>Operating system: Linux 5.14.0-427.40.1.el9_4.x86_64 #​1 SMP PREEMPT_DYNAMIC Wed Oct 16 07:08:17 EDT 2024 x86_64

PHP: 8.3.13 fpm-fcgi

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard,
sockets, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, ldap, exif,
mysqlnd, PDO, Phar, SimpleXML, soap, sodium, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader,
xmlrpc, zip, apcu, selinux, Zend OPcache

Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
upload_max_filesize="20M" disable_functions="" 

Web server: Apache/2.4.57 (AlmaLinux) OpenSSL/3.0.7 ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
Edg/135.0.0.0

Database:
   
Server Software: Percona Server (GPL), Release 30, Revision 41ebc5d9
   
Server Version: 8.0.39-30
   
Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@127.0.0.1/glpi11
   
Host info: 127.0.0.1 via TCP/IP

Requirements:
PHP version (8.3.13) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
mysqli extension is installed.
curl extension is installed.
gd extension is installed.
intl extension is installed.
mbstring extension is installed.
zlib extension is installed.
bcmath extension is installed.
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed.
Database engine version (8.0.39) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi11/files/_cache has been validated.
Write access to /var/lib/glpi11/files/_cron has been validated.
Write access to /var/lib/glpi11/files has been validated.
Write access to /var/lib/glpi11/files/_graphs has been validated.
Write access to /var/lib/glpi11/files/_lock has been validated.
Write access to /var/lib/glpi11/files/_pictures has been validated.
Write access to /var/lib/glpi11/files/_plugins has been validated.
Write access to /var/lib/glpi11/files/_rss has been validated.
Write access to /var/lib/glpi11/files/_sessions has been validated.
Write access to /var/lib/glpi11/files/_tmp has been validated.
Write access to /var/lib/glpi11/files/_uploads has been validated.
For security reasons, SELinux
mode should be Enforcing.

Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/usr/share/glpi11/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: "/usr/share/glpi11"
GLPI_VERSION: "11.0.0-dev"
GLPI_SCHEMA_VERSION: "11.0.0-dev@30aae2f1a8a216f13ed3674d32ae3b45b7cde98c"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.4"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/usr/share/glpi11/locales"
GLPI_CONFIG_DIR: "/etc/glpi11"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: false
GLPI_VAR_DIR: "/var/lib/glpi11/files"
GLPI_LOG_DIR: "/var/log/glpi11"
GLPI_SYSTEM_CRON: true
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_MARKETPLACE_DIR: "/usr/share/glpi11/marketplace"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST:
["#^http://[^@:]+(:80)?(/.*)?$#","#^https://[^@:]+(:443)?(/.*)?$#","#^feed://[^@:]+(/.*)?$#"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_DOC_DIR: "/var/lib/glpi11/files"
GLPI_CACHE_DIR: "/var/lib/glpi11/files/_cache"
GLPI_CRON_DIR: "/var/lib/glpi11/files/_cron"
GLPI_GRAPH_DIR: "/var/lib/glpi11/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi11/files/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi11/files/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi11/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi11/files/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi11/files/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi11/files/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi11/files/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi11/files/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi11/files/_inventories"
GLPI_THEMES_DIR: "/var/lib/glpi11/files/_themes"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"</pre></details><details><summary>Libraries</summary><pre>symfony/mailer not found
simplepie/simplepie version 1.8.1 in /usr/share/glpi11/vendor/simplepie/simplepie/src
tecnickcom/tcpdf version 6.9.0 in /usr/share/glpi11/vendor/tecnickcom/tcpdf
tecnickcom/tc-lib-barcode version  in /usr/share/glpi11/vendor/tecnickcom/tc-lib-barcode/src
sabre/dav version  in /usr/share/glpi11/vendor/sabre/dav/lib/DAV
sabre/http version  in /usr/share/glpi11/vendor/sabre/http/lib
sabre/uri version  in /usr/share/glpi11/vendor/sabre/uri/lib
sabre/vobject version  in /usr/share/glpi11/vendor/sabre/vobject/lib
laminas/laminas-i18n version  in /usr/share/glpi11/vendor/laminas/laminas-i18n/src
monolog/monolog version  in /usr/share/glpi11/vendor/monolog/monolog/src/Monolog
sebastian/diff version  in /usr/share/glpi11/vendor/sebastian/diff/src
donatj/phpuseragentparser version  in /usr/share/glpi11/vendor/donatj/phpuseragentparser/src/UserAgent
elvanto/litemoji version  in /usr/share/glpi11/vendor/elvanto/litemoji/src
gettext/languages version  in /usr/share/glpi11/vendor/gettext/languages/src
symfony/console version  in /usr/share/glpi11/vendor/symfony/console
symfony/config version  in /usr/share/glpi11/vendor/symfony/config/Loader
symfony/dependency-injection version  in /usr/share/glpi11/vendor/symfony/dependency-injection
symfony/event-dispatcher version  in /usr/share/glpi11/vendor/symfony/event-dispatcher
symfony/filesystem version  in /usr/share/glpi11/vendor/symfony/filesystem
symfony/framework-bundle version  in /usr/share/glpi11/vendor/symfony/framework-bundle
symfony/http-foundation version  in /usr/share/glpi11/vendor/symfony/http-foundation
symfony/http-kernel version  in /usr/share/glpi11/vendor/symfony/http-kernel
symfony/routing version  in /usr/share/glpi11/vendor/symfony/routing
scssphp/scssphp version  in /usr/share/glpi11/vendor/scssphp/scssphp/src
laminas/laminas-mail version  in /usr/share/glpi11/vendor/laminas/laminas-mail/src/Protocol
laminas/laminas-mime version  in /usr/share/glpi11/vendor/laminas/laminas-mime/src
rlanvin/php-rrule version  in /usr/share/glpi11/vendor/rlanvin/php-rrule/src
ramsey/uuid version  in /usr/share/glpi11/vendor/ramsey/uuid/src
phpoffice/phpspreadsheet version  in /usr/share/glpi11/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet
psr/log version  in /usr/share/glpi11/vendor/psr/log/src
psr/simple-cache version  in /usr/share/glpi11/vendor/psr/simple-cache/src
psr/cache version  in /usr/share/glpi11/vendor/psr/cache/src
psr/container version  in /usr/share/glpi11/vendor/psr/container/src
league/csv version  in /usr/share/glpi11/vendor/league/csv/src
mexitek/phpcolors version  in /usr/share/glpi11/vendor/mexitek/phpcolors/src/Mexitek/PHPColors
guzzlehttp/guzzle version  in /usr/share/glpi11/vendor/guzzlehttp/guzzle/src
guzzlehttp/psr7 version  in /usr/share/glpi11/vendor/guzzlehttp/psr7/src
glpi-project/inventory_format version  in /usr/share/glpi11/vendor/glpi-project/inventory_format/lib/php
wapmorgan/unified-archive version  in /usr/share/glpi11/vendor/wapmorgan/unified-archive/src
paragonie/sodium_compat version  in /usr/share/glpi11/vendor/paragonie/sodium_compat/src
symfony/cache version  in /usr/share/glpi11/vendor/symfony/cache
html2text/html2text version  in /usr/share/glpi11/vendor/html2text/html2text/src
symfony/css-selector version  in /usr/share/glpi11/vendor/symfony/css-selector
symfony/dom-crawler version  in /usr/share/glpi11/vendor/symfony/dom-crawler
twig/twig version  in /usr/share/glpi11/vendor/twig/twig/src
twig/string-extra version  in /usr/share/glpi11/vendor/twig/string-extra
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php83 not found
league/oauth2-client version  in /usr/share/glpi11/vendor/league/oauth2-client/src/Provider
league/oauth2-google version  in /usr/share/glpi11/vendor/league/oauth2-google/src/Provider
thenetworg/oauth2-azure version  in /usr/share/glpi11/vendor/thenetworg/oauth2-azure/src/Provider
league/commonmark version  in /usr/share/glpi11/vendor/league/commonmark/src/Extension/CommonMark
egulias/email-validator version  in /usr/share/glpi11/vendor/egulias/email-validator/src
symfony/mime not found
apereo/phpcas version  in /usr/share/glpi11/vendor/apereo/phpcas/source
bacon/bacon-qr-code version  in /usr/share/glpi11/vendor/bacon/bacon-qr-code/src
robthree/twofactorauth version  in /usr/share/glpi11/vendor/robthree/twofactorauth/lib
ralouphie/getallheaders not found
symfony/html-sanitizer version  in /usr/share/glpi11/vendor/symfony/html-sanitizer
league/oauth2-server version  in /usr/share/glpi11/vendor/league/oauth2-server/src
league/html-to-markdown version  in /usr/share/glpi11/vendor/league/html-to-markdown/src
twig/markdown-extra version  in /usr/share/glpi11/vendor/twig/markdown-extra
webonyx/graphql-php version  in /usr/share/glpi11/vendor/webonyx/graphql-php/src
phpdocumentor/reflection-docblock version  in /usr/share/glpi11/vendor/phpdocumentor/reflection-docblock/src
symfony/property-access version  in /usr/share/glpi11/vendor/symfony/property-access
symfony/serializer version  in /usr/share/glpi11/vendor/symfony/serializer
symfony/property-info version  in /usr/share/glpi11/vendor/symfony/property-info
symfony/error-handler version  in /usr/share/glpi11/vendor/symfony/error-handler</pre></details>

### Anything else?

(Not a fresh installation, it's was an update from GLPI 10)

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Fix #19456.

In #19167 I changed some behaviors regarding the radio and checkbox questions.
These changes also needed to be done for the dropdown question but I've missed it.

This PR fix this issue and some other minors bugs I've encountered while adding the new tests.

### CODE REVIEW

File: js/modules/Forms/RendererController.js [hunk 1]
```diff
@@ -122,6 +122,9 @@ export class GlpiFormRendererController
 
             debouncedComputeItemsVisibilities();
         });
+
+        // Enable actions
+        $(this.#target).removeClass('pointer-events-none');
```
Comment (AdrienClairembault) [inline js/modules/Forms/RendererController.js:127]: This make sure users can't interact with the form until the JS is loaded (mostly helpful for automated testing like e2e where the test will click too fast on the page - unlikely to happens to a real user).

File: src/Glpi/Form/Condition/Engine.php [hunk 2]
```diff
@@ -130,6 +130,10 @@ private function computeConditions(array $conditions): bool
     {
         $conditions_result = null;
         foreach ($conditions as $condition) {
+            if (empty($condition->getItemUuid())) {
+                continue;
+            }
```
Comment (AdrienClairembault) [inline src/Glpi/Form/Condition/Engine.php:135]: Prevent failure on condition that are not fully defined.

File: src/Glpi/Form/QuestionType/QuestionTypeDropdown.php [hunk 3]
```diff
@@ -247,23 +247,24 @@ public function renderEndUserTemplate(
...
+                    'aria_label': label,
                 }
             ) }}
 TWIG;
 
         $twig = TemplateRenderer::getInstance();
-        $values = array_map(fn ($option) => $option['value'], $this->getValues($question));
         $checked_values = array_map(
-            fn ($option) => $option['value'],
+            fn ($option) => $option['uuid'],
```
Comment (AdrienClairembault) [inline src/Glpi/Form/QuestionType/QuestionTypeDropdown.php:261]: Main fix, send the uuid to be used as the dropdown 'selected' value, not the label.

File: src/Glpi/Form/QuestionType/QuestionTypeDropdown.php [hunk 4]
```diff
@@ -247,23 +247,24 @@ public function renderEndUserTemplate(
...
                 {
-                    'no_label': true,
-                    'values'  : checked_values,
-                    'multiple': is_multiple,
-                    'mb'      : '',
+                    'no_label'  : true,
+                    'values'    : checked_values,
+                    'multiple'  : is_multiple,
+                    'mb'        : '',
+                    'aria_label': label,
```
Comment (AdrienClairembault) [inline src/Glpi/Form/QuestionType/QuestionTypeDropdown.php:254]: For accessibility, needed for e2e tests.

File: src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php [hunk 5]
```diff
@@ -72,6 +72,12 @@ public function applyValueOperator(
         mixed $b,
     ): bool {
         // Normalize values as strings.
+        if (is_array($a)) {
+            $a = array_pop($a);
+        }
+        if (is_array($b)) {
+            $a = array_pop($b);
+        }
```
Comment (AdrienClairembault) [inline src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php:80]: Better value normalization to avoid errors when possible.

**Review by trasher — APPROVED** [review]

File: src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php [hunk 6]
```diff
@@ -72,6 +72,12 @@ public function applyValueOperator(
         mixed $b,
     ): bool {
         // Normalize values as strings.
+        if (is_array($a)) {
+            $a = array_pop($a);
+        }
+        if (is_array($b)) {
+            $a = array_pop($b);
```
Comment (cedric-anne) [inline src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php:79]:
```suggestion
            $b = array_pop($b);
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by cedric-anne — APPROVED** [review]
