### PR TITLE
Fix networkport connection log creation

### LINKED ISSUE #21488: Port history is empty all the time
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

Hi! We are currently testing glpi agent to inventory our network, mainly switches. And history of port on switches are crucial for us. Now GLPI agent is scanning switches itself properly, updating information every hour for at least 3 days, and still there isn't port history on any port on any switch.

GLPI agent version is 1.15

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

GLPI: 11.0.1 ( => /var/www/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: OK

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
Also fix Twig display
closes #21488

### CODE REVIEW

File: src/NetworkPortConnectionLog.php [hunk 1]
```diff
@@ -46,6 +46,7 @@ class NetworkPortConnectionLog extends CommonDBChild
     public static $itemtype        = 'NetworkPort';
     public static $items_id        = 'networkports_id';
     public $dohistory              = false;
+    public static $mustBeAttached  = false;
```
Comment (cedric-anne) [inline src/NetworkPortConnectionLog.php]: This means that a log can be attached to no `NetworkPort`. What is the use case ?

Comment (trasher) [reply src/NetworkPortConnectionLog.php]: There is no use case. I do not understand why existing this change is needed. CommonDBChild prevents adding log.

**Comment by trasher** [comment]
Tests are broken, I do not yet know why. Proposed fix is probably incorrect, I put back as draft.

**Comment by cconard96** [comment]
> Tests are broken, I do not yet know why.

The JS test for the dashboard joke failed :(

File: src/NetworkPortConnectionLog.php (hunk 1 above)
Comment (cedric-anne) [reply src/NetworkPortConnectionLog.php]: It probably means that a `add` or `update` operation does correctly pass the `items_id` value. If this value does not correspond to a valid `NetworkPort` ID, then it will prevent it to be added.

Change proposed in #21524 may help. For instance, I had not yet tried to check if it is a bug or an expected message, but adding this message makes the following test fail:
```
1) tests\units\Glpi\Inventory\Asset\NetworkPortTest::testNetworkEquipmentsConnectionsConverted
Some messages has not been handled in tests\units\Glpi\Inventory\Asset\NetworkPortTest::GLPITestCase::tearDown:
Array
(
    [1] => Array
        (
            [0] => Parent item is invalid.
            [1] => Parent item is invalid.
        )

)
```

Comment (cconard96) [reply src/NetworkPortConnectionLog.php]: Isn't the `$items_id` property wrong? It is set as "networkports_id" but it should be linked by "networkports_id_source" and "networkports_id_destination".

`NetworkPort_NetworkPort::storeConnectionLog` tries adding an entry with this input:
```php
$input = [
    'networkports_id_source'      => $netports_id,
    'networkports_id_destination' => $opposite_port,
    'connected'                   => ($action === 'add'),
    'date'                        => $_SESSION['glpi_currenttime'],
];
```

May be why there is a FIXME to change it to extend CommonDBRelation instead of CommonDBChild.

Comment (trasher) [reply src/NetworkPortConnectionLog.php]: It seem the incorrect field name is the reason of the initial issue, yes.
Changing class to a CommonDBRelation is probably out of the scope of a fix - I'm not sure we should do that kind of change in a bugfixes release.

About the remaining fails, I guess deletion should just be handled  differently - the fix just reveals something that does not work.

**Comment by trasher** [comment]
Finally, I've converted to `CommonDBRelation`: changes are not huge, tests are OK, and this does not require any "suspicious" change.
Also, this is not a central class; change should not have any side effect.

Should I port that change on v10 as well? (otherwise, issue will be fixed only for v11 - I'd be OK with that).

**Comment by cedric-anne** [comment]
> Should I port that change on v10 as well? (otherwise, issue will be fixed only for v11 - I'd be OK with that).

IMHO, this is not a major issue. There is no need to backport it to the 10.0 branch.
