### PR TITLE
Fix path check for minified JS/CSS files

### LINKED ISSUE #22208: Check if minified files are still used
I think minified JS files are no longer being but they are still generated in the production archive.

Maybe we should remove them then?

### PR DESCRIPTION
**Pull request by cedric-anne**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Minified JS/CSS files are in the `/public` directory.

It closes #22208.

### CODE REVIEW

**Comment by cconard96** [comment]
This wouldnt work for plugins, would it?

**Comment by cedric-anne** [comment]
> This wouldnt work for plugins, would it?

Indeed.

File: src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php [hunk 1]
```diff
@@ -179,10 +179,21 @@ public function jsPath(string $path, array $options = []): string
     {
         $is_debug = isset($_SESSION['glpi_use_mode']) && $_SESSION['glpi_use_mode'] === Session::DEBUG_MODE;
 
-        $minified_path = str_replace('.js', '.min.js', $path);
+        if (!$is_debug) {
+            if (!str_starts_with($path, '/')) {
+                $path = '/' . $path; // be sure to have a path starting with `/`
+            }
```
Comment (trasher) [inline src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php]: This should be for non debug paths aswell, no?

**Comment by cconard96** [comment]
Something similar would need done for `csPath` too. I noticed it yesterday while working on the RTL CSS PR.

**Comment by cedric-anne** [comment]
> Something similar would need done for `csPath` too. I noticed it yesterday while working on the RTL CSS PR.

Indeed, I fixed it in my last commit.

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Tests are failing

**Comment by cedric-anne** [comment]
Minified files were not commited due to `.gitignore` rules, this is why tests were passing on my machine but non on the CI context.

**Review by AdrienClairembault — APPROVED** [review]
