### PR TITLE
Fix devices transfer

### LINKED ISSUE #18508: SQL error when trying to transfer devices
Devices are transferred along with the asset they're linked to; but it's also opssible to add them directly to transfer list from massive action.

This last possibility lends to an error:
Image

### PR DESCRIPTION
**Pull request by trasher**
Fixes #18508

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
Maybe the solution is to replace the hardcoded `name` field name by the value returned by `getNameField()`.

**Review by cedric-anne — APPROVED** [review]

File: src/Transfer.php [hunk 1]
```diff
@@ -4181,22 +4181,12 @@ public function showTransferList()
...
-                                'There is no field "%1$s" in table "%2$s"',
-                                'name',
-                                $table
-                            )
-                        );
-                        continue;
-                    }
-
+                    $name_field = $item->getNameField();
+                    $table_name_field = sprintf('%1$s.%2$s', $table, $item->getNameField());
```
Comment (AdrienClairembault) [inline src/Transfer.php]:
```suggestion
                    $table_name_field = $itemtype::getTableField($name_field);
```
