### PR TITLE
restore kanban static column width

### LINKED ISSUE #20910: Project Kanban column widths no longer fixed
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-rc4

### Bug description

In GLPI 10, Kanban columns where fixed-sized. In GLPI 11.0.0-rc4, they seem to be adapting to the text content leading to bad UX as shown below:

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Go to Tools / Projects / Global Kanban
2.Notice the display problem due to the non-fixed column width

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Fixes #20910

### CODE REVIEW

File: js/src/vue/Kanban/Column.vue [hunk 1]
```diff
@@ -408,8 +408,8 @@
     .kanban-column {
         margin-right: 16px;
         border-radius: 5px;
+        width: 400px;
         flex-direction: column;
-        flex: 0 0 350px;
```
Comment (cconard96) [inline js/src/vue/Kanban/Column.vue:412]: This rule never had an effect since the column element is block displayed, not flex.

**Review by orthagh — APPROVED** [review]
