### PR TITLE
Some entries expect to be an array, not an empty string

### LINKED ISSUE #19571: [main] Planning: the form is broken for events with repetition
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

main

### Bug description

If a schedule event has a repetition, it displays an error.

### Relevant log output

```shell
An exception has been thrown during the rendering of a template ("count(): Argument #1 ($value) must be of type Countable|array, string given").
In ./templates/pages/assistance/planning/external_event.html.twig(188)
#0 ./files/_cache/templates/f7/f75cf1b5ff660b89f794a4e1722c2394.php(119): Twig\Template->yieldBlock()
#1 ./vendor/twig/twig/src/Template.php(388): __TwigTemplate_a7afe36ba6eed800c84a4eb683f697bd->doDisplay()
#2 ./files/_cache/templates/a2/a292bd15c22372f3024c40281794efbd.php(50): Twig\Template->yield()
#3 ./vendor/twig/twig/src/Template.php(388): __TwigTemplate_e0c7f197f237f03700f4c21a4b2ba904->doDisplay()
#4 ./vendor/twig/twig/src/Template.php(344): Twig\Template->yield()
#5 ./vendor/twig/twig/src/TemplateWrapper.php(61): Twig\Template->display()
#6 ./src/Glpi/Application/View/TemplateRenderer.php(179): Twig\TemplateWrapper->display()
#7 ./src/PlanningExternalEvent.php(183): Glpi\Application\View\TemplateRenderer->display()
#8 ./src/CommonGLPI.php(667): PlanningExternalEvent->showForm()
#9 ./ajax/common.tabs.php(109): CommonGLPI::displayStandardTab()
#10 ./src/Glpi/Controller/LegacyFileLoadController.php(59): require('...')
#11 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\LegacyFileLoadController->__invoke()
#12 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#13 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#14 ./public/index.php(56): Symfony\Component\HttpKernel\Kernel->handle()
#15 {main}



Previous: count(): Argument #1 ($value) must be of type Countable|array, string given
In ./src/Glpi/Features/PlanningEvent.php(778)
#0 ./src/Glpi/Features/PlanningEvent.php(778): count()
#1 [internal function]: PlanningExternalEvent::showRepetitionForm()
#2 ./src/Glpi/Application/View/Extension/PhpExtension.php(91): call_user_func_array()
#3 ./files/_cache/templates/a2/a292bd15c22372f3024c40281794efbd.php(361): Glpi\Application\View\Extension\PhpExtension->call()
#4 ./vendor/twig/twig/src/Template.php(432): __TwigTemplate_e0c7f197f237f03700f4c21a4b2ba904->block_form_fields()
#5 ./files/_cache/templates/f7/f75cf1b5ff660b89f794a4e1722c2394.php(119): Twig\Template->yieldBlock()
#6 ./vendor/twig/twig/src/Template.php(388): __TwigTemplate_a7afe36ba6eed800c84a4eb683f697bd->doDisplay()
#7 ./files/_cache/templates/a2/a292bd15c22372f3024c40281794efbd.php(50): Twig\Template->yield()
#8 ./vendor/twig/twig/src/Template.php(388): __TwigTemplate_e0c7f197f237f03700f4c21a4b2ba904->doDisplay()
#9 ./vendor/twig/twig/src/Template.php(344): Twig\Template->yield()
#10 ./vendor/twig/twig/src/TemplateWrapper.php(61): Twig\Template->display()
#11 ./src/Glpi/Application/View/TemplateRenderer.php(179): Twig\TemplateWrapper->display()
#12 ./src/PlanningExternalEvent.php(183): Glpi\Application\View\TemplateRenderer->display()
#13 ./src/CommonGLPI.php(667): PlanningExternalEvent->showForm()
#14 ./ajax/common.tabs.php(109): CommonGLPI::displayStandardTab()
#15 ./src/Glpi/Controller/LegacyFileLoadController.php(59): require('...')
#16 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\LegacyFileLoadController->__invoke()
#17 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#18 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#19 ./public/index.php(56): Symfony\Component\HttpKernel\Kernel->handle()
#20 {main}
```

### Page URL

https://glpimain/front/planningexternalevent.form.php?id=1

### Steps To reproduce

1. Go to the Assistance > Planning
2. Create a new event, with repetition (each day for example)
3. Return to the event form (not the schedule)

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
fix #19571

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

File: src/Glpi/Features/PlanningEvent.php [hunk 1]
```diff
@@ -248,13 +248,27 @@ public function encodeRrule(array $rrule = [])
...
+        }
+
+        if (isset($rrule['bymonth']) && empty($rrule['bymonth'])) {
+            $rrule['bymonth'] = [];
+        } elseif (!is_array($rrule['bymonth'])) {
+            $rrule['bymonth'] = [$rrule['bymonth']];
+        }
+
+        if (!empty($rrule['exceptions'])) {
+            if (is_string($rrule['exceptions']) && strlen($rrule['exceptions'])) { //@phpstan-ignore-line
```
Comment (trasher) [inline src/Glpi/Features/PlanningEvent.php:264]: Ignored, I do not understand where phpstan found the issue:
```
 ------ -------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   src/Glpi/Features/PlanningEvent.php (in context of class CommonITILTask)                                                                    
 ------ -------------------------------------------------------------------------------------------------------------------------------------------- 
  264    Right side of && is always true.                                                                                                            
         🪪  booleanAnd.rightAlwaysTrue                                                                                                              
         💡 Because the type is coming from a PHPDoc, you can turn off this check by setting treatPhpDocTypesAsCertain: false in your phpstan.neon.  
```

**Comment by trasher** [comment]
OK, that's no that simple. Putting back to draft, it needs more work.

**Review by AdrienClairembault — APPROVED** [review]

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Maybe there is something to fix elsewhere.
In GLPI 10.0, an event that repeat each day as the rrule stored in DB is `{"freq":"daily","interval":"1","until":""}`, but in GLPI 11.0, it contains unexpected `byday` and `bymonth` data : `{"freq":"daily","interval":"1","until":"","byday":"","bymonth":""}`.

I am afraid that having these empty strings in `byday` and `bymonth` properties can also have unexpected side effects in other pieces of code (for instance in the CalDav). Maybe the `PlanningEvent::encodeRrule()` method should also be updated to clean unexpected empty strings here.

This empty string has probably been introduced by #17074.

**Comment by trasher** [comment]
> Maybe there is something to fix elsewhere. In GLPI 10.0, an event that repeat each day as the rrule stored in DB is `{"freq":"daily","interval":"1","until":""}`, but in GLPI 11.0, it contains unexpected `byday` and `bymonth` data : `{"freq":"daily","interval":"1","until":"","byday":"","bymonth":""}`.
> 
> I am afraid that having these empty strings in `byday` and `bymonth` properties can also have unexpected side effects in other pieces of code (for instance in the CalDav). Maybe the `PlanningEvent::encodeRrule()` method should also be updated to clean unexpected empty strings here.
> 
> This empty string has probably been introduced by #17074.

I've added a check in `encodeRrule()` and a quick unit test.

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]
