### PR TITLE
fix bool custom field search computation

### LINKED ISSUE #23490: Custom asset Yes/No values are all Yes in the asset view
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

I have created a new custom asset (asset definition).
I have created a bunch of custom fields in there, which have functioned properly, mainly string and dropdown types, but when I created the Yes/No type custom fields, although opening the item, I see the Yes/No values as No, when I go back to the asset view, all values are Yes.

### Relevant log output

```shell
No *-error.logs
```

### Page URL

https://glpi.domain.local/front/asset/asset.php?class=Serverroom

### New Custom Asset Definition

1. Go to ``Setup`` - ``Asset definitions``.
2. Click on ``Add`` to create a new asset definition.
3. ``Name`` the new custom asset, make it ``active``, and ``add`` it.
4. Open the new custom asset.

### New Custom Field

1. Go to ``Fields``.
2. At the bottom right, click on the ``+ New field`` link under ``Custom fields``.
3. ``Name`` the new field.
4. Select the ``Yes/No`` type and ``add`` it.

### Create new asset

1. Under Assets, open the new custom asset you just created.
2. Click on ``Add`` to create a new asset.
3. Fill whatever built-in fields you have and set the custom ``Yes/No`` field to ``No``.
4. Save the asset.

### Modify the default items to show view

1. At the header of the asset table, on the right, find an icon that has an alt text ``Select default items to show``. Click on it.
2. In the search box left of the ``Add`` button, type ``custom``, ``select the custom field`` you created earlier, and ``add`` it.
3. Close the modal window.

Although you set the custom field value to No in the Create new asset, point 3, it will show the value in the asset view as Yes.
Open the asset again to ensure that the value there is still No.

### Your GLPI setup information

<details><summary>
         GLPI information
      </summary><pre>
GLPI: 11.0.6 ( =&gt; /opt/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: 1 files changed
  A: inc/downstream.php
</pre></details><details><summary>
         Server
      </summary><pre>
Operating system: Linux Antlia 6.8.12-15-pve #​1 SMP PREEMPT_DYNAMIC PMX 6.8.12-15 (2025-09-12T11:02Z) x86_64

PHP: 8.2.28 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;60&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;256M&quot; post_max_size=&quot;20M&quot; session.cookie_secure=&quot;1&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;Strict&quot; session.save_handler=&quot;files&quot; upload_max_filesize=&quot;20M&quot; 

Web server: Apache/2.4.62 (Debian) (Apache/2.4.62 (Debian) Server at glpi.domain.local Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0

Database:
   
Server Software: Alpine Linux
   
Server Version: 11.4.9-MariaDB
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@101.101.101.101/glpi_db
   
Host info: 111.111.111.111 via TCP/IP

Requirements:
PHP version (8.2.28) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader, xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (11.4.9) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed
Following extensions are installed: ctype, iconv, sodium.
Write access to /opt/glpi/marketplace has been validated.
Timezones seems loaded in database.
</pre></details>
<details><summary>
         GLPI constants
      </summary><pre>
GLPI_ROOT: &quot;/opt/glpi&quot;
GLPI_VERSION: &quot;11.0.6&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.6@84160e91f70f353b33495a7928e5b1476d4b6d98&quot;
GLPI_FILES_VERSION: &quot;11.0.6-15c577a4&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2026&quot;
GLPI_I18N_DIR: &quot;/opt/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/etc/glpi/&quot;
GLPI_VAR_DIR: &quot;/var/lib/glpi&quot;
GLPI_DOC_DIR: &quot;/var/lib/glpi&quot;
GLPI_CRON_DIR: &quot;/var/lib/glpi/_cron&quot;
GLPI_DUMP_DIR: &quot;/var/lib/glpi/_dumps&quot;
GLPI_GRAPH_DIR: &quot;/var/lib/glpi/_graphs&quot;
GLPI_LOCK_DIR: &quot;/var/lib/glpi/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/lib/glpi/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/lib/glpi/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/lib/glpi/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/lib/glpi/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/lib/glpi/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/lib/glpi/_uploads&quot;
GLPI_CACHE_DIR: &quot;/var/lib/glpi/_cache&quot;
GLPI_LOG_DIR: &quot;/var/log/glpi&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_MARKETPLACE_DIR: &quot;/opt/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                                # protocol\n                        (\n                            (?:\n                                (?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                    |\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain name\n                                    |\n                                [a-z0-9\\-\\_]++                                              # a single-level domain name\n                            )\\.?\n                                |                                                           # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}                              # an IP address\n                                |                                                           # or\n                            \\[\n                                (?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n                            \\]                                                              # an IPv6 address\n                        )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n                        (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n                    $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/lib/glpi/_locales&quot;
GLPI_INVENTORY_DIR: &quot;/var/lib/glpi/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/lib/glpi/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/opt/glpi/marketplace&quot;,&quot;/opt/glpi/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;
</pre></details><details><summary>
         LDAP directories
      </summary><pre>
Server: &#39;ldaps://dc.domain.local&#39;, 
	Port: &#39;636&#39;, 
	BaseDN: &#39;OU=Accounts,DC=domain,DC=local&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;CN=GLPI Searcher,OU=Unmanaged,OU=Service Accounts,OU=Administrative Units,DC=domain,DC=local&#39;, 
	Use TLS: &#39;1&#39;
</pre></details><details><summary>
         SQL replicas
      </summary><pre>
Not active
</pre></details><details><summary>
         Notifications
      </summary><pre>
Way of sending emails: PHP
</pre></details><details><summary>
         Plugins list
      </summary><pre>
glpiinventory        Name: GLPI Inventory                 Version: 1.6.7        State: Installed / not activated                Install Method: Marketplace
</pre></details>

### Anything else?

I started using that custom field type with the 11.0.6 version, so I don't know if it has worked correctly before.

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

fixes #23490

### CODE REVIEW

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Could you add a test with a search operation on a boolean custom field to validate that it produces the expected result on both MySQL and MariaDB ?

File: tests/functional/Glpi/Asset/CustomFieldDefinitionTest.php [hunk 1]
```diff
@@ -699,4 +699,64 @@ public function testSearchDropdownField(): void
...
+        foreach ($data['data']['rows'] as $row) {
+            $raw = $row['raw'];
+            $name = $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_1'];
+            if ($name === __FUNCTION__ . '_yes') {
+                $this->assertEquals(1, $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_' . $boolean_opt]);
+            } elseif ($name === __FUNCTION__ . '_no') {
+                $this->assertEquals(0, $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_' . $boolean_opt]);
+            } elseif ($name === __FUNCTION__ . '_default') {
+                $this->assertEquals(0, $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_' . $boolean_opt]);
+            }
```
Comment (cedric-anne) [inline tests/functional/Glpi/Asset/CustomFieldDefinitionTest.php]: If the `ITEM_Glpi\\CustomAsset\\Test01Asset_1` column value change in the future, the test will not assert anything.

```suggestion
            $this->assertEquals($name === __FUNCTION__ . '_yes' ? 1 : 0, $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_' . $boolean_opt]);
```

File: tests/functional/Glpi/Asset/CustomFieldDefinitionTest.php [hunk 2]
```diff
@@ -699,4 +699,64 @@ public function testSearchDropdownField(): void
...
+        $this->assertCount(3, $data['data']['rows']);
+        foreach ($data['data']['rows'] as $row) {
+            $raw = $row['raw'];
+            $name = $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_1'];
+            if ($name === __FUNCTION__ . '_yes') {
+                $this->assertEquals(1, $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_' . $boolean_opt]);
+            } elseif ($name === __FUNCTION__ . '_no') {
+                $this->assertEquals(0, $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_' . $boolean_opt]);
+            } elseif ($name === __FUNCTION__ . '_default') {
+                $this->assertEquals(0, $raw['ITEM_Glpi\\CustomAsset\\Test01Asset_' . $boolean_opt]);
```
Comment (cedric-anne) [inline tests/functional/Glpi/Asset/CustomFieldDefinitionTest.php]:
```suggestion
```

**Review by cedric-anne — APPROVED** [review]
