### PR TITLE
try to fix saving of search query in savedsearch; fix #10430

### LINKED ISSUE #10430: [GLPI 10] The saving of save searches don't save the query
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

When you create a saved searches, the query field in database is empty

The $input['query'] on prepareInputForAdd is empty

```
[2022-01-24 16:19:22] glpiphplog.INFO: SavedSearch::prepareInputForAdd() in C:\wamp64\www\glpi\src\SavedSearch.php line 327
Array
  (
      [entities_id] => 0
      [is_recursive] => 1
      [itemtype] => Contact
      [type] => 1
      [url] => %2Fglpi%2Ffront%2Fcontact.php
      [name] => test
      [do_count] => 2
      [is_private] => 1
      [users_id] => 6
      [_glpi_csrf_token] => b836dfe069540cf6ed05db7b1c11402b7320a6d336172bd7c410df4905476797
      [_no_history] => 
      [_add] => 1
      [query] => 
  )
   {"user":"6@XXX"} 
```

### Relevant log output

_No response_

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10430

Not sure to do the right thing to fix the mentionned issue but on my understanding, with new ajax view for search, there is some double encoding of the query and before the save a bad order of decoding/unscaping.

I'll try to check also #10009 also

### CODE REVIEW

File: src/SavedSearch.php [hunk 1]
```diff
@@ -302,7 +302,7 @@ public function rawSearchOptions()
      */
     public function prepareSearchUrlForDB(array $input): array
     {
-        $taburl = parse_url(rawurldecode(Sanitizer::unsanitize($input['url'])));
+        $taburl = parse_url(Sanitizer::unsanitize(rawurldecode($input['url'])));
```
Comment (cedric-anne) [inline src/SavedSearch.php:305]: Where does the corresponding `rawurlencode` is done ? Maybe the best way to fix this is to `rawurlencode` something that is not already sanitized.

Comment (orthagh) [reply src/SavedSearch.php:305]: at this place, i receive url with %XX (so url encoded) and url decoding is required
Not sure about unsanitize but it may depends on the searched content i think

**Review by cconard96 — APPROVED** [review]
~Seems to fix the issue completely now unless there are specific search terms that don't get decoded properly. I didn't notice any issues though.~

**Comment by cconard96** [comment]
> ~Seems to fix the issue completely now unless there are specific search terms that don't get decoded properly. I didn't notice any issues though.~

Actually `+` character seems to have issues still. Removing the change in the JS file seems to resolve that issue.

**Comment by orthagh** [comment]
I think i got all the dragons now with the last commit.
There was too many superflu encoding decoding in the previous code.

The needed is:

- encodeURIComponent  to set the query String parameter
- unescape GET (as we have the include autoescaper

that's all

**Comment by orthagh** [comment]
https://github.com/glpi-project/glpi/issues/10009 should be fixed now

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
