### PR TITLE
Fix: Adjust shift on Date custom fields caused by UTC conversion

### LINKED ISSUE #21724: Custom field "date" decreases each time an asset is saved
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.x

### Bug description

The date in the custom field decreases each time an asset is recorded (or each time an object is modified without necessarily changing the date).

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create a custom asset
2. Add a custom date field
3. Create an object in this asset and put a date
4. Save and look at the date decrementing (save multiple time and see the date decrementing multiple time)

### Your GLPI setup information

GLPI: 11.0.1 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language: fr_FR
Operating system: Linux 51e8d181c965 6.12.0-55.37.1.el10_0.x86_64 #​1 SMP PREEMPT_DYNAMIC Fri Oct  3 16:07:46 UTC 2025 x86_64

PHP: 8.4.13 fpm-fcgi

PHP extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json,
mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, readline, Reflection, standard, SimpleXML, tokenizer, xml,
xmlreader, xmlwriter, mysqlnd, cgi-fcgi, mysqli, pdo_mysql, gd, intl, exif, zip, Phar, ldap, bcmath, sodium, Zend OPcache

Setup: disable_functions="" max_execution_time="300" max_input_vars="5000" memory_limit="512M" post_max_size="60M"
session.cookie_secure="0" session.cookie_httponly="1" session.cookie_samesite="" session.save_handler="files"
upload_max_filesize="50M" 

Web server: Apache/2.4.65 (Unix) ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 12.0.2-MariaDB-ubu2404
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpidb_user@mariadb/glpi
   
Host info: mariadb via TCP/IP

Requirements:
PHP version (8.4.13) is supported.PHP version (8.4.13) is supported.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer,
xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installedmysqli extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
intl extension is installedintl extension is installed
mbstring extension is installedmbstring extension is installed
zlib extension is installedzlib extension is installed
bcmath extension is installedbcmath extension is installed
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installedopenssl extension is installed
Database engine version (12.0.2) is supported.Database engine version (12.0.2) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/pod/glpi/files/_cache has been validated. Write access to
/var/pod/glpi/files/_cron has been validated. Write access to /var/pod/glpi/files has been validated. Write access to
/var/pod/glpi/files/_graphs has been validated. Write access to /var/pod/glpi/files/_lock has been validated. Write access to
/var/pod/glpi/files/_pictures has been validated. Write access to /var/pod/glpi/files/_plugins has been validated. Write access
to /var/pod/glpi/files/_rss has been validated. Write access to /var/pod/glpi/files/_sessions has been validated. Write access
to /var/pod/glpi/files/_tmp has been validated. Write access to /var/pod/glpi/files/_uploads has been validated.Write access
to /var/pod/glpi/files/_cache has been validated.
Write access to /var/pod/glpi/files/_cron has been validated.
Write access to /var/pod/glpi/files has been validated.
Write access to /var/pod/glpi/files/_graphs has been validated.
Write access to /var/pod/glpi/files/_lock has been validated.
Write access to /var/pod/glpi/files/_pictures has been validated.
Write access to /var/pod/glpi/files/_plugins has been validated.
Write access to /var/pod/glpi/files/_rss has been validated.
Write access to /var/pod/glpi/files/_sessions has been validated.
Write access to /var/pod/glpi/files/_tmp has been validated.
Write access to /var/pod/glpi/files/_uploads has been validated.

Sessions configuration is secured.Sessions configuration is secured.
exif extension is installedexif extension is installed
ldap extension is installedldap extension is installed
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installedZend OPcache extension is installed
Following extensions are installed: ctype, iconv, sodium.Following extensions are installed:
ctype, iconv, sodium.
Write access to /var/pod/glpi/files/plugins has been validated.Write access to
/var/pod/glpi/files/plugins has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

GLPI_ROOT: "/var/www/html/glpi"
GLPI_VERSION: "11.0.1"
GLPI_SCHEMA_VERSION: "11.0.1@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba"
GLPI_FILES_VERSION: "11.0.1-3a9929cf"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.5"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_CONFIG_DIR: "/var/pod/glpi/config"
GLPI_VAR_DIR: "/var/pod/glpi/files"
GLPI_LOG_DIR: "/var/pod/glpi/log"
GLPI_MARKETPLACE_DIR: "/var/pod/glpi/files/plugins"
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&'\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_LOG_LVL: "warning"
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: "interactive"
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: "PT20M"
GLPI_DOC_DIR: "/var/pod/glpi/files"
GLPI_CACHE_DIR: "/var/pod/glpi/files/_cache"
GLPI_CRON_DIR: "/var/pod/glpi/files/_cron"
GLPI_GRAPH_DIR: "/var/pod/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/pod/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/pod/glpi/files/_lock"
GLPI_PICTURE_DIR: "/var/pod/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/pod/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/pod/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/pod/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/pod/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/pod/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/pod/glpi/files/_inventories"
GLPI_THEMES_DIR: "/var/pod/glpi/files/_themes"
GLPI_PLUGINS_DIRECTORIES: ["/var/pod/glpi/files/plugins","/var/www/html/glpi/plugins"]
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by carrarook**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- This PR fixes an off-by-one-day shift in "Date" custom fields for users in negative UTC offsets by treating date values as calendar days instead of timestamps.

### Problem & Root Cause
`DateType` was incorrectly processing date-only values through timestamp/UTC logic. Since date-only fields represent calendar days rather than specific instants in time, interpreting them as `UTC 00:00:00` caused a shift when rendered in local time for negative offsets.

### Fix Details
File modified: `src/Glpi/Asset/CustomFieldType/DateType.php`

1.  **`normalizeValue()`**: Now returns the validated `YYYY-MM-DD` string directly, bypassing unnecessary timezone conversions.
2.  **`formatValueFromDB()`**: Updated to return the `YYYY-MM-DD` format as-is if valid. A fallback parser is maintained for legacy persisted values that may contain datetime content, ensuring backward compatibility.

**Example (GMT-3):**
*   Stored value: `2025-01-01`
*   Interpreted as: `2025-01-01 00:00:00 UTC`
*   Local rendering: `2024-12-31 21:00:00`
*   **Result:** The UI displays the previous day.

### Validation
Manual validation was performed by creating an asset with a `Date` custom field in a **GMT-3** environment. 
*   **Result:** Saved dates now remain consistent (e.g., `2025-01-01` remains `2025-01-01`) upon reload and across sessions without rolling back to the previous day.

### CODE REVIEW

**Review by cconard96 — APPROVED** [review]
LGTM. Thank you for your contribution.

File: src/Glpi/Asset/CustomFieldType/DateType.php [hunk 1]
```diff
@@ -70,15 +70,20 @@ public function normalizeValue(mixed $value): ?string
...
         if (empty($value)) {
             return null;
         }
-        return date('Y-m-d', strtotime($value . ' UTC'));
+        if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $value)) {
+            return $value;
+        }
+
+        // Backward compatibility: old persisted values may contain a datetime part.
+        return date('Y-m-d', strtotime((string) $value));
```
Comment (cedric-anne) [inline src/Glpi/Asset/CustomFieldType/DateType.php]: Looking at the code, since the first version of this class, the stored value uses the `Y-m-d` format, with no time part nor timezone. Therefore, there is no need to reformat the database value.

```suggestion
        return $value;
```

**Review by trasher — APPROVED** [review]

File: src/Glpi/Asset/CustomFieldType/DateType.php (hunk 1 above)
Comment (carrarook) [reply src/Glpi/Asset/CustomFieldType/DateType.php]: Agreed. The actual problem was not in the persisted format itself, but in the conversion path that treated a date-only value as a UTC datetime.

More precisely, strtotime($value . ' UTC') turned a stored `Y-m-d` value into `Y-m-d 00:00:00 UTC`, and `date('Y-m-d', ...)` then reformatted that timestamp in the local timezone.
