### PR TITLE
fix broken tooltip when loading a ticket preview (ticket listing)

### LINKED ISSUE #18680: Bad request when trying to load ticket content in tooltip
Image

### PR DESCRIPTION
**Pull request by SebSept**
htmlescape() which breaks urls, The '&' were replaced with html entities which breaks url parameters

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #18680

### CODE REVIEW

File: src/Html.php [hunk 1]
```diff
@@ -3383,7 +3383,7 @@ class='dropdown_tooltip {$param['link_class']}'";
         if (!is_null($param['url'])) {
             $js .= "
                 ajax: {
-                    url: '" . htmlescape($CFG_GLPI['root_doc'] . $param['url']) . "',
+                    url: '" . URL::sanitizeURL($CFG_GLPI['root_doc'] . $param['url'])  . "',
```
Comment (cedric-anne) [inline src/Html.php:3386]: `URL::sanitizeURL()` is made to prevent malicious links based on user input, but is not handling the "escaping" required here. The correct "escaping" function for a JS variable is `json_encode` (or `|e('js')` in Twig context).

```suggestion
                    url: " . json_encode($CFG_GLPI['root_doc'] . $param['url'])  . ",
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by AdrienClairembault — APPROVED** [review]

**Review by trasher — APPROVED** [review]
