### PR TITLE
try other agent addresses on 5XX error response

### LINKED ISSUE #19479: Contact agent behind proxy
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.18

### Bug description

Glpi check only the first adresses to contact agent behind proxy

If computer is not avalable proxy reply with http/502 and glpi not check others addresses : 
https://github.com/glpi-project/glpi/blob/9f08b76d82dad8949101a3ec64d59ee8f63d820e/src/Agent.php#L725

Squid log
```
1744804492.273      4 172.16.40.100 TCP_MISS/502 3844 GET http://computer:62354/status - HIER_NONE/- text/html
```

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [ ] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

Fixes #19479

I have no way to test, but I guess if GLPI gets a 500 level error with one agent address, it should still try the other ones.

### CODE REVIEW

**Comment by g-bougard** [comment]
IMHO, I don't understand why initially we should stop on the first error. Unless an error is effectively telling the agent is definitively not reachable, even on other ips, but how to be sure when we are not still sure we even have all or goods ips ^^
To be honest, I would myself prefer to just remove the break on any error.

**Comment by cedric-anne** [comment]
> IMHO, I don't understand why initially we should stop on the first error. Unless an error is effectively telling the agent is definitively not reachable, even on other ips, but how to be sure when we are not still sure we even have all or goods ips ^^ To be honest, I would myself prefer to just remove the break on any error.

It seems that it was your own proposal, see https://github.com/glpi-project/glpi/pull/13812.

Is there something in the response headers/content that can be used to be sure that an agent was reached?

**Comment by g-bougard** [comment]
Lol, 2 years ago.

Reading again my previous PR description, I think I would like to make the function returns earlier only when agent really tells that access is forbidden, i.e when it returns a 403 error code with a "Access denied" text. So I understand better this PR purpose. Here is an example curl request with verbose option:
```
[g-bougard@somewhere ~]$ curl -v http://192.168.0.99:62354/now
*   Trying 192.168.0.99:62354...
* Connected to 192.168.0.99 (192.168.0.99) port 62354
> GET /now HTTP/1.1
> Host: 192.168.0.99:62354
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 403 Access denied (invalid request (untrusted address))
< Date: Thu, 17 Apr 2025 14:43:31 GMT
< Server: libwww-perl-daemon/6.16
< Content-Length: 425
< Content-Type: text/html
< 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>

<meta content="text/html; charset=UTF-8" http-equiv="content-type" />
<title>GLPI-Agent</title>
<link rel="stylesheet" href="site.css" type="text/css" />

</head>
<body>
<div id="background">
<p>Access denied</p>
<p><a href="/">Back</a></p>
</div>
</body>
</html>
* Connection #0 to host 192.168.0.99 left intact
```

My guess so is we can not break on 5XX error response and try others.

**Comment by g-bougard** [comment]
Probably, but `Server: libwww-perl-daemon/` still means you have a perl process behind, and on port 62354, this most probably GLPI-Agent... or FIA, so what ever version.

If you want to check a header, check for `libwww-perl-daemon` or `glpi-agent` in `Server`. In later version based on another language, we would probably have to set this `Server` to `glpi-agent/2.x` or so.

File: src/Agent.php [hunk 1]
```diff
@@ -722,6 +723,10 @@ public function requestAgent($endpoint): Response
                 self::$found_address = $address;
                 break;
             } catch (\GuzzleHttp\Exception\RequestException $exception) {
```
[the remark this answers is not in the document]
Comment (trasher) [reply src/Agent.php:725]: > What kind of error should prevent trying to other addresses here?

IMHO, we can try next address on any failure.

File: src/Agent.php [hunk 2]
```diff
@@ -721,11 +722,11 @@ public function requestAgent($endpoint): Response
...
                 self::$found_address = $address;
                 break;
-            } catch (\GuzzleHttp\Exception\RequestException $exception) {
-                // got an error response, we don't need to try other addresses
-                break;
-            } catch (\Throwable $exception) {
-                // many addresses will be incorrect
+            } catch (\GuzzleHttp\Exception\ClientException $exception) {
+                // If a 4XX error seems to be coming from an agent, we can stop trying. For every other exception, we can try other addresses
+                if (str_contains($exception->getResponse()->getHeaderLine('Server'), 'libwww-perl-daemon')) {
```
Comment (g-bougard) [inline src/Agent.php:727]: Can you better check `if "Server" header contains "libwww-perl-daemon" OR "glpi-agent"` ?
Just to anticipate future versions of glpi-agent which won't use perl.

**Review by g-bougard — CHANGES_REQUESTED** [review]

File: src/Agent.php (hunk 2 above)
Comment (cedric-anne) [inline src/Agent.php:727]: The initial purpose was to handle 405 responses. IMHO, we should only handle this specific case.
@g-bougard Do you agree ?

```suggestion
                // If a "405 Not allowed" error is returned by an agent expected address, we can stop trying. For every other exception, we can try other addresses.
                if ($exception->getResponse()->getStatusCode() === 405) {
                    // "405 Not allowed" status is returned when agent don't trust server
```

File: src/Agent.php [hunk 3]
```diff
@@ -721,11 +722,11 @@ public function requestAgent($endpoint): Response
...
+                    break;
+                }
             }
```
Comment (cedric-anne) [inline src/Agent.php:730]: We should prevent connection/request/server exceptions to stop the execution.

```suggestion
            } catch (\GuzzleHttp\Exception\TransferException $exception) {
                // Many addresses will be incorrect. Catch the exception and try other addresses.
            }
```

File: src/Agent.php (hunk 2 above)
Comment (cconard96) [reply src/Agent.php:727]: A 405 doesn't seem like the right status code if the agent doesn't trust the server. This implies that the untrusted server could make the same request to the agent using a different method (GET, POST, etc) and the agent is expected to send an `Allow` header in the response indicating the allowed methods.

A 403 error is what should be used and seems like the only case where we know to stop trying to contact the agent at this time.

Comment (g-bougard) [reply src/Agent.php:727]: Glpi-agent returns "403 Access denied" for untrusted ips. But this doesn't mean GLPI should not try other ips as routing can change the source ip to a trusted ip from glpi-agent point of view.

Maybe the best answer would be to try all ips and cache the first working ip to be reused first later.

Comment (cconard96) [reply src/Agent.php:727]: What are the performance implications? Are there cases where there are more than two different agent addresses or cases where GLPI contacts more than a single agent at a time (so not talking about clicking the buttons to request status or inventory in the computer form)?

Comment (trasher) [reply src/Agent.php]: > Maybe the best answer would be to try all ips and cache the first working ip to be reused first later.

I'd agree. There is no way to really know why one of the address do not work, many are "guessed" at inventory time - and this also seem the simplest way to go (we just take care any of the request takes too long - perhaps adding a configuration parameter).
Caching should maybe help; but there is no way to know if the problem was temporary - so cache lifetime should  maybe not be too long.

I have absolutely no idea how often we really rely on that code part. From a core point of view it's only used on user interaction as far as I remember.

Comment (g-bougard) [reply src/Agent.php]: It should also be used with glpi-inventory plugin with the "wake up agents" feature.

Comment (cedric-anne) [reply src/Agent.php]: It is pretty hard to know if an error result should be considered as temporary or not. The only thing we can improve here is to add a timeout to reduce the waiting time when the request is sent through a firewall that hangs it indefinitely, but it is out of the scope of the current PR.

**Review by cedric-anne — APPROVED** [review]
