### PR TITLE
Fixing CLI usage not having enough rights in GLPI's profile system

### LINKED ISSUE #22931: user:reset_password console command gets an error
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.5

### Bug description

The `user:reset_password` console command won't succeed in resetting an user's password.

I keep getting the following error:

```
An error occurred during password update
Unable to reset password, please contact your administrator
```

### Relevant log output

`php-errors.log` contains:

```shell
[2026-01-30 21:31:48] glpi.WARNING:   *** Test logger
[2026-01-30 21:34:55] glpi.WARNING:   *** Test logger
[2026-01-30 21:35:30] glpi.WARNING:   *** Test logger
[2026-01-30 21:35:53] glpi.WARNING:   *** Test logger
[2026-01-30 21:39:22] glpi.WARNING:   *** Test logger
```

Each call to `bin/console user:reset_password` generates a new `glpi.WARNING:   *** Test logger` line of log.

Calling `bin/console user:disable normal` works (it disables the user, without any error) and also generates a new line of log.

### Page URL

_No response_

### Steps To reproduce

```
cd "$(mktemp -d)"

cat > .env <<'EOT'
GLPI_DB_HOST=db
GLPI_DB_PORT=3306
GLPI_DB_NAME=glpi
GLPI_DB_USER=glpi
GLPI_DB_PASSWORD=glpi
EOT

cat > compose.yml <<'EOT'

name: glpi

services:
  glpi:
    image: "glpi/glpi:11.0.5"
    restart: "unless-stopped"
    volumes:
       - glpi_data:/var/glpi
    env_file: .env # Pass environment variables from .env file to the container
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: "mysql"
    restart: "unless-stopped"
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}

volumes:
   glpi_data:
   db_data:

EOT

# Start the stack:
docker compose up

# Wait some time for the greetings to be displayed

# Detach from `docker compose up` using [D] or open a new terminal in the same directory

# Try to (re)set a password:
docker compose exec glpi bin/console user:reset_password --password 'foo' glpi
```

You'll get:
```
An error occurred during password update
Unable to reset password, please contact your administrator
```

### Your GLPI setup information

<details><summary>
         GLPI information
      </summary><pre>
GLPI: 11.0.5 ( =&gt; /var/www/glpi)
Installation mode: DOCKER
Current language: en_GB
Source Integrity: OK
</pre></details><details><summary>
         Server
      </summary><pre>
Operating system: Linux 594f3d5d3c48 6.8.0-90-generic #​91-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 18 14:14:30 UTC 2025 x86_64

PHP: 8.5.2 apache2handler

PHP extensions: Core, date, lexbor, openssl, pcre, sqlite3, zlib, ctype, curl, uri, json, fileinfo, filter, hash, iconv, SPL,
mbstring, Zend OPcache, session, standard, PDO, pdo_sqlite, bz2, posix, random, Reflection, libxml, SimpleXML, tokenizer, dom,
xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, Phar, exif, gd, intl, ldap, mysqli, redis, soap, sodium, zip

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;128M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;Strict&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache ()

User agent: Mozilla/5.0 (X11; Linux x86_64; rv:146.0) Gecko/20100101 Firefox/146.0

Database:
   
Server Software: MySQL Community Server - GPL
   
Server Version: 9.6.0
   
Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@db:3306/glpi
   
Host info: db via TCP/IP

Requirements:
PHP version (8.5.2) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (9.6.0) is supported.
The log file has been created successfully.
Write access to
/var/glpi/files/_cache has been validated.
Write access to /var/glpi/files/_cron has been validated.
Write access to /var/glpi/files has been validated.
Write access to /var/glpi/files/_graphs has been validated.
Write access to /var/glpi/files/_lock has been validated.
Write access to /var/glpi/files/_pictures has been validated.
Write access to /var/glpi/files/_plugins has been validated.
Write access to /var/glpi/files/_rss has been validated.
Write access to /var/glpi/files/_sessions has been validated.
Write access to /var/glpi/files/_tmp has been validated.
Write access to /var/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/glpi/marketplace has been validated.
Timezones seems loaded in database.
</pre></details><details><summary>
         GLPI constants
      </summary><pre>
GLPI_ROOT: &quot;/var/www/glpi&quot;
GLPI_VERSION: &quot;11.0.5&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.5@647fc66aac29cc8845872d5c4c6c030bb8059dec&quot;
GLPI_FILES_VERSION: &quot;11.0.5-3fab908e&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2026&quot;
GLPI_I18N_DIR: &quot;/var/www/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/var/glpi/config&quot;
GLPI_VAR_DIR: &quot;/var/glpi/files&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/glpi/marketplace&quot;
GLPI_LOG_DIR: &quot;/var/glpi/logs&quot;
GLPI_INSTALL_MODE: &quot;DOCKER&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/var/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/glpi/files/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/glpi/marketplace&quot;,&quot;/var/www/glpi/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;
</pre></details><details><summary>
         SQL replicas
      </summary><pre>
Not active
</pre></details><details><summary>
         Notifications
      </summary><pre>
Way of sending emails: PHP
</pre></details>

### Anything else?

I am using the Dockerized version from https://github.com/glpi-project/docker-images but I doubt it has an impact on the behavior.

I've tested tags `11.0.0` (sha256:d4cea82338b14c761e6707a71241bb85a3f22fc47befeeb518039a251be742c2), `11.0.5` (sha256:f727df6b56b2a0b464dae6111af6da3e215c639ca81e0bfc921219a3cd5574ef) and `11.0-nightly` (sha256:3e266a2ad110c475cdc99477f4ca8a826ea5eada9e6b6cf6e949ba0b72f7b187): got the same error for all of them.

I've looked at the code and the error seems to be in [`User::prepareInputForUpdate()`](https://github.com/glpi-project/glpi/blob/11.0.5/src/User.php#L1077) (called by [`CommonDBTM::update()`](https://github.com/glpi-project/glpi/blob/11.0.5/src/CommonDBTM.php#L1640)).

There is a big if there: https://github.com/glpi-project/glpi/blob/11.0.5/src/User.php#L1167-L1180

```php
                    if (
                        isset($input['id'])
                        && $this->validatePassword($input["password"] ?? '', $password_errors)
                        && (($input['id'] == Session::getLoginUserID())
                        || $this->currentUserHaveMoreRightThan($input['id'])
                        // Permit to change password with token and email
                        || (isset($this->fields['password_forget_token']) && ($input['password_forget_token'] == $glpi_key->decrypt($this->fields['password_forget_token']))
                           && (strtotime($_SESSION["glpi_currenttime"]) < strtotime($this->fields['password_forget_token_date']))))
                    ) {
                        $input["password"]
                        = Auth::getPasswordHash($input["password"]);

                        $input['password_last_update'] = $_SESSION["glpi_currenttime"];
                    } else {
```

I get `bool(true)` for:

* `isset($input['id'])`
* `$this->validatePassword($input["password"] ?? '', $password_errors)`
* `$input['password_forget_token'] == $glpi_key->decrypt($this->fields['password_forget_token'])`

But `bool(false)` for:

* `(($input['id'] == Session::getLoginUserID())`
* `$this->currentUserHaveMoreRightThan($input['id'])`
* `isset($this->fields['password_forget_token'])`

### PR DESCRIPTION
**Pull request by C-Duv**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

- It fixes #22931
- Here is a brief description of what this PR does:
  Adds a check for CLI execution in `Profile::currentUserHaveMoreRightThan()` so it can grants it rights if needed.

### CODE REVIEW

**Comment by trasher** [comment]
This breaks tests

**Review by cedric-anne — CHANGES_REQUESTED** [review]
IMHO, it is preferable to combine the usage of `Session::callAsSystem()` in the command with a `Session::isRightChecksDisabled()` check in the `Profile::currentUserHaveMoreRightThan()` method.

**Comment by C-Duv** [comment]
> IMHO, it is preferable to combine the usage of `Session::callAsSystem()` in the command with a `Session::isRightChecksDisabled()` check in the `Profile::currentUserHaveMoreRightThan()` method.

@cedric-anne Something like that?

```diff
 src/Glpi/Console/User/ResetPasswordCommand.php | 3 +--
 src/Profile.php                                | 5 ++++-
 2 files changed, 5 insertions(+), 3 deletions(-)

diff --git a/src/Glpi/Console/User/ResetPasswordCommand.php b/src/Glpi/Console/User/ResetPasswordCommand.php
index 05d211fd55..e234f5f172 100644
--- a/src/Glpi/Console/User/ResetPasswordCommand.php
+++ b/src/Glpi/Console/User/ResetPasswordCommand.php
@@ -76,8 +76,7 @@ class ResetPasswordCommand extends AbstractUserCommand
         $user_input['password'] = $password;
         $user_input['password2'] = $password;
 
-
-        if ($user->update($user_input)) {
+        if (Session::callAsSystem(fn() => $user->update($user_input))) {
             $output->writeln('<info>' . __('Reset password successful.') . '</info>');
             return 0;
         } else {
diff --git a/src/Profile.php b/src/Profile.php
index 047eed3522..cfbec75846 100644
--- a/src/Profile.php
+++ b/src/Profile.php
@@ -743,7 +743,10 @@ class Profile extends CommonDBTM implements LinkableToTilesInterface
     {
         global $DB;
 
-        if (Session::isCron()) {
+        if (
+            Session::isRightChecksDisabled()
+            || Session::isCron()
+        ) {
             return true;
         }
         if (count($IDs) === 0) {
```

**Review by cedric-anne — APPROVED** [review]

File: src/Glpi/Console/User/ResetPasswordCommand.php [hunk 1]
```diff
@@ -76,8 +76,7 @@ protected function execute(InputInterface $input, OutputInterface $output): ?int
         $user_input['password'] = $password;
         $user_input['password2'] = $password;
 
-
-        if ($user->update($user_input)) {
+        if (Session::callAsSystem(fn() => $user->update($user_input))) {
```
Comment (cedric-anne) [inline src/Glpi/Console/User/ResetPasswordCommand.php]:
```suggestion
        if (\Session::callAsSystem(fn() => $user->update($user_input))) {
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Could you please validate it works as expected? According to the lint test failure, you did not test it, or you would have detect the failure.

File: src/Glpi/Console/User/ResetPasswordCommand.php (hunk 1 above)
Comment (C-Duv) [reply src/Glpi/Console/User/ResetPasswordCommand.php]: Will do

Comment (C-Duv) [reply src/Glpi/Console/User/ResetPasswordCommand.php]: Fix applied, it made `vendor/bin/phpstan analyze` happy.

(and the code still fixes #22931)

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
