### PR TITLE
Fix printer log

### LINKED ISSUE #21519: Printer page counters are not showing anything
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

Printer scanned with snmp is not showing "Page counters" properly even if there is some data. Attaching .csv exported from graph from GLPI
[printer_counter.csv](https://github.com/user-attachments/files/22946040/printer_counter.csv)

Image

### Relevant log output

```shell

```

### Page URL

/front/printer.form.php

### Steps To reproduce

_No response_

### Your GLPI setup information

GLPI: 11.0.1 ( => /var/www/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: OK

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
closes #21519

### CODE REVIEW

File: src/PrinterLog.php [hunk 1]
```diff
@@ -282,15 +282,13 @@ public function showMetrics(Printer|Asset $printer)
                 $series[$printer_id]['name'] = Printer::getById($printer_id)->fields['name'];
             }
 
-            // Keep values if at least 1 label is greater than 0
-            $valuesum = array_sum($metrics);
```
Comment (AdrienClairembault) [inline src/PrinterLog.php:286]: This was added in #16386 to fix a display issue.

Did you make sure it did not break it again?

Comment (trasher) [reply src/PrinterLog.php:286]: Yes, I've checked the original issue. Original fix has been broken on next merge from v10 branch.

Comment (AdrienClairembault) [reply src/PrinterLog.php:286]: It seems the values were wrapped in another array compared to GLPI 10.

Maybe the sum should be moved inside the loop?

```diff
diff --git a/src/PrinterLog.php b/src/PrinterLog.php
index b32d222402..cb196ac6ff 100644
--- a/src/PrinterLog.php
+++ b/src/PrinterLog.php
@@ -283,11 +283,11 @@ class PrinterLog extends CommonDBChild
             }

             // Keep values if at least 1 label is greater than 0
-            $valuesum = array_sum($metrics);
             foreach ($metrics as $metric) {
                 if ($is_comparison) {
                     $series[$printer_id]['data'][array_search($metric['date'], $labels, false)] = $metric[$compare_printer_stat];
                 } else {
+                    $valuesum = array_sum($metric);
                     foreach ($metric as $key => $value) {
                         $label = static::getLabelFor($key);
                         if ($label && $valuesum > 0) {
```

A test on this method would help as it is not convenient to manually tests as you need a lot of specific printer pages data :/

Comment (trasher) [reply src/PrinterLog.php:286]: valuesum is not needed (in facts I do not understand why it's been needed once). Everything works fine without that; I've tested on my side, and this is confirmed on original ticket.

As said, this change was OK when done, but a later merge from 10.0/branch made it useless.

**Review by AdrienClairembault — APPROVED** [review]
