### PR TITLE
Pass solution as trigger for solved ticket notification

### LINKED ISSUE #23071: No attachment in email notification
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.5

### Bug description

Hello, e-mail notifications triggered by Event: "Ticket Solved" + Add Documents: "Only documents related to the item that triggers the event" will be sent without attachments.

We also have a similar notification for follow-ups, and in that case the attachments are sent correctly. This issue seems to affect solutions only.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Notification settings:
[Notification settings](https://i.imgur.com/mbIW80f.png)

2. In the ticket, when we click “Add Solution” and attach one or more files:
[Add new solution](https://imgur.com/kUcwcUo.png)

3. The solution is saved correctly and the attachment is visible in the ticket:
[Solution with attached file](https://i.imgur.com/2NnTSvi.png)

4. Ticket is set to "Solved" after adding solution:
[Solved](https://imgur.com/DkK3iGj.png)

5. The notification is generated and sent by GLPI via email, but no attachment is included:
[E-mail](https://i.imgur.com/SU3QTc0.png)

### Your GLPI setup information

<details><summary>
         GLPI information
      </summary><pre>
GLPI: 11.0.5 ( =&gt; /var/www/html/glpi)
Installation mode: TARBALL
Current language: en_US
Source Integrity: OK
</pre></details><details><summary>
         Server
      </summary><pre>
Operating system: Linux srv5 6.1.0-26-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64

PHP: 8.2.24 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext,
iconv, igbinary, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets,
sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;60&quot; max_input_vars=&quot;5000&quot; memory_limit=&quot;256M&quot; post_max_size=&quot;20M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;20M&quot; 

Web server: Apache/2.4.62 (Debian) (Apache/2.4.62 (Debian) Server at suporte.operacapital.com.br Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:147.0) Gecko/20100101 Firefox/147.0

Database:
   
Server Software: Debian 12
   
Server Version: 10.11.6-MariaDB-0+deb12u1
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@localhost/glpi
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.2.24) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.6) is
supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

PHP directive &quot;session.cookie_secure&quot; should be set to &quot;on&quot; when GLPI
can be accessed on HTTPS protocol.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.
</pre></details><details><summary>
         GLPI constants
      </summary><pre>
GLPI_ROOT: &quot;/var/www/html/glpi&quot;
GLPI_VERSION: &quot;11.0.5&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.5@647fc66aac29cc8845872d5c4c6c030bb8059dec&quot;
GLPI_FILES_VERSION: &quot;11.0.5-f6e40a1f&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2026&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi/locales&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_CONFIG_DIR: &quot;/var/www/html/glpi/config&quot;
GLPI_VAR_DIR: &quot;/var/www/html/glpi/files&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/www/html/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/var/www/html/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/www/html/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/www/html/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/www/html/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/www/html/glpi/files/_lock&quot;
GLPI_LOG_DIR: &quot;/var/www/html/glpi/files/_log&quot;
GLPI_PICTURE_DIR: &quot;/var/www/html/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/www/html/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/www/html/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/www/html/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/www/html/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/www/html/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/www/html/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/www/html/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi/marketplace&quot;,&quot;/var/www/html/glpi/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;
</pre></details><details><summary>
         LDAP directories
      </summary><pre>
Server: &#39;ad0.operacapital.com.br&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;ou=departamentos;dc=ad0;dc=operacapital;dc=com;dc=br&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;sistema.glpi@operacapital.com.br&#39;, 
	Use TLS: none

Server: &#39;operacapital.in&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;ou=jaragua;dc=operacapital;dc=in&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;sistema.glpi@operacapital.in&#39;, 
	Use TLS: none

Server: &#39;ad.operacapital.com.br&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;ou=departamentos;dc=ad;dc=operacapital;dc=com;dc=br&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;sistema.glpi@ad.operacapital.com.br&#39;, 
	Use TLS: none
</pre></details><details><summary>
         SQL replicas
      </summary><pre>
Not active
</pre></details><details><summary>
         Notifications
      </summary><pre>
Way of sending emails: SMTP+OAUTH(smtp://chamados%40operacapital.com.br:********@smtp.gmail.com:587)
Name: &#39;chamados2@operacapital.com.br&#39;
	Active: No
	Server: &#39;{imap.gmail.com:993/imap/ssl}INBOX&#39;
	Login: &#39;chamados2@operacapital.com.br&#39;
	Password: Yes
Name: &#39;chamados@operacapital.com.br&#39;
	Active: Yes
	Server: &#39;{imap.gmail.com:993/imap/ssl}INBOX&#39;
	Login: &#39;chamados@operacapital.com.br&#39;
	Password: Yes
</pre></details><details><summary>
         Plugins list
      </summary><pre>
fields               Name: Additional fields              Version: 1.23.2     State: Enabled                                 
Install Method: Marketplace
behaviors            Name: Behaviors                      Version: 3.0.3      State: Enabled                                 
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.5      State: Enabled                                 
Install Method: Marketplace
notimportedautoreply Name: Not Imported Auto Reply        Version: 1.0.0      State: Enabled                                 
Install Method: Manual
</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #23071 
- Here is a brief description of what this PR does : 

 When a solution with attachments is added to a ticket, the "solved" notification was missing the solution's documents because the ITILSolution was not passed as the trigger to raiseEvent().
 
- Pass the `ITILSolution` instance as `_solution` in the ticket status update input when solving a ticket
- Use this reference as the `$trigger` parameter in `NotificationEvent::raiseEvent()` so that `itemtype_trigger` correctly points to `ITILSolution` instead of `Ticket`
- This ensures documents attached to the solution are included in email notifications when "Add documents" is set to "Only documents related to the item that triggers the event"

## Screenshots : 

Capture d’écran du 2026-02-12 14-07-23

### CODE REVIEW

**Review by AdrienClairembault — DISMISSED** [review]
I am not fully up to speed on the whole notification system but this looks good to me 👍

File: tests/functional/NotificationTest.php
Comment (SebSept) [inline tests/functional/NotificationTest.php:1]: you can improve that test : 

- make separation with arrange/act/assert
- use phpunit assertion to assert expected results not to check condition or preparation (use native php assert)
- group configurations `$CFG_GLPI[...]` 
- use `$this->createItem()` | `$this->updateItem()` when possible

File: tests/functional/NotificationTest.php [hunk 1]
```diff
@@ -535,6 +535,114 @@ public function __toString(): string
...
+
+        // Arrange - Configure notifications
+        $CFG_GLPI['use_notifications'] = true;
+        $CFG_GLPI['notifications_mailing'] = true;
+        $CFG_GLPI['attach_ticket_documents_to_mail'] = \NotificationSetting::ATTACH_FROM_TRIGGER_ONLY;
+
+        $solved_notif = new \Notification();
+        $this->assertTrue($solved_notif->getFromDBByCrit(['itemtype' => \Ticket::class, 'event' => 'solved']));
+
+        $DB->update(
```
Comment (trasher) [inline tests/functional/NotificationTest.php]: Do not forget to test this kind of instruction; as it can have a difficult to understand impact later in tests.

**Review by trasher — DISMISSED** [review]
LGTM

**Review by cedric-anne — COMMENTED** [review]
This only handles addition of a solution, but IMHO, the behaviour should be identical when a solution is rejected (the trigger is a followup), or when the solution is accepted (the trigger may be a followup), ...

This probably needs some more changes.

File: tests/functional/NotificationTest.php [hunk 2]
```diff
@@ -535,6 +535,115 @@ public function __toString(): string
...
+
+        $solved_notif = new \Notification();
+        $this->assertTrue($solved_notif->getFromDBByCrit(['itemtype' => \Ticket::class, 'event' => 'solved']));
+
+        $this->assertTrue($DB->update(
+            \Notification::getTable(),
+            ['is_active' => false],
+            ['id' => ['<>', $solved_notif->getID()]]
+        ));
+        $this->updateItem(\Notification::class, $solved_notif->getID(), [
```
Comment (SebSept) [inline tests/functional/NotificationTest.php]:
```suggestion
        // enable tested notification and set it to attach documents from trigger only
```

File: src/Ticket.php [hunk 3]
```diff
@@ -1501,7 +1501,8 @@ public function post_updateItem($history = true)
 
             // Read again ticket to be sure that all data are up to date
             $this->getFromDB($this->fields['id']);
-            NotificationEvent::raiseEvent($mailtype, $this);
+            $trigger = $this->input['_solution'] ?? null;
+            NotificationEvent::raiseEvent($mailtype, $this, [], $trigger);
```
Comment (SebSept) [inline src/Ticket.php]:
```suggestion
            $solution = $this->input['_solution'] ?? null;
            NotificationEvent::raiseEvent($mailtype, $this, [], $solution);
```

Comment (SebSept) [inline src/Ticket.php]:
```suggestion
            $solution = $this->input['_solution'] ?? null;
            NotificationEvent::raiseEvent($mailtype, $this, [], $solution);
```

**Review by SebSept — COMMENTED** [review]
Changes and Problems also have Solution with documents so changes may be in CommonITILObject, not only for Tickets.

File: src/Ticket.php (hunk 3 above)
Comment (f2cmb) [reply src/Ticket.php]: Good point on `Change` and `Problem`. The notification logic lives in each class's own `post_updateItem()` (not in `CommonITILObject`), so moving it up would require a larger refactor

 I'll apply the same fix to `Change` and `Problem` directly instead.

Regarding the `$solution` rename: the variable now also holds an ITILFollowup instance (following cedric-anne's review), so `$trigger` is the more accurate name.

**Comment by f2cmb** [comment]
Following cedric-anne's and SebSept's reviews, i extended the fix to cover closed and rejectsolution notifications (passing ITILFollowup as trigger via `ParentStatus`), applied the same to `Change` and `Problem`, and added regression tests for all new scenarios.

File: src/Glpi/Features/ParentStatus.php [hunk 4]
```diff
@@ -89,6 +90,10 @@ public function updateParentStatus(CommonITILObject $parentitem, array $input):
                 '_accepted' => true,
             ];
 
+            if ($this instanceof ITILFollowup) {
+                $update['_followup'] = $this;
+            }
```
Comment (cedric-anne) [inline src/Glpi/Features/ParentStatus.php]: We should not limit this to followups. Any item using `ParentStatus` trait to trigger an update of the itil parent item status should be used as trigger. For instance, the trigger could be a task.

To simplify the code, we should use the same key for all items, for instance `_trigger`, or `_source_item`.

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Some ITIL objects updates are triggered from the `CommonITILValidation` class. They should be fixed too.

File: src/Glpi/Features/ParentStatus.php (hunk 4 above)
Comment (f2cmb) [reply src/Glpi/Features/ParentStatus.php]: Done. Replaced both instanceof ITILFollowup checks with `$update['_trigger'] = $this` unconditionally, so any item using the ParentStatus trait (followup, task, document) is passed as trigger. Updated Ticket, Change and Problem to read _trigger instead of _followup.

File: src/ITILSolution.php [hunk 5]
```diff
@@ -332,8 +332,9 @@ public function post_addItem()
             }
 
             $this->item->update([
-                'id'     => $this->item->getID(),
-                'status' => $status,
+                'id'         => $this->item->getID(),
+                'status'     => $status,
+                '_solution'  => $this,
```
Comment (cedric-anne) [inline src/ITILSolution.php]:
```suggestion
                '_trigger'  => $this,
```

File: src/Change.php [hunk 6]
```diff
@@ -387,7 +387,8 @@ public function post_updateItem($history = true)
 
             // Read again change to be sure that all data are up to date
             $this->getFromDB($this->fields['id']);
-            NotificationEvent::raiseEvent($mailtype, $this);
+            $trigger = $this->input['_solution'] ?? $this->input['_trigger'] ?? null;
```
Comment (cedric-anne) [inline src/Change.php]:
```suggestion
            $trigger = $this->input['_trigger'] ?? null;
```

File: src/Problem.php [hunk 7]
```diff
@@ -317,7 +317,8 @@ public function post_updateItem($history = true)
 
             // Read again problem to be sure that all data are up to date
             $this->getFromDB($this->fields['id']);
-            NotificationEvent::raiseEvent($mailtype, $this);
+            $trigger = $this->input['_solution'] ?? $this->input['_trigger'] ?? null;
```
Comment (cedric-anne) [inline src/Problem.php]:
```suggestion
            $trigger = $this->input['_trigger'] ?? null;
```

File: src/Ticket.php [hunk 8]
```diff
@@ -1501,7 +1501,8 @@ public function post_updateItem($history = true)
 
             // Read again ticket to be sure that all data are up to date
             $this->getFromDB($this->fields['id']);
-            NotificationEvent::raiseEvent($mailtype, $this);
+            $trigger = $this->input['_solution'] ?? $this->input['_trigger'] ?? null;
```
Comment (cedric-anne) [inline src/Ticket.php]:
```suggestion
            $trigger = $this->input['_trigger'] ?? null;
```

File: tests/functional/NotificationTest.php [hunk 9]
```diff
@@ -535,6 +535,591 @@ public function __toString(): string
...
+            ]);
+            foreach ($notificationtemplate_it as $notificationtemplate_data) {
+                $template_updated = $DB->update(
+                    'glpi_notificationtemplatetranslations',
+                    ['content_html' => null],
+                    ['notificationtemplates_id' => $notificationtemplate_data['id']]
+                );
+                $this->assertTrue($template_updated);
+            }
+        }
```
Comment (cedric-anne) [inline tests/functional/NotificationTest.php]: Is this really mandatory ? Sending HTML or TXT body should not change how a txt file attachement is handled.
Same remark for other tests.

**Review by cedric-anne — CHANGES_REQUESTED** [review]
1. Please also add the `_trigger` input from `global_validation` updates triggered in the `CommonITILValidation`  class.

2. Test methods are pretty similar, maybe it could be possible to mutualize some code, unless it introduces too much complexity.

File: tests/functional/NotificationTest.php (hunk 9 above)
Comment (f2cmb) [reply tests/functional/NotificationTest.php]: You're right. The `is_html` flag in NotificationEventMailing.php only affects inline image embedding : `.txt` attachments are handled the same way in both paths ([L258–260](https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/NotificationEventMailing.php#L256-L261), [L288–290](https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/NotificationEventMailing.php#L287-L291)). Removed.

**Comment by f2cmb** [comment]
> * Please also add the `_trigger` input from `global_validation` updates triggered in the `CommonITILValidation`  class.
> * Test methods are pretty similar, maybe it could be possible to mutualize some code, unless it introduces too much complexity.


@cedric-anne boths are done :      
                                                                                                                                                                                              
1. _trigger input added to global_validation updates in `CommonITILValidation`
2. Tests mutualized : extracted 3 helpers, merged the 3 solved tests into one foreach over itemtypes, simplified followup tests.

**Review by cedric-anne — APPROVED** [review]
