### PR TITLE
use correct field when adding task from Problem/Change ticket list

### LINKED ISSUE #23556: Massive action on tickets inside problems throws an error
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

Inside problems, when trying to do a massive action on associated tickets, GLPI throws an error. Problematic lines of code are 128 and 129 of Problem_Ticket.php file:
                        if ($ticket->getFromDB($item->fields['tickets_id'])) {
                            $input2 = [$field              => $item->fields['tickets_id'],
Solution is to replace "tickets_id" with "id".

### Relevant log output

```shell
glpi.WARNING:   *** Warning: Undefined array key "tickets_id" at Problem_Ticket.php line 128
  Backtrace :
  ./src/Problem_Ticket.php:128                       
  ./src/MassiveAction.php:1323                       Problem_Ticket::processMassiveActionsForOneItemtype()
  ./src/MassiveAction.php:1301                       MassiveAction->processForSeveralItemtypes()
  ./front/massiveaction.php:63                       MassiveAction->process()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:208        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:71                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

/front/problem.form.php?id=123

### Steps To reproduce

With default config
go to Assistance/Problems/Tickets
mark a ticket and choose "Actions", select an action, "Add a new task" for example
fill in relevant info
Error message appears.

### Your GLPI setup information

Operating system: Linux  3.10.0-1160.119.1.el7.x86_64 #​1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64

PHP: 8.2.20 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, apache2handler, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, ldap, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sodium, sqlite3, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip, igbinary, msgpack, redis, Zend OPcache

Setup: disable_functions="" max_execution_time="30" max_input_vars="1000" memory_limit="1G" post_max_size="8M" session.cookie_secure="0" session.cookie_httponly="1" session.cookie_samesite="" session.save_handler="files" upload_max_filesize="2M" 

Web server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/8.2.20 ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36

Database:
   
Server Software: MariaDB Server
   
Server Version: 10.6.19-MariaDB-log

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #23556 

- Fix `Undefined array key "tickets_id"` error when using the "Add a task" massive action on tickets listed inside a problem or a change.
- Root cause: `$item` in `processMassiveActionsForOneItemtype` is a `Ticket`
  instance : it has no `tickets_id` field. The correct field is `id`.
- The same fix is applied proactively to `Change_Ticket`, which shares the same code pattern.

### CODE REVIEW

File: src/Change_Ticket.php [hunk 1]
```diff
@@ -141,8 +141,8 @@ public static function processMassiveActionsForOneItemtype(
 
                 foreach ($ids as $id) {
                     if ($item->can($id, READ)) {
-                        if ($ticket->getFromDB($item->fields['tickets_id'])) {
-                            $input2 = [$field              => $item->fields['tickets_id'],
+                        if ($ticket->getFromDB($item->fields['id'])) {
```
Comment (trasher) [inline src/Change_Ticket.php]: Not sure for this one. I do not exactly know what type the `$item` is, but it's OK only with `Ticket` and won't be ok if it is a `Change`.
Same for the Problem_Ticket.

Comment (f2cmb) [reply src/Change_Ticket.php]: Isn't `$item` always a Ticket here ? `add_task` is only exposed in `showForChange()/showForProblem()`, where entries are explicitly typed as `Ticket::class`. It seems there is no path where `$item` could be a Change or Problem. cf : 

https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/Change_Ticket.php#L299

https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/Problem_Ticket.php#L259

Comment (trasher) [reply src/Change_Ticket.php]: To be honest, I did not check; it just seems a bit strange to me. 
This code has been added years ago, and never changed. Is that always have been broken? Or maybe there is something else, in another place, that make a wrong call.

Once again, it's just reading the current part of code and its history; I did not dig at all into it.

**Review by AdrienClairembault — APPROVED** [review]
Seems similar to an issue I've fixed on another massive action: #19606.

File: src/Change_Ticket.php (hunk 1 above)
Comment (cedric-anne) [reply src/Change_Ticket.php]: If `$item` is already the expected `$ticket`, then there is no reason to load it again.

```suggestion
```

File: src/Problem_Ticket.php [hunk 2]
```diff
@@ -125,8 +125,8 @@ public static function processMassiveActionsForOneItemtype(
 
                 foreach ($ids as $id) {
                     if ($item->can($id, READ)) {
-                        if ($ticket->getFromDB($item->fields['tickets_id'])) {
-                            $input2 = [$field              => $item->fields['tickets_id'],
+                        if ($ticket->getFromDB($item->fields['id'])) {
```
Comment (cedric-anne) [inline src/Problem_Ticket.php]: Same remark here.

```suggestion
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]
