### PR TITLE
Fix - Restore CRLF line endings in message/rfc822 attachments extracted by mail collector

### LINKED ISSUE #321: eMail attached into eMail are not uploaded via mail collector
Hello,
This is an old issue (already existing in 0.83):
When sending an email to the mail collector with Outlook and attaching into this email another email, then the attached email is not uploaded as any other documents would be.
The reason is Outlook (or MSExchange doesn't provide any FILENAME for the MIME part of the attached email like it would do for any other documents).
As the mail collector will ignore empty FILENAME, then the MIME part is not imported.

I'm going to post a fix for that in 0.85 and 0.90 releases.

regards,
Tomolimo

### PR DESCRIPTION
**Pull request by RomainLvr**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !43086
- Here is a brief description of what this PR does

### Problem

When a user forwards an email as an attachment via Outlook (Microsoft 365), the mail collector saves it as an `.eml` file. Opening this file shows garbled content — special characters are broken and the HTML structure is corrupted, making it unusable. The same email uploaded manually via "Add a document" works perfectly as `.msg`.

The difference is not a bug in the file format choice (`.eml` is correct for `message/rfc822` MIME parts, `.msg` is a proprietary Outlook binary — they are two distinct representations). The actual bug is that the `.eml` file is written with LF-only line endings instead of the RFC 2822-required `\r\n`, corrupting Quoted-Printable encoding (`=\r\n` → `=\n`).

### Root cause

`Laminas\Mime\Decode::splitMime` strips all `\r` characters before splitting MIME parts — a known upstream limitation introduced when `imap_*` was replaced by Laminas Mail in 2019 (commit `f64859cd4d`). All `message/rfc822` attachments extracted since then silently lose their CRLF line endings.

> Note: `.eml` generation for `message/rfc822` parts was intentionally introduced in 2015 (commit `292337a024`, fixes #321).

### Fix

After extracting a `message/rfc822` part, restore `\r\n` using a negative-lookbehind regex that replaces only standalone `\n` (not existing `\r\n`), before writing to disk.

A regression test is added to `MailCollectorTest`: it builds a multipart email with a CRLF-encoded embedded message, runs `getAttached()`, and asserts `\r\n` line endings in the resulting file.

### CODE REVIEW

**Review by stonebuzz — APPROVED** [review]
seems good to me

**Review by trasher — APPROVED** [review]

File: phpunit/imap/MailCollectorTest.php [hunk 1]
```diff
@@ -1450,4 +1450,87 @@ public function testCleanContent(
...
+            '',
+            '--test-boundary-48',
+            'Content-Type: text/plain; charset=utf-8',
+            '',
+            'Please find the forwarded email below.',
+            '--test-boundary-48',
+            'Content-Type: message/rfc822',
+            'Content-Disposition: attachment',
+            '',
+        ]) . $crlf . $embedded_email . $crlf . '--test-boundary-48--' . $crlf;
```
Comment (cedric-anne) [inline phpunit/imap/MailCollectorTest.php]: It should produce the same, while being more readable.

```suggestion
            '',
            $embedded_email,
            '--test-boundary-48--'
            '',
        ]);
```

**Review by AdrienClairembault — APPROVED** [review]

**Comment by Rom1-B** [comment]
If I understand correctly, GLPI converts the .MSG file to .EML because the file name is not included in the original file's MIME type. Is that right?
Is it necessary to perform this conversion and risk corrupting the content?

**Comment by trasher** [comment]
> If I understand correctly, GLPI converts the .MSG file to .EML because the file name is not included in the original file's MIME type. Is that right? Is it necessary to perform this conversion and risk corrupting the content?

It's not about the format, but how data is encoded client side.

Since the fix replace wrong end lines without affecting correct ones, all shoudl be good.

**Comment by trasher** [comment]
Also, I'm pretty sure existing tests would not be happy :)

**Review by cedric-anne — APPROVED** [review]
