### PR TITLE
Avoid ldap synced users to get restored after second sync

### LINKED ISSUE #21423: Issue sync ldap user deleted
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

Hello, I am using debian with a version of GLPI 11.0.1. I am encountering an issue with LDAP synchronization involving disabled users and deleted AD accounts. The following command runs every 5 minutes via a CRON job on my debian server: `bin/console glpi:ldap:synchronize_users`.
The accounts are successfully moved to the trash in GLPI, but 5 minutes later, when the command runs again, the accounts are restored.

I do not understand the behavior of GLPI. Can you help me?

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

Launch the synchronization command with an ad account outside the synchronized OU

The account is deleted

Relaunch the command, the account is restored

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
## Description

- It fixes #21423
- Here is a brief description of what this PR does

Avoid to restore ldap imported from ldap server after a second sync after deletion in ldap by removing a condition on is_deleted_ldap. Restoration if user have to be sync into GLPI is well-handled here https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/AuthLDAP.php#L2703 in ldapImportUserByServerId method.

### CODE REVIEW

File: src/AuthLDAP.php [hunk 1]
```diff
@@ -2036,11 +2036,9 @@ public static function getAllUsers(array $options, &$results, &$limitexceeded)
                             // If user is marked as coming from LDAP, but is not present in it anymore
                             User::manageDeletedUserInLdap($user['id']);
                             $results[self::USER_DELETED_LDAP]++;
-                        } elseif ((int) $user['is_deleted_ldap'] === 1) {
```
Comment (cedric-anne) [inline src/AuthLDAP.php:2039]: IMHO, the issue comes from commit e797bbe2f2e918d86a1d865c9113da5eb2a64962 that deleted some conditions here.

~~Your commit may work in the synchronization context, but it breaks the `$results[self::USER_RESTORED_LDAP]` count and have maybe some unexpected side effects.~~

It seems that the condition was always falsy. Maybe the `$results[self::USER_RESTORED_LDAP]`  should be added somewhere else.

Comment (cconard96) [reply src/AuthLDAP.php:2039]: I am not sure about the change in the linked commit.

I tested with AD 2025 with the recycle bin enabled and confirmed the original issue of users being "restored" even when they are still in the AD recycle bin. The PR does indeed resolve that issue.

An issue still exists where if you restore the user in AD and they try to log in before a sync, the is_deleted_ldap flag clears in GLPI without the restore action taking place so it remains soft-deleted and GLPI will not restore it properly during the next sync. This seems to happen even before this PR and before the PHPStan-related commit.

Comment (cedric-anne) [reply src/AuthLDAP.php:2039]: The `$userfound` condition was added in #15635 to prevent the behaviour we are trying to fix now. It made it always falsy and has the same effect than removing the code as proposed here.

Maybe we could merge the current PR to fix the regression introduced by commit e797bbe2f2e918d86a1d865c9113da5eb2a64962, and create a new issue for the "restore the user in AD and they try to log in before a sync" specific case.

**Review by cedric-anne — APPROVED** [review]
