### PR TITLE
Fix alert message display

### LINKED ISSUE #21017: GLPI 11.0.0-RC4: Automatic actions - top alert truncated
Image

### PR DESCRIPTION
**Pull request by trasher**
closes #21017

### CODE REVIEW

**Comment by trasher** [comment]
I did not have the same issue (I have no pagination dropdown); but it still should fix.

As draft since it should be moved in an external twig file.

**Comment by trasher** [comment]
OK, that fix a small display issue when pagination is not set on top; but that does not fix the reported issue...

File: src/CronTask.php [hunk 1]
```diff
@@ -1959,18 +1959,13 @@ public static function showSearchStatusArea()
         if (count($warnings) > 0) {
             $msg = __('Automatic actions may not be running as expected');
```
Comment (cedric-anne) [inline src/CronTask.php]: A `|raw` filter is used in the template, HTML special chars have to be escaped here.

```suggestion
            $msg = __s('Automatic actions may not be running as expected');
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by cedric-anne — APPROVED** [review]
