### PR TITLE
Change reservation modals to use ajax endpoint

### LINKED ISSUE #19946: Infinite loading when editing an existing reservation
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-beta5

### Bug description

In the Reservations menu (under Tools), I created a new reservation for a Computer. When I go to edit the entry by accessing it from the reservation calendar, the record's modal gets stuck in an infinite loading state upon trying to save the edit, and the record is not updated.

The same issue occurs when trying to edit it from the Reservations tab within the Computer asset itself.

### Relevant log output

```shell

```

### Page URL

http://server.com/front/reservation.php

### Steps To reproduce

1. Register a computer as an asset.
2. On the 'Reservations' tab for that asset, enable booking/reservation authorization.
3. In the reservation calendar, create a new reservation for any date, any duration, any user, and add a comment.
4. Save the new record.
5. Click on the newly created record in the calendar. A modal with the record's information will appear.
6. Edit any information and try to save.

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0-dev ( => /var/www/glpi/glpi)
Installation mode: TARBALL
Current language: pt_BR</pre></details><details><summary>Server</summary><pre>Operating system: Linux glpi11-teste 6.1.0-37-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22) x86_64

PHP: 8.3.21 fpm-fcgi

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv,
igbinary, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem,
sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, redis, Zend OPcache

Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M" disable_functions="" 

Web server: nginx/1.22.1 ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36

Database:
   
Server Software: Debian 12
   
Server Version: 10.11.11-MariaDB-0+deb12u1
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@localhost/glpi
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.3.21) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.11) is
supported.
The log file has been created successfully.
Write access to /var/www/glpi/files//_cache has been validated.
Write access to /var/www/glpi/files//_cron has been validated.
Write access to /var/www/glpi/files/ has been validated.
Write access to /var/www/glpi/files//_graphs has been validated.
Write access to /var/www/glpi/files//_lock has been validated.
Write access to /var/www/glpi/files//_pictures has been validated.
Write access to /var/www/glpi/files//_plugins has been validated.
Write access to /var/www/glpi/files//_rss has been validated.
Write access to /var/www/glpi/files//_sessions has been validated.
Write access to /var/www/glpi/files//_tmp has been validated.
Write access to /var/www/glpi/files//_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
openssl extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/glpi/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: "/var/www/glpi/glpi"
GLPI_VERSION: "11.0.0-dev"
GLPI_SCHEMA_VERSION: "11.0.0-dev@328dd9a958b1c9fb579af5427e3e1ef6ee0b1f34"
GLPI_FILES_VERSION: "11.0.0-dev-480ba94c"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.4"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/var/www/glpi/glpi/locales"
GLPI_CONFIG_DIR: "/var/www/glpi/config/"
GLPI_VAR_DIR: "/var/www/glpi/files/"
GLPI_LOG_DIR: "/var/www/glpi/log/"
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/glpi/marketplace"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST:
["#^http://[^@:]+(:80)?(/.*)?$#","#^https://[^@:]+(:443)?(/.*)?$#","#^feed://[^@:]+(/.*)?$#"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_LOG_LVL: "warning"
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_DOC_DIR: "/var/www/glpi/files/"
GLPI_CACHE_DIR: "/var/www/glpi/files//_cache"
GLPI_CRON_DIR: "/var/www/glpi/files//_cron"
GLPI_GRAPH_DIR: "/var/www/glpi/files//_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files//_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files//_lock"
GLPI_PICTURE_DIR: "/var/www/glpi/files//_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files//_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files//_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files//_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files//_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files//_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files//_inventories"
GLPI_THEMES_DIR: "/var/www/glpi/files//_themes"
GLPI_PLUGINS_DIRECTORIES: ["/var/www/glpi/glpi/marketplace","/var/www/glpi/glpi/plugins"]
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"</pre></details><details><summary>Réplicas SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: PHP</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

Fixes #19946. Loading duplicate JS and other resources cause the page scripts to break. This PR makes the modal load using the AJAX endpoint for both new and editing reservations in modals. Previously, only new reservations were loaded using the AJAX script.

### CODE REVIEW

**Review by orthagh — APPROVED** [review]

File: src/Reservation.php [hunk 1]
```diff
@@ -703,7 +706,7 @@ public function showForm($ID, array $options = [])
         } else {
             $resa->getEmpty();
             $options = Planning::cleanDates($options);
-            $resa->fields["begin"] = date("Y-m-d H:i:s", strtotime($options['begin']));
+            $resa->fields["begin"] = !empty($options['begin']) ? date("Y-m-d H:i:s", strtotime($options['begin'])) : date('Y-m-d H:00:00');
```
Comment (AdrienClairembault) [inline src/Reservation.php]: We try to reuse only one source of "current time" to make sure it is always the same time, which is set in the session.

```suggestion
            $resa->fields["begin"] = !empty($options['begin']) ? date("Y-m-d H:i:s", strtotime($options['begin'])) : date('Y-m-d H:00:00', strtotime(Session::getCurrentTime()));
```

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]

**Review by AdrienClairembault — APPROVED** [review]

File: .phpstan-baseline.php [hunk 2]
```diff
@@ -7528,7 +7528,7 @@
 $ignoreErrors[] = [
 	'message' => '#^Function strtotime is unsafe to use\\. It can return FALSE instead of throwing an exception\\. Please add \'use function Safe\\\\strtotime;\' at the beginning of the file to use the variant provided by the \'thecodingmachine/safe\' library\\.$#',
 	'identifier' => 'theCodingMachineSafe.function',
-	'count' => 42,
+	'count' => 43,
```
Comment (trasher) [inline .phpstan-baseline.php]: New entries should not be added in baseline

Comment (cconard96) [reply .phpstan-baseline.php]: Changing almost 50 `strtotime` function calls in this file by using `Safe\strtotime` and changing the logic flow is beyond the scope of this PR and changing one or two calls seemed inconsistent.

I've changed the two calls on the changed line.

Comment (trasher) [reply .phpstan-baseline.php]: Usingn `Safe\strtotime` should be OK on the whole file; but that's not the goal of present PR.
