### PR TITLE
block savedsearch visibility ma for users without permission

### LINKED ISSUE #22808: Users can make saved searches public without required permissions
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

A user profile with permission to view public saved searches (but without permission to create or modify public searches) is still able to change the visibility of a saved search from Private to Public.

After making the saved search public, the user is then unable to revert the visibility back to private due to missing modification rights. This creates an inconsistent permission behavior where users can publish saved searches without authorization and are subsequently locked out from correcting the visibility.

This behavior bypasses the expected permission checks and may lead to unintended exposure of saved searches.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create or edit a profile and grant only the permission to view public saved searches, without any permission to create, modify, or manage public searches.

Image

2. Create a new saved search with a user assigned to this profile.

Image

3. Edit the saved search and change its visibility from Private to Public.

Image

Image

4. User is unable to change back visibility.

Image

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

fixes #22808

### CODE REVIEW

File: src/SavedSearch.php [hunk 1]
```diff
@@ -416,7 +420,9 @@ public function prepareSearchUrlForDB(array $input): array
 
     public function prepareInputForAdd($input)
     {
-
+        if (isset($input['is_private']) && (int) $input['is_private'] === 0 && !Session::haveRight(self::$rightname, UPDATE)) {
+            return false;
+        }
```
Comment (trasher) [inline src/SavedSearch.php:425]: I think test cases must be added for those changes (add & update).

**Review by trasher — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
