### PR TITLE
fix(forms): Fix JS error when switching form Long answer question type multiple times

### LINKED ISSUE #22437: Changing form input type shows: TypeError: value.getDatatype is not a function convertDefaultValue
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

v11.0.4 docker

### Bug description

Go to:

- Administration -> Forms
- edit or create new one
- Question: Long answer
- change 3-5 times type: long ans. -> short ans. -> long ans. -> short ans.
- red error message is in right-down corner:  An unexpected error occurred 
- when enabling debug mode on Console tab it is:

```
form.form.php:63:23

Uncaught (in promise) TypeError: value.getDatatype is not a function
    convertDefaultValue https://mycompany.com/front/form/form.form.php?id=3 line 190 > injectedScript:63
    #changeQuestionType https://mycompany.com/js/modules/Forms/EditorController.js?v=91766baf:1949

NS_ERROR_UNEXPECTED: 
25 times (sometimes there is value 35 times)
theme.js:29621:1
```

It is same for Firefox and Chrome.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ccailly**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

- It fixes #22437

Fixes a JavaScript error that occurred when switching a form question type 
multiple times (e.g., Long answer → Short answer → Long answer).

## Root cause
When a Long answer question was loaded from database and TinyMCE was not 
yet initialized, the `extractDefaultValue` function returned an empty string 
instead of a proper value object, causing `convertDefaultValue` to fail 
when calling `getDatatype()` on it.

## Solution
Always return a valid `GlpiFormEditorConvertedExtractedDefaultValue` object 
from `extractDefaultValue`, falling back to the textarea value when TinyMCE 
is not initialized.

### CODE REVIEW

File: src/Glpi/Form/QuestionType/QuestionTypeLongText.php [hunk 1]
```diff
@@ -71,19 +71,15 @@ public function getFormEditorJsOptions(): string
...
-
-                        return new GlpiFormEditorConvertedExtractedDefaultValue(
-                            GlpiFormEditorConvertedExtractedDefaultValue.DATATYPE.STRING,
-                            content
-                        );
-                    }
-
-                    return '';
+                    let content = inst ? inst.getContent() : textarea.val() || "";
+                    let tmp = document.createElement("DIV");
```
Comment (cconard96) [inline src/Glpi/Form/QuestionType/QuestionTypeLongText.php]:
```suggestion
                    const tmp = document.createElement("DIV");
```

**Review by cconard96 — APPROVED** [review]

**Review by AdrienClairembault — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
