### PR TITLE
Client side validation for mandatory questions

### LINKED ISSUE #19490: GLPI 11 - Mandatory questions and sections
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0-dev (main-82c29b5)

### Bug description

Hello,

I've noticed that the compulsory questions are not compulsory, either to display the next step or to create the form.

Best regards,

https://github.com/user-attachments/assets/ca37c88f-bef9-4315-a942-57ce6d4b6145

### Relevant log output

```shell
No log
```

### Page URL

_No response_

### Steps To reproduce

1. Create a mandatory question with a question in a section
2. This will not be required to change section.
3. The ticket can be created without any problem

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0-dev ( => /var/www/glpi)
Installation mode: TARBALL
Current language: fr_FR</pre></details><details><summary>Server</summary><pre>Operating system: Linux glpi-modele-it-gouvernance 6.1.0-32-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.129-1 (2025-03-06)
x86_64

PHP: 8.3.20 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv,
intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer,
xmlreader, xmlwriter, xsl, zip, Zend OPcache

Setup: max_execution_time="600" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M" disable_functions="" 

Web server: Apache/2.4.63 (Debian) (Apache/2.4.63 (Debian) Server at XX Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 11.4.5-MariaDB-deb12
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi11@localhost/glpi
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.3.20) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
mysqli extension is installed.
curl extension is installed.
gd extension is installed.
intl extension is installed.
mbstring extension is installed.
zlib extension is installed.
bcmath extension is installed.
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed.
Database engine version (11.4.5) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: "/var/www/glpi"
GLPI_VERSION: "11.0.0-dev"
GLPI_SCHEMA_VERSION: "11.0.0-dev@30aae2f1a8a216f13ed3674d32ae3b45b7cde98c"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.4"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST:
["#^http://[^@:]+(:80)?(/.*)?$#","#^https://[^@:]+(:443)?(/.*)?$#","#^feed://[^@:]+(/.*)?$#"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_STRICT_DEPRECATED: false
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_DOC_DIR: "/var/www/glpi/files"
GLPI_CACHE_DIR: "/var/www/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/files/_cron"
GLPI_GRAPH_DIR: "/var/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files/_inventories"
GLPI_THEMES_DIR: "/var/www/glpi/files/_themes"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"</pre></details><details><summary>Libraries</summary><pre>symfony/mailer not found
simplepie/simplepie version 1.8.1 in /var/www/glpi/vendor/simplepie/simplepie/src
tecnickcom/tcpdf version 6.9.0 in /var/www/glpi/vendor/tecnickcom/tcpdf
tecnickcom/tc-lib-barcode version  in /var/www/glpi/vendor/tecnickcom/tc-lib-barcode/src
sabre/dav version  in /var/www/glpi/vendor/sabre/dav/lib/DAV
sabre/http version  in /var/www/glpi/vendor/sabre/http/lib
sabre/uri version  in /var/www/glpi/vendor/sabre/uri/lib
sabre/vobject version  in /var/www/glpi/vendor/sabre/vobject/lib
laminas/laminas-i18n version  in /var/www/glpi/vendor/laminas/laminas-i18n/src
monolog/monolog version  in /var/www/glpi/vendor/monolog/monolog/src/Monolog
sebastian/diff version  in /var/www/glpi/vendor/sebastian/diff/src
donatj/phpuseragentparser version  in /var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent
elvanto/litemoji version  in /var/www/glpi/vendor/elvanto/litemoji/src
gettext/languages version  in /var/www/glpi/vendor/gettext/languages/src
symfony/console version  in /var/www/glpi/vendor/symfony/console
symfony/config version  in /var/www/glpi/vendor/symfony/config/Loader
symfony/dependency-injection version  in /var/www/glpi/vendor/symfony/dependency-injection
symfony/event-dispatcher version  in /var/www/glpi/vendor/symfony/event-dispatcher
symfony/filesystem version  in /var/www/glpi/vendor/symfony/filesystem
symfony/framework-bundle version  in /var/www/glpi/vendor/symfony/framework-bundle
symfony/http-foundation version  in /var/www/glpi/vendor/symfony/http-foundation
symfony/http-kernel version  in /var/www/glpi/vendor/symfony/http-kernel
symfony/routing version  in /var/www/glpi/vendor/symfony/routing
scssphp/scssphp version  in /var/www/glpi/vendor/scssphp/scssphp/src
laminas/laminas-mail version  in /var/www/glpi/vendor/laminas/laminas-mail/src/Protocol
laminas/laminas-mime version  in /var/www/glpi/vendor/laminas/laminas-mime/src
rlanvin/php-rrule version  in /var/www/glpi/vendor/rlanvin/php-rrule/src
ramsey/uuid version  in /var/www/glpi/vendor/ramsey/uuid/src
phpoffice/phpspreadsheet version  in /var/www/glpi/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet
psr/log version  in /var/www/glpi/vendor/psr/log/src
psr/simple-cache version  in /var/www/glpi/vendor/psr/simple-cache/src
psr/cache version  in /var/www/glpi/vendor/psr/cache/src
psr/container version  in /var/www/glpi/vendor/psr/container/src
league/csv version  in /var/www/glpi/vendor/league/csv/src
mexitek/phpcolors version  in /var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors
guzzlehttp/guzzle version  in /var/www/glpi/vendor/guzzlehttp/guzzle/src
guzzlehttp/psr7 version  in /var/www/glpi/vendor/guzzlehttp/psr7/src
glpi-project/inventory_format version  in /var/www/glpi/vendor/glpi-project/inventory_format/lib/php
wapmorgan/unified-archive version  in /var/www/glpi/vendor/wapmorgan/unified-archive/src
paragonie/sodium_compat version  in /var/www/glpi/vendor/paragonie/sodium_compat/src
symfony/cache version  in /var/www/glpi/vendor/symfony/cache
html2text/html2text version  in /var/www/glpi/vendor/html2text/html2text/src
symfony/css-selector version  in /var/www/glpi/vendor/symfony/css-selector
symfony/dom-crawler version  in /var/www/glpi/vendor/symfony/dom-crawler
twig/twig version  in /var/www/glpi/vendor/twig/twig/src
twig/string-extra version  in /var/www/glpi/vendor/twig/string-extra
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php83 not found
league/oauth2-client version  in /var/www/glpi/vendor/league/oauth2-client/src/Provider
league/oauth2-google version  in /var/www/glpi/vendor/league/oauth2-google/src/Provider
thenetworg/oauth2-azure version  in /var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider
league/commonmark version  in /var/www/glpi/vendor/league/commonmark/src/Extension/CommonMark
egulias/email-validator version  in /var/www/glpi/vendor/egulias/email-validator/src
symfony/mime not found
apereo/phpcas version  in /var/www/glpi/vendor/apereo/phpcas/source
bacon/bacon-qr-code version  in /var/www/glpi/vendor/bacon/bacon-qr-code/src
robthree/twofactorauth version  in /var/www/glpi/vendor/robthree/twofactorauth/lib
ralouphie/getallheaders not found
symfony/html-sanitizer version  in /var/www/glpi/vendor/symfony/html-sanitizer
league/oauth2-server version  in /var/www/glpi/vendor/league/oauth2-server/src
league/html-to-markdown version  in /var/www/glpi/vendor/league/html-to-markdown/src
twig/markdown-extra version  in /var/www/glpi/vendor/twig/markdown-extra
webonyx/graphql-php version  in /var/www/glpi/vendor/webonyx/graphql-php/src
phpdocumentor/reflection-docblock version  in /var/www/glpi/vendor/phpdocumentor/reflection-docblock/src
symfony/property-access version  in /var/www/glpi/vendor/symfony/property-access
symfony/serializer version  in /var/www/glpi/vendor/symfony/serializer
symfony/property-info version  in /var/www/glpi/vendor/symfony/property-info
symfony/error-handler version  in /var/www/glpi/vendor/symfony/error-handler</pre></details><details><summary>Annuaires LDAP</summary><pre>Server: 'ldaps://.onmicrosoft.com', 
	Port: '636', 
	BaseDN: 'DC=,DC=local', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=glpi,CN=Users,DC=itgouv,DC=local', 
	Use TLS: none</pre></details><details><summary>Réplicats SQL</summary><pre>Not active</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Fix #19490, make sure a form can't be submitted if mandatory questions are not filled.

This is only validated on the client, I'd like to add server side validation too but I'll do it another PR (or someone else, I'll add it to the backlog).

## Screenshots

image

### CODE REVIEW

File: js/modules/Forms/RendererController.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ export class GlpiFormRendererController
      */
     constructor(target, form_id) {
         // Target must be a valid form
-        this.#target = target;
+        this.#target = document.querySelector(target);
```
Comment (AdrienClairembault) [inline js/modules/Forms/RendererController.js:69]: Change to a real HTMLFormElement instead of a raw selector for convenience when the code doesn't need jquery.

**Review by orthagh — APPROVED** [review]

**Review by ccailly — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
