### PR TITLE
Handle null values, fixes #18173

### LINKED ISSUE #18173: ticket, glpi_logs.new_value = null
In my local GLPI instance with data of 10 years, I have a few lines of historical with new_value = null.
It breaks the timeline view of related tickets: 

```
[2024-10-31 10:47:20] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Glpi\RichText\RichText::getTextFromHtml(): Argument glpi-project/illustrations#1 ($content) must be of type string, null given, called in src/Log.php on line 834 in src/Glpi/RichText/RichText.php at line 90
  Backtrace :
  src/Log.php:834                                    Glpi\RichText\RichText::getTextFromHtml()
  src/CommonITILObject.php:8051                      Log::getHistoryData()
  src/Ticket.php:3975                                CommonITILObject->getTimelineItems()
  src/CommonGLPI.php:667                             Ticket->showForm()
  ajax/common.tabs.php:112                           CommonGLPI::displayStandardTab()
  ...Glpi/Controller/LegacyFileLoadController.php:59 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  src/Glpi/Kernel/Kernel.php:255                     Symfony\Component\HttpFoundation\Response->send()
  public/index.php:58                                Glpi\Kernel\Kernel->sendResponse()
  ```

### PR DESCRIPTION
**Pull request by trasher**
## Description

Fix for #18173

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]

File: src/Log.php [hunk 1]
```diff
@@ -830,8 +830,8 @@ public static function getHistoryData(CommonDBTM $item, $start = 0, $limit = 0,
                             break;
 
                         default:
-                            $data["old_value"] = RichText::getTextFromHtml($item->getValueToDisplay($searchopt, $data["old_value"]), false, true);
-                            $data["new_value"] = RichText::getTextFromHtml($item->getValueToDisplay($searchopt, $data["new_value"]), false, true);
+                            $data["old_value"] = RichText::getTextFromHtml($item->getValueToDisplay($searchopt, $data["old_value"] ?? ''), false, true);
+                            $data["new_value"] = RichText::getTextFromHtml($item->getValueToDisplay($searchopt, $data["new_value"] ?? ''), false, true);
```
Comment (cedric-anne) [inline src/Log.php:834]: W should probably not alter the value passed to ``$item->getValueToDisplay()``, but rather handle the fact that it may return null.
```suggestion
                            $data["old_value"] = RichText::getTextFromHtml($item->getValueToDisplay($searchopt, $data["old_value"]) ?? '', false, true);
                            $data["new_value"] = RichText::getTextFromHtml($item->getValueToDisplay($searchopt, $data["new_value"]) ?? '', false, true);
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/Log.php (hunk 1 above)
Comment (trasher) [reply src/Log.php:834]: Indeed, that was the initial intention
