### PR TITLE
Fix CAS server status check

### LINKED ISSUE #18346: CAS status incorrect
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0.17

### Bug description

Using `bin/console system:status`, I get `No CAS server` which is in valid because I  Use a cas server, and the configuration is set to `cas_host=cas.domain.tld`
If I change the configuration for `cas_host=https://cas.domain.tld`, `system:status shows` `CAS_SERVER_OK` but I'm unable to log because I'm redirected to `https://https://cas.domain.tld/cas`

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cedric-anne**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

The `cas_host` configuration corresponds to the CAS server hostname. It must be prefixed by `https://` to build a valid URL.
It fixes #18346.

I cannot test against a real CAS server, so I cannot validate the rest of the status checking logic.

### CODE REVIEW

**Comment by trasher** [comment]
This seems OK, but we probably need to also prevent usage of protocol in configuration, no? Or at least check here if it's already present.

**Comment by cedric-anne** [comment]
> This seems OK, but we probably need to also prevent usage of protocol in configuration, no? Or at least check here if it's already present.

We may indeed improve this part, but I have no time to do it right now.

Right now, the status check will not work when the configuration is already done. The proposed changes focus on fixing that.

**Review by trasher — APPROVED** [review]
Cannot test.

**Review by AdrienClairembault — APPROVED** [review]

**Comment by cedric-anne** [comment]
In GLPI, the default `cas_port` value is 443 (the default HTTPS port). I added a commit to consider the presence of the `:80` port in HTTP URLs and the `:443` port in HTTPS URLs as safe.

File: src/System/Status/StatusChecker.php [hunk 1]
```diff
@@ -389,11 +389,14 @@ public static function getCASStatus($public_only = true): array
         if ($status === null) {
             $status['status'] = self::STATUS_NO_DATA;
             if (!empty($CFG_GLPI['cas_host'])) {
-                $url = $CFG_GLPI['cas_host'];
+                // Rebuild CAS URL
+                // see `CAS_Client::_getServerBaseURL()`
+                $url = 'https://' . $CFG_GLPI['cas_host'];
```
Comment (AdrienClairembault) [inline src/System/Status/StatusChecker.php:394]: If `http` is now allowed, how do you know if it is `http` or `https` here ?

Comment (cedric-anne) [reply src/System/Status/StatusChecker.php:394]: A CAS server is always exposed on HTTPS.

**Review by AdrienClairembault — APPROVED** [review]

**Review by trasher — APPROVED** [review]
