### PR TITLE
Fix: prevent base64 image to be stored when upload fails

### LINKED ISSUE #20265: Copy and Paste image to validation comment fails
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.18 / 11.0.0-dev

### Bug description

When adding a comment to a validation request and inserting a image which is "too large" the comment will not be saved.

I replaced the long Base64 String within the error message. The screenshot was just the whole desktop of the user.

In GLPI 10: No error message shown to user, fails silently and just shows error message in `sql-errors.log`

In GLPI 11: 
Shows error and also logs the same error message but in `php-errors.log`

Image

### Relevant log output

```shell
[2025-07-10 05:22:24] glpisqllog.ERROR: DBmysql::doQuery() in /var/www/glpi/src/DBmysql.php line 395
  *** MySQL query error:
  SQL: UPDATE `glpi_ticketvalidations` SET `comment_validation` = 'Validation Comment &#60;/p&#62;\r\n&#60;p&#62;&#60;img id=\"45335ba7-b2d8e96f-686f4dd51983d4.62703053\" src=\"data:image/png;base64,[LONG Base64 String]\" data-upload_id=\"0.20604472842034172\"&#62;&#60;/p&#62;', `status` = '4', `validation_date` = '2025-07-10 07:22:24' WHERE `id` = '1113'
  Error: Data too long for column 'comment_validation' at row 1
  Backtrace :
  src/DBmysql.php:1499                               DBmysql->doQuery()
  src/CommonDBTM.php:690                             DBmysql->update()
  src/CommonDBTM.php:1713                            CommonDBTM->updateInDB()
  front/commonitilvalidation.form.php:112            CommonDBTM->update()
  front/ticketvalidation.form.php:40                 include()
  public/index.php:82                                require()
  {"user":"24@****"}
```

### Page URL

_No response_

### Steps To reproduce

1. Have a validation request in a ticket
2. Add a comment to approve/refuse and add a larger image via Copy&Paste
3. Try to save

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### LINKED ISSUE #22596: GLPI 10.0.22 – Pasted images in ticket follow-ups are embedded as Base64 instead of saved as attachments
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.22

### Bug description

In GLPI 10.0.22, we are still facing an issue similar to #20265, even after the fix mentioned by @cedric-anne https://github.com/glpi-project/glpi/issues/20265#issuecomment-3612651219

When adding a new ticket follow-up and pasting or inserting an image, the image is not saved as an attachment. Instead, it is embedded directly in the follow-up content as Base64.

Image

As a result:
- Image is not stored as a document/attachment
- Follow-up content becomes very large
- Potential impact on performance, readability, and storage
- Behavior is inconsistent with expected image handling

### Relevant log output

```shell
No relevant errors or warnings were found in logs.
```

### Page URL

_No response_

### Steps To reproduce

1. Open an existing ticket
2. Create a new follow-up
3. Paste an image
4. Add the follow-up

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.22 ( => /usr/share/glpi)
Installation mode: RPM
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux 26f02ddc2dd7 6.12.0-105.51.5.1.el10uek.x86_64 #​1 SMP PREEMPT_DYNAMIC Mon Dec  1 17:00:17 PST 2025
	x86_64
PHP 8.1.33 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, krb5, ldap, libxml, mbstring,
	msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, selinux, session, shmop, snmp, soap, sockets,
	sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: disable_functions="" max_execution_time="30" max_input_vars="1000" memory_limit="512M" post_max_size="100M"
	session.cookie_secure="0" session.cookie_httponly="1" session.cookie_samesite="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.62 (Oracle Linux Server) OpenSSL/3.5.1 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 33, Revision 9dc49998
	Server Version: 8.0.42-33
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpiprod@percona-glpi-metabase/glpiprod
	Host info: percona-glpi-metabase via TCP/IP
	
PHP version (8.1.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.42) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/usr/share/glpi"
GLPI_CONFIG_DIR: "/etc/glpi"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: false
GLPI_VAR_DIR: "/var/lib/glpi/files"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_SYSTEM_CRON: true
GLPI_INSTALL_MODE: "RPM"
GLPI_MARKETPLACE_DIR: "/usr/share/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["~^\n                (http|https|feed)://                                                # protocol\n                (\n                    (?:\n                        (?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                            |\n                        (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain name\n                            |\n                        [a-z0-9\\-\\_]++                                              # a single-level domain name\n                    )\\.?\n                        |                                                           # or\n                    \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}                              # an IP address\n                        |                                                           # or\n                    \\[\n                        (?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n                    \\]                                                              # an IPv6 address\n                )\n                (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n                (?:\\? (?:[\\pL\\pN\\-._\\~!$&'\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n            $~ixuD"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/lib/glpi/files"
GLPI_CACHE_DIR: "/var/lib/glpi/files/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/files/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/files/_inventories"
GLPI_NETWORK_API_URL: "https://services.glpi-network.com/api"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/usr/share/glpi/locales"
GLPI_VERSION: "10.0.22"
GLPI_SCHEMA_VERSION: "10.0.22@f240fda6b7e7829ec89cca85f4803b9c1f91198b"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.6.0"
GLPI_YEAR: "2025"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.8.0 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/usr/share/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/usr/share/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/usr/share/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (yourmail@mail.com.br@yourmail.mail.com.br)

</pre></details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alerts                         Version: 1.12.2     State: Enabled                                 
		Install Method: Manual
	fields               Name: Campos adicionais              Version: 1.21.11    State: Enabled                                 
		Install Method: Manual
	screenshot           Name: Captura de tela                Version: 2.0.3      State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.3      State: Enabled                                 
		Install Method: Manual
	customlogin          Name: Custom Login                   Version: 1.0.6      State: Installed / not activated               
		Install Method: Manual
	archimap             Name: Diagrams                       Version: 3.3.7      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.10    State: Enabled                                 
		Install Method: Manual
	formvalidation       Name: Form Validation                Version: 2.0.1      State: Not installed                           
		Install Method: Manual
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.11.7     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.14.9     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Manual
	holiday              Name: Holidays                       Version: 1.2        State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Importação de dados            Version: 2.14.3     State: Not installed                           
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Not installed                           
		Install Method: Manual
	timelineticket       Name: Linha do tempo dos chamados    Version: 10.0+1.2   State: Enabled                                 
		Install Method: Manual
	singlesignon         Name: Logon Único                    Version: 1.3.3      State: Installed / not activated               
		Install Method: Manual
	mailanalyzer         Name: Mail Analyzer                  Version: 3.2.1      State: To update                               
		Install Method: Manual
	satisfaction         Name: Mais satisfação                Version: 1.6.2      State: Not installed                           
		Install Method: Manual
	metabase             Name: Metabase                       Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	mfa                  Name: MFA                            Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: To update                               
		Install Method: Manual
	dashboard            Name: Painel                         Version: 1.0.3      State: Enabled                                 
		Install Method: Manual
	stsync               Name: ST-Sync                        Version: 1.0.0      State: Error / to clean                        
		Install Method: Manual
	tasklists            Name: Tasks list                     Version: 2.0.3      State: Installed / not activated               
		Install Method: Manual
	webhook              Name: Webhooks                       Version: 1.0.18     State: Enabled                                 
		Install Method: Manual

</pre></details><details><summary>Locales overrides</summary><pre></pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
It fixes #20265

if the image is too big : then triggers a dom.remove to avoid saving that cause base_64 storing

### CODE REVIEW

**Review by trasher — APPROVED** [review]
LGTM (but I'm not a JS expert). Not tested

File: src/Html.php [hunk 1]
```diff
@@ -5656,6 +5656,26 @@ function(index, file) {
...
+                                    var img = editor.dom.select('img[data-upload_id=\"' + uploaded_image.upload_id + '\"]');
+                                    if (img.length > 0) {
+                                        editor.dom.remove(img);
+                                    }
+                                    uploaded_images = uploaded_images.filter(function(entry) {
+                                        return entry.upload_id !== uploaded_image.upload_id;
+                                    });
+                                }
+                            }
+                        }
```
Comment (cconard96) [inline src/Html.php]: Not tested functionally. For the code itself, please use "let" or "const" only rather than "var". "var" has scoping issues which can become confusing to troubleshoot and defaulting to using "const" help avoid accidentally overwriting a variable you expected to stay the same.

We also have ESLint rules to prefer arrow functions to avoid issues with "this" bindings. "this" inside a regular function refers to the function context while "this" inside an arrow function is inherited instead. Not an issue here, but it does make a difference when using JS classes.
```suggestion
                        const editor_id = '{$p['editor_id']}';
                        if (editor_id && typeof tinyMCE !== 'undefined') {
                            const editor = tinyMCE.get(editor_id);
                            if (editor) {
                                const uploaded_image = uploaded_images.find((entry) => {
                                    return entry.filename === file.name;
                                });
                                if (uploaded_image) {
                                    const img = editor.dom.select('img[data-upload_id=\"' + uploaded_image.upload_id + '\"]');
                                    if (img.length > 0) {
                                        editor.dom.remove(img);
                                    }
                                    uploaded_images = uploaded_images.filter((entry) => {
                                        return entry.upload_id !== uploaded_image.upload_id;
                                    });
                                }
                            }
                        }
```

**Review by AdrienClairembault — COMMENTED** [review]
I'm worried about the impact for forms as we still have some images saved in base64 there (we have on ongoing issue but it is not trivial to fix, @ccailly has been making good process tho).

I can't test it since this PR is for 10.0 but will this prevent adding base64 images to helpdesk forms descriptions ?

**Comment by cedric-anne** [comment]
> I'm worried about the impact for forms as we still have some images saved in base64 there (we have on ongoing issue but it is not trivial to fix, @ccailly has been making good process tho).
> 
> I can't test it since this PR is for 10.0 but will this prevent adding base64 images to helpdesk forms descriptions ?

The purpose here is to remove images when their upload fail because they are too big compared to the GLPI documents configuration. I guess the forms are not using this upload process, so they are probably not impacted.

**Comment by cconard96** [comment]
JS code looks fine now but I do not believe this resolves the reported issue. The reported issue had the image "uploaded" successfully but fail to save the base64 content because it was too long for the `text` DB column. As far as I could tell, images are handled in two parts as explained in my comment on the issue. I am fairly certain that the base64 content is only added when the file upload succeeds.

**Comment by f2cmb** [comment]
> JS code looks fine now but I do not believe this resolves the reported issue. The reported issue had the image "uploaded" successfully but fail to save the base64 content because it was too long for the `text` DB column. As far as I could tell, images are handled in two parts as explained in my comment on the issue. I am fairly certain that the base64 content is only added when the file upload succeeds.

The fix here handle one behaviour : when the user drag and drop or paste an image. The bug is specific to this case as i also tested the "upload" button use case. Using the button triggers another document loading scenario, with no JS. In the original issue it is mentioned to work on the JS logic.

I'm agree that maybe it's not perfect, but this PR with the reworked JS (thanks to you) is in the scope of #20265 another issue if there is a known or new bug with a mention of this one could help, idk.

**Review by AdrienClairembault — APPROVED** [review]
I've just tested and it fix the original issue 👍

**Review by cedric-anne — APPROVED** [review]
