### PR TITLE
Fix network report rendering error

### LINKED ISSUE #20544: Network report trigger Twig error
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0/bugfixes

### Bug description

_No response_

### Relevant log output

```shell
[2025-08-04 23:34:50] glpi.CRITICAL:   *** Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "session" does not exist in "pages/tools/report/network_criteria.html.twig" at line 56." at network_criteria.html.twig line 56
  Backtrace :
  ...ages/tools/report/network_criteria.html.twig:56 
  ...ates/bb/bbd625fdaf3258567c134a4cab53a0d5.php:89 __TwigTemplate_aee53b24c3938e5c83e88751afb3ad43->{closure:__TwigTemplate_aee53b24c3938e5c83e88751afb3ad43::doDisplay():89}()
  ./vendor/twig/twig/src/Template.php:402            __TwigTemplate_aee53b24c3938e5c83e88751afb3ad43->doDisplay()
  ./vendor/twig/twig/src/Template.php:358            Twig\Template->yield()
  ./vendor/twig/twig/src/TemplateWrapper.php:61      Twig\Template->display()
  .../Glpi/Application/View/TemplateRenderer.php:186 Twig\TemplateWrapper->display()
  ./src/Report.php:479                               Glpi\Application\View\TemplateRenderer->display()
  ./src/Report.php:734                               Report::showNetworkReportCriteria()
  ./front/report.networking.php:52                   Report::showNetworkReport()
  ...Glpi/Controller/LegacyFileLoadController.php:63 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

The network port report page was throwing an error during its rendering due to a missing variable:
```
Twig\Error\RuntimeError: Variable "session" does not exist in "pages/tools/report/network_criteria.html.twig" at line 56.
```

Fixed by sending missing `session` variable, I also contemplated sending only `$_SESSION['glpiactive_entity']` since this is actually the only value being used by the template but I didn't do it to avoid changing the template behavior (even if it is extremely unlikely that some plugin reuse it).

## References

Fix #20544

### CODE REVIEW

File: src/Report.php [hunk 1]
```diff
@@ -476,7 +476,13 @@ public static function showDefaultReport(): void
 
     public static function showNetworkReportCriteria(bool $embeded): void
     {
-        TemplateRenderer::getInstance()->display('pages/tools/report/network_criteria.html.twig', ['embeded' => $embeded]);
+        TemplateRenderer::getInstance()->display(
+            'pages/tools/report/network_criteria.html.twig',
+            [
+                'embeded' => $embeded,
+                'session' => $_SESSION,
```
Comment (cconard96) [inline src/Report.php]: Should use the `session` twig function instead to access session data.

Comment (AdrienClairembault) [reply src/Report.php]: 👍
