### PR TITLE
fix(CommonITILObject): ensure ticket template updates when category is modified

### LINKED ISSUE #22316: [11.0] Changing a ticket category don't change the ticket template
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

11.0.x-dev

### Bug description

After creating a ticket, if you change it's category the template linked to it is not updated.

Making some fields not visible for example.

No issue in GLPI 10.x

Maybe it's the desired behavior but I found weird that if we change the category we don't follow anymore the new category templating rule (and no way to change the current ticket template so)

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create a ticket using a category with a template that hide Urgency/Impact field.
2. Change the create ticket category to another one that has nothing hidden
3. The field are still hidden, in the Ticket table the `tickettemplates_id` is still linked to one that was present originally

https://github.com/user-attachments/assets/0aaefe7f-d160-4c89-9e6b-02f63a2ce74a

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>
GLPI: 11.0.5-dev-git-fix-entity-creating-child-entity-229cf2e131 ( =&gt; /var/www/glpi)
Installation mode: GIT
Current language: en_GB
Source Integrity: N/A
</pre></details><details><summary>Server</summary><pre>
Operating system: Linux 011be9671d8e 6.12.54-linuxkit #​1 SMP PREEMPT_DYNAMIC Tue Nov  4 21:39:03 UTC 2025 x86_64

PHP: 8.4.15 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json,
mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader,
xmlwriter, mysqlnd, apache2handler, bcmath, Phar, exif, gd, intl, ldap, memcached, mysqli, pcntl, redis, sodium, xmlrpc, zip,
Zend OPcache, xdebug

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;128M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache/2.4.65 (Debian) (Apache/2.4.65 (Debian) Server at localhost Port 8080)

User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:145.0) Gecko/20100101 Firefox/145.0

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 11.8.5-MariaDB-ubu2404
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: root@db:3306/glpi
   
Host info: db via TCP/IP

Requirements:
PHP version (8.4.15) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (11.8.5) is supported.
The log file has been created successfully.
Write access
to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.
</pre></details><details><summary>GLPI constants</summary><pre>
GLPI_ROOT: &quot;/var/www/glpi&quot;
GLPI_VERSION: &quot;11.0.5-dev&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.5-dev@6fb23347853af210966f29093a92f26ee444d14f&quot;
GLPI_FILES_VERSION: &quot;11.0.5-dev-00000000&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/glpi/locales&quot;
GLPI_ENVIRONMENT_TYPE: &quot;development&quot;
GLPI_CONFIG_DIR: &quot;/var/www/glpi/config&quot;
GLPI_VAR_DIR: &quot;/var/www/glpi/files&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;GIT&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;debug&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: true
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;1&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/www/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/var/www/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/www/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/www/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/www/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/www/glpi/files/_lock&quot;
GLPI_LOG_DIR: &quot;/var/www/glpi/files/_log&quot;
GLPI_PICTURE_DIR: &quot;/var/www/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/www/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/www/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/www/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/www/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/www/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/www/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/www/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/glpi/marketplace&quot;,&quot;/var/www/glpi/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;
</pre></details><details><summary>SQL replicas</summary><pre>
Not active
</pre></details><details><summary>Notifications</summary><pre>
Way of sending emails: SMTP(smtp://mailpit:1025)
Name: &#39;glpidebug@gmail.com&#39;
	Active: Yes
	Server: &#39;{imap.gmail.com:993/imap/ssl}INBOX&#39;
	Login: &#39;glpidebug@gmail.com&#39;
	Password: Yes
</pre></details><details><summary>Plugins list</summary><pre>
anonymize            Name: Anonymize                      Version: 2.8.0      State: Not installed                           
Install Method: Manual
collaborativetools   Name: Collaborative tools            Version: 1.3.0-beta5 State: Not installed                           
Install Method: Manual
myplugin             Name: myplugin                       Version: 0.0.3      State: Not installed                           
Install Method: Manual
tester               Name: tester                         Version: 1.0.0      State: Not installed                           
Install Method: Manual
vulnerability        Name: Vulnerability                  Version: 0.0.1      State: Not installed                           
Install Method: Manual
whatsapp             Name: whatsapp                       Version: 1.0.0-beta1 State: Enabled                                 
Install Method: Manual
</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MyvTsv**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !42376
- When a user changed the category of an existing ticket, the associated template was not updated according to the new category.
This behavior was inconsistent with that observed when creating a ticket, where the template is correctly applied according to the selected category.

## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by Rom1-B** [comment]
I'm not sure if we want this behavior?

A template can hide fields, but it can also predefine them. Should we apply the predefined values from the new template when the category changes?
In my opinion, the template is useful for simplifying creation. And I think if we want to change the template, it should be done explicitly: probably through a dedicated action, not automatically in the background.

**Comment by stonebuzz** [comment]
Apparently, this was possible in version 10. @MyvTsv , could you please verify if it is indeed the case in this version?

**Comment by MyvTsv** [comment]
ping @stonebuzz

**Review by stonebuzz — APPROVED** [review]

File: src/CommonITILObject.php [hunk 1]
```diff
@@ -2006,15 +2016,15 @@ public function prepareInputForUpdate($input)
...
-        }
-
         if ($this->getType() !== Ticket::getType()) {
             //cannot be handled here for tickets. @see Ticket::prepareInputForUpdate()
+
+            // Map unique template field to template foreign key
+            // Leave original field. The new field is stored in the DB, while the original is used for everything else (left for BC)
+            if (isset($input[static::getTemplateFormFieldName()]) && (int) $input[static::getTemplateFormFieldName()] > 0) {
+                $tpl_class = static::getTemplateClass();
+                $input[$tpl_class::getForeignKeyField()] = (int) $input[static::getTemplateFormFieldName()];
```
Comment (cedric-anne) [inline src/CommonITILObject.php]: Could you explain why you moved this ?

File: src/CommonITILObject.php [hunk 2]
```diff
@@ -1889,7 +1889,17 @@ class_exists($validation_class)
...
-        if ($tt && count($tt->mandatory)) {
+
+        if (!$tt) {
+            return $input;
+        }
+
+        if (isset($input['itilcategories_id'])) {
+            $tpl_class = static::getTemplateClass();
+            $input[$tpl_class::getForeignKeyField()] = $tt->getID();
+        }
```
Comment (cedric-anne) [inline src/CommonITILObject.php]: This looks like a hack. The template to use may depends on many parameters, like the ticket type or the ticket entity.

If the template value must be updated in the input at this point, then maybe it should be done like this, without specific conditions:
```
$input[static::getTemplateFormFieldName()] = $tt->getID();
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]
Please triple check all consequences of this change. The related code is a mess, and changing this may have many unexpected side effects.

File: src/CommonITILObject.php (hunk 1 above)
Comment (MyvTsv) [reply src/CommonITILObject.php]: I made this change because:

getForeignKeyField() allows you to save the newly selected template.

getTemplateFormFieldName() saved the old template before updating the ticket/change/problem.

The initial idea was that keeping the old template could be useful when updating an ITIL object (ticket, change, problem).

However, after checking, this information does not appear to be used in the update process.

File: src/CommonITILObject.php [hunk 3]
```diff
@@ -1889,7 +1889,18 @@ class_exists($validation_class)
 
         // First get ticket template associated: entity and type/category
         $tt = $this->getITILTemplateFromInput($input);
-        if ($tt && count($tt->mandatory)) {
+
+        if (!$tt) {
+            return $input;
+        }
+
+        if (isset($input['itilcategories_id'])) {
```
Comment (cedric-anne) [inline src/CommonITILObject.php]: Why restricting to `isset($input['itilcategories_id'])`? The template may change depending on other parameters.

**Review by RomainLvr — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]
