### PR TITLE
Link recurrent items to their template

### LINKED ISSUE #20566: Recurrently created Tickets and Changes do not record template ID
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0/bugfixes

### Bug description

A Ticket or Change created recurrently does not record the template ID in the database. This makes the "Allow limiting available statuses in ITIL Templates" feature unusable for them.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Link recurrent items to their template.

## References

Fix #20566.

### CODE REVIEW

File: phpunit/abstracts/CommonITILRecurrentTest.php [hunk 1]
```diff
@@ -736,4 +739,35 @@ public function testPrepareInputForUpdateWithPartialData()
...
+        ]);
+
+        // Act: trigger recurrent item creation
+        $item = null;
+        $reccurent_itil->createItem([], $item);
+
+        // Assert: template should be linked
+        $this->assertEquals(
+            $template->getID(),
+            $item->fields[$template->getForeignKeyField()],
```
Comment (cconard96) [inline phpunit/abstracts/CommonITILRecurrentTest.php]:
```suggestion
            $item->fields[$template::getForeignKeyField()],
```

**Review by cconard96 — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
