### PR TITLE
Streamline search for solution process

### LINKED ISSUE #18490: When searching for a solution, the ticket loses the Lock status
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

If I start to edit a ticket, the ticket stays Locked.
But, when adding a new solution, if I press the "search a solution" button, the ticket loses the Lock status, and other user can edit it.

When we are searching for a solution, if we go back to the previous page, we get the lock (if other user didn't lock it before).

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Open a ticket and request lock
2. Press the Add new solution button and search for a solution.
3. Ask another user to open that ticket, while searching for a solution
4. The other user will have the acess to request lock for the ticket, and it shouldn't.

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

When using object locks, there was an opportunity for a technician to lose the lock on a ticket when searching for a solution because the process redirects out of the ticket for the solution search/selection part.

This PR moves the solution selection to a modal and allows adding the article content directly to the solution content without any redirects/page reloads.

Fixes #18490

### CODE REVIEW

File: src/KnowbaseItem.php [hunk 1]
```diff
@@ -1615,12 +1615,8 @@ public static function showList($options, $type = 'search')
                 }
 
                 if (isset($options['item_itemtype'], $options['item_items_id']) && ($output_type === Search::HTML_OUTPUT)) {
-                    $forcetab = $options['item_itemtype'] . '$main';
-                    $item_itemtype = $options['item_itemtype'];
-                    $content = "<a href='" . $item_itemtype::getFormURLWithID($options['item_items_id']) .
-                        "&amp;load_kb_sol=" . $data['id'] .
```
Comment (cedric-anne) [inline src/KnowbaseItem.php:1621]: Il the `load_kb_sol` related code still used somewhere else? It it is not used anymore, you could clean the ajax, front and class code.

File: src/Glpi/Controller/KBController.php [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+final class KBController extends AbstractController
+{
+    #[Route(
+        "/Knowbase/KnowbaseItem/{knowbaseitems_id}/Content",
+        name: "knowbaseitem_content",
+        requirements: [
+            'knowbaseitems_id' => '\d+',
+        ]
+    )]
+    public function getArticleContent(Request $request): Response
```
Comment (cedric-anne) [inline src/Glpi/Controller/KBController.php:53]: The route path should match the controller namespace/class name/method name.

For instance, if your route is `/Knowbase/KnowbaseItem/{knowbaseitems_id}/Content`, then the method path should be `\Glpi\Controller\Knowbase\KnowbaseItemController::content()`.

With this, it would be easier to locate the corresponding file as it would not require to do a text search to find the route declaration.

File: src/KnowbaseItem.php (hunk 1 above)
Comment (orthagh) [reply src/KnowbaseItem.php:1621]: It should 
I didn't the current diff, but it corresponds to the action of moving back grom the kb to the ticket with content from an article to the solution

Comment (orthagh) [reply src/KnowbaseItem.php:1621]: Ok I checked out and tested the pr.
The parameter is indeed probably not used anymore.

**Comment by orthagh** [comment]
Regarding UX.
I like the idea of getting the kb directly displayed in a modal and it's a good starting point.
But the view of the content of an article is bad currently.
We move to a full layout of GLPI if we click on an article's title, and we don't have anymore a "use as solution" button.
image


Also, this part is very badly displayed:
image

I think we should probably remove it completely in the modal

**Comment by cconard96** [comment]
There are a few things that aren't handled yet like linking the KB article in addition to just copying the content, pagination, etc.

This work is going to need be more complex so I put it to draft.

**Comment by cconard96** [comment]
It is rough, but here is a replacement UI proposal for searching solutions:
Selection_380

I pushed commits that add this and it should be functional. The only main thing missing is pagination.

When you click the button to search for a solution, it presents you with a list of matching articles rather than the table that was there previously. Each result has two buttons; A button to use it as the solution and a button to preview the article. If you preview an article, the results are hidden and the "full" form of the article is shown in its place in the modal. A button at the top of the preview lets you go back to the results. Searching from inside this modal refreshes the results via AJAX.

**Comment by orthagh** [comment]
It should be good like this.

**Review by AdrienClairembault — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Comment by cedric-anne** [comment]
@orthagh Is this PR OK for you ?

**Review by orthagh — CHANGES_REQUESTED** [review]
Almost
There is UI polishing to do:

- [x] KB articles with HTML elements (images, bold, titles, etc) appear raw. At least, I expect to have the new lines respected, if you prefer to display only text.
  image

- [x] Maybe we can truncate (rather overflow hidden) articles in the list searching for a solution and avoid them being higher than 100-150px

- [x] mini button "Use as solution" and "preview" should have tooltips.

- [x] avoid double border 


- The preview mode of an article has some quirks
  - [x] can avoid double border also here
  - [x] We miss a "Use as solution" button

   image

**Comment by cconard96** [comment]
>     * Maybe we can truncate (rather overflow hidden) articles in the list searching for a solution and avoid them being higher than 100-150px
The truncation is based on `$CFG_GLPI['cut']`, although maybe it could be based on the constant `GLPI_TEXT_MAXSIZE`.

**Comment by orthagh** [comment]
> maybe it could be based...

I'm not sure, we can just set a fixed limit for this feature. I don't see any advantage to let the user change the height here.

**Comment by orthagh** [comment]
UI/UX review: 

- [ ] add a margin here or better add the primary action on right (margin left auto)
  image
- [ ] "Use as solution" should be `btn-primary` class 
- [ ] Remove `justify-content-center` on search header and remove `size=50` from search input
  image
- [ ] Move the "Showing 1 to 4 of 4 rows" message at bottom
- [ ] I think we can reduce more the max height of an article in the list (150px seems good)
   But I'm not fan of the current way of designing an ellipsis. I suggest using line-clamp property set to 6 or 7 lines, it should match the 150px (and replace it)
  ```css
  .solution-content-preview {
    ...
    display: -webkit-box;
    -webkit-line-clamp: 7;
    -webkit-box-orient: vertical;
  }
  ```
  image

**Comment by cconard96** [comment]
>     * [ ]  Remove `justify-content-center` on search header and remove `size=50` from search input

The size limitation was intentional. It is the same limit as the regular KB search which has always been limited. I'm not sure why it was done, but I guess there are performance implications at the very least and a change to this limit should be extracted into its own PR.

>     * [ ]  I think we can reduce more the max height of an article in the list (150px seems good)
>       But I'm not fan of the current way of designing an ellipsis. I suggest using line-clamp property set to 6 or 7 lines, it should match the 150px (and replace it)
>       (note browser support seems ok: https://caniuse.com/css-line-clamp)

I was trying to avoid using properties that were not official or deprecated. The line-clamp property at least is widely supported because of how much it is used. I cannot find anything on `-webkit-box-orient` except that the official `box-orient` property is deprecated. I don't know how supported all of this will be. I've done it inside a `@supports` rule. If a browser doesn't support these properties, it will fallback to a simple `max-height` limitation.

**Review by orthagh — APPROVED** [review]
Good for merge

**Comment by trasher** [comment]
Could you please rebase to solve conflict? That will also unlock test suite that did not ran on latest commit.

**Comment by cconard96** [comment]
Issues seemed to only happen if you clicked on the icon. The rest of the button worked. I've fixed the click listener.

**Comment by cedric-anne** [comment]
> I've fixed the click listener.

Your push operation probably failed.
