### PR TITLE
fix(forms-migration): Add null handling for mapped items and update horizontal rank

### LINKED ISSUE #19362: GLPI11 - Migrate forms
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

glpi11-dev (main-d1ad730)

### Bug description

Hello,

I'm testing the forms migration, but I'm getting an error (see below).

Image

Sincerely,

### Relevant log output

```shell
[2025-04-04 09:40:03] glpi.ERROR:   *** array_map(): Argument #2 ($array) must be of type array, int given
  Backtrace :
  ...tionType/AbstractQuestionTypeSelectable.php:187
  ...tionType/AbstractQuestionTypeSelectable.php:187 array_map()
  ./src/Glpi/Form/Migration/FormMigration.php:423    Glpi\Form\QuestionType\AbstractQuestionTypeSelectable->convertDefaultValue()
  ./src/Glpi/Form/Migration/FormMigration.php:246    Glpi\Form\Migration\FormMigration->processMigrationOfQuestions()
  ...c/Glpi/Migration/AbstractPluginMigration.php:99 Glpi\Form\Migration\FormMigration->processMigration()
  ...Migration/AbstractPluginMigrationCommand.php:84 Glpi\Migration\AbstractPluginMigration->execute()
  ./vendor/symfony/console/Command/Command.php:326   Glpi\Console\Migration\AbstractPluginMigrationCommand->execute()
  ./vendor/symfony/console/Application.php:1096      Symfony\Component\Console\Command\Command->run()
  ./src/Glpi/Console/Application.php:297             Symfony\Component\Console\Application->doRunCommand()
  ./vendor/symfony/console/Application.php:324       Glpi\Console\Application->doRunCommand()
  ./vendor/symfony/console/Application.php:175       Symfony\Component\Console\Application->doRun()
  ./bin/console:157                                  Symfony\Component\Console\Application->run()
```

### Page URL

_No response_

### Steps To reproduce

1.Migrate form with :  bin/console migration:formcreator_plugin_to_core

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0-dev ( => /var/www/nightly_glpi11)
Installation mode: TARBALL
Current language: fr_FR</pre></details><details><summary>Server</summary><pre>Operating system: Linux 6.1.0-32-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.129-1 (2025-03-06)
x86_64

PHP: 8.3.19 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv,
intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer,
xmlreader, xmlwriter, xsl, zip, Zend OPcache

Setup: max_execution_time="600" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M" disable_functions="" 

Web server: Apache/2.4.63 (Debian) (Apache/2.4.63 (Debian) Server at XX Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 11.4.5-MariaDB-deb12
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi11@localhost/nightly_glpi11
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.3.19) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
mysqli extension is installed.
curl extension is installed.
gd extension is installed.
intl extension is installed.
mbstring extension is installed.
zlib extension is installed.
bcmath extension is installed.
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed.
Database engine version (11.4.5) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/nightly_glpi11/files/_cache has been validated.
Write access to /var/www/nightly_glpi11/files/_cron has been validated.
Write access to /var/www/nightly_glpi11/files has been validated.
Write access to /var/www/nightly_glpi11/files/_graphs has been validated.
Write access to /var/www/nightly_glpi11/files/_lock has been validated.
Write access to /var/www/nightly_glpi11/files/_pictures has been validated.
Write access to /var/www/nightly_glpi11/files/_plugins has been validated.
Write access to /var/www/nightly_glpi11/files/_rss has been validated.
Write access to /var/www/nightly_glpi11/files/_sessions has been validated.
Write access to /var/www/nightly_glpi11/files/_tmp has been validated.
Write access to /var/www/nightly_glpi11/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/nightly_glpi11/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: "/var/www/nightly_glpi11"
GLPI_VERSION: "11.0.0-dev"
GLPI_SCHEMA_VERSION: "11.0.0-dev@a53ca92172d538281e6c5a1754f3bc0d0f49a07c"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.4"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/var/www/nightly_glpi11/locales"
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_CONFIG_DIR: "/var/www/nightly_glpi11/config"
GLPI_VAR_DIR: "/var/www/nightly_glpi11/files"
GLPI_MARKETPLACE_DIR: "/var/www/nightly_glpi11/marketplace"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST:
["#^http://[^@:]+(:80)?(/.*)?$#","#^https://[^@:]+(:443)?(/.*)?$#","#^feed://[^@:]+(/.*)?$#"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_DOC_DIR: "/var/www/nightly_glpi11/files"
GLPI_CACHE_DIR: "/var/www/nightly_glpi11/files/_cache"
GLPI_CRON_DIR: "/var/www/nightly_glpi11/files/_cron"
GLPI_GRAPH_DIR: "/var/www/nightly_glpi11/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/nightly_glpi11/files/_locales"
GLPI_LOCK_DIR: "/var/www/nightly_glpi11/files/_lock"
GLPI_LOG_DIR: "/var/www/nightly_glpi11/files/_log"
GLPI_PICTURE_DIR: "/var/www/nightly_glpi11/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/nightly_glpi11/files/_plugins"
GLPI_RSS_DIR: "/var/www/nightly_glpi11/files/_rss"
GLPI_SESSION_DIR: "/var/www/nightly_glpi11/files/_sessions"
GLPI_TMP_DIR: "/var/www/nightly_glpi11/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/nightly_glpi11/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/nightly_glpi11/files/_inventories"
GLPI_THEMES_DIR: "/var/www/nightly_glpi11/files/_themes"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"</pre></details><details><summary>Libraries</summary><pre>symfony/mailer not found
simplepie/simplepie version 1.8.1 in /var/www/nightly_glpi11/vendor/simplepie/simplepie/src
tecnickcom/tcpdf version 6.9.0 in /var/www/nightly_glpi11/vendor/tecnickcom/tcpdf
tecnickcom/tc-lib-barcode version  in /var/www/nightly_glpi11/vendor/tecnickcom/tc-lib-barcode/src
sabre/dav version  in /var/www/nightly_glpi11/vendor/sabre/dav/lib/DAV
sabre/http version  in /var/www/nightly_glpi11/vendor/sabre/http/lib
sabre/uri version  in /var/www/nightly_glpi11/vendor/sabre/uri/lib
sabre/vobject version  in /var/www/nightly_glpi11/vendor/sabre/vobject/lib
laminas/laminas-i18n version  in /var/www/nightly_glpi11/vendor/laminas/laminas-i18n/src
monolog/monolog version  in /var/www/nightly_glpi11/vendor/monolog/monolog/src/Monolog
sebastian/diff version  in /var/www/nightly_glpi11/vendor/sebastian/diff/src
donatj/phpuseragentparser version  in /var/www/nightly_glpi11/vendor/donatj/phpuseragentparser/src/UserAgent
elvanto/litemoji version  in /var/www/nightly_glpi11/vendor/elvanto/litemoji/src
gettext/languages version  in /var/www/nightly_glpi11/vendor/gettext/languages/src
symfony/console version  in /var/www/nightly_glpi11/vendor/symfony/console
symfony/config version  in /var/www/nightly_glpi11/vendor/symfony/config/Loader
symfony/dependency-injection version  in /var/www/nightly_glpi11/vendor/symfony/dependency-injection
symfony/event-dispatcher version  in /var/www/nightly_glpi11/vendor/symfony/event-dispatcher
symfony/filesystem version  in /var/www/nightly_glpi11/vendor/symfony/filesystem
symfony/framework-bundle version  in /var/www/nightly_glpi11/vendor/symfony/framework-bundle
symfony/http-foundation version  in /var/www/nightly_glpi11/vendor/symfony/http-foundation
symfony/http-kernel version  in /var/www/nightly_glpi11/vendor/symfony/http-kernel
symfony/routing version  in /var/www/nightly_glpi11/vendor/symfony/routing
scssphp/scssphp version  in /var/www/nightly_glpi11/vendor/scssphp/scssphp/src
laminas/laminas-mail version  in /var/www/nightly_glpi11/vendor/laminas/laminas-mail/src/Protocol
laminas/laminas-mime version  in /var/www/nightly_glpi11/vendor/laminas/laminas-mime/src
rlanvin/php-rrule version  in /var/www/nightly_glpi11/vendor/rlanvin/php-rrule/src
ramsey/uuid version  in /var/www/nightly_glpi11/vendor/ramsey/uuid/src
phpoffice/phpspreadsheet version  in /var/www/nightly_glpi11/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet
psr/log version  in /var/www/nightly_glpi11/vendor/psr/log/src
psr/simple-cache version  in /var/www/nightly_glpi11/vendor/psr/simple-cache/src
psr/cache version  in /var/www/nightly_glpi11/vendor/psr/cache/src
psr/container version  in /var/www/nightly_glpi11/vendor/psr/container/src
league/csv version  in /var/www/nightly_glpi11/vendor/league/csv/src
mexitek/phpcolors version  in /var/www/nightly_glpi11/vendor/mexitek/phpcolors/src/Mexitek/PHPColors
guzzlehttp/guzzle version  in /var/www/nightly_glpi11/vendor/guzzlehttp/guzzle/src
guzzlehttp/psr7 version  in /var/www/nightly_glpi11/vendor/guzzlehttp/psr7/src
glpi-project/inventory_format version  in /var/www/nightly_glpi11/vendor/glpi-project/inventory_format/lib/php
wapmorgan/unified-archive version  in /var/www/nightly_glpi11/vendor/wapmorgan/unified-archive/src
paragonie/sodium_compat version  in /var/www/nightly_glpi11/vendor/paragonie/sodium_compat/src
symfony/cache version  in /var/www/nightly_glpi11/vendor/symfony/cache
html2text/html2text version  in /var/www/nightly_glpi11/vendor/html2text/html2text/src
symfony/css-selector version  in /var/www/nightly_glpi11/vendor/symfony/css-selector
symfony/dom-crawler version  in /var/www/nightly_glpi11/vendor/symfony/dom-crawler
twig/twig version  in /var/www/nightly_glpi11/vendor/twig/twig/src
twig/string-extra version  in /var/www/nightly_glpi11/vendor/twig/string-extra
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php83 not found
league/oauth2-client version  in /var/www/nightly_glpi11/vendor/league/oauth2-client/src/Provider
league/oauth2-google version  in /var/www/nightly_glpi11/vendor/league/oauth2-google/src/Provider
thenetworg/oauth2-azure version  in /var/www/nightly_glpi11/vendor/thenetworg/oauth2-azure/src/Provider
league/commonmark version  in /var/www/nightly_glpi11/vendor/league/commonmark/src/Extension/CommonMark
egulias/email-validator version  in /var/www/nightly_glpi11/vendor/egulias/email-validator/src
symfony/mime not found
apereo/phpcas version  in /var/www/nightly_glpi11/vendor/apereo/phpcas/source
bacon/bacon-qr-code version  in /var/www/nightly_glpi11/vendor/bacon/bacon-qr-code/src
robthree/twofactorauth version  in /var/www/nightly_glpi11/vendor/robthree/twofactorauth/lib
ralouphie/getallheaders not found
symfony/html-sanitizer version  in /var/www/nightly_glpi11/vendor/symfony/html-sanitizer
league/oauth2-server version  in /var/www/nightly_glpi11/vendor/league/oauth2-server/src
league/html-to-markdown version  in /var/www/nightly_glpi11/vendor/league/html-to-markdown/src
twig/markdown-extra version  in /var/www/nightly_glpi11/vendor/twig/markdown-extra
webonyx/graphql-php version  in /var/www/nightly_glpi11/vendor/webonyx/graphql-php/src
phpdocumentor/reflection-docblock version  in /var/www/nightly_glpi11/vendor/phpdocumentor/reflection-docblock/src
symfony/property-access version  in /var/www/nightly_glpi11/vendor/symfony/property-access
symfony/serializer version  in /var/www/nightly_glpi11/vendor/symfony/serializer
symfony/property-info version  in /var/www/nightly_glpi11/vendor/symfony/property-info
symfony/error-handler version  in /var/www/nightly_glpi11/vendor/symfony/error-handler</pre>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ccailly**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Should fix #19362 
Improve form migration by handling null values for mapping and updating horizontal rank to match the new sorting system.

### CODE REVIEW

File: src/Glpi/Form/Migration/FormMigration.php [hunk 1]
```diff
@@ -534,13 +535,14 @@ private function processMigrationOfComments(): void
...
+     * Sets horizontal_rank to null for blocks that are contained in a horizontal layout
+     * and have only one element.
      *
      * @return void
      */
-    private function updateBlockHorizontalRank(): void
+    private function removeUselessHorizontalRanks(): void
     {
-        $this->progress_indicator?->setProgressBarMessage(__('Updating horizontal rank...'));
+        $this->progress_indicator?->setProgressBarMessage(__('Removing useless horizontal ranks...'));
```
Comment (AdrienClairembault) [inline src/Glpi/Form/Migration/FormMigration.php:545]: Maybe this message is a bit too technical, I would prefer something generic like "Normalizing layout" (open to better suggestions).

File: src/Glpi/Form/Migration/FormMigration.php [hunk 2]
```diff
@@ -592,6 +594,59 @@ private function updateBlockHorizontalRank(): void
         }
     }
 
+    /**
+     * The new form system no longer allows defining a precise width for a block
+     * The width of each block is now determined by the number of elements contained in the horizontal layout
+     */
+    private function updateHorizontalRanks(): void
+    {
+        $this->progress_indicator?->setProgressBarMessage(__('Updating horizontal ranks...'));
```
Comment (AdrienClairembault) [inline src/Glpi/Form/Migration/FormMigration.php:603]: Same here, I am not sure "horizontal rank" is something that users will understand easily.

File: src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php [hunk 3]
```diff
@@ -147,7 +147,7 @@ public function convertFieldConfig(FormMigration $migration, Form $form, array $
                     specific_question_id: $migration->getMappedItemTarget(
                         'PluginFormcreatorQuestion',
                         $rawData['category_question']
-                    )['items_id'],
+                    )['items_id'] ?? 0
```
Comment (cedric-anne) [inline src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php:150]: It means that the target question does not exists, IMHO, it should trigger an error, not be ignored silently.
The same remark is valid for all other similar occurences.

File: src/Glpi/Form/Migration/FormMigration.php (hunk 1 above)
Comment (cedric-anne) [reply src/Glpi/Form/Migration/FormMigration.php:545]: `Cleaning imported data...`.

File: src/Glpi/Form/Migration/FormMigration.php (hunk 2 above)
Comment (cedric-anne) [reply src/Glpi/Form/Migration/FormMigration.php:603]: `Fixing forms layouts...`

File: src/Glpi/Migration/AbstractPluginMigration.php [hunk 4]
```diff
@@ -59,7 +59,7 @@ abstract class AbstractPluginMigration
     /**
      * Current execution results.
      */
-    protected PluginMigrationResult $result;
+    public PluginMigrationResult $result;
```
Comment (cedric-anne) [inline src/Glpi/Migration/AbstractPluginMigration.php:62]: Please add a `getResult()` method, to prevent anyone to be able to redefine this property with another object.

```suggestion
    protected PluginMigrationResult $result;
```

File: src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php [hunk 5]
```diff
@@ -272,14 +273,22 @@ public function convertFieldConfig(FormMigration $migration, Form $form, array $
...
+
                     return new AssociatedItemsFieldConfig(
                         strategies: [AssociatedItemsFieldStrategy::SPECIFIC_ANSWERS],
-                        specific_question_ids: [
-                            $migration->getMappedItemTarget(
-                                'PluginFormcreatorQuestion',
-                                $rawData['associate_question']
-                            )['items_id']
-                        ],
+                        specific_question_ids: [$mapped_item['items_id'] ?? 0]
```
Comment (cedric-anne) [inline src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php:291]: Does this make sense ? Will this generate issues when the form will be used ?

IMHO, if a reference is broken, we should just not import this destination field config an output a generic error message like `sprintf(__('The "%s" destination field configuration of the form "%s" cannot be imported.'), $configurable_field->getLabel(), $form->getName())` should be logged. This can probably be done with a `try/catch` surrounding the `$configurable_field->convertFieldConfig()` call and an exception thrown when a required value is not found.

File: src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php [hunk 6]
```diff
@@ -45,6 +45,7 @@
 use Glpi\Form\Migration\FormMigration;
 use Glpi\Form\QuestionType\QuestionTypeItem;
 use Glpi\Form\QuestionType\QuestionTypeUserDevice;
+use Glpi\Message\MessageType;
```
Comment (cedric-anne) [inline src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php:48]: This import is now useless here and in all other modified files.

```suggestion
```

**Review by AdrienClairembault — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
