### PR TITLE
Fix unfixed failure paths for image uploads

### LINKED ISSUE #23110: GLPI 10.0.23 – Pasted images in ticket follow-ups are embedded as Base64 instead of saved as attachments
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [ ] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.23

### Bug description

In GLPI 10.0.23, we are still facing an issue similar to #20265 / #22596, even after the fix mentioned by @cedric-anne https://github.com/glpi-project/glpi/issues/20265#issuecomment-3612651219 and @f2cmb https://github.com/glpi-project/glpi/issues/22596#issuecomment-3743605983.

Image

When adding a new ticket follow-up and pasting or inserting an image, the image is not saved as an attachment. Instead, it is embedded directly in the follow-up content as Base64.

As a result:
- Image is not stored as a document/attachment
- Follow-up content becomes very large
- Potential impact on performance, readability, and storage
- Behavior is inconsistent with expected image handling

### Relevant log output

```shell
No relevant errors or warnings were found in logs.
```

### Page URL

_No response_

### Steps To reproduce

1. Open an existing ticket
2. Create a new follow-up
3. Paste an image
4. Add the follow-up

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.23 ( => /usr/share/glpi)
Installation mode: RPM
Current language:pt_BR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux 1bc791932a3c 6.12.0-106.55.4.2.el10uek.x86_64 #​1 SMP PREEMPT_DYNAMIC Fri Dec 19 18:58:06 PST 2025
	x86_64
PHP 8.1.33 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, krb5, ldap, libxml, mbstring,
	msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, selinux, session, shmop, snmp, soap, sockets,
	sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: disable_functions="" max_execution_time="30" max_input_vars="1000" memory_limit="512M" post_max_size="100M"
	session.cookie_secure="0" session.cookie_httponly="1" session.cookie_samesite="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.62 (Oracle Linux Server) OpenSSL/3.5.1 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 35, Revision 20f82371
	Server Version: 8.0.44-35
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpiprod@percona-glpi-metabase/glpiprod
	Host info: percona-glpi-metabase via TCP/IP
	
PHP version (8.1.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.44) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/usr/share/glpi"
GLPI_CONFIG_DIR: "/etc/glpi"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: false
GLPI_VAR_DIR: "/var/lib/glpi/files"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_SYSTEM_CRON: true
GLPI_INSTALL_MODE: "RPM"
GLPI_MARKETPLACE_DIR: "/usr/share/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["~^\n                (http|https|feed)://                                                # protocol\n                (\n                    (?:\n                        (?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                            |\n                        (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain name\n                            |\n                        [a-z0-9\\-\\_]++                                              # a single-level domain name\n                    )\\.?\n                        |                                                           # or\n                    \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}                              # an IP address\n                        |                                                           # or\n                    \\[\n                        (?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n                    \\]                                                              # an IPv6 address\n                )\n                (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n                (?:\\? (?:[\\pL\\pN\\-._\\~!$&'\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n            $~ixuD"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/lib/glpi/files"
GLPI_CACHE_DIR: "/var/lib/glpi/files/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/files/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/files/_inventories"
GLPI_NETWORK_API_URL: "https://services.glpi-network.com/api"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/usr/share/glpi/locales"
GLPI_VERSION: "10.0.23"
GLPI_SCHEMA_VERSION: "10.0.23"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.6.0"
GLPI_YEAR: "2026"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.8.0 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/usr/share/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/usr/share/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/usr/share/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (yourmail@mail.com.br@yourmail.mail.com.br)

</pre></details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alerts                         Version: 1.12.2     State: Enabled                                 
		Install Method: Manual
	fields               Name: Campos adicionais              Version: 1.21.11    State: Enabled                                 
		Install Method: Manual
	screenshot           Name: Captura de tela                Version: 2.0.3      State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.3      State: Enabled                                 
		Install Method: Manual
	customlogin          Name: Custom Login                   Version: 1.0.6      State: Not installed                           
		Install Method: Manual
	archimap             Name: Diagrams                       Version: 3.3.7      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.10    State: Enabled                                 
		Install Method: Manual
	formvalidation       Name: Form Validation                Version: 2.0.1      State: Not installed                           
		Install Method: Manual
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.11.7     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.14.9     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Manual
	holiday              Name: Holidays                       Version: 1.2        State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Importação de dados            Version: 2.14.3     State: Not installed                           
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Not installed                           
		Install Method: Manual
	timelineticket       Name: Linha do tempo dos chamados    Version: 10.0+1.2   State: Enabled                                 
		Install Method: Manual
	singlesignon         Name: Logon Único                    Version: 1.3.3      State: Not installed                           
		Install Method: Manual
	mailanalyzer         Name: Mail Analyzer                  Version: 3.2.1      State: Enabled                                 
		Install Method: Manual
	satisfaction         Name: Mais satisfação                Version: 1.6.2      State: Not installed                           
		Install Method: Manual
	metabase             Name: Metabase                       Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	mfa                  Name: MFA                            Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: To update                               
		Install Method: Manual
	dashboard            Name: Painel                         Version: 1.0.3      State: Not installed                           
		Install Method: Manual
	tasklists            Name: Tasks list                     Version: 2.0.4      State: Enabled                                 
		Install Method: Manual
	ticketanswers        Name: Ticket Answers                 Version: 1.1.0      State: Enabled                                 
		Install Method: Manual
	webhook              Name: Webhooks                       Version: 1.0.18     State: Enabled                                 
		Install Method: Manual

</pre></details><details><summary>Locales overrides</summary><pre></pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #23110 
- Here is a brief description of what this PR does : 

GLPI converts TinyMCE image uploads from a base64 data: URI into a proper Document via an asynchronous upload flow. 

However, PR #22187 only fixed only one of the seven failure paths that could leave raw base64 data stored in the database. This PR addresses the remaining six paths and adds a server-side safety net.

A shared `removeFailedUploadImage` helper centralizes the cleanup logic and is used across all failure paths:                                                                                 
                                                                                                                                                                                              
**1. Fetch failure** : if converting the data: URI to a Blob fails, the base64 image is removed from the editor
**2. Server error in successful response :** if the upload endpoint returns HTTP 200 but with an error in the JSON body (e.g. upload_max_filesize exceeded), the image is removed
**3. Upload HTTP failure** : if the upload endpoint returns a 4xx/5xx, the image is removed
**4. Tag resolution failure :** if the getFileTag.php call fails, the image is removed
**5. Race condition on form submit** : the submit button is now re-enabled only after tag resolution completes, preventing form submission while base64 content is still in the editor
**6. processfail refactoring** : the existing fix from PR #22187 is refactored to use the shared helper instead of duplicated inline code
**7. Server-side safety net** : the HTML sanitizer now restricts media schemes to http and https, stripping any data: URI that reaches the server as a defense-in-depth measure

The existing RichText unit test is updated accordingly, and a new Playwright E2E test validates the full paste-upload-save flow end to end.

### CODE REVIEW

**Comment by f2cmb** [comment]
Some minor observations for future consideration (none are blockers) :

- Silent fetch().catch() (fileupload.js:333): a console.warn would help debugging, like the getFileTag.php error callback does.                                                            
- No unit test for audio/video with data: URI: only  is tested — the sanitizer handles all media elements the same way, but explicit cases would strengthen coverage.                 
- handleUploadedFile Promise never rejects: intentional (submit must always re-enable), but worth noting if other callers are added later.

File: js/common.js [hunk 1]
```diff
@@ -1961,11 +1962,12 @@ function setupFileUpload(config) {
...
-                );
-                // enable submit button after upload
-                $(this).closest('form').find(':submit').prop('disabled', false);
-                // remove required
-                $('#' + field_id).removeAttr('required');
+                ).then(() => {
+                    // enable submit button after upload
+                    form.find(':submit').prop('disabled', false);
+                    // remove required
+                    $('#' + field_id).removeAttr('required');
```
Comment (cconard96) [inline js/common.js]:
```suggestion
                    $(`#${field_id}`).removeAttr('required');
```
eslint rules are a bit inconsistent/broken at the moment but the `prefer-template` rule is supposed to be applied everywhere.

File: src/Glpi/RichText/RichText.php [hunk 2]
```diff
@@ -567,6 +567,7 @@ private static function getHtmlSanitizer(): HtmlSanitizer
             ])
             ->allowRelativeLinks()
             ->allowRelativeMedias()
+            ->allowMediaSchemes(['http', 'https'])
```
Comment (cconard96) [inline src/Glpi/RichText/RichText.php]: How important is this? It seems a little risky to change this in a bugfix version and IMO there is nothing inherently wrong with `data` URIs beyond issues parsing them if they are too long.

**Review by cconard96 — COMMENTED** [review]
I don't know enough about the file upload system so my review is strictly about the code itself.

File: src/Glpi/RichText/RichText.php (hunk 2 above)
Comment (f2cmb) [reply src/Glpi/RichText/RichText.php]: this is a server-side inforcement, maybe that should be considered as optional 

@cedric-anne what do you think ?

Comment (cedric-anne) [reply src/Glpi/RichText/RichText.php]: If you think it is necessary, please do this in another PR.

Comment (f2cmb) [reply src/Glpi/RichText/RichText.php]: Done. Changes on this PR now are only about JS. I'm preparing an additional PR.

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]
