### PR TITLE
Configure database ssl support

### LINKED ISSUE #23754: GLPI 11 Fix CLI database install command to support ssl
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

The bin/console database:install --no-interaction command can initialize GLPI database on deployment script, by pre-staging config/config_db.php file with appropriate contents.

However this works only when MySQL servers are allowing non-SSL connection. In case of strict security requirements of using connection with SSL, this command will result to have connection failure, even though the config_db.php was appropriatelly prepared with parameters of SSL connection.

### Relevant log output

```shell
n/a
```

### Page URL

_No response_

### Steps To reproduce

1. Prepare Mysql database disallow non-SSL connection
2. Prepare config_db.php file with SSL config
3. Execute bin/console db:install --no-interaction
4. Error about db connection failure and db installation cannot be made.

### Your GLPI setup information

N/A
Since the glpi installation is not made for this situation, there are no setup information.
Usage of MySQL database server provided by Cloud service.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by froozeify**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description
Add support for database SSL configuration, initial request was made for docker and was so tested on docker

It fixes #23754

Docker PR : https://github.com/glpi-project/docker-images/pull/292

### CODE REVIEW

**Review by AdrienClairembault — COMMENTED** [review]
I thought SSL was already supported?

https://glpi-install.readthedocs.io/en/latest/install/advanced-configuration.html

**Comment by froozeify** [comment]
Indeed, didn't saw them first when reading from the `bin/console database:install --help` command

**Comment by cedric-anne** [comment]
> Indeed, didn't saw them first when reading from the `bin/console database:install --help` command

This is because there is only a minimal support that requires the database config file to be crafted manually, see #19081.

Being able to define these DB connection params with the configure/install command is an interesting feature. I reopen this PR.

File: src/Glpi/Console/Database/AbstractConfigureCommand.php [hunk 1]
```diff
@@ -150,11 +151,70 @@ protected function configure()
...
 
+        $question_helper = new QuestionHelper();
+
+        // Ask for optional connection options
+        $optional_options = [
+            'db-host' => ['-H', __('Database host:')],
+            'db-port' => ['-P', __('Database port (optional):')],
+        ];
+        foreach ($optional_options as $name => [$short, $label]) {
+            if (!$input->hasParameterOption('--' . $name) && !$input->hasParameterOption($short)) {
```
Comment (cedric-anne) [inline src/Glpi/Console/Database/AbstractConfigureCommand.php]: You can do it like this.

```suggestion
            if (!$input->hasParameterOption(['--' . $name, $short])) {
```

**Review by cedric-anne — APPROVED** [review]

**Review by AdrienClairembault — APPROVED** [review]

**Review by trasher — APPROVED** [review]
