### PR TITLE
fix itemtype param being used for FieldUnicity itemtype field

### LINKED ISSUE #22994: Field Unicity form "Unique fields" defaults to its own fields
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0/bugfixes

### Bug description

In the field unicity form, the default options for the Unique Fields dropdown are the fields for the FieldUnicity datatype. After selecting an itemtype, they are updated properly.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

fixes #22994
Adjustment to change made in #22673 to only add the `itemtype` parameter for devices.

GLPI pushes the options array values into the item's fields array in some cases which causes unwanted behavior. At least if it is limited to devices, any potential damage can be limited.

### CODE REVIEW

**Review by trasher — DISMISSED** [review]

File: src/Glpi/Controller/DropdownFormController.php [hunk 1]
```diff
@@ -209,7 +209,9 @@ public function __invoke(Request $request): Response
         }
         $options['formoptions'] = ($options['formoptions'] ?? '') . ' data-track-changes=true';
         $options['id'] = $id;
-        $options['itemtype'] = $class;
+        if (is_subclass_of($class, CommonDevice::class)) {
+            $options['itemtype'] = $class;
+        }
```
Comment (cedric-anne) [inline src/Glpi/Controller/DropdownFormController.php]: Instead of having a specific behaviour here, I think it would be preferable to override the `displayFullPageForItem()` method in the `CommonDevice` class:
```php
    public static function displayFullPageForItem(
        $id,
        ?array $menus = null,
        array $options = []
    ): void {
        $options['itemtype'] = $class;

        parent::displayFullPageForItem($id, $menus, $options);
    }
```

It permits to keep this generic controller as much as possible, and delegate the specific behaviour to the impacted class itself.

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by trasher — APPROVED** [review]
CS is failing, but fix seems OK to me.

**Comment by cedric-anne** [comment]
> CS is failing, but fix seems OK to me.

Since it is an error inherited from the overriden method PHPDoc, I added it to the baseline. It will be fixed when the inherited method doc will be enhanced.

**Review by cedric-anne — APPROVED** [review]
