### PR TITLE
ini_set restrictions should not be fatal most of the time

### LINKED ISSUE #21357: Fatal error when ini_set is restricted
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0

### Bug description

Exception when trying to import an xml report from the web interface.

### Relevant log output

```shell
[2025-10-08 15:23:29] glpi.CRITICAL: *** Uncaught PHP Exception Error: "Typed property Glpi\Inventory\Request::$inventory must not be accessed before initialization" at Request.php line 577
  Backtrace :
  ./src/Glpi/Inventory/Request.php:577
  ./src/Glpi/Inventory/Conf.php:275 Glpi\Inventory\Request->getInventory()
  ./src/Glpi/Inventory/Conf.php:197 Glpi\Inventory\Conf->importContentFile()
  ./src/Glpi/Controller/InventoryController.php:195 Glpi\Inventory\Conf->importFiles()
  ./vendor/symfony/http-kernel/HttpKernel.php:181 Glpi\Controller\InventoryController->report()
  ./vendor/symfony/http-kernel/HttpKernel.php:76 Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197 Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70 Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

1. Migration from GLPI  10.0.20 with database upgrade
2. Activation of glpiinventory 1.6.0
3. Generate a report from a server Debian 12.0 (bookworm) with GLPI-Agent 1.15-1 (all.deb)
4. Administration -> GLPI Inventory -> Task -> Import File (xml format)

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**
closes #21357

When `ini_set` fails to set a memory limit or a timeout, user will deal with another error if something goes wrong; therefore `ini_set` restrictions should not be fatal.

For now, I've replaced all occurrences but maybe session cookies related ones (at least) should still be fatal unless setting is correctly set in `php.ini`?

### CODE REVIEW

File: src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php [hunk 1]
```diff
@@ -50,7 +51,7 @@ public function process(MiddlewareInput $input, callable $next): void
         }
         // User could be authenticated by a cookie
         // Need to use cookies for session and start it manually
-        ini_set('session.use_cookies', '1');
+        Toolbox::iniSet('session.use_cookies', '1');
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Middleware/CookieAuthMiddleware.php]: This one should not be caught, because the feature cannot work without session cookies. However, it may fail if the value is already enforced to a truthy value in the PHP configuration.

```suggestion
        $use_cookies = filter_var(ini_get('session.use_cookies'), FILTER_VALIDATE_BOOLEAN);
        if ($use_cookies !== true) {
            ini_set('session.use_cookies', '1');
        }
```

**Comment by trasher** [comment]
> What are the conditions where ini_set return false? Is this legitimate?

The problem is we now rely on Safe" lib methods, and an exception is thrown if `ini_set` cannot be called.

File: src/Toolbox.php [hunk 2]
```diff
@@ -3463,4 +3464,25 @@ public static function cleanPaths(string $message): string
...
+        string $loglvl = LogLevel::WARNING
+    ): void
+    {
+        try {
+            ini_set($name, $value);
+        } catch (InfoException $e) {
+            self::log(
+                $loglvl,
+                sprintf(
+                    'Unable to set `%s` to `%s`. You should enforce the value in your PHP configuration. Error is: %s',
```
Comment (cedric-anne) [inline src/Toolbox.php]: In #21236, this message was added as the corresponding ini entries are expected to be always configured the same for the whole GLPI context.

For the current PR, it is different. We do not want people to enforce `memory_limit` to `1024M` or `max_execution_time` to `300`.

```suggestion
                    'Unable to set `%s` to `%s`. This may be caused by a `php_admin_flag` or a `php_admin_value` directive in your web server configuration. Try to use `php_flag` or `php_value` instead. Error is: %s',
```

File: src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php [hunk 3]
```diff
@@ -106,7 +105,7 @@ public function onPostBoot(): void
             if ($this->php_sapi !== 'cli') {
                 // Stateless endpoints will often have to start their own PHP session (based on a token for instance).
                 // Be sure to not use cookies defined in the request or to send a cookie in the response.
-                ini_set('session.use_cookies', 0);
+                Toolbox::iniSet('session.use_cookies', 0);
```
Comment (cedric-anne) [inline src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php]: This one should not be caught. Indeed, having cookies used may prevent stateless endpoints to work as expected or can even result in altering the current session and sometime give access to unexpected data (e.g. the calendar ical export endpoint overrides the session rights to list planning data).

```suggestion
                $use_cookies = filter_var(ini_get('session.use_cookies'), FILTER_VALIDATE_BOOLEAN);
                if ($use_cookies !== false) {
                    ini_set('session.use_cookies', '0');
                }
```

File: src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php [hunk 4]
```diff
@@ -44,8 +44,7 @@
 use Symfony\Component\DependencyInjection\Attribute\Autowire;
 use Symfony\Component\EventDispatcher\EventSubscriberInterface;
 use Symfony\Component\HttpFoundation\Request;
-
-use function Safe\ini_set;
+use Toolbox;
```
Comment (cedric-anne) [inline src/Glpi/Kernel/Listener/PostBootListener/SessionStart.php]: Related to the other comment.

```suggestion

use function Safe\ini_set;
```

**Comment by trasher** [comment]
Renamed to `Toolbox::safeIniSet()`
