### PR TITLE
Fix race condition in Entity ID generation

### LINKED ISSUE #22625: Handle ID conflicts for entities.
The entity class do not use the auto increment feature and instead manually compute the next id.

This can lead to concurrent INSERT requests picking the same id and thus failing the primary key constraint.

### PR DESCRIPTION
**Pull request by f2cmb**
Fixes #22625 

- Remove manual `MAX(id)+1` calculation in `Entity::prepareInputForAdd()`
- Rely on MySQL AUTO_INCREMENT for ID generation
- Prevents duplicate ID errors when creating entities concurrently

Tested manually, w/ a script to simulate same-time entities creation, unit tests also provided.

### CODE REVIEW

**Comment by f2cmb** [comment]
Investigating why unit tests are failing on CI..

**Review by AdrienClairembault — COMMENTED** [review]
It looks good, I just have a general question:

Do we always want to enable `NO_AUTO_VALUE_ON_ZERO` or should it be done only when creating the root entity in the install?

Limiting it to the install script would require a bit more code but could be safer in a bugfix release (while unlikely, a global change could in theory impact plugins if they relied on a 0 value being auto incremented).

@cedric-anne @trasher?

**Comment by trasher** [comment]
> Do we always want to enable `NO_AUTO_VALUE_ON_ZERO` or should it be done only when creating the root entity in the install?

If possible, it would probably be better to avoid changing that every time, yes.

**Comment by f2cmb** [comment]
NO_AUTO_VALUE_ON_ZERO applied only on install time, instead of globally on all DB

**Comment by trasher** [comment]
Tests are failing

**Comment by trasher** [comment]
I've re-run failing tests; there is something wrong in this PR (no idea what after a quick review).

**Comment by f2cmb** [comment]
> I've re-run failing tests; there is something wrong in this PR (no idea what after a quick review).

Still investigating on it ;)

File: src/Update.php [hunk 1]
```diff
@@ -225,6 +225,10 @@ public function doUpdates(
             $DB->doQuery(sprintf('SET SESSION sql_mode = %s', $DB->quote(implode(',', $sql_mode_flags))));
         }
 
+        // Add NO_AUTO_VALUE_ON_ZERO to allow operations on entities with id=0 (root entity)
+        // This is required because glpi_entities uses id=0 for the root entity
+        $DB->doQuery("SET SESSION sql_mode = CONCAT(@@sql_mode, ',NO_AUTO_VALUE_ON_ZERO')");
```
Comment (trasher) [inline src/Update.php]: It should maybe moved to `install/migrations/update_11.0.3_to_11.0.5/entities.php`

File: tests/functional/EntityTest.php [hunk 2]
```diff
@@ -165,6 +165,46 @@ public function testPrepareInputForAdd()
...
+    {
+        $this->login();
+        $entity = new Entity();
+
+        $prepared = $entity->prepareInputForAdd([
+            'name' => 'Test Entity No Manual ID',
+            'entities_id' => 0,
+        ]);
+
+        $this->assertArrayNotHasKey('id', $prepared);
```
Comment (trasher) [inline tests/functional/EntityTest.php]: I'm not sure this is really usefull

File: tests/functional/EntityTest.php [hunk 3]
```diff
@@ -165,6 +165,46 @@ public function testPrepareInputForAdd()
...
+                'entities_id' => 0,
+            ]);
+            $ids[] = $entity->getID();
+        }
+
+        $this->assertCount(5, array_unique($ids));
+
+        for ($i = 1; $i < count($ids); $i++) {
+            $this->assertGreaterThan($ids[$i - 1], $ids[$i]);
+        }
```
Comment (trasher) [inline tests/functional/EntityTest.php]: Probably not needed to work with 2 iterations. Asserting count is useless.
```suggestion
        $id = 0;
        for ($i = 1; $i <= 5; $i++) {
            $entity = $this->createItem(Entity::class, [
                'name' => "Test Entity AutoIncrement $i",
                'entities_id' => 0,
            ]);
            $this->assertGreaterThan($id, $entity->getID());
            $id = $entity->getID();
        }
```

**Review by trasher — APPROVED** [review]
LGTM.

**Comment by trasher** [comment]
It's not needed to add "WIP" in PR titles, just use draft state.

**Review by cedric-anne — APPROVED** [review]
