### PR TITLE
Fix warning on delegation form rendering

### LINKED ISSUE #20551: Array to string conversion error on simplified interface
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.18

### Bug description

On simplified interface for Self-Service user i got 500 error when changing type of request or category. 
It happened since i add mail notifications. To fix this i change line 362 in glpi\vendor\twig\twig\src\Template.php 
The original line is : $data = ob_get_clean() . $data; 
If $data is an array PHP will throw an error, so to fix this i changed line by : 
$data = ob_get_clean() . (is_array($data) ? json_encode($data) : $data);
Now if $data is an array it will be encode as json. This fix seems to work well.
More details on my forum post : https://forum.glpi-project.org/viewtopic.php?id=291980

### Relevant log output

```shell
[2025-08-04 16:48:55] glpiphplog.WARNING:   *** PHP Warning (2): Array to string conversion in C:\GLPI\glpi\vendor\twig\twig\src\Template.php at line 362
  Backtrace :
  vendor\twig\twig\src\Template.php:327              Twig\Template->yield()
  vendor\twig\twig\src\TemplateWrapper.php:45        Twig\Template->display()
  src\Application\View\TemplateRenderer.php:184      Twig\TemplateWrapper->display()
  src\Ticket.php:4063                                Glpi\Application\View\TemplateRenderer->display()
  front\tracking.injector.php:114                    Ticket->showFormHelpdesk()
  public\index.php:82                                require()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

GLPI 10.0.18 ( => C:\GLPI\glpi)
Installation mode: GIT
Current language:fr_FR

Operating system: Windows NT SRV-GLPI2 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.3.23 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mysqli, mysqlnd, openssl, pcre, random, readline,
	session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="6M" disable_functions="" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 11.8.2-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiuser@localhost/glpidb
	Host info: localhost via TCP/IP

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

When loading the self service form there are two errors related to delegation:

image

These change fix the first error by correcting `Ticket::getDefaultValues()` which wrap some values in an array when it shouldn't (the `Change` and `Problem` methods already have the correct format).

I'll look into the second error in another PR, it seems linked to the recent security fix as the email dropdown refuse to load.

## References

Fix #20551.

### CODE REVIEW

**Comment by trasher** [comment]
Please rebase to fix conflicts

**Comment by AdrienClairembault** [comment]
> Please rebase to fix conflicts

My bad, It's been a while since I worked on the 10.0 branch, forgot to target it in the PR settings :)

File: src/Ticket.php [hunk 1]
```diff
@@ -4146,25 +4146,25 @@ public static function getDefaultValues($entity = 0)
 
         // Set default values...
         return  ['_users_id_requester'       => $users_id_requester,
-            '_users_id_requester_notif' => ['use_notification'  => [$default_use_notif],
+            '_users_id_requester_notif' => ['use_notification'  => $default_use_notif,
```
Comment (cedric-anne) [inline src/Ticket.php]: This format was correct (even if it does not seems relevant) and is supported elsewhere in the code. I think it is preferable to fix the location where it is not supported rather than changing this. Indeed, it may have unexpected side effects.

See the `TicketTest::addActorsProvider()` for all expected formats.

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/Ticket.php (hunk 1 above)
Comment (AdrienClairembault) [reply src/Ticket.php]: I'll look into it but it isn't ideal because Change and Problem do not use the array format in their default values.
