### PR TITLE
Fix table border attribute removal

### LINKED ISSUE #21489: Table borders in knowledge base articles no longer appear
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

I migrated from GLPI 10.0.20 to GLPI 11.0.0 and then 11.0.1.
I have many articles in my knowledge base with tables inside.
But since the migration, the table rows no longer appear; they're like invisible.

Image

The view when editing and before migration :

Image

When I go back to the table properties and specify a border style, the table rows reappear, but since I have more than 500 articles affected, I can't manually change each one.
Furthermore, when you create a new table, it also automatically hides the borders. You have to specify a border style for them to display.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create an article in the knowledge base
2. Add a table
3. Save, table rows do not appear 

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.1 ( =&gt; /opt/glpi/instance1/versions/11.0.1)
Installation mode: TARBALL
Current language: fr_FR
Source Integrity: 1 files changed
  M: css/glpi.scss</pre></details><details><summary>Server</summary><pre>Operating system: Linux serveur330 6.1.0-40-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.153-1 (2025-09-20) x86_64

PHP: 8.3.26 fpm-fcgi

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
cgi-fcgi, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, intl,
ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer,
xmlreader, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;128M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;1&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache/2.4.65 (Debian) (Apache/2.4.65 (Debian) Server at glpi.chiab.fr Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
Edg/140.0.0.0

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 12.0.2-MariaDB-deb12
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@localhost/glpi10010
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.3.26) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (12.0.2) is supported.
The log file has been created successfully.
Write access to /opt/glpi/instance1/files/_cache has been
validated.
Write access to /opt/glpi/instance1/files/_cron has been validated.
Write access to /opt/glpi/instance1/files has been validated.
Write access to /opt/glpi/instance1/files/_graphs has been validated.
Write access to /opt/glpi/instance1/files/_lock has been validated.
Write access to /opt/glpi/instance1/files/_pictures has been validated.
Write access to /opt/glpi/instance1/files/_plugins has been validated.
Write access to /opt/glpi/instance1/files/_rss has been validated.
Write access to /opt/glpi/instance1/files/_sessions has been validated.
Write access to /opt/glpi/instance1/files/_tmp has been validated.
Write access to /opt/glpi/instance1/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write
access to /opt/glpi/instance1/versions/11.0.1/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/opt/glpi/instance1/versions/11.0.1&quot;
GLPI_VERSION: &quot;11.0.1&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.1@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.1-3a9929cf&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/opt/glpi/instance1/versions/11.0.1/locales&quot;
GLPI_CONFIG_DIR: &quot;/opt/glpi/instance1/config/&quot;
GLPI_VAR_DIR: &quot;/opt/glpi/instance1/files&quot;
GLPI_DOC_DIR: &quot;/opt/glpi/instance1/files&quot;
GLPI_CRON_DIR: &quot;/opt/glpi/instance1/files/_cron&quot;
GLPI_DUMP_DIR: &quot;/opt/glpi/instance1/files/_dumps&quot;
GLPI_GRAPH_DIR: &quot;/opt/glpi/instance1/files/_graphs&quot;
GLPI_LOCK_DIR: &quot;/opt/glpi/instance1/files/_lock&quot;
GLPI_PICTURE_DIR: &quot;/opt/glpi/instance1/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/opt/glpi/instance1/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/opt/glpi/instance1/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/opt/glpi/instance1/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/opt/glpi/instance1/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/opt/glpi/instance1/files/_uploads&quot;
GLPI_CACHE_DIR: &quot;/opt/glpi/instance1/files/_cache&quot;
GLPI_LOG_DIR: &quot;/var/log/glpi&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_MARKETPLACE_DIR: &quot;/opt/glpi/instance1/versions/11.0.1/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_LOCAL_I18N_DIR: &quot;/opt/glpi/instance1/files/_locales&quot;
GLPI_INVENTORY_DIR: &quot;/opt/glpi/instance1/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/opt/glpi/instance1/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES:
[&quot;/opt/glpi/instance1/versions/11.0.1/marketplace&quot;,&quot;/opt/glpi/instance1/versions/11.0.1/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>Annuaires LDAP</summary><pre>Server: &#39;10.40.0.130&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;DC=chiab,DC=fr&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;glpi&#39;, 
	Use TLS: none

Server: &#39;10.40.0.131&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;DC=chiab,DC=fr&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;glpi&#39;, 
	Use TLS: none</pre></details><details><summary>Réplicats SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://10.40.0.102:25?verify_peer=0)</pre></details><details><summary>Plugins list</summary><pre>accounts             Name: Accounts                       Version: 3.1.1      State: Activé                                 
Install Method: Marketplace
datainjection        Name: Data injection                 Version: 2.15.0     State: Activé                                 
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.0      State: Activé                                 
Install Method: Marketplace</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
## Description

- It fixes #21489

The `border` attribute on `<table>`, `<td>`, and `<th>` elements was being removed by `HtmlSanitizer` 
because it's marked as non-safe (`false`) in Symfony's `W3CReference::ATTRIBUTES` [1]. While this attribute 
is deprecated in HTML5 in favor of CSS, it poses no XSS security risk and is commonly preserved by other 
sanitizers [2]. This fix explicitly allows the `border` attribute, similar to how `class` and `style` 
(also marked non-safe) are already allowed in GLPI's configuration [3].

[1] https://github.com/symfony/html-sanitizer/blob/6.4/Reference/W3CReference.php#L213
[2] https://github.com/mganss/HtmlSanitizer (allows border, bgcolor, cellpadding, etc.)
[3] src/Glpi/RichText/RichText.php:604-605

Chrome screenshot (tables were not shown in this browser, but ok in Mozilla)
image

### CODE REVIEW

File: src/Glpi/RichText/RichText.php [hunk 1]
```diff
@@ -603,6 +603,9 @@ private static function getHtmlSanitizer(): HtmlSanitizer
         // Allow class and style attribute
         $config = $config->allowAttribute('class', '*');
         $config = $config->allowAttribute('style', '*');
+        // Allow border attribute for table tags
+        $config = $config->allowAttribute('border', ['table', 'td', 'th']);
```
Comment (cedric-anne) [inline src/Glpi/RichText/RichText.php]: 1. We could also add the `bgcolor` support.
2. `border` is only valid for `<table>` elements.

See https://www.w3.org/TR/xhtml1/dtds.html and https://www.w3.org/TR/html401/sgml/dtd.html for attributes reference.

```suggestion
        // Allow layout attribute for table tags
        $config = $config->allowAttribute('bgcolor', ['table', 'tr', 'th', 'td']);
        $config = $config->allowAttribute('border', ['table']);
```

**Comment by f2cmb** [comment]
Support for more attributes added
image

File: src/Glpi/RichText/RichText.php [hunk 2]
```diff
@@ -603,6 +603,10 @@ private static function getHtmlSanitizer(): HtmlSanitizer
         // Allow class and style attribute
         $config = $config->allowAttribute('class', '*');
         $config = $config->allowAttribute('style', '*');
+        // Allow border attribute for table tags
```
Comment (cedric-anne) [inline src/Glpi/RichText/RichText.php]:
```suggestion
        // Allow layout attribute for table tags
```
