### PR TITLE
Handle upload of large files

### LINKED ISSUE #8176: GLPI does not shown an error message when upload fails (POST_MAX_SIZE PHP directive)
**Describe the bug**

GLPI doesn't show an error message when upload fails when ''POST_MAX_SIZE'' PHP directive size is lower than the uploaded document. E.g. Trying to upload a 42 MB ''mpg'' file with the following directive:

```
upload_max_filesize = 150M ;
```

post_max_size_unset

The upload will fail because the default post_max_size value is ''8 M'' (notice that the file isn't uploaded, the upload field is just empty).

Changing the ''php.ini'' file to the following:

```
upload_max_filesize = 150M ;
post_max_size = 150M ;
```

The upload works nicely:

post_max_size_set

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

- https://glpi.example.com/front/document.form.php
- https://glpi.example.com/front/ticket.form.php

**To reproduce**

1. Go to 'Assistance > Create Ticket'
2. Fill the required fields and create the ticket.
3. Go to 'Assistance > Tickets'
4. Click into the name of the ticket created early
5. In 'Processing Tickets' section, click on 'Document'
6. Click on 'Choose file' to upload a new document
4. No error is shown

The same happens when trying to upload a new document through ''Documents'' or when creating a ticket (through 'Files' section of ticket creation).

**Expected behavior**

GLPI should detect when ``post_max_size`` and ``upload_max_filesize`` is lower than the selected file and show a friendly message, like ''Filesize not allowed'', so users could search into the Internet or the GLPI forums for the message and find a solution for this issue.

**Logs**

No errors is thrown at ``glpi/files/_log/`` log files, only into ``error.log`` PHP error log: 

```
[Tue Oct 27 08:08:34.893825 2020] [proxy_fcgi:error] [pid 2112549] [client 192.168.0.22:58457] AH01071: Got error 'PHP message: PHP Warning:  POST Content-Length of 44353961 bytes exceeds the limit of 8388608 bytes in Unknown on line 0\nPHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/clients/client0/web1/web/inc/glpiuploadhandler.class.php on line 134\n', referer: https://glpi.example.com/front/document.form.php?id=105
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
[code]   GLPI 9.5.2 ( => /var/www/clients/client0/web1/web) Installation mode: TARBALL
--

Operating system: Linux ispconfig.example.com 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 PHP 7.2.34 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, 	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sodium, sqlite3, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.3.17-MariaDB 	Server SQL Mode:  	Parameters: c0glpiuser@localhost/c0glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.17) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/clients/client0/web1/web/config has been validated. Write access to /var/www/clients/client0/web1/web/files has been validated. Write access to /var/www/clients/client0/web1/web/files/_dumps has been validated. Write access to /var/www/clients/client0/web1/web/files/_sessions has been validated. Write access to /var/www/clients/client0/web1/web/files/_cron has been validated. Write access to /var/www/clients/client0/web1/web/files/_graphs has been validated. Write access to /var/www/clients/client0/web1/web/files/_lock has been validated. Write access to /var/www/clients/client0/web1/web/files/_plugins has been validated. Write access to /var/www/clients/client0/web1/web/files/_tmp has been validated. Write access to /var/www/clients/client0/web1/web/files/_cache has been validated. Write access to /var/www/clients/client0/web1/web/files/_rss has been validated. Write access to /var/www/clients/client0/web1/web/files/_uploads has been validated. Write access to /var/www/clients/client0/web1/web/files/_pictures has been validated. Write access to /var/www/clients/client0/web1/web/marketplace has been validated. Web access to files directory is protected For security reasons, SELinux mode should be Enforcing.

GLPI_ROOT: /var/www/clients/client0/web1/web GLPI_CONFIG_DIR: /var/www/clients/client0/web1/web/config GLPI_VAR_DIR: /var/www/clients/client0/web1/web/files GLPI_MARKETPLACE_DIR: /var/www/clients/client0/web1/web/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/clients/client0/web1/web/files GLPI_CACHE_DIR: /var/www/clients/client0/web1/web/files/_cache GLPI_CRON_DIR: /var/www/clients/client0/web1/web/files/_cron GLPI_DUMP_DIR: /var/www/clients/client0/web1/web/files/_dumps GLPI_GRAPH_DIR: /var/www/clients/client0/web1/web/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/clients/client0/web1/web/files/_locales GLPI_LOCK_DIR: /var/www/clients/client0/web1/web/files/_lock GLPI_LOG_DIR: /var/www/clients/client0/web1/web/files/_log GLPI_PICTURE_DIR: /var/www/clients/client0/web1/web/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/clients/client0/web1/web/files/_plugins GLPI_RSS_DIR: /var/www/clients/client0/web1/web/files/_rss GLPI_SESSION_DIR: /var/www/clients/client0/web1/web/files/_sessions GLPI_TMP_DIR: /var/www/clients/client0/web1/web/files/_tmp GLPI_UPLOAD_DIR: /var/www/clients/client0/web1/web/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/clients/client0/web1/web/locales GLPI_VERSION: 9.5.2 GLPI_SCHEMA_VERSION: 9.5.2 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/clients/client0/web1/web/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/clients/client0/web1/web/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.5 in (/var/www/clients/client0/web1/web/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/clients/client0/web1/web/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/clients/client0/web1/web/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/clients/client0/web1/web/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/clients/client0/web1/web/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/clients/client0/web1/web/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/clients/client0/web1/web/vendor/sabre/http/lib) sabre/uri in (/var/www/clients/client0/web1/web/vendor/sabre/uri/lib) sabre/vobject in (/var/www/clients/client0/web1/web/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/clients/client0/web1/web/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/clients/client0/web1/web/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/clients/client0/web1/web/vendor/elvanto/litemoji/src) symfony/console in (/var/www/clients/client0/web1/web/vendor/symfony/console) scssphp/scssphp in (/var/www/clients/client0/web1/web/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/clients/client0/web1/web/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/clients/client0/web1/web/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/clients/client0/web1/web/vendor/ramsey/uuid/src) psr/log in (/var/www/clients/client0/web1/web/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/clients/client0/web1/web/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/clients/client0/web1/web/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/clients/client0/web1/web/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/clients/client0/web1/web/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/clients/client0/web1/web/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/clients/client0/web1/web/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/pear)

Server: 'ldaps://example.com', Port: '389', BaseDN: 'OU=Example,DC=example,DC=com', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(memberOf=CN=Contas de Serviço - 		Negar Logon Interativo,OU=Serviços,OU=TI,OU=São 		Leopoldo,OU=Example,DC=Example,DC=com,DC=br))(!(sAMAccountName=fabrica))(!(sAMAccountName=cq))(!(sAMAccountName=manutencao)))', 		RootDN: 'glpiaduser@example.com', Use TLS: none

Not active

Way of sending emails: PHP

Name: 'glpi@example.com' Active: Yes 	Server: '{smtp.kinghost.net:110/pop}' Login: 'glpi@example.com' Password: Yes

behaviors            Name: Comportamentos                 Version: 2.4.1      State: Enabled 	accounts             Name: Contas                         Version: 2.6.0      State: Enabled 	genericobject        Name: Gerenciamento de objetos       Version: 2.9.0      State: Enabled 	pdf                  Name: Imprimir em PDF                Version: 1.7.0      State: Enabled
[/code]
```

**Additional context**

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #8176 

While searching how to fix #8176 , I noticed multiple things:
1. `maxChunkSize` option can be used to split upload on multiple request when using `fileupload` jQuery plugin.
2. Uploading from file input was using `fileupload` jQuery plugin capabilities, but uploading from image pasting into rich text editor was not.
3. Upload using `drop` event was configured to be handled by `fileupload` jQuery plugin but was also manually handled.

So, after some iterations, I finally mutualize code and use `fileupload` jQuery plugin for all uploads, which permits to upload large files chunks by chunks.

~~In the end, there is no more limitation on uploaded files size.
I think administrators may want to keep a limit, so, if everyone is OK with that, I will put back a limitation that could be set in GLPI configuration (set by default to `upload_max_filesize` PHP configuration).~~

In the end, I added a limitation that can be configured, and added a browser side validation of file size and type.

### CODE REVIEW

File: install/empty_data.php [hunk 1]
```diff
@@ -305,7 +305,8 @@
    'default_dashboard_mini_ticket'           => 'mini_tickets',
    'admin_email_noreply'                     => '',
    'admin_email_noreply_name'                => '',
-   Impact::CONF_ENABLED                      => exportArrayToDB(Impact::getDefaultItemtypes())
+   Impact::CONF_ENABLED                      => exportArrayToDB(Impact::getDefaultItemtypes()),
+   'document_max_size'                       => '1',
```
Comment (trasher) [inline install/empty_data.php:309]:
```suggestion
   'document_max_size'                       => Toolbox::return_bytes_from_ini_vars(ini_get('upload_max_filesize')),
```
same as in update script

File: inc/documenttype.class.php [hunk 2]
```diff
@@ -183,4 +183,36 @@ static function showAvailableTypesLink($options = []) {
          return $display;
       }
    }
+
+   /**
+    * Return pattern that can be used to validate that name of an uploaded file matches accepted extensions.
+    *
+    * @return string
+    */
+   public static function getUploadableFilePattern(): string {
```
Comment (trasher) [inline inc/documenttype.class.php:192]: should be tested

File: inc/toolbox.class.php [hunk 3]
```diff
@@ -1741,6 +1741,19 @@ static function return_bytes_from_ini_vars($val) {
       return $val;
    }
 
+
+   /**
+    * Get max upload size from php config.
+    *
+    * @return int
+    */
+   static function getPhpUploadSizeLimit(): int {
```
Comment (trasher) [inline inc/toolbox.class.php:1750]: maybe add a unit test on that one too

**Review by trasher — CHANGES_REQUESTED** [review]

File: install/empty_data.php [hunk 4]
```diff
@@ -305,7 +305,8 @@
    'default_dashboard_mini_ticket'           => 'mini_tickets',
    'admin_email_noreply'                     => '',
    'admin_email_noreply_name'                => '',
-   Impact::CONF_ENABLED                      => exportArrayToDB(Impact::getDefaultItemtypes())
+   Impact::CONF_ENABLED                      => exportArrayToDB(Impact::getDefaultItemtypes()),
+   'document_max_size'                       => Toolbox::return_bytes_from_ini_vars(ini_get('upload_max_filesize')),
```
Comment (cedric-anne) [inline install/empty_data.php:309]:
```suggestion
   'document_max_size'                       => max(1, floor(Toolbox::return_bytes_from_ini_vars(ini_get('upload_max_filesize') / 1024 / 1024)),
```

File: inc/toolbox.class.php (hunk 3 above)
Comment (cedric-anne) [reply inc/toolbox.class.php:1750]: I did not find a solution for this.

I have to mock the `ini_get` function, but I have this error `Error: The function you are trying to mock already exists: 'ini_get'. This may be because you are trying to mock a function from a class in the root namespace.`.

If I try to change the put my test in a sub namespace, I have this error `Tested class 'Glpi\Toolbox' does not exist for test class 'tests\units\Glpi\Toolbox'`.

File: inc/documenttype.class.php (hunk 2 above)
Comment (cedric-anne) [reply inc/documenttype.class.php:192]: done

**Review by trasher — COMMENTED** [review]
Looks good to me from the code point of view; not tested yet

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]
