### PR TITLE
Fix duplicate ProjectTask_Ticket link and Dropdown used filter

### LINKED ISSUE #22042: Project tasks can be linked twice to ticket, leading to an error
Image

Image

```
MySQL query error: Duplicate entry '1-1' for key 'unicity' (1062) in SQL query "INSERT INTO `glpi_projecttasks_tickets` (`projecttasks_id`, `tickets_id`) VALUES ('1', '1')".
In ./src/DBmysql.php(371)
#0 ./src/DBmysql.php(1327): DBmysql->doQuery('INSERT INTO `gl...')
#1 ./src/CommonDBTM.php(781): DBmysql->insert('glpi_projecttas...', Array)
#2 ./src/CommonDBTM.php(1386): CommonDBTM->addToDB()
#3 ./front/projecttask_ticket.form.php(50): CommonDBTM->add(Array)
#4 ./src/Glpi/Controller/LegacyFileLoadController.php(64): require('./f...')
#5 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\LegacyFileLoadController->__invoke(Object(Symfony\Component\HttpFoundation\Request))
#6 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 {main}
```

### PR DESCRIPTION
**Pull request by f2cmb**
## Description

- It fixes #22042
- Here is a brief description of what this PR does : 

- check if a an ticket is not linked twice to a task
- avoid dropdown value to get crushed

### CODE REVIEW

File: src/Dropdown.php [hunk 1]
```diff
@@ -2990,7 +2990,11 @@ public static function getDropdownValue($post, $json = true)
                         // Ensure condition contains table name to prevent ambiguity with fields from `glpi_entities` table
                         $where["$table.$key"] = $value;
                     } else {
-                        $where[$key] = $value;
+                        if ($key === 'NOT' && isset($where['NOT'])) {
```
Comment (trasher) [inline src/Dropdown.php]: I guess the fix is incomplete. Issue will be the same with key different than `NOT`. Also, I'm not entirely sure we should reach this case here.

File: src/ProjectTask_Ticket.php [hunk 2]
```diff
@@ -59,6 +59,23 @@ public function getForbiddenStandardMassiveAction()
...
+        if (
+            countElementsInTable(
+                static::getTable(),
+                [
+                    static::$items_id_1 => $input[static::$items_id_1] ?? 0,
+                    static::$items_id_2 => $input[static::$items_id_2] ?? 0,
+                ]
+            ) > 0
+        ) {
+            return false;
```
Comment (trasher) [inline src/ProjectTask_Ticket.php:74]: Not sure this should be handled here, and it should not be a silent issue, anyway.

Comment (f2cmb) [reply src/ProjectTask_Ticket.php:74]: I saw this there : https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/CommonItilObject_Item.php#L128-L145 but i agree, maybe there is another way although this fix the original issue / error.

File: src/Dropdown.php (hunk 1 above)
Comment (f2cmb) [reply src/Dropdown.php]: Could be optional with `ProjectTask_Ticket::prepareInputForAdd()` 

But this aspect was mentioned in the original issue so seems logical to fix additonnally her after having the tests written. I'm open to any suggestions :)

File: src/Dropdown.php [hunk 3]
```diff
@@ -2990,7 +2990,11 @@ public static function getDropdownValue($post, $json = true)
...
+                            $where[] = ['NOT' => $value];
+                        } else {
+                            $where[$key] = $value;
+                        }
```
Comment (trasher) [inline src/Dropdown.php]: Maybe a better way would be to do that:
```suggestion
                        if (isset($where[$key])) {
                            $where[] = [$key => $value];
                        } else {
                            $where[$key] = $value;
                        }
```

File: src/ProjectTask_Ticket.php (hunk 2 above)
Comment (trasher) [reply src/ProjectTask_Ticket.php:74]: OK, I do not have any proposal. Maybe add an extra TODO/FIXME (also in original) so we know something have to be fixed?
Current file has a low impact, it would be OK.

File: tests/functional/ProjectTask_TicketTest.php [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <https://www.gnu.org/licenses/>.
+ *
+ * ---------------------------------------------------------------------
+ */
+
+namespace tests\units;
+
+use DbTestCase;
```
Comment (trasher) [inline tests/functional/ProjectTask_TicketTest.php]:
```suggestion
use Glpi\Tests\DbTestCase;
```

File: src/ProjectTask_Ticket.php (hunk 2 above)
Comment (trasher) [reply src/ProjectTask_Ticket.php:74]:
```suggestion
            //FIXME: check should probably be done at higher level to prevent this case. Also @see CommonItilObject_Item::prepareInputForAdd()
            return false;
```

File: src/Dropdown.php [hunk 5]
```diff
@@ -2990,7 +2990,11 @@ public static function getDropdownValue($post, $json = true)
                         // Ensure condition contains table name to prevent ambiguity with fields from `glpi_entities` table
                         $where["$table.$key"] = $value;
```
Comment (cedric-anne) [inline src/Dropdown.php]: This case should also be fixed.

```suggestion
                        $where[] = ["$table.$key" => $value];
```

File: src/Dropdown.php [hunk 6]
```diff
@@ -2990,7 +2990,11 @@ public static function getDropdownValue($post, $json = true)
...
                     } else {
-                        $where[$key] = $value;
+                        if (isset($where[$key])) {
+                            $where[] = [$key => $value];
+                        } else {
+                            $where[$key] = $value;
+                        }
```
Comment (cedric-anne) [inline src/Dropdown.php]: I guess it could be simplified.

```suggestion
                        $where[] = [$key => $value];
```

File: src/ProjectTask_Ticket.php (hunk 2 above)
Comment (cedric-anne) [inline src/ProjectTask_Ticket.php:74]: Please add a message, to ease the debugging.

```suggestion
            Session::addMessageAfterRedirect(__s('Relation already exists.'), false, ERROR);
            return false;
```

File: src/Dropdown.php (hunk 5 above)
Comment (trasher) [reply src/Dropdown.php]: Indeed, it can also cause issues.

File: tests/functional/ProjectTask_TicketTest.php [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
```
Comment (cedric-anne) [inline tests/functional/ProjectTask_TicketTest.php]:
```suggestion
use Glpi\Tests\DbTestCase;
```

**Comment by developer-labs-lcc** [comment]
Before this fix it was possible to override the default values for **is_deleted** and **is_template**. 

Old code:

```
if ($item->maybeDeleted()) {
    $where["$table.is_deleted"] = 0;
}
if ($item->maybeTemplate()) {
    $where["$table.is_template"] = 0;
}
...
$where[$key] = $value;
```

And with an array you could simply override this values:

```
$condition = [
    $table . '.contracts_id' => 0,
    $table . '.is_deleted'   => $deleted,
    $table . '.is_template'  => $template
];

\Dropdown::show($itemType,
    [
        'name'        => 'myname',
        'value'       => 'myvalue',
        'emptylabel'  => 'myemptylabel',
        'condition'   => $condition,
        'width'       => '100%'
    ]
);

```
New code:

```
if ($item->maybeDeleted()) {
    $where["$table.is_deleted"] = 0;
}
if ($item->maybeTemplate()) {
    $where["$table.is_template"] = 0;
}
```

This should be changed to be compatible with the new structure, I guess:

```
if ($item->maybeDeleted()) {
    $where[] = ["$table.is_deleted" => 0];
}
if ($item->maybeTemplate()) {
    $where[] = ["$table.is_template" => 0];
}
```

And with

`$where[] = [$key => $value];`

everything will only be added and there is no possibility to override **is_deleted** and **is_template** anymore.

Now with the new version any Dropdown will be forced to display only non deleted items and no templates. But our plugin needs Dropdowns which can display templates too.

**Comment by cedric-anne** [comment]
> Before this fix it was possible to override the default values for **is_deleted** and **is_template**.

@developer-labs-lcc Could you check the fix proposed in #22772 ?

**Comment by developer-labs-lcc** [comment]
Yes, it is working, thanks.
