### PR TITLE
Fix LDAP import and sync failures when only one directory is active

### LINKED ISSUE #22452: LDAP CLI synchronization fails with "Undefined array key" (basedn, login_field)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

**Describe the bug**
After upgrading to the latest version, the LDAP user synchronization via UI (`https://GLPI_URL/front/ldap.import.php`) fails. The script throws PHP Warnings about undefined array keys for critical LDAP configurations (`basedn`, `login_field`, `condition`), causing the synchronization to abort or fail to find users.

It seems related to recent changes in `src/AuthLDAP.php` where direct access to `$authldap->fields[...]` is used instead of the getter methods. In the CLI context, the `$fields` array appears to be incomplete or not fully hydrated when these lines are executed.

**To reproduce**
1. Setup a valid LDAP directory.
2. Run the synchronization command via CLI:
   `php bin/console glpi:ldap:synchronize_users 1 --allow-superuser`
3. See the error in the console output.

**Expected behavior**
The synchronization should read the LDAP configuration from the database and sync users without PHP warnings, as it did in previous versions.

### Relevant log output

```shell
glpi.WARNING:   *** Warning: Undefined array key "basedn" at AuthLDAP.php line 3673
  Backtrace :
  ./src/AuthLDAP.php:3673                            
  ./front/ldap.import.php:40                         AuthLDAP::manageRequestValues()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()

glpi.WARNING:   *** Warning: Undefined array key "login_field" at AuthLDAP.php line 3819
  Backtrace :
  ./src/AuthLDAP.php:3819                            
  ./src/AuthLDAP.php:3698                            AuthLDAP::buildLdapFilter()
  ./front/ldap.import.php:40                         AuthLDAP::manageRequestValues()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()

glpi.WARNING:   *** Warning: Undefined array key "condition" at AuthLDAP.php line 3830
  Backtrace :
  ./src/AuthLDAP.php:3830                            
  ./src/AuthLDAP.php:3698                            AuthLDAP::buildLdapFilter()
  ./front/ldap.import.php:40                         AuthLDAP::manageRequestValues()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SamuelMTeixeira**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [ ] I have read the CONTRIBUTING document.
- [ ] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #22452 
- Here is a brief description of what this PR does

This PR fixes a critical bug where importing or synchronizing users from an LDAP directory fails if there is only **one** active directory configured in GLPI. 

When a single directory is active, the UI does not send the `authldaps_id` parameter (it defaults to `0`). Inside `src/AuthLDAP.php::manageRequestValues()`, the system was attempting to hydrate the `$authldap` object from the database using `authldaps_id = 0` **before** the code block that resolves the default ID from the entity. 

Because `getFromDB(0)` returns false/empty, the `$authldap->fields` array remained empty, causing a cascade of undefined key warnings and ultimately generating a malformed LDAP filter (e.g., falling back to `N/A`).

### Errors Resolved
This fix eliminates the following errors that occur during the import/sync process:
* `PHP Warning (2): Undefined array key "basedn" in src/AuthLDAP.php at line 3667`
* `PHP Warning (2): Undefined array key "login_field" in src/AuthLDAP.php at line 3813`
* `PHP Warning (2): Undefined array key "condition" in src/AuthLDAP.php at line 3824`
* `LDAP search with base DN N/A and filter (& (N/A=*usuario*) N/A) failed error: Bad search filter (-7) at AuthLDAP.php line 1803`

### Solution
The line of code that loads the database object (`$authldap->getFromDB($_REQUEST['authldaps_id']);`) was placed in the wrong order. 

I moved it to sit directly **below** the `if ($_REQUEST['authldaps_id'] === 0) { ... }` block. This ensures the object is only fetched from the database *after* the `authldaps_id` has been correctly replaced by the entity's default LDAP ID.

### CODE REVIEW

**Review by trasher — APPROVED** [review]

File: src/AuthLDAP.php [hunk 1]
```diff
@@ -3654,13 +3654,13 @@ public static function manageRequestValues(bool $is_users = true): void
...
             ) {
-                $authldap->getFromDB($_REQUEST['authldaps_id']);
-
                 if ($_REQUEST['authldaps_id'] === 0) {
                     // authldaps_id wasn't submitted by the user -> take entity config
                     $_REQUEST['authldaps_id'] = $entity->fields['authldaps_id'];
                 }
 
+                $authldap->getFromDB($_REQUEST['authldaps_id']);
+
```
Comment (AdrienClairembault) [inline src/AuthLDAP.php]:
```suggestion

```

**Review by AdrienClairembault — APPROVED** [review]
