### PR TITLE
Massive Actions for status visibility do not work : Updates through massive actions for core itemtypes does not work. - fix #21520 

### LINKED ISSUE #21520: Massive Actions for status visibility do not work
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

Two issues seen while looking at another bug report:
- Visibility for custom asset types do not show in the update massive action for statuses
- Updates through massive actions for core itemtypes does not work.

### Relevant log output

```shell

```

### Page URL

/front/state.php

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SebSept**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes one of the bug reported in #21520 
- Massive Actions for status visibility do not work : Updates through massive actions for core itemtypes does not work.

### CODE REVIEW

File: src/State.php [hunk 1]
```diff
@@ -735,6 +755,31 @@ public function rawSearchOptions()
             'datatype'           => 'bool',
         ];
 
+        // custom Assets
+        $custom_asset_search_id = 4000; // random choice, see @todo below
```
Comment (SebSept) [inline src/State.php]: Any solution for this ?

File: src/State.php [hunk 2]
```diff
@@ -735,6 +755,31 @@ public function rawSearchOptions()
...
+        foreach (AssetDefinitionManager::getInstance()->getDefinitions() as $definition) {
+            $tab[] = [
+                'id'                 => $custom_asset_search_id++, // @todo I don't know what to put here...
```
Comment (cedric-anne) [inline src/State.php]: The search option id must be stable over time, even if a definition is removed.

```suggestion
                'id'                 => $custom_asset_search_id + $definition->getID(),
```

File: src/State.php [hunk 3]
```diff
@@ -735,6 +755,31 @@ public function rawSearchOptions()
             'datatype'           => 'bool',
         ];
 
+        // custom Assets
+        $custom_asset_search_id = 4000; // random choice, see @todo below
+        foreach (AssetDefinitionManager::getInstance()->getDefinitions() as $definition) {
```
Comment (cedric-anne) [inline src/State.php]: You should not generate search options for inactive definitions.

```suggestion
        foreach (AssetDefinitionManager::getInstance()->getDefinitions(only_active: true) as $definition) {
```

File: src/State.php [hunk 4]
```diff
@@ -371,6 +372,7 @@ public function rawSearchOptions()
             'id'                 => '21',
             'table'              => DropdownVisibility::getTable(),
             'field'              => 'is_visible',
+            'linkfield'          => 'is_visible_computer',
```
Comment (cedric-anne) [inline src/State.php]: Why using a linkfield here ? You are targetting a field that does not exist anymore in DB. I am not sure it is the best way to do, I cannot tell if it could have unexpected side effects.

Comment (SebSept) [reply src/State.php]: fields must be named this way to trigger the DropdowVisibility object -> 
https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/State.php#L345 
without this convention, it doesn't work.

Comment (SebSept) [reply src/State.php]: maybe all the is_visible_xxx logic can be removed, I don't know, because I don't know why it was added. I can give a try if you want. (I'll also add a backward compat layer).

Comment (cedric-anne) [reply src/State.php]: The `is_visible_xxx` fields were real fields before GLPI 11.0. The DB structure changed in GLPI 11.0 to handle states visibility of generic assets. These fields were maintain,ed as "virtual" fields to ease the compatibility with the existing behaviour.
Maybe it should use a specific massive action logic rather than reusing this `linkfield` option that is probably not supposed to be used for this.

Comment (SebSept) [reply src/State.php]: Can you explain what you mean by "it should use a specific massive action logic" ?
Do you mean implement some specific actions ? https://glpi-developer-documentation.readthedocs.io/en/master/devapi/massiveactions.html#specific-massive-actions 

So I should create a dedicated `update_visibility` action, implement showMassiveActionsSubForm() and `processMassiveActionsForOneItemtype()` ?

File: src/State.php [hunk 5]
```diff
@@ -76,6 +77,8 @@ public function getAdditionalFields()
         ];
 
         foreach ($this->getvisibilityFields() as $type => $field) {
+            // $type is a class-string representing an item class (eg. Computer::class)
+            /** @var class-string<CommonDBTM> $type */
```
Comment (AdrienClairembault) [inline src/State.php]: Maybe you should fix the return type from `getvisibilityFields` instead of overriding it here?

File: src/State.php [hunk 6]
```diff
@@ -339,6 +340,151 @@ public function post_addItem()
...
+        }
+
+        // Itemtype choice
+        global $CFG_GLPI;
+        $itemtype_options = [];
+
+        if (!empty($CFG_GLPI['state_types']) && is_array($CFG_GLPI['state_types'])) {
+            foreach ($CFG_GLPI['state_types'] as $itemtype) {
+                // Ensure the itemtype/class exists and provides a type name
+                if (class_exists($itemtype) && method_exists($itemtype, 'getTypeName')) {
```
Comment (cedric-anne) [inline src/State.php]: We expect classes here to be `CommonDBTM`.

```suggestion
                if (is_a($itemtype, CommonDBTM::class, true)) {
```

File: src/State.php [hunk 7]
```diff
@@ -339,6 +340,151 @@ public function post_addItem()
...
+                    $itemtype_options[$itemtype] = $itemtype::getTypeName(Session::getPluralNumber());
+                }
+            }
+        }
+
+        // Add custom asset definitions
+        foreach (AssetDefinitionManager::getInstance()->getDefinitions(only_active: true) as $definition) {
+            $asset_class = $definition->getAssetClassName();
+            $itemtype_options[$asset_class] = $definition->getFriendlyName() ?: $asset_class;
+        }
```
Comment (cedric-anne) [inline src/State.php]: They are already present in `$CFG_GLPI['state_types']`, see https://github.com/glpi-project/glpi/blob/de6366dd20e52a50f4e006e9387d000c7aaa567b/src/Glpi/Asset/AssetDefinitionManager.php#L191-L203

File: src/State.php [hunk 8]
```diff
@@ -339,6 +340,151 @@ public function post_addItem()
...
+                    }
+                    return;
+                }
+
+                // Validate itemtypes against allowed types and skip processing for invalid ones
+                global $CFG_GLPI;
+                $allowed_itemtypes = $CFG_GLPI['state_types'] ?? [];
+                foreach (AssetDefinitionManager::getInstance()->getDefinitions(only_active: true) as $definition) {
+                    $allowed_itemtypes[] = $definition->getAssetClassName();
+                }
```
Comment (cedric-anne) [inline src/State.php]:
```suggestion
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/State.php [hunk 9]
```diff
@@ -810,6 +999,12 @@ protected function getvisibilityFields(): array
         foreach ($CFG_GLPI['state_types'] as $type) {
             $fields[$type] = 'is_visible_' . strtolower($type);
         }
+
+        // Add custom assets
+        foreach (AssetDefinitionManager::getInstance()->getDefinitions() as $definition) {
+            $fields[$definition->getAssetClassName()] = strtolower(str_replace('\'', '_', 'is_visible_' . $definition->getAssetClassName()));
```
Comment (AdrienClairembault) [inline src/State.php]: Is there a reason you are replacing quotes by slashes here? I don't think assets classes names can contain quotes.

Maybe you meant to replace backslashes instead?

File: src/State.php [hunk 10]
```diff
@@ -735,6 +900,30 @@ public function rawSearchOptions()
...
+                    'jointype' => 'itemtypeonly',
+                    'table'      => static::getTable(),
+                    'condition' => [
+                        'NEWTABLE.visible_itemtype' => $definition->getAssetClassName(),
+                        'NEWTABLE.items_id' => new QueryExpression('REFTABLE.id'),
+                    ],
+                ],
+                'massiveaction'      => false,
+            ];
+        };
```
Comment (AdrienClairembault) [inline src/State.php]:
```suggestion
        }
```

File: src/State.php (hunk 9 above)
Comment (cedric-anne) [inline src/State.php]:
```suggestion
            $fields[$definition->getAssetClassName()] = strtolower(str_replace('\\', '_', 'is_visible_' . $definition->getAssetClassName()));
```

File: src/State.php [hunk 11]
```diff
@@ -810,6 +991,12 @@ protected function getvisibilityFields(): array
         foreach ($CFG_GLPI['state_types'] as $type) {
             $fields[$type] = 'is_visible_' . strtolower($type);
         }
+
+        // Add custom assets (they are not included in $CFG_GLPI['state_types']) if not active
+        foreach (AssetDefinitionManager::getInstance()->getDefinitions() as $definition) {
+            $fields[$definition->getAssetClassName()] = strtolower('is_visible_' . $definition->getAssetClassName());
+        }
+
```
Comment (cedric-anne) [inline src/State.php]: I think they should not be added for inactive definitions.

**Review by cedric-anne — APPROVED** [review]

**Review by AdrienClairembault — APPROVED** [review]
