### PR TITLE
fix custom asset model and type discrimination in api

### LINKED ISSUE #22268: [API] Specific Asset Definition Model endpoint returns models from other Asset Definition (Lack of Isolation)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

I am using the REST API to list available models for a specific Generic Object type (e.g., Bornesmobiles). When querying the specific endpoint for this object's models, the API returns a list containing Models that belong to other Generic Objects or standard Assets. This breaks data integrity because trying to link these "foreign" Model IDs via API (PATCH/POST) results in a silent failure (field remains null) or a 500 error, as the model is not compatible with the target asset type.

The behavior is the same with type

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

Create a Asset Definition Type A (e.g., MobileTerminal). 
Create a Asset Definition Type B (e.g., Car). 
Create a Model for Type A (e.g., "Scanner Model X", ID: 4).
Query the API endpoint for Type B models:
GET /api.php/Assets/Custom/BornesmobilesModel (or the equivalent endpoint for the custom object).
Header: Range: 0-10

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

fixes #22268

### CODE REVIEW

File: src/Glpi/Api/HL/Controller/CustomAssetController.php [hunk 1]
```diff
@@ -213,6 +213,13 @@ protected static function getRawKnownSchemas(): array
                 'x-version-introduced' => '2.0',
                 'x-itemtype' => $asset_type_class,
                 'type' => Doc\Schema::TYPE_OBJECT,
+                'x-rights-conditions' => [
+                    'read' => static function () use ($asset_class, $definition) {
+                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')];
+                        $criteria['WHERE']['_.assets_assetdefinitions_id'] = $definition->getID();
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Controller/CustomAssetController.php]: There is a method to apply filtering on definitions.

```suggestion
                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class getSystemSQLCriteria('_');
```

File: src/Glpi/Api/HL/Controller/CustomAssetController.php [hunk 2]
```diff
@@ -254,6 +261,13 @@ protected static function getRawKnownSchemas(): array
                 'x-version-introduced' => '2.0',
                 'x-itemtype' => $asset_model_class,
                 'type' => Doc\Schema::TYPE_OBJECT,
+                'x-rights-conditions' => [
+                    'read' => static function () use ($asset_class, $definition) {
+                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')];
+                        $criteria['WHERE']['_.assets_assetdefinitions_id'] = $definition->getID();
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Controller/CustomAssetController.php]:
```suggestion
                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class getSystemSQLCriteria('_');
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/Glpi/Api/HL/Controller/CustomAssetController.php [hunk 3]
```diff
@@ -213,6 +213,12 @@ protected static function getRawKnownSchemas(): array
                 'x-version-introduced' => '2.0',
                 'x-itemtype' => $asset_type_class,
                 'type' => Doc\Schema::TYPE_OBJECT,
+                'x-rights-conditions' => [
+                    'read' => static function () use ($asset_class, $definition) {
+                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class getSystemSQLCriteria('_');
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Controller/CustomAssetController.php]:
```suggestion
                    'read' => static function () use ($asset_class) {
                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class::getSystemSQLCriteria('_');
```

File: src/Glpi/Api/HL/Controller/CustomAssetController.php [hunk 4]
```diff
@@ -254,6 +260,12 @@ protected static function getRawKnownSchemas(): array
                 'x-version-introduced' => '2.0',
                 'x-itemtype' => $asset_model_class,
                 'type' => Doc\Schema::TYPE_OBJECT,
+                'x-rights-conditions' => [
+                    'read' => static function () use ($asset_class, $definition) {
+                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class getSystemSQLCriteria('_');
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Controller/CustomAssetController.php]:
```suggestion
                    'read' => static function () use ($asset_class) {
                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class::getSystemSQLCriteria('_');
```

**Review by cedric-anne — APPROVED** [review]

File: src/Glpi/Api/HL/Controller/CustomAssetController.php [hunk 5]
```diff
@@ -213,6 +213,12 @@ protected static function getRawKnownSchemas(): array
                 'x-version-introduced' => '2.0',
                 'x-itemtype' => $asset_type_class,
                 'type' => Doc\Schema::TYPE_OBJECT,
+                'x-rights-conditions' => [
+                    'read' => static function () use ($asset_class) {
+                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class::getSystemSQLCriteria('_');
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Controller/CustomAssetController.php]:
```suggestion
                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_') + $asset_class::getSystemSQLCriteria('_')];
```

File: src/Glpi/Api/HL/Controller/CustomAssetController.php [hunk 6]
```diff
@@ -254,6 +260,12 @@ protected static function getRawKnownSchemas(): array
                 'x-version-introduced' => '2.0',
                 'x-itemtype' => $asset_model_class,
                 'type' => Doc\Schema::TYPE_OBJECT,
+                'x-rights-conditions' => [
+                    'read' => static function () use ($asset_class) {
+                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_')] + $asset_class::getSystemSQLCriteria('_');
```
Comment (cedric-anne) [inline src/Glpi/Api/HL/Controller/CustomAssetController.php]:
```suggestion
                        $criteria = ['WHERE' => $asset_class::getAssignableVisiblityCriteria('_') + $asset_class::getSystemSQLCriteria('_')];
```

**Review by trasher — APPROVED** [review]
