### PR TITLE
fix(notification): fix missing attachments in notification emails

### LINKED ISSUE #22315: Attachments aren´t being included in email notifications
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.22

### Bug description

In GLPI 10.0.22 (latest version), task attachments added by technicians are not being included in email notifications as intended.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create an active notification (and template) of type `Ticket > Task creation` with defined recipients.
2. Make sure mail notifications are enabled and properly configured.
3. Create a ticket.
4. Create a task within the ticket and add one attachment (e.g., .pdf, .csv, .zip, etc.).
5. Go to `Administration > Notification queue` and check when the email is scheduled to be sent but most importantly, do not trigger the send manually.
6. Once the email arrives in your inbox, verify that it does not include the attachment.

### Anything else?

**IMPORTANT**: When the notification is manually dispatched in the `Notification queue` then it works as expected.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.22 ( => /var/www/glpi)
Installation mode: GIT
Current language:en_GB

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@127.0.0.1)
</pre>

### PR DESCRIPTION
**Pull request by MyvTsv**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !41656
- Attachments were not attached to notifications when no session was active. For example, when a notification is sent via CLI. If permissions are not bypassed, permissions will be checked using the canView method, or if no session is active, this will return false.

### CODE REVIEW

**Review by stonebuzz — APPROVED** [review]
That seems OK for me.

File: src/CommonITILObject.php [hunk 1]
```diff
@@ -7983,7 +7996,15 @@ public function getAssociatedDocumentsCriteria($bypass_rights = false/*, ?User $
         ];
 
         // documents associated to followups
-        if ($bypass_rights || ITILFollowup::canView()) {
+        if (
+            $bypass_rights ||
+            ITILFollowup::canView() ||
```
Comment (Rom1-B) [inline src/CommonITILObject.php:8001]: `ITILFollowup::canView()` checks the session permissions, so if the session has permissions, the IF will be true even if `$user` is defined and does not have permissions.
In my opinion, you should check the permissions of `$user` if it is defined, otherwise check the session permissions.

```suggestion
            ($user === null && ITILFollowup::canView()) ||
```

_The same applies to other cases._

**Review by Rom1-B — CHANGES_REQUESTED** [review]

**Review by Rom1-B — APPROVED** [review]

File: src/User.php [hunk 2]
```diff
@@ -7093,4 +7093,23 @@ public function hasRight($module, $right, $entities_id)
...
+
+    /**
+     * User has at least one of the rights for given module.
+     *
+     * @param string  $module Module to check
+     * @param array   $rights Rights to check
+     * @param integer $entities_id Entity to check
+     *
+     * @return boolean|int
+     **/
```
Comment (trasher) [inline src/User.php]:
```suggestion
     * @return bool
     */
```

**Review by trasher — APPROVED** [review]
Seems OK, but I'm never confident with rights

File: src/CommonITILObject.php [hunk 3]
```diff
@@ -7983,7 +7996,15 @@ public function getAssociatedDocumentsCriteria($bypass_rights = false/*, ?User $
...
+            (
+                $user !== null &&
+                $user->hasRightsOr($this->getType(), $can_view_itilobject[$this->getType()], $this->fields['entities_id']) &&
```
Comment (cedric-anne) [inline src/CommonITILObject.php]: Unless I am wrong, the passed value is not correct here. I guess it works only because the corresponding SQL request is case insensitive and module name corresponds to the lowercas form of the class.

```suggestion
                $user->hasRightsOr(static::$rightname, $can_view_itilobject[$this->getType()], $this->fields['entities_id']) &&
```

File: src/CommonITILObject.php [hunk 4]
```diff
@@ -8016,7 +8037,14 @@ public function getAssociatedDocumentsCriteria($bypass_rights = false/*, ?User $
         }
 
         // documents associated to solutions
-        if ($bypass_rights || ITILSolution::canView()) {
+        if (
+            $bypass_rights ||
+            ITILSolution::canView() ||
+            (
+                $user !== null &&
+                $user->hasRightsOr($this->getType(), $can_view_itilobject[$this->getType()], $this->fields['entities_id'])
```
Comment (cedric-anne) [inline src/CommonITILObject.php]:
```suggestion
                $user->hasRightsOr(static::$rightname, $can_view_itilobject[$this->getType()], $this->fields['entities_id'])
```

File: src/CommonITILObject.php [hunk 5]
```diff
@@ -8037,7 +8065,17 @@ public function getAssociatedDocumentsCriteria($bypass_rights = false/*, ?User $
...
         $validation_class = static::getType() . 'Validation';
-        if (class_exists($validation_class) && ($bypass_rights ||  $validation_class::canView())) {
+        if (
+            class_exists($validation_class) &&
+            (
+                $bypass_rights ||
+                $validation_class::canView() ||
+                (
+                    $user !== null &&
+                    $user->hasRightsOr($this->getType(), $can_view_itilobject[$this->getType()], $this->fields['entities_id'])
```
Comment (cedric-anne) [inline src/CommonITILObject.php]:
```suggestion
                    $user->hasRightsOr(static::$rightname, $can_view_itilobject[$this->getType()], $this->fields['entities_id'])
```

Also, maybe there is a missing check, to reproduce the `CommonITILValidation::canView()`, something like `&& $user->hasRightsOr($validation_class::$rightname, array_merge($validation_class::getCreateRights(), $validation_class::getValidateRights(), $validation_class::getPurgeRights()))`.

File: src/CommonITILObject.php [hunk 6]
```diff
@@ -8056,7 +8094,14 @@ public function getAssociatedDocumentsCriteria($bypass_rights = false/*, ?User $
         }
 
         // documents associated to tasks
-        if ($bypass_rights || $task_class::canView()) {
+        if (
+            $bypass_rights ||
+            $task_class::canView() ||
+            (
+                $user !== null &&
+                $user->hasRightsOr($this->getType(), $can_view_itilobject[$this->getType()], $this->fields['entities_id'])
```
Comment (cedric-anne) [inline src/CommonITILObject.php]:
```suggestion
                $user->hasRightsOr(static::$rightname, $can_view_itilobject[$this->getType()], $this->fields['entities_id'])
```

Also, maybe a check on the `$task_class::SEEPUBLIC` right sholuld be added, like for followups.

**Review by cedric-anne — COMMENTED** [review]
It will not permit to get all missing items. Indeed, there are additional checks done in `canViewItem()` methods, for instance https://github.com/glpi-project/glpi/blob/57059dea67c2ebd8e63c451625ef311fb15e3bae/src/TicketTask.php#L103-L118

But I am not sure it is possible to apply all these checks in the current method.

**Review by stonebuzz — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
