### PR TITLE
add verification on key to fix error on reimport

### LINKED ISSUE #21544: Undefined array key in src/Inventory/Asset/InventoryAsset.php (10.0.19-20)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.20

### Bug description

Hello,

I can see some warnings in php-errors.log triggered by computer inventoring process:

[2025-07-30 21:19:17] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "444dc901a15520fdaf5fda9f6cdef7cb" in src/Inventory/Asset/InventoryAsset.php at line 478
  Backtrace :
  src/Inventory/Asset/MainAsset.php:916              Glpi\Inventory\Asset\InventoryAsset->handleInput()
  src/RuleImportAsset.php:985                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1537                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1658                        Rule->process()
  src/Inventory/Asset/MainAsset.php:581              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:727                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:358                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:381                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:100                            Glpi\Agent\Communication\AbstractRequest->handleRequest()
  index.php:93                                       include_once()
  public/index.php:82                                require()

 It seems that the started after GLPI update from 10.0.18 to 10.0.19 and are still present after update to 10.0.20.

After some debugging, it appears that the key concerned by this warning is states_id for computers.

When raw links are created, its value is 0 (probably because the agent has no particular value to send) and an md5 key is generated with this.
[2025-10-17 15:43:44] glpiphplog.WARNING:   *** PHP User Warning (512): KKK: handle raw_links: bef73c6d71de207a1de7a17bff581fcb <= states_id = 0 in src/Inventory/Asset/InventoryAsset.php at line 237

We can see it in the raw_link array once in handleInput:
[2025-10-17 15:43:44] glpiphplog.WARNING:   *** PHP User Warning (512): KKK: inventorying raw_links: Array
[bef73c6d71de207a1de7a17bff581fcb] => 0
...

But as the field is locked with a manual value set (1):
[2025-10-17 15:43:44] glpiphplog.WARNING:   *** PHP User Warning (512): KKK: inventorying item: Computer/3543 key: states_id val:1 in src/Inventory/Asset/InventoryAsset.php at line 484

Newly generated md5 is different from the one used before to fill the raw_links array. So this key can not be found  in known_links. In addition, as it is not a new item (else statement) the following line can not succeed:

$input[$key] = $this->raw_links[$known_key];

[2025-10-17 15:43:44] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "444dc901a15520fdaf5fda9f6cdef7cb" in src/Inventory/Asset/InventoryAsset.php at line 486

### Relevant log output

```shell
See above
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
- It fixes #21544

Backported from GLPI 11.0, where the issue was already resolved https://github.com/glpi-project/glpi/blob/11.0/bugfixes/src/Glpi/Inventory/Asset/InventoryAsset.php#L501-L511

Testing : Reproduced the bug using the test fixture computer_locked_states_id.json, applied the fix, and confirmed that the error no longer occurs while the locked field behavior remains correct.

### CODE REVIEW

**Comment by trasher** [comment]
This needs unit tests

File: phpunit/functional/Glpi/Inventory/Assets/ComputerTest.php [hunk 1]
```diff
@@ -1762,4 +1762,72 @@ public function testOsCommentRuleLocation()
...
+        $json = json_decode($json_str);
+
+        // Create initial states
+        $state = new \State();
+        $states_id_inventory = $state->add([
+            'name' => 'State from inventory',
+            'entities_id' => 0
+        ]);
+        $this->assertGreaterThan(0, $states_id_inventory);
+
```
Comment (trasher) [inline phpunit/functional/Glpi/Inventory/Assets/ComputerTest.php:1791]: Seems not used

**Review by trasher — COMMENTED** [review]
I'm not sure the test is correct; a state must be set from the inventory.

File: phpunit/functional/Glpi/Inventory/Assets/ComputerTest.php (hunk 1 above)
Comment (f2cmb) [reply phpunit/functional/Glpi/Inventory/Assets/ComputerTest.php:1791]: Fixed in https://github.com/glpi-project/glpi/pull/21669/commits/353df1c9a2d4f938177afa8d5478754a97d196fc

File: phpunit/functional/Glpi/Inventory/Assets/ComputerTest.php [hunk 2]
```diff
@@ -1762,4 +1762,95 @@ public function testOsCommentRuleLocation()
...
+        $this->assertCount(1, $locks);
+
+        // Reload and verify the manual state is set
+        $this->assertTrue($computer->getFromDB($computers_id));
+        $this->assertEquals($states_id_manual, $computer->fields['states_id']);
+
+        // Reimport the same inventory - this should NOT trigger an error
+        // Before the fix, this would cause: "Undefined array key" in $raw_links[$known_key]
+        // because the inventory wants to set states_id_inventory but the field is locked
+        // with states_id_manual, and the key doesn't exist in raw_links
```
Comment (trasher) [inline phpunit/functional/Glpi/Inventory/Assets/ComputerTest.php]:
```suggestion
```

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Please fix lint

**Review by AdrienClairembault — APPROVED** [review]
