### PR TITLE
fix(ticket): category no longer saved when at a lower level entity

### LINKED ISSUE #18240: Ticket category no longer saved when at a lower level entity (normal interface)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0.17

### Bug description

We got most of our ITIL categories at the top level entity with recursive enabled, when creating a ticket to a lower level entity I can select the category options but after selecting the form auto submits and the category is empty again. It does work for the simplified interface.

### Relevant log output

Cannot find anything in the logs

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. Set all ITIL categories at the top level with recursive on
2. Go to lower level and do not use the simplified interface
3. Create a new ticket and select a top level itil category
4. Form submits and category is empty

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Rom1-B**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #18240
Ticket category no longer saved when at a lower level entity

### CODE REVIEW

**Review by flegastelois — APPROVED** [review]

File: src/Ticket.php [hunk 1]
```diff
@@ -4379,7 +4379,7 @@ public function showForm($ID, array $options = [])
                         break;
                 }
                 // Check category / entity validity
-                if (!in_array($cat->fields['entities_id'], getSonsOf('glpi_entities', $options['entities_id']))) {
+                if (!in_array($cat->fields['entities_id'], getSonsAndAncestorsOf('glpi_entities', $options['entities_id']))) {
```
Comment (AdrienClairembault) [inline src/Ticket.php:4382]: What about this scenario:

>Category entity is `Root` with `is_recursive = false`
>Ticket entity is `Root > A`.

With the proposed change, I think the category will be considered as valid despite not being visible from the tickets entity.

Shouldn't the ancestors be checked only if the category is recursive ?

**Comment by AdrienClairembault** [comment]
Also, shouldn't this fix target the bugfixes branch ?

File: src/Ticket.php [hunk 2]
```diff
@@ -4379,7 +4379,13 @@ public function showForm($ID, array $options = [])
...
                 }
                 // Check category / entity validity
-                if (!in_array($cat->fields['entities_id'], getSonsOf('glpi_entities', $options['entities_id']))) {
+                if (
+                    in_array($cat->fields['entities_id'], getSonsOf('glpi_entities', $options['entities_id']))
+                    || (
+                        $cat->isRecursive()
+                        && !in_array($cat->fields['entities_id'], getAncestorsOf('glpi_entities', $options['entities_id']))
+                    )
+                ) {
```
Comment (cedric-anne) [inline src/Ticket.php:4388]: If I understand correctly, we want to drop a category whenever it is not available on the entity passed in `$options['entities_id']`. If I am correct it means that we must refuse the category
if the category IS NOT recursive and its entity does not match `$options['entities_id']`
OR
if the category IS and `$options['entities_id']` is not part of the sons of the entities of the category 

```suggestion
                if (
                    (
                        !$cat->isRecursive()
                        && $cat->fields['entities_id'] !== $options['entities_id']
                    )
                    || (
                        $cat->isRecursive()
                        && !in_array($options['entities_id'], getSonsOf('glpi_entities', $cat->fields['entities_id']))
                    )
                ) {
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/Ticket.php [hunk 3]
```diff
@@ -4379,7 +4379,12 @@ public function showForm($ID, array $options = [])
                         break;
                 }
                 // Check category / entity validity
-                if (!in_array($cat->fields['entities_id'], getSonsOf('glpi_entities', $options['entities_id']))) {
+                if (
+                    !in_array($cat->fields['entities_id'], array_merge(
+                        getSonsOf('glpi_entities', $options['entities_id']),
```
Comment (cedric-anne) [inline src/Ticket.php:4384]: I am not sure to understand this `getSonsOf('glpi_entities', $options['entities_id'])`.

It mean that we would agree to create a ticket in the root entity with a category that is present only in a child entity ?

Comment (Rom1-B) [reply src/Ticket.php:4384]: Yes, you're right. In the latest commit, I adapted your previous suggestion to fix the original issue #17811

Since we don’t have E2E tests on BF, I’m not sure how to implement an automated test for this. (It works in manual testing, though.)

Comment (AdrienClairembault) [reply src/Ticket.php]: Or move the entity check code into a method and test the method directly, which might be simpler to understand.

File: phpunit/functional/TicketTest.php [hunk 4]
```diff
@@ -7296,4 +7296,133 @@ public function testComputeDefaultValuesForAdd(): void
...
+    {
+        $ent0 = getItemByTypeName('Entity', '_test_root_entity', true);
+        $ent1 = getItemByTypeName('Entity', '_test_child_1', true);
+
+        // Create Categories
+        $category1 = $this->createItem('ITILCategory', [
+            'name' => 'category_root_entity_recursive',
+            'entities_id' => $ent0,
+            'is_recursive' => 1,
+        ]);
```
Comment (cedric-anne) [inline phpunit/functional/TicketTest.php:7310]: Creating items in data providers is not a good idea, you should pass the `$category_fields` to the test method and create the category directly inside the method.

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: phpunit/functional/TicketTest.php (hunk 4 above)
Comment (AdrienClairembault) [reply phpunit/functional/TicketTest.php]: (this is because items created in data providers are not removed from the database after the tests end since we switched to phpunit)

File: src/Ticket.php [hunk 5]
```diff
@@ -4249,6 +4249,48 @@ public static function getDefaultValues($entity = 0)
...
 
 
+    /**
+     * Check if the category is valid for the given type and entity.
+     *
+     * @param array $input An associative array containing 'itilcategories_id', 'type', and 'entities_id'.
+     *
+     * @return bool
+     */
+    public static function isCategoryValid($input): bool
```
Comment (cedric-anne) [inline src/Ticket.php:4259]:
```suggestion
    public static function isCategoryValid(array $input): bool
```

File: src/Ticket.php [hunk 6]
```diff
@@ -4249,6 +4249,48 @@ public static function getDefaultValues($entity = 0)
...
+    {
+        $cat = new ITILCategory();
+        if ($cat->getFromDB($input['itilcategories_id'])) {
+            switch ($input['type']) {
+                case self::INCIDENT_TYPE:
+                    if (!$cat->getField('is_incident')) {
```
Comment (cedric-anne) [inline src/Ticket.php:4265]: `getField()` should be used only to display values.

```suggestion
                    if (!$cat->fields['is_incident']) {
```

File: src/Ticket.php [hunk 7]
```diff
@@ -4249,6 +4249,48 @@ public static function getDefaultValues($entity = 0)
...
+                        return false;
+                    }
+                    break;
+
+                case self::DEMAND_TYPE:
+                    if (!$cat->getField('is_request')) {
```
Comment (cedric-anne) [inline src/Ticket.php:4271]:
```suggestion
                    if (!$cat->fields['is_request']) {
```

**Review by cedric-anne — APPROVED** [review]
Seems OK.

The few minor changes proposed should not change the results.

File: phpunit/functional/TicketTest.php [hunk 8]
```diff
@@ -7296,4 +7296,145 @@ public function testComputeDefaultValuesForAdd(): void
         $this->assertGreaterThan(0, $id);
         $this->checkInput($ticket, $id, $expected);
     }
+
+    public function isCategoryValidProvider(): array
```
[the remark this answers is not in the document]
Comment (trasher) [reply phpunit/functional/TicketTest.php]: Providers should be static yes; and this is required on main (among others).

**Review by trasher — APPROVED** [review]

**Comment by RobertoMarcelino** [comment]
In which .php file should I change the lines? 

I looked in src/Ticket.php and couldn't find any reference to changing the specified lines.

**Comment by RobertoMarcelino** [comment]
GLPI-11.0.0-dev:

`3611                 if (!in_array($cat->fields['entities_id'], getAncestorsOf('glpi_entities', $options['entities_id']))) {
`
