### PR TITLE
Multiple form migrations fixes

### LINKED ISSUE #20249: Récupérer formulaires GLPI 10.0.18 dans GLPI 11
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11 beta 7

### Bug description

Bonjour,
Je suis en train de tester le GLPI 11. 
Afin de récupérer mes formulaires, j'ai suivi le ticket #20191 , et passé la commande bin/console migration:formcreator_plugin_to_core.
J'ai le message d'erreur ci-dessous, en sachant que aucuns formulaires n'a été récupéré, malgrés les messages "✓ 1491 items created.
✓ 74 items reused."
Je n'ai aucunes traces dans les logs access, php, event..

Auriez-vous une idée de la problématique ? Merci ++

[==================>---------]  67%
Importing ticket targets...
The migration failed.
x The "Request type" destination field configuration of the form "DSIN-Signaler un Incident" cannot be imported : Question not found in a target form
x The "Lieu" destination field configuration of the form "DSIN-Signaler un Incident" cannot be imported : Question not found in a target form
x The "Urgence" destination field configuration of the form "Effectuer une demande_old" cannot be imported : Question not found in a target form
x The "Urgence" destination field configuration of the form "Effectuer une demande_old" cannot be imported : Question not found in a target form
x The "Catégorie ITIL" destination field configuration of the form "Signaler un incident [Copie]" cannot be imported : Question not found in a target form
x The "Urgence" destination field configuration of the form "Signaler un incident [Copie]" cannot be imported : Question not found in a target form
x The "Catégorie ITIL" destination field configuration of the form "Signaler un incident [Copie]" cannot be imported : Question not found in a target form
x The "Urgence" destination field configuration of the form "Signaler un incident [Copie]" cannot be imported : Question not found in a target form
x The "Catégorie ITIL" destination field configuration of the form "Signaler un incident [Copie]" cannot be imported : Question not found in a target form
x The "Urgence" destination field configuration of the form "Signaler un incident [Copie]" cannot be imported : Question not found in a target form
x An unexpected error occurred
✓ 1491 items created.
✓ 74 items reused.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0-dev ( => /var/www/glpi)
Installation mode: TARBALL
Current language: fr_FR</pre></details><details><summary>Server</summary><pre>Operating system: Linux HR-GLPI-11 6.8.0-63-generic #​66-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 13 20:25:30 UTC 2025 x86_64

PHP: 8.2.28 fpm-fcgi

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
cgi-fcgi, bz2, curl, FFI, ftp, fileinfo, gd, gettext, intl, mbstring, exif, shmop, zip, mysqlnd, PDO, xml, bcmath, calendar,
ctype, dom, iconv, ldap, mysqli, pdo_mysql, Phar, posix, readline, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer,
xmlreader, xmlwriter, xsl, Zend OPcache

Setup: max_execution_time="300" memory_limit="512M" post_max_size="32M" safe_mode="" session.save_handler="files"
upload_max_filesize="20M" disable_functions="" 

Web server: Apache/2.4.58 (Ubuntu) (Apache/2.4.58 (Ubuntu) Server at test2-informatique.cahm.net Port 80)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:140.0) Gecko/20100101 Firefox/140.0

Database:
   
Server Software: Ubuntu 24.04
   
Server Version: 10.11.13-MariaDB-0ubuntu0.24.04.1
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@localhost/glpi
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.2.28) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.13) is
supported.
The log file has been created successfully.
Write access
to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: "/var/www/glpi"
GLPI_VERSION: "11.0.0-dev"
GLPI_SCHEMA_VERSION: "11.0.0-dev@3625b5fec3b12824545d9777d46d72fa99584d03"
GLPI_FILES_VERSION: "11.0.0-dev-ae8cbfd4"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.4"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST:
["#^http://[^@:]+(:80)?(/.*)?$#","#^https://[^@:]+(:443)?(/.*)?$#","#^feed://[^@:]+(/.*)?$#"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_LOG_LVL: "warning"
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_DOC_DIR: "/var/www/glpi/files"
GLPI_CACHE_DIR: "/var/www/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/files/_cron"
GLPI_GRAPH_DIR: "/var/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files/_inventories"
GLPI_THEMES_DIR: "/var/www/glpi/files/_themes"
GLPI_PLUGINS_DIRECTORIES: ["/var/www/glpi/marketplace","/var/www/glpi/plugins"]
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"</pre></details><details><summary>Annuaires LDAP</summary><pre>Server: '10.50.1.13', 
	Port: '389', 
	BaseDN: 'OU=AD2014,OU=Mairie,DC=ville-agde,DC=net', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Comptes_de_Service,OU=AD2014,OU=Mairie,DC=ville-agde,DC=net', 
	Use TLS: none

Server: '10.254.1.8', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=hermed,DC=fr', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=hermed,DC=fr', 
	Use TLS: none

Server: '10.254.31.5', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=mairie-pinet,DC=fr', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=mairie-pinet,DC=fr', 
	Use TLS: none

Server: '10.254.29.5', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=nezignan,DC=org', 
	Connection filter: '(&(objectClass=user)(objectCategory=Person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=nezignan,DC=org', 
	Use TLS: none

Server: '10.254.32.5', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=saint-thibery,DC=fr', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=saint-thibery,DC=fr', 
	Use TLS: none

Server: '10.254.45.5', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=LEZIGNAN,DC=local', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=LEZIGNAN,DC=local', 
	Use TLS: none

Server: '10.40.40.5', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=MAIRIEDEVIAS,DC=local', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=MAIRIEDEVIAS,DC=local', 
	Use TLS: none

Server: '10.254.43.6', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=mairiepomerols,DC=local', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=mairiepomerols,DC=local', 
	Use TLS: none

Server: '10.254.37.6', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=nizas,DC=fr', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=NIZAS,DC=fr', 
	Use TLS: none

Server: '10.254.33.6', 
	Port: '389', 
	BaseDN: 'OU=02-Sites,DC=cazouls,DC=fr', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 
	RootDN: 'CN=SINFGLPI,OU=Service Accounts,OU=01-Infra-IT,DC=CAZOULS,DC=fr', 
	Use TLS: none</pre></details><details><summary>Réplicats SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTPS(smtps://no-reply%40hermed.fr:********@10.254.1.224:587?verify_peer=0)
Name: 'support-informatique@agglohm.net'
	Active: No
	Server: '{10.254.1.224:993/imap/ssl/novalidate-cert/notls}'
	Login: 'hermed\support-informatique'
	Password: Yes
Name: 'consommables_facsimile@agglohm.net'
	Active: Yes
	Server: '{10.254.1.224:993/imap/ssl/novalidate-cert/notls}INBOX/test-collecteur'
	Login: 'hermed\consommable_facsimil'
	Password: Yes
Name: 'interventions_facsimile@agglohm.net'
	Active: Yes
	Server: '{10.254.1.224:993/imap/ssl/novalidate-cert/notls}INBOX'
	Login: 'hermed\interventions_facsim'
	Password: Yes</pre></details><details><summary>Plugins list</summary><pre>advanceddashboard    Name: advanceddashboard              Version: 1.6.2      State: Installé / non activé                 
Install Method: Marketplace
news                 Name: Alertes                        Version: 1.12.4     State: Installé / non activé                 
Install Method: Marketplace
archires             Name: Architecture réseau            Version: 1.0.2      State: Installé / non activé                 
Install Method: Manual
fields               Name: Champs supplémentaires         Version: 1.21.21    State: A mettre à jour                        
Install Method: Marketplace
printercounters      Name: Compteurs Imprimantes          Version: 2.0.1      State: Installé / non activé                 
Install Method: Marketplace
mydashboard          Name: Dashboard                      Version: 2.1.5      State: Installé / non activé                 
Install Method: Manual
datainjection        Name: Data Injection                 Version: 2.13.5     State: Installé / non activé                 
Install Method: Manual
escalade             Name: Escalades                      Version: 2.9.13     State: A mettre à jour                        
Install Method: Marketplace
formcreator          Name: Form Creator                   Version: 2.13.10    State: Installé / non activé                 
Install Method: Marketplace
order                Name: Gestion des commandes          Version: 2.10.6     State: Non installé                           
Install Method: Marketplace
tag                  Name: Gestion des tags               Version: 2.11.7     State: Non installé                           
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.5.3      State: A mettre à jour                        
Install Method: Marketplace
manufacturersimports Name: Imports fabricants             Version: 3.0.9      State: Installé / non activé                 
Install Method: Marketplace
pdf                  Name: Impression pdf                 Version: 4.0.1      State: Installé / non activé                 
Install Method: Marketplace
metademands          Name: Meta-Demandes                  Version: 3.3.16     State: Non installé                           
Install Method: Marketplace
mreporting           Name: Plus de rapports               Version: 1.8.7      State: Installé / non activé                 
Install Method: Marketplace
reports              Name: Rapports                       Version: 1.16.0     State: Installé / non activé                 
Install Method: Marketplace
localeoverride       Name: Renommer les chaînes de GLPI   Version: 1.1.9      State: Installé / non activé                 
Install Method: Marketplace
vip                  Name: VIP                            Version: 1.8.3      State: Installé / non activé                 
Install Method: Marketplace</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

* Do no import questions with an invalid type (a warning will be emitted)
* Handle already formatted values in `ValidationField::prepareInput()`

## References

Fix #20249.

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
Draft because another point need to be fixed, not done yet.

File: src/Glpi/Migration/AbstractPluginMigration.php [hunk 1]
```diff
@@ -95,17 +95,22 @@ final public function execute(bool $simulate = false): PluginMigrationResult
     {
         $this->result = new PluginMigrationResult();
 
+        // Use a transaction unless we are already inside one.
+        $use_transaction = !$this->db->inTransaction();
```
Comment (cedric-anne) [inline src/Glpi/Migration/AbstractPluginMigration.php]: Same remark as https://github.com/glpi-project/glpi/pull/20227#discussion_r2206514092

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/Glpi/Migration/AbstractPluginMigration.php (hunk 1 above)
Comment (AdrienClairembault) [reply src/Glpi/Migration/AbstractPluginMigration.php]: See answer in the linked PR.

File: src/Glpi/Migration/AbstractPluginMigration.php [hunk 2]
```diff
@@ -108,7 +108,7 @@ final public function execute(bool $simulate = false): PluginMigrationResult
                 if ($simulate === false && $fully_processed === true) {
                     $this->db->commit();
                 } else {
-                    $this->db->rollBack();
+                    $fully_processed = $this->processMigration();
```
Comment (cedric-anne) [inline src/Glpi/Migration/AbstractPluginMigration.php]: Is this a bad conflict resolution ?

**Review by cedric-anne — APPROVED** [review]
