### PR TITLE
fix change of status on assign (without UPDATE), fix #3655

### LINKED ISSUE #3655: Does not change a ticket status
Hello!
Does not change the status of a ticket after assigned ticket itself. Even after wrote followup with chenging the status on "Processing (assigned)".
This problem is in 9.1.4 and 9.2.2.

glpi - tickets - 32 - mozilla firefox 2018-03-02 11 42 42

glpi - tickets - 32 - mozilla firefox 2018-03-02 11 50 20

glpi - tickets - 32 - mozilla firefox 2018-03-02 11 49 33

Rights of the profile:
glpi - profiles - 6 - google chrome 2018-03-02 11 36 18

### PR DESCRIPTION
**Pull request by orthagh**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3655

### CODE REVIEW

**Comment by AircraftRu** [comment]
Hi
I updated the issue #3655

File: tests/functionnal/Ticket.php [hunk 1]
```diff
@@ -1599,4 +1599,92 @@ public function testPrepareInputForAdd($input, $expected, $rich) {
...
+      $this->integer((int) $ticket_user->add($input_ticket_user))->isGreaterThan(0);
+      $this->boolean($ticket_user->getFromDB($ticket_user->getId()))->isTrue();
+
+      // check status (should still be ASSIGNED)
+      $this->boolean($ticket->getFromDB($tickets_id))->isTrue();
+      $this->integer((int) $ticket->fields['status'])
+           ->isEqualto(\CommonITILObject::ASSIGNED);
+
+      // restore right
+      $_SESSION['glpiactiveprofile'] = $saverights;
```
Comment (trasher) [inline tests/functionnal/Ticket.php]: would be better I guess to reset right just after `add()` has been called; to prevent issues when following tests fails.

**Comment by trasher** [comment]
@AircraftRu please test with latest changes; will be merged if you're OK. Thank you :)
