### PR TITLE
Fix calendar holiday computation when dates are invalid

### LINKED ISSUE #22263: An unexpected error occurred - after upgrading glpi from version 10.0.6 to latest version (running in docker)
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

When I try to create or close a ticket, it gives me an error as you can see bellow in log output.

### Relevant log output

```shell
Safe\strtotime(): Argument #1 ($datetime) must be of type string, null given, called in ./src/Calendar.php on line 245
In ./vendor/thecodingmachine/safe/generated/8.4/datetime.php(1219)
#0 ./src/Calendar.php(245): Safe\strtotime()
#1 ./src/Calendar.php(354): Calendar->isHoliday()
#2 ./src/Calendar.php(386): Calendar->isAWorkingDay()
#3 ./src/CommonITILObject.php(10616): Calendar->isAWorkingHour()
#4 ./src/Ticket.php(5531): CommonITILObject->fillInputForBusinessRules()
#5 ./src/CommonITILObject.php(11205): Ticket->fillInputForBusinessRules()
#6 ./src/Ticket.php(6172): CommonITILObject->processRules()
#7 ./src/Ticket.php(1045): Ticket->processRules()
#8 ./src/CommonDBTM.php(1682): Ticket->prepareInputForUpdate()
#9 ./front/ticket.form.php(90): CommonDBTM->update()
#10 ./src/Glpi/Controller/LegacyFileLoadController.php(64): require('...')
#11 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\LegacyFileLoadController->__invoke()
#12 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#13 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#14 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle()
#15 {main}
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.4 ( =&gt; /var/www/glpi)
Installation mode: DOCKER
Current language: pt_PT
Source Integrity: OK</pre></details><details><summary>Server</summary><pre>Operating system: Linux glpi 6.1.0-38-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.147-1 (2025-08-02) x86_64

PHP: 8.4.15 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json,
mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader,
xmlwriter, mysqlnd, apache2handler, apcu, bcmath, Phar, exif, gd, intl, ldap, mysqli, redis, soap, sodium, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;128M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;Strict&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache ()

User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 12.1.2-MariaDB-ubu2404
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@MariaDB/glpi
   
Host info: MariaDB via TCP/IP

Requirements:
PHP version (8.4.15) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (12.1.2) is supported.
The log file has been created successfully.
Write access to
/var/glpi/files/_cache has been validated.
Write access to /var/glpi/files/_cron has been validated.
Write access to /var/glpi/files has been validated.
Write access to /var/glpi/files/_graphs has been validated.
Write access to /var/glpi/files/_lock has been validated.
Write access to /var/glpi/files/_pictures has been validated.
Write access to /var/glpi/files/_plugins has been validated.
Write access to /var/glpi/files/_rss has been validated.
Write access to /var/glpi/files/_sessions has been validated.
Write access to /var/glpi/files/_tmp has been validated.
Write access to /var/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/glpi&quot;
GLPI_VERSION: &quot;11.0.4&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.4@9065df1ff6b8ff1d77b519d1c4856507d18258b0&quot;
GLPI_FILES_VERSION: &quot;11.0.4-b3ce0587&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/var/glpi/config&quot;
GLPI_VAR_DIR: &quot;/var/glpi/files&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/glpi/marketplace&quot;
GLPI_LOG_DIR: &quot;/var/glpi/logs&quot;
GLPI_INSTALL_MODE: &quot;DOCKER&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/var/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/glpi/files/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/glpi/marketplace&quot;,&quot;/var/www/glpi/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>Directórios LDAP</summary><pre>Server: &#39;192.168.76.1&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;dc=domain,dc=com&#39;, 
	Connection filter: &#39;(&amp;(objectclass=qmailUser)(objectclass=sambaSamAccount))&#39;, 
	RootDN: &#39;uid=user,ou=users,dc=domain,dc=com&#39;, 
	Use TLS: none</pre></details><details><summary>Réplicas do SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://suporte:********@groupware.domain.com:25)
Name: &#39;suporte@domain.com&#39;
	Active: Yes
	Server: &#39;{groupware.domain.com:993/imap/ssl/validate-cert/notls}INBOX&#39;
	Login: &#39;suporte&#39;
	Password: Yes</pre></details><details><summary>Plugins list</summary><pre>actualtime           Name: ActualTime                     Version: 2.1.0      State: Activar                                 
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Activar                                 
Install Method: Marketplace
mreporting           Name: Mais Relatórios                Version: 1.8.7      State: Activar                                 
Install Method: Marketplace
reports              Name: Reports                        Version: 1.16.0     State: Não instalado                          
Install Method: Marketplace</pre></details>

### Anything else?

With the following correction, the problem is solved:

--- a/src/Calendar.php
+++ b/src/Calendar.php
@@ -225,6 +225,11 @@ class Calendar extends CommonDropdown
      **/
     public function isHoliday($date)
     {
+        // Validação: se $date for null ou vazio, retorna false
+        if (empty($date)) {
+            return false;
+        }
+
         $calendar_holiday = new Calendar_Holiday();
         $holidays = $calendar_holiday->getHolidaysForCalendar($this->fields['id']);
 
@@ -232,6 +237,11 @@ class Calendar extends CommonDropdown
         foreach ($holidays as $holiday) {
+            // Validação adicional: verificar se begin_date e end_date não são null
+            if (empty($holiday['begin_date']) || empty($holiday['end_date'])) {
+                continue;
+            }
+
             if ($holiday['is_perpetual']) {
                 // Compare only month and day for holidays that occurs every year.
                 $date_to_compare = date('m-d', strtotime($date));
                 $begin_date      = date('m-d', strtotime($holiday['begin_date']));
                 $end_date        = date('m-d', strtotime($holiday['end_date']));

### PR DESCRIPTION
**Pull request by ljpinho**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have performed a self-review of my code.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #22263
- Error opening and/or closing tickets

### CODE REVIEW

File: src/Calendar.php [hunk 1]
```diff
@@ -234,10 +234,19 @@ public function cleanDBonPurge()
...
+        // Validação: se $date for null ou vazio, retorna false
+        if (empty($date)) {
+            return false;
+        }
+
         $calendar_holiday = new Calendar_Holiday();
         $holidays = $calendar_holiday->getHolidaysForCalendar($this->fields['id']);
 
         foreach ($holidays as $holiday) {
+            // Validação adicional: verificar se begin_date e end_date não são null
```
Comment (trasher) [inline src/Calendar.php]:
```suggestion
            // CHeck if begin_date and end_date are not null or empty
```

File: src/Calendar.php [hunk 2]
```diff
@@ -234,10 +234,19 @@ public function cleanDBonPurge()
      **/
     public function isHoliday($date)
     {
+        // Validação: se $date for null ou vazio, retorna false
```
Comment (trasher) [inline src/Calendar.php]:
```suggestion
        // Check if date is null or emtpy
```

**Review by trasher — APPROVED** [review]

File: src/Calendar.php [hunk 3]
```diff
@@ -722,3 +731,4 @@ public static function getIcon()
         return "ti ti-calendar";
     }
 }
+
```
Comment (cedric-anne) [inline src/Calendar.php]:
```suggestion
```

**Comment by cedric-anne** [comment]
Thanks for the contribution.
