### PR TITLE
Fix multiple escaping issues in marketplace

### LINKED ISSUE #19922: GLPI 11 beta 5 - Marketplace - Display issue on plugin descriptions
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11 beta 5

### Bug description

Hello,

There is a display issue on plugins description.

Image

Image

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Fixes #19922

### CODE REVIEW

File: src/Glpi/Marketplace/View.php [hunk 1]
```diff
@@ -912,8 +806,8 @@ public static function getButtons(string $plugin_key = ""): string
                                        ' . _x("button", "Uninstall") . '
                                    </a>',
                 'content' => sprintf(
-                    __s('By uninstalling the "%s" plugin you will lose all the data of the plugin.'),
```
Comment (trasher) [inline src/Glpi/Marketplace/View.php:915]: This sounds weird we have to change a source string. Should not `__s()` behave the same than `htmlescape()`?

Comment (cconard96) [reply src/Glpi/Marketplace/View.php:915]: Well, translated strings could be used inside HTML attributes so quotes must be encoded to prevent XSS. `htmlspecialchars` encodes quotes by default.

Comment (cconard96) [reply src/Glpi/Marketplace/View.php:915]: Also `__s` is indeed just wrapping the translated string in a `htmlspecialchars` call with the default flags.

Comment (cedric-anne) [reply src/Glpi/Marketplace/View.php:915]: `__s` should not be used here, `content` is automatically escaped by the template. I fixed this.
