### PR TITLE
fix(forms): Add missing dropdown restriction parameters

### LINKED ISSUE #19969: Forms - Additional dropdown filtering needed
- Categories can be limited to request or incident types.
- Request sources can be configured to not apply to tickets themselves.
- Inactive dropdown items, like with request sources, are not filtered.
- Contract dropdown should ignore linked item limitation checks

There may be other relevant filtering, but those are the other ones I see just from looking at the ticket fields panel template.

_Originally posted by @cconard96 in https://github.com/glpi-project/glpi/issues/19967#issuecomment-2962700391_

### PR DESCRIPTION
**Pull request by ccailly**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

- It fixes #19969

Added restrictions on the items returned by the Item type question dropdown.
Added the `nochecklimit` option for Contracts.

### CODE REVIEW

**Comment by ccailly** [comment]
@cconard96 you mentioned in your issue the possibility of filtering ticket categories.
This is already possible with the advanced options in #19880.

> Request sources can be configured to not apply to tickets themselves

I'm not sure I've understood the limitations, can you tell me more?

**Comment by cconard96** [comment]
> @cconard96 you mentioned in your issue the possibility of filtering ticket categories. This is already possible with the advanced options in #19880.

OK. I missed that.

> > Request sources can be configured to not apply to tickets themselves
> 
> I'm not sure I've understood the limitations, can you tell me more?

RequestType items have a `is_ticketheader` field for "Request source visible for tickets". If a category has it set to No, it should not be an option for a ticket's request source, but it could still be a request source for a followup (which uses the "is_itilfollowup" field instead)

**Comment by ccailly** [comment]
> RequestType items have a `is_ticketheader` field for "Request source visible for tickets". If a category has it set to No, it should not be an option for a ticket's request source, but it could still be a request source for a followup (which uses the "is_itilfollowup" field instead)

I see. But I don't think we should condition `RequestSources` in questions.
A user isn't necessarily going to use the answer to the question as the `RequestSources` for the target created (ticket or otherwise for that matter).
Especially as it's not currently possible to set the value dynamically (this may be a problem, but it's not implemented in Formcreator either).
Here are the available strategies:
image

However, there's a problem here: no condition is applied when `Specific request source` is selected, allowing a `RequestSource` to be used for a ticket when it doesn't allow it.

File: src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php [hunk 1]
```diff
@@ -273,11 +274,20 @@ public function getDropdownRestrictionParams(?Question $question): array
                         ),
                     };
 
-                    $params[$itemtype::getTableField($key)] = 1;
+                    $type_params['AND']['OR'][] = [
+                        $itemtype::getTableField($key) => 1,
+                    ];
                 }
+
+                $params[] = $type_params;
```
Comment (cedric-anne) [inline src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php]: It does not change the result, but I find it easier to read and it will simplify the SQL criteria array.

```suggestion
                    $type_params[$itemtype::getTableField($key)] = 1;
                }

                $params[] = ['OR' => $type_params];
```

**Review by cedric-anne — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
