### PR TITLE
Fix $CFG_GLPI['root_doc'] computation

### LINKED ISSUE #6458: [9.2, 9.3, 9.4, 9.5] detectRootDoc() doesn't compute correct $CFG_GLPI["root_doc"] value when called via cron.php
Hello,

**Bug description**

When cron.php is started, the Config::detectRootDoc() method will wrongly set the $CFG_GLPI["root_doc"] to the string: "cron.php"

**To reproduce**

1. add the following code block at the end of the config.php file: 
```
$notiftarget = new NotificationTarget;
$item = new Ticket;
$item->getFromDB(1); // need to have a ticket in DB with id == 1
Toolbox::logInFile('php-errors', "CFG_GLPI['root_doc']: ".$CFG_GLPI["root_doc"]."\n".
                                 "URL: " . $notiftarget->formatURL(NotificationTarget::EXTERNAL_USER, urlencode($item->getLinkURL())).
                                 "\n", true);
```
2. start a command line terminal
3. go to glpi/front/ folder
4. start cron.php: `php cron.php 1`
5. look in the php error log file. you should see a line like: 

> 2019-10-11 15:36:58 [@FRY09565]
> CFG_GLPI['root_doc']: **cron.php**
> URL: http://../index.php?redirect=**cron.php**/front/ticket.form.php?id=1

**Expected behavior**

> 2019-10-11 15:36:58 [@FRY09565]
> CFG_GLPI['root_doc']: (= empty string)
> URL: http://.../index.php?redirect=/front/ticket.form.php?id=1

Thank you
Regards,
Tomolimo

### LINKED ISSUE #10614: Compute incorrect root_doc
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Good night, after much searching found a problem in the root_doc calculation on my server.
When I upload glpi on my server the calculated root_doc is never correct, I identified that it is because of the logic in the inc/config.class.php file.

before finding the directory of glpi($glpidir) the call "chdir(GLPI_ROOT);" it returns the disk in uppercase and when it calculates glpidir the path is wrong.

I solved it locally by changing str_replace to str_ireplace.
image

### Relevant log output

_No response_

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10614, #6458

- Ensure computation is based on realpath; fixes #10614
- Computation based on $CFG_GLPI['url_base'] on CLI context; fixes #6458

### CODE REVIEW

File: src/Config.php [hunk 1]
```diff
@@ -2480,33 +2480,61 @@ public static function getLanguage($lang)
...
+            $root_doc = str_replace($current_dir_relative, '', $request_dir_relative);
+            $root_doc = rtrim($root_doc, '/');
+
+            // urldecode for space redirect to encoded URL : change entity
+            // note: not sure this line is actually used
+            $root_doc = urldecode($root_doc);
+
+            $CFG_GLPI['root_doc'] = $root_doc;
+        } else {
+            // $_SERVER['REQUEST_URI'] is set, meaning that GLPI is probably acces from CLI.
```
Comment (orthagh) [inline src/Config.php:2526]:
```suggestion
            // $_SERVER['REQUEST_URI'] is not set, meaning that GLPI is probably acces from CLI.
```

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]
