### PR TITLE
Fix installation memory usage

### LINKED ISSUE #22173: Session::loadAllCoreLocales huge memory usage
This method load all locales files and messages, costing 50MB of memory.

This is huge, especially since GLPI memory recommandation is 64MB.

The installation use 126MB on GLPI 11 (versus 35MB on GLPI 10) so we need to either fix it or increase the recommendation.

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.

## Description

Install on GLPI 10 uses 38MB of memory:
image

On GLPI 11, it uses 126MB:
image

This PR reduce the memory overhead for the default form translation process by preventing all languages translation from being stored in the application memory.

The code is also simplified by calling `Form::listTranslationsHandlers()` rather than manually building the data for each translatable element.

After these changes, we drop back to 78MB (which is still too much BTW, we should keep looking into it):
image

## Reference

Fix #22173.

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
There is still an issue, the "description" question is not translated for some reason (I'll look into it tomorrow).

File: src/Toolbox.php [hunk 1]
```diff
@@ -2242,7 +2242,6 @@ public static function createSchema($lang = 'en_GB', ?DBmysql $database = null,
         $progress_indicator?->addMessage(MessageType::Success, __('Default data imported.'));
 
         $progress_indicator?->setProgressBarMessage(__('Creating default forms…'));
-        Session::loadAllCoreLocales();
```
Comment (trasher) [inline src/Toolbox.php:2245]: I guess the call from `Update` class is candidate to be removed, and `Session::loadAllCoreLocales` to deprecation, no?

Comment (AdrienClairembault) [reply src/Toolbox.php:2245]: Good call for the update, I'll delete it.

It can't be deprecated because the call is still done inside `addFormsTranslations` (I've just moved the call closer to where it is used).

File: src/Glpi/Helpdesk/DefaultDataManager.php [hunk 2]
```diff
@@ -131,53 +132,154 @@ public function initializeData(): void
...
+            // Standard translation
+            $translated_value = $TRANSLATE->translate(
+                $to_translate->getValue(),
+                'glpi',
+                $lang,
+            );
+        }
+
+        // The translate method of laminas says it return a string in its
+        // PHPDoc but this is a LIE, do not believe it.
```
Comment (trasher) [inline src/Glpi/Helpdesk/DefaultDataManager.php:200]: Laminas phpdocs are a nightmare -_-

File: src/Glpi/Helpdesk/DefaultDataManager.php [hunk 3]
```diff
@@ -131,53 +132,163 @@ public function initializeData(): void
...
+
+                if ($translated_value === null) {
+                    continue;
+                }
+
+                // Make sure a real translation exist for this value
+                // TODO: in this case, is there a point to saving the data,
+                // can't we just skip the value with a `continue;` statement?
+                // I didn't risk it when rewritting this code but maybe we can
+                // investigate this later.
```
Comment (cedric-anne) [inline src/Glpi/Helpdesk/DefaultDataManager.php:261]: As far as I remember, the purpose is to items already initialized so they appears properly in the translation UI.

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]
