### PR TITLE
Use a custom `htmlescape()` function to handle unexpected null values

### LINKED ISSUE #17933: [main] deprecated htmlspecialchars error in setup > general > assistance (planning dropdowns)
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

main

### Bug description

front/config.form.php > Assistance tab > "Limit of the schedules for planning" dropdowns.

```
[2024-09-25 14:02:36] glpiphplog.INFO:   *** PHP Deprecated function (8192): htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /www/glpi-core/main/htdocs/src/Dropdown.php at line 2308
  Backtrace :
  src/Dropdown.php:2308                              htmlspecialchars()
  src/Dropdown.php:1580                              Dropdown::showFromArray()
  :                                                  Dropdown::showHours()
  .../Application/View/Extension/PhpExtension.php:91 call_user_func_array()
  ...es/85/858ef281925101dbc1f9a7bee22da4e5.php:1976 Glpi\Application\View\Extension\PhpExtension->call()
  .../twig/twig/src/Extension/CoreExtension.php:1919 __TwigTemplate_ce9da0a3a722f5ababa00f7437c3ff27->{closure}()
  ...es/85/858ef281925101dbc1f9a7bee22da4e5.php:1973 Twig\Extension\CoreExtension::captureOutput()
  .../twig/twig/src/Extension/CoreExtension.php:1919 __TwigTemplate_ce9da0a3a722f5ababa00f7437c3ff27->{closure}()
  ...es/85/858ef281925101dbc1f9a7bee22da4e5.php:1933 Twig\Extension\CoreExtension::captureOutput()
  .../twig/twig/src/Extension/CoreExtension.php:1293 __TwigTemplate_ce9da0a3a722f5ababa00f7437c3ff27->macro_dropdownHoursField()
  ...ates/0d/0d9f7b1f090925f4856910540e74bf77.php:76 Twig\Extension\CoreExtension::callMacro()
  .../twig/twig/src/Extension/CoreExtension.php:1919 __TwigTemplate_76cf77bfaf131aa5103c0aed3ce4d43d->{closure}()
  ...ates/0d/0d9f7b1f090925f4856910540e74bf77.php:71 Twig\Extension\CoreExtension::captureOutput()
  vendor/twig/twig/src/Template.php:437              __TwigTemplate_76cf77bfaf131aa5103c0aed3ce4d43d->block_config_fields()
  ...ates/21/215a65ca6d065fd44c0a3f140b6c17da.php:68 Twig\Template->yieldBlock()
  vendor/twig/twig/src/Template.php:393              __TwigTemplate_0c51b1aea3bb967921c6f458701d0ce3->doDisplay()
  ...ates/0d/0d9f7b1f090925f4856910540e74bf77.php:54 Twig\Template->yield()
  vendor/twig/twig/src/Template.php:393              __TwigTemplate_76cf77bfaf131aa5103c0aed3ce4d43d->doDisplay()
  vendor/twig/twig/src/Template.php:349              Twig\Template->yield()
  vendor/twig/twig/src/TemplateWrapper.php:42        Twig\Template->display()
  src/Glpi/Application/View/TemplateRenderer.php:185 Twig\TemplateWrapper->display()
  src/Config.php:608                                 Glpi\Application\View\TemplateRenderer->display()
  src/Config.php:1440                                Config->showFormHelpdesk()
  src/CommonGLPI.php:665                             Config::displayTabContentForItem()
  ajax/common.tabs.php:110                           CommonGLPI::displayStandardTab()
  ...Glpi/Controller/LegacyFileLoadController.php:58 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  public/index.php:58                                Symfony\Component\HttpFoundation\Response->send()
```

image

### Relevant log output

_No response_

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cedric-anne**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.

## Description

Fixes #17933.

There are many places in our code where `htmlspecialchars()` may be call for a null value (or even an integer, a float, ...). Instead of using the `?? ''` to fix occurences that triggers a deprecation notice, I propose to use a custom `htmlescape()` function that ensures that non-string legitimate values are correctly handled.

### CODE REVIEW

File: src/AuthLDAP.php [hunk 1]
```diff
@@ -3882,13 +3882,13 @@ public static function showUserImportForm(AuthLDAP $authldap)
...
                     echo "<tr><td style='width: 250px' class='text-end'><label for='basedn'>" . __('BaseDN') . "</label></td><td colspan='3'>";
-                    echo "<input type='text' class='form-control' id='basedn' name='basedn' value=\"" . htmlspecialchars($_SESSION['ldap_import']['basedn'], ENT_QUOTES) .
+                    echo "<input type='text' class='form-control' id='basedn' name='basedn' value=\"" . htmlescape($_SESSION['ldap_import']['basedn'], ENT_QUOTES) .
                      "\" " . (!$_SESSION['ldap_import']['basedn'] ? "disabled" : "") . ">";
                     echo "</td></tr>";
 
                     echo "<tr><td class='text-end'><label for='ldap_filter'>" . __('Search filter for users') . "</label></td><td colspan='3'>";
                     echo "<input type='text' class='form-control' id='ldap_filter' name='ldap_filter' value=\"" .
-                      htmlspecialchars($_SESSION['ldap_import']['ldap_filter'], ENT_QUOTES) . "\">";
+                      htmlescape($_SESSION['ldap_import']['ldap_filter'], ENT_QUOTES) . "\">";
```
Comment (trasher) [inline src/AuthLDAP.php:3891]:
```suggestion
                      htmlspecialchars($_SESSION['ldap_import']['ldap_filter'] ?? '', ENT_QUOTES) . "\">";
```

Comment (trasher) [reply src/AuthLDAP.php:3891]: CS is complaining about several issues like this one. LGTM appart of that.

**Comment by cedric-anne** [comment]
Required for #17981.

**Review by trasher — APPROVED** [review]

**Review by AdrienClairembault — APPROVED** [review]
