### PR TITLE
[11.0] Fix read only fields saved update in database

### LINKED ISSUE #21046: GLPI 11 : customs assets, it's possible to update a read-only field
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0/bugfixes

### Bug description

I set a field to read-only in my asset definition.

Image

In the interface, I can select the field, but the input is disabled.

Image

However, by modifying the DOM (by removing ```readonly=""```), the field becomes editable again, and saving the form correctly records the change.

Image

Value changed:

Image

### PR DESCRIPTION
**Pull request by froozeify**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

- It fixes #21046
- User could update a readonly field value and saved it. The input would be saved in the database.
- Update DbTestCase assertion on input to support array (in the case here, the array is json_encoded after, currently was throwing an error due to a string comparison on an array)

### CODE REVIEW

File: src/Glpi/Asset/Asset.php [hunk 1]
```diff
@@ -416,12 +416,69 @@ public function prepareInputForAdd($input)
...
         return $this->prepareDefinitionInput($input);
     }
 
+    protected function handleReadonlyFieldUpdate($input): array
+    {
+        try {
+            $profileId = Session::getCurrentProfile()->getId();
+        } catch (\Exception) {
+            return $input;
+        }
```
Comment (cedric-anne) [inline src/Glpi/Asset/Asset.php]: I think it is preferable to not silently catch all exceptions here.

```suggestion
        $profileId = $_SESSION['glpiactiveprofile']['id'] ?? null
        if ($profileId === null) {
            return $input;
        }
```

File: src/Glpi/Asset/Asset.php [hunk 2]
```diff
@@ -416,12 +416,82 @@ public function prepareInputForAdd($input)
...
+
+        return $input;
+    }
+
+    /**
+     * Determine if a field is readonly for the current active profile.
+     *
+     * @param array|string $field_options
+     * @return bool
```
Comment (cedric-anne) [inline src/Glpi/Asset/Asset.php]: The signature already provide types.

```suggestion
```

File: src/Glpi/Asset/Asset.php [hunk 3]
```diff
@@ -416,12 +416,82 @@ public function prepareInputForAdd($input)
...
+     */
+    private function isReadonlyForCurrentProfile(mixed $field_options): bool
+    {
+        $profile_id = $_SESSION['glpiactiveprofile']['id'] ?? null;
+        if ($profile_id === null) {
+            return false;
+        }
+
+        if (empty($field_options) || !array_key_exists('readonly', (array) $field_options)) {
```
Comment (cedric-anne) [inline src/Glpi/Asset/Asset.php]:
```suggestion
        if (!is_array($field_options) || !array_key_exists('readonly', $field_options)) {
```

File: src/Glpi/Asset/Asset.php [hunk 4]
```diff
@@ -416,12 +416,82 @@ public function prepareInputForAdd($input)
...
+        if (is_array($readonly_profile_ids)) {
+            return in_array($profile_id, $readonly_profile_ids, true);
+        }
+
+        if (is_string($readonly_profile_ids) || is_int($readonly_profile_ids)) {
+            // accept int or string profile identifiers
+            return (string) $profile_id === (string) $readonly_profile_ids;
+        }
+
+        return false;
```
Comment (cedric-anne) [inline src/Glpi/Asset/Asset.php:471]: IMHO, we should consider that `$field_options['readonly']` is always an array. Trying to handle other types may hide some issues in the settings logic.

```suggestion
        return in_array($profile_id, $readonly_profile_ids, true);
```

Maybe the JSON contains strings, so it is also possible to cast values.
`return in_array((int) $profile_id, array_map('intval', $readonly_profile_ids), true);`

File: phpunit/functional/Glpi/Asset/AssetTest.php [hunk 5]
```diff
@@ -184,6 +184,48 @@ public function testPrepareInputForAdd()
...
+        $asset_settings['field_options']['readonly'][] = $user_profile->getID();
+        $this->createItem(CustomFieldDefinition::class, $asset_settings);
+
+        $asset_definition->getFromDB($asset_definition->getID());
+
+        $asset = new ($asset_definition->getAssetClassName());
+        $input = $asset->prepareInputForAdd([
+            'custom_test2_string' => 'test',
+        ]);
+        $this->assertEquals('[]', $input['custom_fields']);
```
Comment (cedric-anne) [inline phpunit/functional/Glpi/Asset/AssetTest.php]:
```suggestion
        $this->assertArrayNotHasKey('custom_test2_string', $input);
        $this->assertEquals('[]', $input['custom_fields']);
```

File: phpunit/functional/Glpi/Asset/AssetTest.php [hunk 6]
```diff
@@ -184,6 +184,48 @@ public function testPrepareInputForAdd()
...
+        $string_field = $this->createItem(CustomFieldDefinition::class, $asset_settings);
+
+        $asset_definition->getFromDB($asset_definition->getID());
+
+        $asset = new ($asset_definition->getAssetClassName());
+        $input = $asset->prepareInputForAdd([
+            'custom_test_string' => 'test',
+        ]);
+        $this->assertEquals(json_encode([$string_field->getID() => 'test']), $input['custom_fields']);
+        $this->assertEquals('test', $input['custom_test_string']);
```
Comment (cedric-anne) [inline phpunit/functional/Glpi/Asset/AssetTest.php:214]:
```suggestion
        $this->assertEquals('test', $input['custom_test_string']);
        $this->assertEquals(json_encode([$string_field->getID() => 'test']), $input['custom_fields']);
```

File: src/Glpi/Asset/Asset.php [hunk 7]
```diff
@@ -416,12 +416,82 @@ public function prepareInputForAdd($input)
...
+    }
+
+    /**
+     * Ensure the input value for a readonly field is the persisted value.
+     */
+    private function applyPersistedReadonlyValue(array $input, string $field_name): array
+    {
+        if (array_key_exists($field_name, $this->fields)) {
+            $input[$field_name] = $this->fields[$field_name];
```
Comment (cedric-anne) [inline src/Glpi/Asset/Asset.php:480]: This case is not tested.

File: src/Glpi/Asset/Asset.php (hunk 4 above)
Comment (froozeify) [reply src/Glpi/Asset/Asset.php:471]: I've seen in some case the $field_options['readonly'] beeing an empty string. For example in locations_id field, but it could be the default value instead of being an empty array. I'll have to  take a look to find were it's firstly created

Comment (froozeify) [reply src/Glpi/Asset/Asset.php:471]: Just tested and I confirm sometime a string is sended and not an array

File: src/Glpi/Asset/Asset.php [hunk 8]
```diff
@@ -416,12 +416,74 @@ public function prepareInputForAdd($input)
...
     {
         $input = $this->prepareGroupFields($input);
-
+        $input = $this->handleReadonlyFieldUpdate($input);
         $input = $this->handleCustomFieldsUpdate($input);
 
         return $this->prepareDefinitionInput($input);
     }
 
+    protected function handleReadonlyFieldUpdate(array $input): array
```
Comment (cedric-anne) [inline src/Glpi/Asset/Asset.php]:
```suggestion
    private function handleReadonlyFieldUpdate(array $input): array
```

**Review by cedric-anne — APPROVED** [review]
