### PR TITLE
fix plugin join handling

### LINKED ISSUE #20622: [GLPI 11.0 RC2] Exception during Search Computers with plugin TAG
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11.0 RC2

### Bug description

During test of V 11.0 RC2 with version beta of plugin TAG, an exception occurs when searching with tag.

### Relevant log output

```shell
An exception has been thrown during the rendering of a template ("Glpi\Search\Provider\SQLProvider::parseJoinString(): Argument #1 ($raw_joins) must be of type string, array given, called in ./src/Glpi/Search/Provider/SQLProvider.php on line 2848") in "pages/generic_list.html.twig" at line 37.
In ./templates/pages/generic_list.html.twig(37)
#0 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
#1 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
#2 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
#3 ./src/Glpi/Application/View/TemplateRenderer.php(168): Twig\TemplateWrapper->render()
#4 ./src/Glpi/Controller/AbstractController.php(68): Glpi\Application\View\TemplateRenderer->render()
#5 ./src/Glpi/Controller/GenericListController.php(51): Glpi\Controller\AbstractController->render()
#6 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\GenericListController->__invoke()
#7 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#8 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#9 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle()
#10 {main}

Previous: Glpi\Search\Provider\SQLProvider::parseJoinString(): Argument #1 ($raw_joins) must be of type string, array given, called in ./src/Glpi/Search/Provider/SQLProvider.php on line 2848
In ./src/Glpi/Search/Provider/SQLProvider.php(2663)
#0 ./src/Glpi/Search/Provider/SQLProvider.php(2848): Glpi\Search\Provider\SQLProvider::parseJoinString()
#1 ./src/Search.php(720): Glpi\Search\Provider\SQLProvider::getLeftJoinCriteria()
#2 ./src/Glpi/Search/Provider/SQLProvider.php(4183): Search::addLeftJoin()
#3 ./src/Glpi/Search/SearchEngine.php(656): Glpi\Search\Provider\SQLProvider::constructSQL()
#4 ./src/Glpi/Search/SearchEngine.php(672): Glpi\Search\SearchEngine::getData()
#5 ./src/Glpi/Search/SearchEngine.php(629): Glpi\Search\SearchEngine::showOutput()
#6 [internal function]: Glpi\Search\SearchEngine::show()
#7 ./src/Glpi/Application/View/Extension/PhpExtension.php(93): call_user_func_array()
#8 /var/lib/glpi110/_cache/11.0.0-rc2-040d3081-production/templates/26/261cdf48e21cbd3217b514b88e1621a0.php(55): Glpi\Application\View\Extension\PhpExtension->call()
#9 ./vendor/twig/twig/src/Template.php(402): __TwigTemplate_cfad014b18affc2a8081a995b8e7464d->doDisplay()
#10 ./vendor/twig/twig/src/Template.php(358): Twig\Template->yield()
#11 ./vendor/twig/twig/src/Template.php(373): Twig\Template->display()
#12 ./vendor/twig/twig/src/TemplateWrapper.php(51): Twig\Template->render()
#13 ./src/Glpi/Application/View/TemplateRenderer.php(168): Twig\TemplateWrapper->render()
#14 ./src/Glpi/Controller/AbstractController.php(68): Glpi\Application\View\TemplateRenderer->render()
#15 ./src/Glpi/Controller/GenericListController.php(51): Glpi\Controller\AbstractController->render()
#16 ./vendor/symfony/http-kernel/HttpKernel.php(181): Glpi\Controller\GenericListController->__invoke()
#17 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#18 ./vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#19 ./public/index.php(70): Symfony\Component\HttpKernel\Kernel->handle()
#20 {main}
```

### Page URL

http://xxxx.yyyyy.zzzz/front/computer.php

### Steps To reproduce

1. Install V 11.0 RC2 with datas saved from production site,
2. Install version beta of TAG compatible with this GLPI Version (OK),
3. Activate plugin TAG -OK,
4. Search some computers (OK),
5. Search some computers with one TAG (KO)

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0-rc2 (/glpi11 => /var/www/glpi110)
Installation mode: TARBALL
Current language: fr_FR</pre></details><details><summary>Server</summary><pre>Operating system: Linux Serveur 6.6.87.2-microsoft-standard-WSL2 #​1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025
x86_64

PHP: 8.4.11 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv,
igbinary, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm,
tokenizer, xmlreader, xmlwriter, xsl, zip, redis, Zend OPcache

Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="redis"
upload_max_filesize="2M" disable_functions="" 

Web server: Apache/2.4.58 (Ubuntu) (Apache/2.4.58 (Ubuntu) Server at glpi.localhost Port 80)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Iron Safari/537.36

Database:
   
Server Software: mariadb.org binary distribution
   
Server Version: 11.4.8-MariaDB-ubu2404
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi_user@localhost/glpi110
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.4.11) is supported.
OS and PHP are relying on 64 bits
integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The
constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (11.4.8) is
supported.
The log file has been created
successfully.
Write access to
/var/lib/glpi110/_cache has been validated.
Write access to /var/lib/glpi110/_cron has been validated.
Write access to /var/lib/glpi110 has been validated.
Write access to /var/lib/glpi110/_graphs has been validated.
Write access to /var/lib/glpi110/_lock has been validated.
Write access to /var/lib/glpi110/_pictures has been validated.
Write access to /var/lib/glpi110/_plugins has been validated.
Write access to /var/lib/glpi110/_rss has been validated.
Write access to /var/lib/glpi110/_sessions has been validated.
Write access to /var/lib/glpi110/_tmp has been validated.
Write access to /var/lib/glpi110/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are
installed: bz2, Phar, zip.
Zend OPcache extension is installed
Following extensions are
installed: ctype, iconv, sodium.
Write access to
/var/www/glpi110/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: "/var/www/glpi110"
GLPI_VERSION: "11.0.0-rc2"
GLPI_SCHEMA_VERSION: "11.0.0-rc2@7ed75826524089b643d5b6cbe144c97b30787fb7"
GLPI_FILES_VERSION: "11.0.0-rc2-040d3081"
GLPI_MIN_PHP: "8.2"
GLPI_MAX_PHP: "8.4"
GLPI_YEAR: "2025"
GLPI_I18N_DIR: "/var/www/glpi110/locales"
GLPI_CONFIG_DIR: "/etc/glpi110/"
GLPI_VAR_DIR: "/var/lib/glpi110"
GLPI_LOG_DIR: "/var/log/glpi110"
GLPI_OAUTH_ACCESS_TOKEN_EXPIRES: 300
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi110/_locales"
GLPI_ENVIRONMENT_TYPE: "production"
GLPI_MARKETPLACE_DIR: "/var/www/glpi110/marketplace"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&'\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD"]
GLPI_DISALLOWED_UPLOADS_PATTERN: "/\\.(php\\d*|phar)$/i"
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DOCUMENTATION_ROOT_URL: "https://links.glpi-project.org"
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_LOG_LVL: "warning"
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: "1"
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: "4000"
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: "0"
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_DOC_DIR: "/var/lib/glpi110"
GLPI_CACHE_DIR: "/var/lib/glpi110/_cache"
GLPI_CRON_DIR: "/var/lib/glpi110/_cron"
GLPI_GRAPH_DIR: "/var/lib/glpi110/_graphs"
GLPI_LOCK_DIR: "/var/lib/glpi110/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi110/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi110/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi110/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi110/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi110/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi110/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi110/_inventories"
GLPI_THEMES_DIR: "/var/lib/glpi110/_themes"
GLPI_PLUGINS_DIRECTORIES: ["/var/www/glpi110/marketplace","/var/www/glpi110/plugins"]
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"</pre></details><details><summary>Annuaires LDAP</summary><pre>Server: 'ldaps://xxxx.yyyy.zzzz', 
	Port: '636', 
	BaseDN: 'ou=yyyyy,dc=zzzz', 
	Connection filter: '(&(objectClass=arPersonne)(uid=*))', 
	RootDN: 'ou=GLPB,ou=arApplications,ou=Recouvrement,dc=recouv', 
	Use TLS: none

Server: 'ldap://xxxx.yyyy.zzzz', 
	Port: '389', 
	BaseDN: 'DC=urdom,DC=ad,DC=recouv', 
	Connection filter: '(&(objectClass=user)(objectCategory=person)(mail=*))', 
	RootDN: 'urdom\AC750T2603', 
	Use TLS: none

Server: 'ldap://xxxx.yyyy.zzzz', 
	Port: '389', 
	BaseDN: 'ou=yyyyy,dc=zzzz', 
	Connection filter: '(objectClass=anaisUser)', 
	RootDN: 'cn=USR_READ_NAT_APP_GLPI,ou=GLPI,ou=Applications,OU=Technique,dc=zzzz', 
	Use TLS: none

Server: 'ldaps://xxxx.yyyy.zzzz', 
	Port: '636', 
	BaseDN: 'ou=yyyyy,dc=zzzz', 
	Connection filter: '(&(objectClass=arPersonne)(uid=*)(nsAccountLock=FALSE))', 
	RootDN: 'ou=GLPB,ou=arApplications,ou=yyyy,dc=zzzz', 
	Use TLS: none

Server: 'ldaps://xxxx.yyyy.zzzz', 
	Port: '636', 
	BaseDN: 'ou=yyyy,dc=zzzz', 
	Connection filter: '(&(objectClass=arPersonne)(uid=*)(nsAccountLock=FALSE))', 
	RootDN: 'ou=GLPB,ou=arApplications,ou=yyyyy,dc=zzzz', 
	Use TLS: none</pre></details><details><summary>Réplicats SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://smtp.km.recouv:25)</pre></details><details><summary>Plugins list</summary><pre>cnpsynchro           Name: cnpsynchro                     Version: 0.8.0      State: Activé                                 
Install Method: Manual
datainjection        Name: Data injection                 Version: 2.15.0-beta1 State: Activé                                 
Install Method: Manual
pdf                  Name: Print to pdf                   Version: 4.1.0-beta2 State: Activé                                 
Install Method: Manual
tag                  Name: Tag Management                 Version: 2.13.0-beta4 State: Activé                                 
Install Method: Manual
treeview             Name: Tree view                      Version: 1.20.0-beta1 State: Activé                                 
Install Method: Manual</pre></details><details><summary>Locales overrides</summary><pre>/var/lib/glpi110/_locales/core/fr_FR.mo</pre></details>

### Anything else?

This issue seems to be link with this one=> https://github.com/glpi-project/glpi/issues/20050

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Fixes #20622

### CODE REVIEW

**Comment by stonebuzz** [comment]
Highly impactful: 
any plugin that adds *search options* without implementing the `plugin_myplugin_addLeftJoin` hook will trigger a fatal error as soon as a search option is added.

**Comment by cconard96** [comment]
> Highly impactful: any plugin that adds _search options_ without implementing the `plugin_myplugin_addLeftJoin` hook will trigger a fatal error as soon as a search option is added.

Is that a separate issue after this patch is applied?
Can you confirm the plugin(s) work with this fix without any other issues?

**Comment by stonebuzz** [comment]
it works correctly with this PR

File: src/Glpi/Search/Provider/SQLProvider.php [hunk 1]
```diff
@@ -2814,7 +2814,6 @@ public static function getLeftJoinCriteria(
             $specific_leftjoin_criteria = Plugin::doOneHook($plugin_name, $hook_closure);
             $specific_leftjoin_criteria ??= []; // convert null into an empty array
             if (!is_array($specific_leftjoin_criteria)) {
-                // Toolbox::deprecated('Plugin hook ' . $hook_function . ' should return an array of join criteria');
```
Comment (trasher) [inline src/Glpi/Search/Provider/SQLProvider.php:2817]: Hum... I do not know why it's not yet deprecated, but sounds like it really should one day, no?

**Comment by trasher** [comment]
Also, I guess it should be possible to add a test case

File: src/Glpi/Search/Provider/SQLProvider.php (hunk 1 above)
Comment (cconard96) [reply src/Glpi/Search/Provider/SQLProvider.php:2817]: The consequence of not being allowed to finish the refactor/DBAL stuff I planned, having the original release plan be for this to have been a minor version 10.1, and expecting a sooner release. It is too late now and even when it wasn't, I thought there were enough issues getting plugins compatible with GLPI 11 so it was left as an optional change to use the new format.

The search engine still relies on converting the array format to a raw strings in the `constructSQL` part.

Comment (cedric-anne) [reply src/Glpi/Search/Provider/SQLProvider.php:2817]: I noticed 2 weeks ago that we should have deprecated this, but the RC released was already published.
We should deprecate all this kind of result from plugin hooks it in GLPI 11.1, but for GLPI 11.0 it is too late.

Comment (trasher) [reply src/Glpi/Search/Provider/SQLProvider.php:2817]: In that case, we usually keep the depreciation commented with a fixme for the new version
