### PR TITLE
fix(entity): Creating a child entity will redirect the user to an exception page

### LINKED ISSUE #21497: Problem with entity creation
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11

### Bug description

Hello, 

When i create an new entity, i have this message error (Debug mode)

I test with my account (ldap) superadmin and glpi local admin account. 

Thank you for your help.

### Relevant log output

```shell
User ID: `713` tried to execute an invalid request on `/front/entity.form.php?id=11`.
  Additional information: Missing READ right. Cannot view the item.
  Backtrace :
  ./src/CommonDBTM.php:6499
  .../Glpi/Controller/DropdownFormController.php:213 CommonDBTM::displayFullPageForItem()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\DropdownFormController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

```
<details><summary>GLPI information</summary><pre>GLPI: 11.0.0 ( =&gt; /var/www/html/glpi)
Installation mode: TARBALL
Current language: fr_FR</pre></details><details><summary>Server</summary><pre>Operating system: Linux srv-info 6.1.0-40-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.153-1 (2025-09-20) x86_64

PHP: 8.2.29 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext,
iconv, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem,
sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;60&quot; max_input_vars=&quot;5000&quot; memory_limit=&quot;256M&quot; post_max_size=&quot;20M&quot;
session.cookie_secure=&quot;1&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;20M&quot; 

Web server: Apache/2.4.65 (Debian) (Apache/2.4.65 (Debian) Server at srv-info Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36
Edg/141.0.0.0

Database:
   
Server Software: Debian 12
   
Server Version: 10.11.14-MariaDB-0+deb12u2
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@localhost/glpi
   
Host info: Localhost via UNIX socket

Requirements:
PHP version (8.2.29) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.14) is
supported.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/html/glpi&quot;
GLPI_VERSION: &quot;11.0.0&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.0@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.0-f682f73d&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/etc/glpi/&quot;
GLPI_VAR_DIR: &quot;/var/lib/glpi&quot;
GLPI_LOG_DIR: &quot;/var/log/glpi&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/lib/glpi&quot;
GLPI_CACHE_DIR: &quot;/var/lib/glpi/_cache&quot;
GLPI_CRON_DIR: &quot;/var/lib/glpi/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/lib/glpi/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/lib/glpi/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/lib/glpi/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/lib/glpi/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/lib/glpi/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/lib/glpi/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/lib/glpi/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/lib/glpi/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/lib/glpi/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/lib/glpi/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/lib/glpi/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi/marketplace&quot;,&quot;/var/www/html/glpi/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>Annuaires LDAP</summary><pre>Server: &#39;192.168.74.99&#39;, 
	Port: &#39;389&#39;, 

Server: &#39;192.168.75.10&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;DC=annecy,DC=technology,DC=local&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;administrateur&#39;, 
	Use TLS: none</pre></details><details><summary>Réplicats SQL</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://192.168.74.163:25?verify_peer=0)</pre></details><details><summary>Plugins list</summary><pre>accounts             Name: Accounts                       Version: 3.1.1      State: Activé                                 
Install Method: Marketplace
webapplications      Name: Appliance dashboard            Version: 5.1.1      State: Non installé                           
Install Method: Marketplace
datainjection        Name: Data injection                 Version: 2.15.0     State: Activé                                 
Install Method: Marketplace
escalade             Name: Escalation                     Version: 2.10.0     State: Activé                                 
Install Method: Marketplace
formcreator          Name: Formcreator End-of-Life Update Version: 3.0.0      State: Installé / non activé                 
Install Method: Marketplace
gantt                Name: gantt                          Version: 1.2.0      State: Activé                                 
Install Method: Marketplace
genericobject        Name: Generic Objects End-of-Life Up Version: 3.0.0      State: Activé                                 
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.0      State: Activé                                 
Install Method: Marketplace
pdf                  Name: Impression pdf                 Version: 4.1.0      State: Activé                                 
Install Method: Marketplace
addressing           Name: IP Addressing                  Version: 3.1.0      State: Activé                                 
Install Method: Marketplace
metabase             Name: Metabase                       Version: 1.4.0      State: Activé                                 
Install Method: Marketplace
mreporting           Name: More Reporting                 Version: 1.9.0      State: Activé                                 
Install Method: Marketplace
moreticket           Name: More ticket                    Version: 1.8.0      State: Activé                                 
Install Method: Marketplace
mydashboard          Name: My Dashboard                   Version: 2.2.2      State: Activé                                 
Install Method: Marketplace
order                Name: Orders management              Version: 2.12.0     State: Activé                                 
Install Method: Marketplace
useditemsexport      Name: Used items export              Version: 2.6.0      State: Activé                                 
Install Method: Marketplace</pre></details>
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by froozeify**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

- It fixes #21497

Creating a subentity the form will redirect the user to it , but since the user has activated an entity, he won't have access.

This PR is the implementation of my proposal number 3 : https://github.com/glpi-project/glpi/issues/21497#issuecomment-3467508534

### Before

[Screencast from 2025-11-03 09-52-19.webm](https://github.com/user-attachments/assets/e86ccf84-0ced-4aab-9250-678d8bbfbb15)

### After
The message is only visible (and save button disabled) when the recursive is not enabled (on a multi-entity context)

image
image

### CODE REVIEW

File: src/Entity.php [hunk 1]
```diff
@@ -751,12 +751,8 @@ public function post_getFromDB()
...
     {
         parent::post_addItem();
-
-        // Add right to current user - Hack to avoid login/logout
-        $_SESSION['glpiactiveentities'][$this->fields['id']] = $this->fields['id'];
-        $_SESSION['glpiactiveentities_string']              .= ",'" . $this->fields['id'] . "'";
-        // Root entity cannot be deleted, so if we added an entity this means GLPI is now multi-entity
-        $_SESSION['glpi_multientitiesmode'] = 1;
+        // We force the recursivity, so the new entity is visible in the current session
+        Session::changeActiveEntities(Session::getActiveEntity(), true);
```
Comment (AdrienClairembault) [inline src/Entity.php]: Do we need to check that the user is allowed to see recursive content?

I think the "add entity" action is only available for users that can see recursive content anyway but I guess it doesn't hurt to check twice here?

Not a mandatory change, just wondering out loud.

Comment (cedric-anne) [reply src/Entity.php]: IMHO, we must only add the newly created entity to the active scope. The existing hack was probably incomplete, maybe only updating one or two more session variables is enough.

**Comment by trasher** [comment]
ping?

**Comment by froozeify** [comment]
After debugging the root cause of the existing hack, we have identify the cause: 

Once the `entity.form.php` is submitted (the session is well updated with `$_SESSION['glpiactiveentities']`  as  in the code), then the user is redirect to that newly entity created page and we got that error (now `$_SESSION['glpiactiveentities']` is set as before and don't have the newly created entity in it).

After investigating, the issue is located under `Session::shouldReloadActiveEntities` that return true in that case because inside it `count($entities)` will return 1 compared to the 2 we now have

image

We are in a state were we have 2 entities enabled (and not in a `recursive` state).   
I'm not sure GLPI had that case/state before.

After talking a bit @cedric-anne we should exchange on how we could implement a fix.   

Here are some proposal:

1. Enabling is_recursive - could a bit too violent/wide
2. When the user land on the form automatically switch to the tree structure - could  also be a bit dangerous since the administrator won't know it's Entity filtering has changed.
3. We could also display a warning on the form if the user is not in a `Entity tree structure` mode and disabling the form submission

Ping @AdrienClairembault @trasher

**Comment by froozeify** [comment]
We should go for choice 4 : Display a warning on the form and in that case don't redirect the user after the creation

**Comment by AdrienClairembault** [comment]
I think we are missing the point.

If a user is logged into a specific entity with recursion disabled, then he should not be allowed to create entities at all (since he won't be able to see them anyway).

So the issue is not the error, which is correct.
The issue is that the "add" button should not be available in this case.

**Comment by trasher** [comment]
> If a user is logged into a specific entity with recursion disabled, then he should not be allowed to create entities at all (since he won't be able to see them anyway).
> 
> So the issue is not the error, which is correct. The issue is that the "add" button should not be available in this case.

If that solution is correct, I guess this would be the best one.


> We should go for choice 4 : Display a warning on the form and in that case don't redirect the user after the creation

Or we could go for that.
I'm against forcing anything (proposals 1 and 2); that seems really incorrect.

**Comment by cedric-anne** [comment]
> > If a user is logged into a specific entity with recursion disabled, then he should not be allowed to create entities at all (since he won't be able to see them anyway).
> > So the issue is not the error, which is correct. The issue is that the "add" button should not be available in this case.
> 
> If that solution is correct, I guess this would be the best one.
> 
> > We should go for choice 4 : Display a warning on the form and in that case don't redirect the user after the creation
> 
> Or we could go for that. I'm against forcing anything (proposals 1 and 2); that seems really incorrect.

When installing a fresh instance of GLPI, I think the initial entity scope is not recursive. We have to ensure that the `add` button is still available to be able to create child entities.

For me, the solution would be:
 - if GLPI is not yet in "multi entities mode", then creating an entity result in switching the session to the "show full structure" mode;
 - if GLPI already has multiple entities, disable the "add" button and show a warning to explain that entities can only be created in recursive mode, with a button to switch to recursive mode.

**Comment by trasher** [comment]
> Also I am unsure about "you must be in entity recursivity mode", I don't know if all users will understand because "recursive" is not shown often in the UI, it is more of a technical name. Maybe "You can't create child entities because your session is restricted to the current entity."?

Indeed, users maye not understand "recursive", but "restricted to the current entity" does not seem correct either. "recursive" should be replaced with "tree structure" like entities selector?

File: src/Entity.php [hunk 2]
```diff
@@ -692,16 +709,60 @@ public static function displayTabContentForItem(CommonGLPI $item, $tabnum = 1, $
...
+                ],
+            ];
+        }
+
+        return $fields;
+    }
+
+    public static function getMissingPermissionsHtmlAlert(): string
+    {
+        $message = __s("To create a child entity, you must be in entity recursivity mode.");
```
Comment (trasher) [inline src/Entity.php]: Maybe:
```suggestion
        $message = __s("To create a child entity, you must enable entity tree structure.");
```

**Comment by froozeify** [comment]
> How about using a session message instead of truncating the form render?
> It is not great for UX because all inputs are lost but this form only has two inputs so I guess it would be OK here and more consistant with others similar checks.

The goal was to disable the possibility to save the form so the user know he have to activate the tree view mode. 
That's why I disabled the actions (only `+ Add` in the video) and display an alert banner so the user could well see it.

I'm afraid that just displaying the alert on the bottom right, the user won't see it and still go to save it. 
I had take a look at letting the actions buttons and just disabling the save button (so clicking on it won't have done anything) but this will require some heavy modification as this form use the generic  twig from `CommonDropdown::showForm` and inside it then  `components/form/buttons.html.twig`

**Comment by trasher** [comment]
> I'm afraid that just displaying the alert on the bottom right, the user won't see it and still go to save it.

Well.. That's the way GLPI currently display errors. A new way, even if better, won't be consistent.

**Comment by froozeify** [comment]
Blocking the Entity creation in the `prepareInputForAdd` method wasn't working as it will [break the CI execution](https://github.com/glpi-project/glpi/actions/runs/19923842894/job/57118871779?pr=21761).

After talking with cedric the solution, we found, was in that case to disable the creation via `canCreate` and display the error message on the form listing page.

**Comment by AdrienClairembault** [comment]
> After talking with cedric the solution, we found, was in that case to disable the creation via canCreate and display the error message on the form listing page.

Ok but the message should only be shown to users that have the right to create entities IMO.

If someone can only read entities, there is no point displaying this information.

File: src/Entity.php [hunk 3]
```diff
@@ -269,8 +269,25 @@ public static function getSectorizedDetails(): array
         return ['admin', self::class];
     }
 
+    /**
+     * Verify the current user can create a child entity.
+     * This method is used for example in the showSearchStatusArea.
+     * @return bool
+     */
+    public static function canCreateChild(): bool
```
Comment (cedric-anne) [inline src/Entity.php]:
```suggestion
    private static function canCreateChild(): bool
```

File: src/Entity.php [hunk 4]
```diff
@@ -744,6 +779,10 @@ public function post_getFromDB()
     public function post_addItem()
     {
         parent::post_addItem();
+        // If first time, we allow the creation of an entity and switch to recursive mode
+        if (!Session::isMultiEntitiesMode()) {
+            $_SESSION["glpiactive_entity_recursive"] = true;
+        }
```
Comment (AdrienClairembault) [inline src/Entity.php]: Is this still relevant? I don't think it will trigger since we no longer allow creation.

File: src/Entity.php [hunk 5]
```diff
@@ -692,6 +709,24 @@ public static function displayTabContentForItem(CommonGLPI $item, $tabnum = 1, $
...
+     * @return void
+     * @used-by templates/components/search/controls.html.twig
+     */
+    public static function showSearchStatusArea(): void
+    {
+        if (!self::canCreateChild() && Session::haveRight(static::$rightname, CREATE)) {
+            Session::addMessageAfterRedirect(
+                __s("To create a child entity, you must enable entity tree structure."),
+                false,
+                ERROR
```
Comment (AdrienClairembault) [inline src/Entity.php]: Maybe INFO or WARNING instead of ERROR? 

At this point the user didn't try to create an entity so it seems a bit too much to show him an error, a simple info message would be better IMO :)

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]

File: src/Entity.php (hunk 4 above)
Comment (froozeify) [reply src/Entity.php]: Indeed, and looks like when we first log with only one Entity (root one) we are in the Tree structure.

image

I'm removing it so

File: src/Entity.php (hunk 5 above)
Comment (froozeify) [reply src/Entity.php]: Switching it to info
