### PR TITLE
Fix #20837 add multiple group in charge of an asset main

### LINKED ISSUE #20837: Can't add multiple groups in charge of an asset using Business Rules for Assets
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11 RC3

### Bug description

When creating a business rule for assets and adding the action of Assign Group in Charge I can't choose more than one, neither add a new action with the item `Group in charge``

Image

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Create a business rule for assets
2. Add any criterion
3. Try to assign Group in charge – you may just add one
4. Assign a Group in charge
5. Try to assign a new Group in charge – you don't find the action anymore, since it's already added

### Your GLPI setup information

_No response_

### Anything else?

Since GLPI 11 there's the option of multiple groups in charge of an asset. It would be greato to be possible to add them using business rules for assets.

### PR DESCRIPTION
**Pull request by SebSept**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] This change requires a documentation update.

## Description

- It fixes #20837
- Asset rules : add _append_/_add_ actions for _group_ and _group\_in\_charge_ (several permitted)

Replacement for #21668

### CODE REVIEW

File: tests/functional/Glpi/Features/AssignableItemTest.php [hunk 1]
```diff
@@ -128,6 +131,57 @@ public function testAddAndUpdateMultipleGroups(string $class): void
...
+    {
+        // --- arrange - create 2 groups
+        $this->login();
+
+        $tested_fields = ['groups_id_tech', 'groups_id'];
+
+        foreach ($tested_fields as $field) {
+            $group_1 = $this->createItem(Group::class, $this->getMinimalCreationInput(Group::class));
+            $group_2 = $this->createItem(Group::class, $this->getMinimalCreationInput(Group::class));
+
```
Comment (trasher) [inline tests/functional/Glpi/Features/AssignableItemTest.php]: maybe can you create those 2 groups outside the loop? (same for all other loops, probably better for tests performances)

File: tests/functional/RuleAssetTest.php [hunk 2]
```diff
@@ -638,6 +644,403 @@ public function testUserLocationAssignFromRule()
...
+            $this->assertEqualsCanonicalizing([$rule_group_1->getID(), $rule_group_2->getID()], $fetched_group_ids, 'Unexpected Asset associated groups with ' . $class . ' ' . $field);
+        }
+    }
+
+    /**
+     * Assign groups & tech group to asset on creation
+     */
+    #[TestWith(['groups_id_tech'])]
+    #[TestWith(['groups_id'])]
+    public function xtestAddGroupOnAddWithInput(string $field): void // @todo sup le x
```
Comment (trasher) [inline tests/functional/RuleAssetTest.php]: ?
```suggestion
    public function testAddGroupOnAddWithInput(string $field): void
```

File: tests/functional/RuleAssetTest.php [hunk 3]
```diff
@@ -638,6 +644,403 @@ public function testUserLocationAssignFromRule()
...
+
+        $this->assertEqualsCanonicalizing([$input_group->getID(), $rule_group_1->getID(), $rule_group_2->getID()], $fetched_group_ids, 'Unexpected Asset associated groups');
+    }
+
+    /**
+     * Assign groups on update
+     *
+     * Notice group set on creation is lost after the update.
+     * - this is because of \Glpi\Features\AssignableItem::updateGroupFields() implementation that remove previous groups
+     * - important : behavior is not the same for Tickets (@todo ajouter ref au tests + ajouter ref à ici dans la ref)
```
Comment (trasher) [inline tests/functional/RuleAssetTest.php]: Todos must be done :)

File: tests/src/Glpi/Asset/ProviderTrait.php [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+{
+    /**
+     * @return \Generator Item type that are both assets and assignable
+     */
+    public static function assignableAssetsItemtypeProvider(): \Generator
+    {
+        global $CFG_GLPI;
+        $assignable_assets_itemtypes = array_intersect($CFG_GLPI['assignable_types'], $CFG_GLPI['asset_types']);
+
+        dump($assignable_assets_itemtypes);
```
Comment (trasher) [inline tests/src/Glpi/Asset/ProviderTrait.php]:
```suggestion
```

**Review by trasher — COMMENTED** [review]
See comments. Will finish the review once todos wil be processed.

File: tests/functional/RuleAssetTest.php (hunk 3 above)
Comment (SebSept) [reply tests/functional/RuleAssetTest.php]: Thanks, sorry, I finished too fast.

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Review by AdrienClairembault — APPROVED** [review]
