### PR TITLE
adjust operator precedence for ticket priority recalculation

### LINKED ISSUE #21946: [GLPI 11] Change Impact don't change priority ticket
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.2

### Bug description

When i change the Impact on a ticket it doesn't change the priority. Only Urgency trigger the priority change

Image

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Change impact to have another urgency x impact value
2. Save
3. No change in priority

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.2 ( =&gt; /var/www/html/glpi)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: 4 files changed
  A: inc/downstream.php
  D: install/install.php
  M: src/Glpi/Search/Provider/SQLProvider.php
  A: src/Glpi/Search/Provider/SQLProvider_old.php</pre></details><details><summary>Server</summary><pre>Operating system: Linux LIN-DIN012-Z 6.12.48+deb13-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.12.48-1 (2025-09-20) x86_64

PHP: 8.4.11 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium,
apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext,
iconv, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm,
tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;30&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;128M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;0&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Apache/2.4.65 (Debian) (Apache/2.4.65 (Debian) Server at itsmdev.cordongroup.com Port 80)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
Edg/142.0.0.0

Database:
   
Server Software: -- Please help get to 10k stars at https://github.com/MariaDB/Server
   
Server Version: 11.8.3-MariaDB-0+deb13u1 from Debian
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi@172.16.10.15/itsm2
   
Host info: 172.16.10.15 via TCP/IP

Requirements:
PHP version (8.4.11) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (11.8.3) is supported.
The log file has been created successfully.
Write access
to /var/lib/glpi/files/_cache has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
/var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;/var/www/html/glpi&quot;
GLPI_VERSION: &quot;11.0.2&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.2@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.2-52505ef9&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi/locales&quot;
GLPI_CONFIG_DIR: &quot;/etc/glpi/&quot;
GLPI_VAR_DIR: &quot;/var/lib/glpi/files&quot;
GLPI_LOG_DIR: &quot;/var/log/glpi&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/lib/glpi/files&quot;
GLPI_CACHE_DIR: &quot;/var/lib/glpi/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/lib/glpi/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/lib/glpi/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/lib/glpi/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/lib/glpi/files/_lock&quot;
GLPI_PICTURE_DIR: &quot;/var/lib/glpi/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/lib/glpi/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/lib/glpi/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/lib/glpi/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/lib/glpi/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/lib/glpi/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/lib/glpi/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/lib/glpi/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi/marketplace&quot;,&quot;/var/www/html/glpi/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>LDAP directories</summary><pre>Server: &#39;ldap://172.16.10.1&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;OU=CordonGroup,DC=corp,DC=cordongroup,DC=com&#39;, 
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(mail=*@*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;CN=svc_ldap,OU=Infra,DC=corp,DC=cordongroup,DC=com&#39;, 
	Use TLS: none

Server: &#39;ldap://10.22.2.1&#39;, 
	Port: &#39;3268&#39;, 
	BaseDN: &#39;DC=cordon,DC=cordonweb,DC=com&#39;, 
	Connection filter:
&#39;(&amp;(objectClass=user)(objectCategory=person)(extensionAttribute10=*@*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;CN=LDAP Connector,CN=Users,DC=cordon,DC=cordonweb,DC=com&#39;, 
	Use TLS: none</pre></details><details><summary>SQL replicas</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: SMTP(smtp://fortimail.cordongroup.com:25)
Name: &#39;itsm-dev@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm-dev@cordongroup.com&#39;
	Password: Yes
Name: &#39;itsm.infra-dev@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.infra-dev@cordongroup.com&#39;
	Password: Yes
Name: &#39;itsm.ssi-dev@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.ssi-dev@cordongroup.com&#39;
	Password: No
Name: &#39;itsm.mwp-dev@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.mwp-dev@cordongroup.com&#39;
	Password: Yes
Name: &#39;itsm.sysnet-dev@cordongroup.com&#39;
	Active: Yes
	Server: &#39;{outlook.office365.com:993/imap-oauth-1/ssl}INBOX&#39;
	Login: &#39;itsm.sysnet-dev@cordongroup.com&#39;
	Password: No</pre></details><details><summary>Plugins list</summary><pre>accounts             Name: Accounts                       Version: 3.1.1      State: Installed / not activated               
Install Method: Marketplace
actualtime           Name: ActualTime                     Version: 3.2.0      State: Not installed                           
Install Method: Marketplace
fields               Name: Additional fields              Version: 1.23.0     State: Installed / not activated               
Install Method: Marketplace
behaviors            Name: Behaviours                     Version: 3.0.1      State: Not installed                           
Install Method: Marketplace
costs                Name: Costs                          Version: 3.0.3      State: Not installed                           
Install Method: Marketplace
mydashboard          Name: Dashboard                      Version: 2.2.2      State: Not installed                           
Install Method: Marketplace
webapplications      Name: Dashboard applicatif           Version: 5.1.2      State: Not installed                           
Install Method: Marketplace
datainjection        Name: Data injection                 Version: 2.15.1     State: Enabled                                 
Install Method: Marketplace
escalade             Name: Escalation                     Version: 2.10.0     State: Enabled                                 
Install Method: Marketplace
formcreator          Name: Form Creator                   Version: 3.0.0      State: Installed / not activated               
Install Method: Marketplace
tag                  Name: Gestion des tags               Version: 2.13.0     State: Not installed                           
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.1      State: Not installed                           
Install Method: Marketplace
uninstall            Name: Item&#39;s Lifecycle (uninstall)   Version: 2.10.2     State: Installed / not activated               
Install Method: Marketplace
metademands          Name: Meta-Demands                   Version: 3.5.3      State: Not installed                           
Install Method: Marketplace
mreporting           Name: More Reporting                 Version: 1.9.1      State: Installed / not activated               
Install Method: Marketplace
oauthimap            Name: Oauth IMAP                     Version: 1.5.0      State: Enabled                                 
Install Method: Marketplace
reports              Name: Reports                        Version: 1.16.0     State: Not installed                           
Install Method: Marketplace
samlsso              Name: samlsso                        Version: 1.2.2      State: Enabled                                 
Install Method: Manual
manufacturersimports Name: Suppliers imports              Version: 3.1.1      State: Enabled                                 
Install Method: Marketplace
timelineticket       Name: Timeline of tickets            Version: 10.0+1.2   State: Not installed                           
Install Method: Marketplace
vip                  Name: VIP                            Version: 1.9.1      State: Not installed                           
Install Method: Marketplace</pre></details><details><summary>Locales overrides</summary><pre>/var/lib/glpi/files/_locales/formcreator/form_152_en_GB.php
/var/lib/glpi/files/_locales/formcreator/form_152_fr_FR.php
/var/lib/glpi/files/_locales/formcreator/form_153_en_GB.php
/var/lib/glpi/files/_locales/formcreator/form_153_fr_FR.php
/var/lib/glpi/files/_locales/formcreator/form_154_en_GB.php
/var/lib/glpi/files/_locales/formcreator/form_154_fr_FR.php
/var/lib/glpi/files/_locales/formcreator/form_155_en_GB.php
/var/lib/glpi/files/_locales/formcreator/form_156_en_GB.php
/var/lib/glpi/files/_locales/formcreator/form_157_en_GB.php
/var/lib/glpi/files/_locales/formcreator/form_157_fr_FR.php</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by f2cmb**
## Description

- It fixes #21946 
- Here is a brief description of what this PR does : adjust operator  as they backend code in Ticket.php doesn't recalculate priority even if required.

### CODE REVIEW

**Review by AdrienClairembault — APPROVED** [review]
Tested manually and it seems good, it now work as expected 👍

File: src/Ticket.php [hunk 1]
```diff
@@ -936,9 +936,11 @@ public function prepareInputForUpdate($input)
...
         $canpriority               = Session::haveRight(self::$rightname, self::CHANGEPRIORITY);
         if (
-            (isset($input['urgency']) && $input['urgency'] != $this->fields['urgency'])
-            || (isset($input['impact']) && $input['impact'] != $this->fields['impact'])
-            && ($canpriority && !isset($input['priority']) || !$canpriority)
+            (
+                (isset($input['urgency']) && $input['urgency'] != $this->fields['urgency'])
+                || (isset($input['impact']) && $input['impact'] != $this->fields['impact'])
+            )
+            && (!$canpriority || !isset($input['priority']) || $input['priority'] == $this->fields['priority'])
```
Comment (cedric-anne) [inline src/Ticket.php]: User must be able to define manually the priority.

```suggestion
            && (!$canpriority || !isset($input['priority']))
```

Comment (cedric-anne) [inline src/Ticket.php]: This prevent the user to update the `urgency` or the `impact` and to keep the current `priority` value.

```suggestion
            && (!$canpriority || !isset($input['priority']))
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]
There is a piece of JS that is not executed. The priority should be updated in the front end when impact/urgency is updated.

**Review by trasher — APPROVED** [review]

File: tests/cypress/e2e/ITILObject/ticket_form.cy.js [hunk 2]
```diff
@@ -382,4 +382,26 @@ describe("Ticket Form", () => {
...
+            content: 'Test priority recalculation',
+            urgency: 3,
+            impact: 3,
+        }).then((ticket_id) => {
+            cy.visit(`/front/ticket.form.php?id=${ticket_id}`);
+
+            cy.get('select[name="priority"]').should('have.value', '3');
+
+            cy.getDropdownByLabelText('Urgency').selectDropdownValue('High');
+            cy.waitForNetworkIdle(500);
```
Comment (AdrienClairembault) [inline tests/cypress/e2e/ITILObject/ticket_form.cy.js]:
```suggestion
```

This is not needed, cy.should() will wait and retry on its own until the correct value is found (up to 4 seconds by default).

File: tests/cypress/e2e/ITILObject/ticket_form.cy.js [hunk 3]
```diff
@@ -382,4 +382,26 @@ describe("Ticket Form", () => {
...
+            cy.get('select[name="priority"]').should('have.value', '4');
+
+            cy.get('select[name="impact"]').next('.select2').find('[role=combobox]').click();
+            cy.document().its('body').findByRole('option', { name: 'Very high' }).click();
+            cy.waitForNetworkIdle(500);
```
Comment (AdrienClairembault) [inline tests/cypress/e2e/ITILObject/ticket_form.cy.js]:
```suggestion
```

This is not needed, cy.should() will retry on its own until the correct value is found (up to 4 seconds by default).

File: tests/cypress/e2e/ITILObject/ticket_form.cy.js [hunk 4]
```diff
@@ -382,4 +382,26 @@ describe("Ticket Form", () => {
...
+    it('Priority recalculates when urgency or impact changes', () => {
+        cy.createWithAPI('Ticket', {
+            name: 'Test priority recalculation',
+            content: 'Test priority recalculation',
+            urgency: 3,
+            impact: 3,
+        }).then((ticket_id) => {
+            cy.visit(`/front/ticket.form.php?id=${ticket_id}`);
+
+            cy.get('select[name="priority"]').should('have.value', '3');
```
Comment (AdrienClairembault) [inline tests/cypress/e2e/ITILObject/ticket_form.cy.js]:
```suggestion
            cy.getDropdownByLabelText("Priority").should('have.value', '3');
```

If the aria label does not exist, you might need to manually add it (you can check how it is done for "Urgency").

File: tests/cypress/e2e/ITILObject/ticket_form.cy.js [hunk 5]
```diff
@@ -382,4 +382,26 @@ describe("Ticket Form", () => {
...
+
+            cy.getDropdownByLabelText('Urgency').selectDropdownValue('High');
+            cy.waitForNetworkIdle(500);
+            cy.get('select[name="priority"]').should('have.value', '4');
```
Comment (AdrienClairembault) [inline tests/cypress/e2e/ITILObject/ticket_form.cy.js]:
```suggestion
            cy.getDropdownByLabelText("Priority").should('have.value', '4');
```

File: tests/cypress/e2e/ITILObject/ticket_form.cy.js [hunk 6]
```diff
@@ -382,4 +382,26 @@ describe("Ticket Form", () => {
...
+
+            cy.get('select[name="impact"]').next('.select2').find('[role=combobox]').click();
+            cy.document().its('body').findByRole('option', { name: 'Very high' }).click();
```
Comment (AdrienClairembault) [inline tests/cypress/e2e/ITILObject/ticket_form.cy.js]:
```suggestion
            cy.getDropdownByLabelText("Impact").selectDropdownValue('Very high');
```

File: tests/cypress/e2e/ITILObject/ticket_form.cy.js [hunk 7]
```diff
@@ -382,4 +382,26 @@ describe("Ticket Form", () => {
...
+            cy.waitForNetworkIdle(500);
+            cy.get('select[name="priority"]').should('have.value', '5');
```
Comment (AdrienClairembault) [inline tests/cypress/e2e/ITILObject/ticket_form.cy.js]:
```suggestion
            cy.getDropdownByLabelText("Priority").should('have.value', '5');
```

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
