### PR TITLE
fix(core): Mandatory fields not enforced

### LINKED ISSUE #20454: [BETA] Mandatory fields not enforced in asset definition when using custom label types
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

Version 11 - Beta7

### Bug description

Hello, 
In the asset definition configuration, I marked some fields as "Mandatory". However, this setting has no effect—even when the checkbox is selected. It seems this issue only occurs when using a custom label type or a label type with specific naming. 

This happens in my case for the "state" label and two custom dropdowns.

Image

### Relevant log output

```shell
No error is displayed: The record is saved successfully even though it shouldn't be, since the mandatory field is not filled in.
```

### Page URL

_No response_

### Steps To reproduce

Create a new asset definition.
Add a mandatory field based on a label-type field (e.g., a status field).
Add other fields (e.g., text or date fields — any type).
Save the asset definition.
Try to create a new asset without filling in the mandatory label-type field.
The asset is created without any error, even though the field is marked as required (with a *).

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by froozeify**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
 
## Description

- It fixes #20454
- It also fix an issue where the field wasn't always displayed as required

## Screenshots:
image

### CODE REVIEW

File: src/Html.php [hunk 1]
```diff
@@ -4612,14 +4614,39 @@ public static function jsAjaxDropdown($name, $field_id, $url, $params = [])
...
         $options['class'] = $params['class'] ?? 'form-select';
-        if ($params['required'] === true) {
+
+        if ((bool) $params['required'] === true) {
             $options['required'] = 'required';
+
+            if (!empty($emptyLabel)) {
+                $selectVarName = "select_" . mt_rand();
+                $formVarName = "form_" . mt_rand();
+                $jsEmptyLabel = str_replace("'", "\\'", $emptyLabel);
```
Comment (cedric-anne) [inline src/Html.php]:
```suggestion
                $jsEmptyLabel = jsescape($emptyLabel);
```

File: src/Html.php [hunk 2]
```diff
@@ -4612,14 +4614,39 @@ public static function jsAjaxDropdown($name, $field_id, $url, $params = [])
...
+
+                $js .= <<<JS
+                    const $selectVarName = document.getElementById('{$field_id}');
+                    const $formVarName = $selectVarName.closest('form');
+                    if ($formVarName) {
+                        $formVarName.addEventListener("submit", (evt) => {
+                            if ($selectVarName.options[$selectVarName.selectedIndex].text === '$jsEmptyLabel') {
+                                $selectVarName.setCustomValidity(__('This field is mandatory'));
```
Comment (cedric-anne) [inline src/Html.php]: `xgettext` will not be able to extract this translation. You have to put it in a PHP variable.

File: src/Html.php [hunk 3]
```diff
@@ -4612,14 +4614,55 @@ public static function jsAjaxDropdown($name, $field_id, $url, $params = [])
...
+                                evt.preventDefault();
+                                evt.stopPropagation();
+                            }
+                        });
+
+                        \$('#$field_id').on('change', function (e) {
+                          $selectVarName.setCustomValidity('');
+                        });
+
+                        $formVarName.addEventListener('invalid', function (event) {
```
Comment (cedric-anne) [inline src/Html.php:4650]:
```suggestion
                        // Make sure the hidden <select> has the same size than the select2 container, to display the error message at a correct position
                        $formVarName.addEventListener('invalid', function (event) {
```
