### PR TITLE
Fix displayHeader misuse

### LINKED ISSUE #10593: Computer > Components Tab: Component detail links open Component detail page but shows bread crumb for Dropdowns detail page
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 rc1, master.26a36ec

### Bug description

When you click the Component Link on Computer > Components Tab, page is opened as expected but with the bread crumb belongs to Dropdown detail page.

image
image

### Relevant log output

_No response_

### Page URL

../front/device.form.php?itemtype=DeviceFirmware&id=1

### Steps To reproduce

1. Open any Computer Item detail page,
2. Go to Components Tab,
3. Click any of the component's link to see the details of it.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0-rc1 ( => E:\XAMPP\htdocs\glpi10)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT xxxx 10.0 build 19044 (Windows 10) AMD64
PHP 7.4.22 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sodium, standard, tokenizer, xml, xmlreader,
	xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="2048M" post_max_size="400M" safe_mode="" session.save_handler="files"
	upload_max_filesize="400M" 
Software: Apache/2.4.48 (Win64) OpenSSL/1.1.1k PHP/7.4.22 (Apache/2.4.48 (Win64) OpenSSL/1.1.1k PHP/7.4.22 Server at
	glpi10.moonictlocal.com Port 8080
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.31
	Server SQL Mode: 
	Parameters: root@127.0.0.1/glpi10
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (7.4.22) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (5.7.31) is supported.
The log file has been created successfully.
Write access to E:\XAMPP\htdocs\glpi10/files/_cache has been validated.
Write access to E:\XAMPP\htdocs\glpi10/config has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_cron has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_dumps has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_graphs has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_lock has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_pictures has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_plugins has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_rss has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_sessions has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_tmp has been validated.
Write access to E:\XAMPP\htdocs\glpi10/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to E:\XAMPP\htdocs\glpi10/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: E:\XAMPP\htdocs\glpi10
GLPI_CONFIG_DIR: E:\XAMPP\htdocs\glpi10/config
GLPI_VAR_DIR: E:\XAMPP\htdocs\glpi10/files
GLPI_MARKETPLACE_DIR: E:\XAMPP\htdocs\glpi10/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: E:\XAMPP\htdocs\glpi10/files
GLPI_CACHE_DIR: E:\XAMPP\htdocs\glpi10/files/_cache
GLPI_CRON_DIR: E:\XAMPP\htdocs\glpi10/files/_cron
GLPI_DUMP_DIR: E:\XAMPP\htdocs\glpi10/files/_dumps
GLPI_GRAPH_DIR: E:\XAMPP\htdocs\glpi10/files/_graphs
GLPI_LOCAL_I18N_DIR: E:\XAMPP\htdocs\glpi10/files/_locales
GLPI_LOCK_DIR: E:\XAMPP\htdocs\glpi10/files/_lock
GLPI_LOG_DIR: E:\XAMPP\htdocs\glpi10/files/_log
GLPI_PICTURE_DIR: E:\XAMPP\htdocs\glpi10/files/_pictures
GLPI_PLUGIN_DOC_DIR: E:\XAMPP\htdocs\glpi10/files/_plugins
GLPI_RSS_DIR: E:\XAMPP\htdocs\glpi10/files/_rss
GLPI_SESSION_DIR: E:\XAMPP\htdocs\glpi10/files/_sessions
GLPI_TMP_DIR: E:\XAMPP\htdocs\glpi10/files/_tmp
GLPI_UPLOAD_DIR: E:\XAMPP\htdocs\glpi10/files/_uploads
GLPI_INVENTORY_DIR: E:\XAMPP\htdocs\glpi10/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: E:\XAMPP\htdocs\glpi10/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (E:\XAMPP\htdocs\glpi10\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.5.3 in (E:\XAMPP\htdocs\glpi10\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (E:\XAMPP\htdocs\glpi10\vendor\simplepie\simplepie\library)
mpdf/mpdf in (E:\XAMPP\htdocs\glpi10\vendor\mpdf\mpdf\src)
michelf/php-markdown in (E:\XAMPP\htdocs\glpi10\vendor\michelf\php-markdown\Michelf)
true/punycode in (E:\XAMPP\htdocs\glpi10\vendor\true\punycode\src)
iamcal/lib_autolink in (E:\XAMPP\htdocs\glpi10\vendor\iamcal\lib_autolink)
sabre/dav in (E:\XAMPP\htdocs\glpi10\vendor\sabre\dav\lib\DAV)
sabre/http in (E:\XAMPP\htdocs\glpi10\vendor\sabre\http\lib)
sabre/uri in (E:\XAMPP\htdocs\glpi10\vendor\sabre\uri\lib)
sabre/vobject in (E:\XAMPP\htdocs\glpi10\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (E:\XAMPP\htdocs\glpi10\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (E:\XAMPP\htdocs\glpi10\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (E:\XAMPP\htdocs\glpi10\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (E:\XAMPP\htdocs\glpi10\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (E:\XAMPP\htdocs\glpi10\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (E:\XAMPP\htdocs\glpi10\vendor\elvanto\litemoji\src)
symfony/console in (E:\XAMPP\htdocs\glpi10\vendor\symfony\console)
scssphp/scssphp in (E:\XAMPP\htdocs\glpi10\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (E:\XAMPP\htdocs\glpi10\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (E:\XAMPP\htdocs\glpi10\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (E:\XAMPP\htdocs\glpi10\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (E:\XAMPP\htdocs\glpi10\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (E:\XAMPP\htdocs\glpi10\vendor\ramsey\uuid\src)
psr/log in (E:\XAMPP\htdocs\glpi10\vendor\psr\log\Psr\Log)
psr/simple-cache in (E:\XAMPP\htdocs\glpi10\vendor\psr\simple-cache\src)
psr/cache in (E:\XAMPP\htdocs\glpi10\vendor\psr\cache\src)
league/csv in (E:\XAMPP\htdocs\glpi10\vendor\league\csv\src)
mexitek/phpcolors in (E:\XAMPP\htdocs\glpi10\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (E:\XAMPP\htdocs\glpi10\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (E:\XAMPP\htdocs\glpi10\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (E:\XAMPP\htdocs\glpi10\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (E:\XAMPP\htdocs\glpi10\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (E:\XAMPP\htdocs\glpi10\vendor\paragonie\sodium_compat\src)
symfony/cache in (E:\XAMPP\htdocs\glpi10\vendor\symfony\cache)
html2text/html2text in (E:\XAMPP\htdocs\glpi10\vendor\html2text\html2text\src)
symfony/dom-crawler in (E:\XAMPP\htdocs\glpi10\vendor\symfony\dom-crawler)
twig/twig in (E:\XAMPP\htdocs\glpi10\vendor\twig\twig\src)
twig/string-extra in (E:\XAMPP\htdocs\glpi10\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (E:\XAMPP\htdocs\glpi10\vendor\symfony\polyfill-php80)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additionnal fields             Version: 1.13.0-rc2 State: Enabled
	branding             Name: Branding                       Version: 1.2.0-rc2  State: Installed / not activated
	cmdb                 Name: CMDB                           Version: 3.0.0-rc2  State: Enabled
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.3 State: To update
	agentconfig          Name: GLPI Agent config              Version: 1.2.0-rc2  State: Enabled
	resources            Name: Human Resources                Version: 3.0.0-rc2  State: Enabled
	ldaptools            Name: LDAP Tools                     Version: 0.0.2      State: Enabled
	genericobject        Name: Objects management             Version: 2.12.0-rc2 State: Enabled

</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Fix #10593

`CommonDropdown::displayHeader()` handle breadcrumbs using the item properties: 

image

Instead of overriding these properties, some item override the `displayHeader` method, for example:

image

These items should redefine `$first_level_menu`, `second_level_menu` and `$third_level_menu` properly instead of changing this function.  
I've set the function to final to avoid this but it may trigger some fatal error if some plugins are doing the same thing.  
Maybe a depreciation warning instead ? Or is it OK since we are doing a major update from 9 to 10 ?  

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10593

### CODE REVIEW

**Comment by cedric-anne** [comment]
Instead of changing the method to final, you could move the `displayHeader` method logic to the only place it is actually called, and deprecate it.
Deprecation warning is acceptable, as it is not blocking, unlike a fatal error.

**Comment by AdrienClairembault** [comment]
> Instead of changing the method to final, you could move the `displayHeader` method logic to the only place it is actually called, and deprecate it. Deprecation warning is acceptable, as it is not blocking, unlike a fatal error.

Note that in this case the method will never be called and thus the depreciation will never be shown.
Plugin maintainers will have no warnings in their logs that some breadcrumbs aren't displayed correctly.

**Comment by cedric-anne** [comment]
> Plugin maintainers will have no warnings in their logs

They will have is this method is used by their plugin (for instance it is used by some plugins I maintain), and the fact that this method is deprecated and so is not anymore used by GLPI core will be documented in the changelog.
At worse, if developper miss this change, it will generate imprecise title, which is not a big deal.

**Comment by AdrienClairembault** [comment]
Unless I'm missing something, a depreciation is useless because the issue is found in classes **overriding** `displayHeader` (see changed files for examples).
If you add a depreciation warning in `Dropdown::displayHeader` it will never be issued because these classes call their override of the method and thus never run the original code.

We can either have a fatal error (with the current **final** qualifier) on override OR no warning at all (remove the **final** qualifier), no in-between.

**Comment by cedric-anne** [comment]
My opinion is that we should remove usage from this method from core, remove its overrides in core, adn add a deprecation warning in case some plugins are calling this method.
The method overrides in plugins will never be called, and this will not be a big deal (in contrary to a fatal error that will block usage of GLPI as long as the plugin class is loaded).

File: src/CommonDropdown.php [hunk 1]
```diff
@@ -202,22 +202,31 @@ public function defineTabs($options = [])
...
-        if (empty($this->third_level_menu)) {
-            $this->third_level_menu = $this->getType();
-        }
-        Html::header(
-            $this->getTypeName(Session::getPluralNumber()),
-            '',
-            $this->first_level_menu,
-            $this->second_level_menu,
-            $this->third_level_menu
+        Toolbox::deprecated(
```
Comment (cedric-anne) [inline src/CommonDropdown.php:207]: Method logic should not be removed when it is deprecated.

Comment (AdrienClairembault) [reply src/CommonDropdown.php:207]: Indeed, I forgot to call the new method... should be fixed now

File: src/CommonDBTM.php [hunk 2]
```diff
@@ -6219,25 +6195,28 @@ public function getBrowserTabName(): string
     /**
      * Display a full helpdesk page (header + content + footer) for a given item
      *
-     * @param int|string $id       Id of the item to be displayed, may be a
+     * @param int|string  $id      Id of the item to be displayed, may be a
      *                             string due to some weird default values.
      *                             Will be cast to int straight away.
-     * @param array      $menus    Menu path used to load specific JS file and
+     * @param anull|array $menus   Menu path used to load specific JS file and
```
Comment (cedric-anne) [inline src/CommonDBTM.php:6201]:
```suggestion
     * @param null|array $menus    Menu path used to load specific JS file and
```

File: src/CommonDBTM.php [hunk 3]
```diff
@@ -6311,4 +6277,67 @@ public static function displayFullPageForItem(
...
+    ): void {
+        // Default title if not specified: current itemtype
+        if (is_null($title)) {
+            $title = static::getTypeName(1);
+        }
+
+        // Default menu if not specified: default values of Html::header
+        if (is_null($menus)) {
+            $menus = ['none', 'none', ''];
+        }
```
Comment (cedric-anne) [inline src/CommonDBTM.php:6301]: This is not usefull, the `??` operator will handle the null value correctly.

```
$ php -r '$a = null; echo $a[0] ?? "default\n";'
default
```

File: src/CommonDBTM.php [hunk 4]
```diff
@@ -6311,4 +6277,67 @@ public static function displayFullPageForItem(
...
+    ): void {
+        // Default title if not specified: itemtype
+        if (is_null($title)) {
+            $title = static::getTypeName(1);
+        }
+
+        // Default menu if not specified: default values of Html::helpHeader
+        if (is_null($menus)) {
+            $menus = ['self-service', 'none', ''];
+        }
```
Comment (cedric-anne) [inline src/CommonDBTM.php:6333]: Same remark.

File: src/CommonDropdown.php [hunk 5]
```diff
@@ -202,22 +202,32 @@ public function defineTabs($options = [])
...
+    ): void {
+        if (is_null($menus)) {
+            $dropdown = new static();
+
+            $menus = [
+                $dropdown->first_level_menu,
+                $dropdown->second_level_menu,
+                empty($dropdown->third_level_menu) ?
+                    $dropdown->getType() :
+                    $dropdown->third_level_menu
```
Comment (cedric-anne) [inline src/CommonDropdown.php:225]: The Elvis operator could handle this.
```suggestion
                $dropdown->third_level_menu ?: $dropdown->getType()
```

File: src/CommonDropdown.php [hunk 6]
```diff
@@ -202,22 +202,32 @@ public function defineTabs($options = [])
...
-        if (empty($this->third_level_menu)) {
-            $this->third_level_menu = $this->getType();
-        }
-        Html::header(
-            $this->getTypeName(Session::getPluralNumber()),
-            '',
-            $this->first_level_menu,
-            $this->second_level_menu,
-            $this->third_level_menu
+        Toolbox::deprecated(
```
Comment (cedric-anne) [inline src/CommonDropdown.php:207]: A line should be added in changelog.

File: CHANGELOG.md [hunk 7]
```diff
@@ -20,6 +20,7 @@ The present file will list all changes made to the project; according to the
 - Usage of XML-RPC API is deprecated.
 - The database "slaves" property in the status checker (/status.php and glpi:system:status) is deprecated. Use "replicas" instead,
 - The database "master" property in the status checker (/status.php and glpi:system:status) is deprecated. Use "main" instead,
+- `CommonDropdown::displayHeader()` has been deprecated, call `CommonDropdown::displayCentralHeader()` instead and make sure to override properly `first_level_menu`, `second_level_menu` and `third_level_menu`.
```
Comment (cedric-anne) [inline CHANGELOG.md:23]: Should be moved in the `API` deprecated section (line 70).

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Review by trasher — APPROVED** [review]
