### PR TITLE
Fix - Linked ITIL objects visibility across entities and rights verification

### LINKED ISSUE #21545: Problem with adding Linked assistance object ( ticket )
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.1

### Bug description

In ticket window when we try to link this  tickets together with another one through "Link assistance object" we can only select tickets from main entity ( organization) . We cant see any other tickets which are  located in subentities.
Even when we are working in specific subentity and we want Link assistance object ( ticket) from the same subentity we cannot see it. 

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

we checked all permissions . we are trying on super-admin profile (with all permissions) and any other profile.

### PR DESCRIPTION
**Pull request by RomainLvr**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !41711
- Here is a brief description of what this PR does

Fixes an issue where users could not link tickets between parent/child entities from the root entity, and could see titles of tickets they don't have access to in the linked objects panel.

### Issues addressed

1. **Self-linking possible**: Users could link a ticket to itself, causing an "Unknown ITIL object" error.

2. **Duplicate links possible**: Users could select items already linked in the dropdown, leading to duplicate link attempts.

3. **Incomplete Change/Problem handling in Dropdown**: The Dropdown.php was missing rights restriction handling for `Change` and `Problem` itemtypes (only `Ticket` was handled).

4. **Missing visual distinction for inaccessible items**: Linked items were displayed with clickable links even when the user cannot access them.

### Changes

* **CommonITILObject_CommonITILObject.php**: Added self-link prevention in `prepareInputForAdd()` - an item cannot be linked to itself.

* **Dropdown.php**: Mutualized `Ticket`, `Change`, and `Problem` cases into a single block with proper rights restrictions using `Search::addDefaultJoin/addDefaultWhere`.

* **linked_itilobjects.html.twig**:
  * Removed `entity_restrict` (uses default behavior respecting entity visibility as discussed in #21680)
  * Added `used` parameter to exclude current item AND already linked items from dropdown
  * Added `canViewItem()` check: items the user can access are displayed as clickable links, others are displayed as muted text without link

### Tests added

* **testPreventSelfLink**: Tests that tickets, changes, and problems cannot be linked to themselves.

### CODE REVIEW

File: src/CommonITILObject_CommonITILObject.php [hunk 1]
```diff
@@ -283,10 +283,11 @@ private function updateParentItems(): void
      *
      * @param string $itemtype Itemtype of the ITIL Object (Ticket, Change, or Problem)
      * @param int $items_id ID of the ITIL Object
+     * @param bool $check_view_rights Whether to check view rights on linked items
      *
      * @return array Array of linked ITIL Objects  array(id=>linktype)
      **/
-    public static function getLinkedTo(string $itemtype, int $items_id): array
+    public static function getLinkedTo(string $itemtype, int $items_id, bool $check_view_rights = false): array
```
Comment (Rom1-B) [inline src/CommonITILObject_CommonITILObject.php]: I think the default action should be the most restrictive, i.e., check permissions and, if necessary, be able to bypass this check.

This seems to me to be the most secure approach, but it may impact plugins such as `escalade` and `pdf` that call `getLinkedTo()`.

```suggestion
    public static function getLinkedTo(string $itemtype, int $items_id, bool $bypass_right_checks = false): array
```

_The same logic applies to other modified functions._

File: src/CommonITILObject_CommonITILObject.php [hunk 2]
```diff
@@ -349,6 +350,14 @@ public static function getLinkedTo(string $itemtype, int $items_id): array
                 }
             }
 
+            // Check view rights on linked item if requested
+            if ($check_view_rights) {
```
Comment (Rom1-B) [inline src/CommonITILObject_CommonITILObject.php]:
```suggestion
            if (!$bypass_right_checks) {
```

**Review by Rom1-B — APPROVED** [review]

**Review by stonebuzz — APPROVED** [review]

**Comment by cedric-anne** [comment]
> Missing rights verification: Linked items were displayed without checking if the current user has read access to them, exposing ticket titles to unauthorized users.

This is a common behaviour in GLPI. When a user does not have enough rights to see the linked item, most of the time, the name of this item is displayed instead of a link.

File: src/Dropdown.php [hunk 3]
```diff
@@ -3592,6 +3592,42 @@ public static function getDropdownValue($post, $json = true)
...
+                    }
+                    if (!Session::haveRight(Problem::$rightname, Problem::READALL)) {
+                        $unused_ref = [];
+                        $joins_str = Search::addDefaultJoin(Problem::class, Problem::getTable(), $unused_ref);
+                        if (!empty($joins_str)) {
+                            $criteria['LEFT JOIN'] = [new QueryExpression($joins_str)];
+                        }
+                        $where[] = new QueryExpression(Search::addDefaultWhere(Problem::class));
+                    }
+                    break;
```
Comment (cedric-anne) [inline src/Dropdown.php:3596]: This code is similar to the `Tcket::class` case. Maybe it could be mutualized.
```php
$itemtype = $post['itemtype'];

// then used to adapt the values
// Ticket::$rightname -> $itemtype::$rightname
// Ticket::READALL -> $itemtype::READALL
// ...
```

File: templates/components/itilobject/linked_itilobjects.html.twig [hunk 4]
```diff
@@ -81,6 +81,19 @@
...
+   {# Build used items list: current item + all already linked items #}
+   {% set used_items = {(item.getType()): [item.fields['id']]} %}
+   {% for linked in linked_itilobjects %}
+      {% set linked_type = linked['itemtype'] %}
+      {% set linked_id = linked['items_id'] %}
+      {% if used_items[linked_type] is defined %}
+         {% set used_items = used_items|merge({(linked_type): used_items[linked_type]|merge([linked_id])}) %}
+      {% else %}
+         {% set used_items = used_items|merge({(linked_type): [linked_id]}) %}
+      {% endif %}
```
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig]: If someone have to update this code in the future, it is preferable to not have 2 distinct but similar `set` operations. Indeed, the developer may forgot to update the `else` block, but consider it is working by testing its change with a unique linked item.

```suggestion
      {% if used_items[linked_type] is not defined %}
         {% set used_items = used_items|merge({(linked_type): []}) %}
      {% endif %}
      {% set used_items = used_items|merge({(linked_type): used_items[linked_type]|merge([linked_id])}) %}
```

File: templates/components/itilobject/linked_itilobjects.html.twig [hunk 5]
```diff
@@ -99,7 +112,8 @@
             'itemtype_name': '_link[itemtype_2]',
             'itemtypes': ['Ticket', 'Change', 'Problem'],
             'checkright': true,
-            'entity_restrict': session('glpiactive_entity'),
+            'entity_restrict': -1,
```
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig]: The `glpiactive_entity` was a bit too restrictive, but `-1` is not enough restrictive.

We already discussed about it in #21680.

The conclusion was:
 - Tickets have no `is_recursive` field, so they are not supposed to be visible in child entities and therefore cannot be linked to problems or changes from a child entity.
 - Problem and changes can be recursive, so they may be visible in child entities, and therefore can be linked to tickets from a child entity.

File: src/CommonITILObject_CommonITILObject.php [hunk 6]
```diff
@@ -349,6 +350,14 @@ public static function getLinkedTo(string $itemtype, int $items_id): array
                 }
             }
 
+            // Check view rights on linked item unless bypassed
+            if (!$bypass_right_checks) {
+                $linked_item = getItemForItemtype($link['itemtype']);
+                if ($linked_item === false || !$linked_item->can($link['items_id'], READ)) {
+                    continue;
+                }
+            }
```
Comment (cedric-anne) [inline src/CommonITILObject_CommonITILObject.php]: IMHO, the filtering should not be done here. In GLPI, we used to display the name of the linked items, even if you have no rights to see them. Changing this probably requires a global approach, as the same behaviour should probably be replacated for every items. There are multiple ways to address this:
 - we could display a `Ticket #XXX` text instead of the name;
 - we could display `+ XXX other items (not visible by you)` at the end of the list;
 - we could display nothing, but the user will not be able to know if there is no data or if there is data but he cannot access it;
 - ...

Anyway, I think we should keep the common behaviour here: displaying the ticket name, even if the user cannot access it.

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: src/CommonITILObject_CommonITILObject.php (hunk 6 above)
Comment (cedric-anne) [reply src/CommonITILObject_CommonITILObject.php]: In #21680, the proposal was to use `canViewItem` to display the name only.

File: src/CommonITILObject_CommonITILObject.php [hunk 7]
```diff
@@ -70,7 +70,7 @@ public function prepareInputForAdd($input)
 
         $input = self::normalizeParentSonRelation($input);
 
-        // No multiple links
+        // No multiple links (bypass rights check to find all existing links for unicity validation)
```
Comment (cedric-anne) [inline src/CommonITILObject_CommonITILObject.php]:
```suggestion
        // No multiple links
```

File: templates/components/itilobject/linked_itilobjects.html.twig [hunk 8]
```diff
@@ -39,6 +39,7 @@
       <div class="list-group list-group-flush list-group-hoverable">
          {% for id, linked in linked_itilobjects %}
             {% set new_itilobject = get_item(linked['itemtype'], linked['items_id']) %}
+            {% set can_view_item = new_itilobject.canViewItem() %}
```
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig]: `can($id, READ)` will also check for global rights. It is safer to use it.

```suggestion
            {% set can_view_item = new_itilobject.can(linked['items_id'], constant('READ')) %}
```

File: templates/components/itilobject/linked_itilobjects.html.twig [hunk 9]
```diff
@@ -99,7 +122,7 @@
             'itemtype_name': '_link[itemtype_2]',
             'itemtypes': ['Ticket', 'Change', 'Problem'],
             'checkright': true,
-            'entity_restrict': session('glpiactive_entity'),
```
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig:102]: The entity restriction must be fixed.

Considering the following entity tree:
```
Root
  > A
    > A.1
    > A.2
  > B
```

- In a Change or a Problem assigned to the `A` entity WITHOUT the `is_recursive` flag, the dropdown must show only elements from the `A` entity.
- In a Change or a Problem assigned to the `A` entity WITH the `is_recursive` flag, the dropdown must show only elements from the `A`, `A.1` and `A.2` entities (`A + its sub entities`).
- In a Ticket assigned to the `A` entity, the dropdown must show only elements from the `A` entity (Ticket have no `is_recursive` flag).

**Review by cedric-anne — CHANGES_REQUESTED** [review]

File: templates/components/itilobject/linked_itilobjects.html.twig (hunk 9 above)
Comment (Rom1-B) [reply templates/components/itilobject/linked_itilobjects.html.twig:102]: In our case, for example, where each customer has their own entity, we may have two customers on separate entities reporting the same issue for tickets. Since it's the same subject, it seems legitimate to me to be able to link the tickets. However, this can only be done if we are placed on a parent entity for both tickets, and only then can the link be added and viewed. I think we can apply the same reasoning to Changes and Problems.

In your example, we should be able to link A and B, but only from Root.

Comment (cedric-anne) [reply templates/components/itilobject/linked_itilobjects.html.twig:102]: Linking objects from two distinct entity branches is not something that is supposed to be possible in GLPI, as far as I know.

File: src/CommonITILObject_CommonITILObject.php (hunk 7 above)
Comment (cedric-anne) [inline src/CommonITILObject_CommonITILObject.php]:
```suggestion
        // No multiple links
```

File: templates/components/itilobject/linked_itilobjects.html.twig (hunk 8 above)
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig]:
```suggestion
            {% set can_view_item = new_itilobject.can(linked['items_id'], constant('READ')) %}
```

Comment (RomainLvr) [reply templates/components/itilobject/linked_itilobjects.html.twig]: My bad i forgot to pull before rebasing

**Review by cedric-anne — CHANGES_REQUESTED** [review]
As discussed IRL, the entity restriction has been introduced by #10989 and should be reverted.

File: src/CommonITILObject_CommonITILObject.php [hunk 10]
```diff
@@ -362,10 +362,11 @@ public static function getLinkedTo(string $itemtype, int $items_id): array
      *
      * @param string $itemtype Itemtype of the ITIL Object (Ticket, Change, or Problem)
      * @param int $items_id ID of the ITIL Object
+     * @param bool $bypass_right_checks If true, skip READ rights verification (default: false - checks rights)
      *
      * @return array Array of linked ITIL Objects  array(id=>linktype)
      **/
-    public static function getAllLinkedTo(string $itemtype, int $items_id): array
+    public static function getAllLinkedTo(string $itemtype, int $items_id, bool $bypass_right_checks = false): array
```
Comment (cedric-anne) [inline src/CommonITILObject_CommonITILObject.php]: In bugfixes version, you cannot add strict types to new methods parameters as it can result in a PHP compile error if any plugin overrides this method.

```suggestion
    public static function getAllLinkedTo(string $itemtype, int $items_id, $bypass_right_checks = false): array
```

File: src/CommonITILObject_CommonITILObject.php [hunk 11]
```diff
@@ -499,12 +509,13 @@ public static function getAllLinkClasses(): array
      *
      * @param string $itemtype
      * @param int $items_id
+     * @param bool $bypass_right_checks If true, skip READ rights verification (default: false - checks rights)
      *
      * @return int
      */
-    public static function countAllLinks(string $itemtype, int $items_id): int
+    public static function countAllLinks(string $itemtype, int $items_id, bool $bypass_right_checks = false): int
```
Comment (cedric-anne) [inline src/CommonITILObject_CommonITILObject.php]:
```suggestion
    public static function countAllLinks(string $itemtype, int $items_id, $bypass_right_checks = false): int
```

**Review by cedric-anne — CHANGES_REQUESTED** [review]
The `getAllLinkedTo()` method is used during notification generation, with a session context that, most of the time, does not correspond to the notification target user. It means that the filtering cannot be done using the session.

Anyway, as notification data is shared accross all users, I have no idea how we could make it compatible with the fact we want to relations out of the current entity scope in the UI.

**Review by cedric-anne — APPROVED** [review]

File: templates/components/itilobject/linked_itilobjects.html.twig [hunk 12]
```diff
@@ -33,12 +33,14 @@
...
 <input type="hidden" name="_link[items_id_1]" value="{{ item.fields['id'] }}" />
 
-{% set linked_itilobjects = item.isNewItem() ? 0 : call('CommonITILObject_CommonITILObject::getAllLinkedTo', [item.getType(), item.getId()]) %}
+{% set linked_itilobjects = item.isNewItem() ? [] : call('CommonITILObject_CommonITILObject::getAllLinkedTo', [item.getType(), item.getId()]) %}
 {% if linked_itilobjects|length %}
    <div class="card">
       <div class="list-group list-group-flush list-group-hoverable">
          {% for id, linked in linked_itilobjects %}
             {% set new_itilobject = get_item(linked['itemtype'], linked['items_id']) %}
+            {% set can_view_item = new_itilobject.canViewItem() %}
```
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig]:
```suggestion
            {% set can_view_item = new_itilobject.can(linked['items_id'], constant('READ')) %}
```

File: templates/components/itilobject/linked_itilobjects.html.twig [hunk 13]
```diff
@@ -33,12 +33,14 @@
...
+            {% set can_update_item = new_itilobject.canUpdateItem() %}
```
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig]: Checking for the DELETE right is more relevant here.

```suggestion
            {% set can_delete_relation = new_itilobject.can(linked['items_id'], constant('DELETE')) %}
```

File: templates/components/itilobject/linked_itilobjects.html.twig [hunk 14]
```diff
@@ -49,17 +51,27 @@
...
+                           <span title="{{ new_itilobject.fields['name'] }}" data-bs-toggle="tooltip">
+                              {{ new_itilobject.fields['name'] }}
+                           </span>
+                           ({{ new_itilobject.fields['id'] }})
+                        </span>
+                     {% endif %}
                   </div>
 
-                  {% if canupdate %}
+                  {% if can_update_item %}
```
Comment (cedric-anne) [inline templates/components/itilobject/linked_itilobjects.html.twig]:
```suggestion
                  {% if can_delete_relation %}
```

**Review by cedric-anne — APPROVED** [review]
