### PR TITLE
fix #22558 - Event::log() threshold not respected

### LINKED ISSUE #22558: Log-Level of event log not working
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

When setting the Log Level under Setup > General > System to 3  no events of level 3 are logged in the event.log file. If you set the log level to 5 events of level 3 are logged.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SebSept**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

when setting event log level to x, lower level (=more critical) are logged but not error of the limit level.
e.g. if set to 3, errors at level 1 & 2 are logged, but not level 3.

### CODE REVIEW

File: tests/functional/EventTest.php [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+        $CFG_GLPI["event_loglevel"] = $threshold;
+        $log_file = GLPI_LOG_DIR . "/event.log"; // event.log is hardcoded \Glpi\Event::log()
+        $log_service = $this->getUniqueString();
+        file_put_contents($log_file, ""); // empty log file for easier debugging
+
+        // --- act
+        Event::log(0, self::class, $level, $log_service, 'event');
+
+        // --- assert
+        $expected_count = $level <= $threshold ? 1 : 0;
```
Comment (cedric-anne) [inline tests/functional/EventTest.php]: Your provider should provide a `should_be_logged_in_db` param.

```suggestion
        $expected_count = $should_be_logged_in_db ? 1 : 0;
```

File: tests/functional/EventTest.php [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+            ? $this->assertStringContainsString(
+                "[$log_service]",
+                file_get_contents($log_file),
+                implode(' ', ['service' => $log_service, 'level' => $level, 'should be logged in file' => $should_be_logged_in_file])
+            )
+            : $this->assertStringNotContainsString(
+                "[$log_service]",
+                file_get_contents($log_file),
+                implode(' ', ['service' => $log_service, 'level' => $level, 'should be logged in file' => $should_be_logged_in_file])
+            );
```
Comment (cedric-anne) [inline tests/functional/EventTest.php]: It could b easiert to read with a `$this->assertEquals($should_be_logged_in_file, str_contains("[$log_service]", file_get_contents($log_file));`

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by cedric-anne — APPROVED** [review]

**Review by AdrienClairembault — APPROVED** [review]
