### PR TITLE
Fix forms failure when a template use the "NOW" value

### LINKED ISSUE #21267: Native forms fails to create ticket
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.0

### Bug description

When Creating a ticket on newly created forms I get a brief popup about an invalid date. The form has just text entries and no date related fields defined. Php Log shows Date:Now but there is no definition for that in the form or target 

### Relevant log output

```shell
[2025-10-02 22:01:25] glpi.CRITICAL:   *** Uncaught PHP Exception Exception: "Failed to create Ticket: {"name":"After Hours support Request","content":"<p><b>1) Would you like to page the person on call<\/b>: Yes<br><b>2) Issue description<\/b>: Test<br><\/p>","entities_id":0,"itilcategories_id":133,"tickettemplates_id":1,"date":"NOW","priority":"2","type":1,"urgency":5,"_users_id_requester":[7],"_users_id_requester_notif":{"use_notification":[0],"alternative_email":[""]}}" at AbstractCommonITILFormDestination.php line 187
  Backtrace :
  ...ation\AbstractCommonITILFormDestination.php:187 
  ...Glpi\Form\AnswersHandler\AnswersHandler.php:390 Glpi\Form\Destination\AbstractCommonITILFormDestination->createDestinationItems()
  ...Glpi\Form\AnswersHandler\AnswersHandler.php:243 Glpi\Form\AnswersHandler\AnswersHandler->createDestinations()
  ...Glpi\Form\AnswersHandler\AnswersHandler.php:181 Glpi\Form\AnswersHandler\AnswersHandler->doSaveAnswers()
  ...\Controller\Form\SubmitAnswerController.php:132 Glpi\Form\AnswersHandler\AnswersHandler->saveAnswers()
  ...i\Controller\Form\SubmitAnswerController.php:79 Glpi\Controller\Form\SubmitAnswerController->saveSubmittedAnswers()
  .\vendor\symfony\http-kernel\HttpKernel.php:181    Glpi\Controller\Form\SubmitAnswerController->__invoke()
  .\vendor\symfony\http-kernel\HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  .\vendor\symfony\http-kernel\Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  .\public\index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()



Form JSON
{"version":1,"forms":[{"id":19,"uuid":"8831fbda-8449-479e-8332-403524c7c2f0","name":"After Hours support Request","header":"<p>This will page the after hours person on call. If this is not an after hours request please select another form.\u00a0<\/p>","description":null,"entity_name":"xxx","is_recursive":true,"is_active":true,"submit_button_visibility_strategy":"visible_if","illustration":"","submit_button_conditions":[{"item_uuid":"9c5e6e6b-df65-483e-b9a3-332117892b3e","item_type":"question","value_operator":"equals","logic_operator":"and","value":709271739}],"sections":[{"id":47,"uuid":"637dc35c-1a50-4b22-8912-d529b4944e5b","name":"First section","description":null,"rank":0,"visibility_strategy":"","conditions":[]}],"comments":[],"questions":[{"id":204,"uuid":"9c5e6e6b-df65-483e-b9a3-332117892b3e","name":"Would you like to page the person on call","type":"Glpi\\Form\\QuestionType\\QuestionTypeRadio","is_mandatory":false,"vertical_rank":0,"horizontal_rank":null,"description":"<h1>NOTICE THIS WILL Page the person on call and wake up someone. Please use accordingly.<\/h1>","default_value":null,"extra_data":{"options":{"709271739":"Yes","af8b08d2-ef1c-4b12-b9e5-41648e77c8ce":"No"}},"section_id":47,"visibility_strategy":"","validation_strategy":"","conditions":[],"validation_conditions":[]},{"id":205,"uuid":"a7dac911-a4c6-4671-ac65-597e0c53ebd5","name":"Issue description","type":"Glpi\\Form\\QuestionType\\QuestionTypeShortText","is_mandatory":false,"vertical_rank":1,"horizontal_rank":null,"description":"","default_value":"","extra_data":null,"section_id":47,"visibility_strategy":"","validation_strategy":"","conditions":[],"validation_conditions":[]}],"policies":[{"strategy":"Glpi\\Form\\AccessControl\\ControlType\\AllowList","config":{"user_ids":["all"],"group_ids":[],"profile_ids":[]},"is_active":true},{"strategy":"Glpi\\Form\\AccessControl\\ControlType\\DirectAccess","config":{"token":"xxx","allow_unauthenticated":false},"is_active":false}],"destinations":[{"id":24,"itemtype":"Glpi\\Form\\Destination\\FormDestinationTicket","name":"Ticket","config":{"glpi-form-destination-commonitilfield-titlefield":{"value":"<span class=\"border-yellow border-start border-3 bg-dark-lt\" contenteditable=\"false\" data-form-tag=\"true\" data-form-tag-value=\"19\" data-form-tag-provider=\"Glpi\\Form\\Tag\\FormTagProvider\">#Form name: Untitled form<\/span>"},"glpi-form-destination-commonitilfield-entityfield":{"strategy":"form_filler"},"glpi-form-destination-commonitilfield-olattofield":{"strategy":"from_template"},"glpi-form-destination-commonitilfield-olattrfield":{"strategy":"from_template"},"glpi-form-destination-commonitilfield-slattofield":{"strategy":"from_template"},"glpi-form-destination-commonitilfield-slattrfield":{"strategy":"from_template"},"glpi-form-destination-commonitilfield-statusfield":{"value":"default_status"},"glpi-form-destination-commonitilfield-urgencyfield":{"strategy":"specific_value","specific_urgency_value":"5"},"glpi-form-destination-commonitilfield-assigneefield":{"strategies":["from_template"],"specific_question_ids":null,"specific_itilactors_ids":null},"glpi-form-destination-commonitilfield-itiltaskfield":{"strategy":"no_task"},"glpi-form-destination-commonitilfield-locationfield":{"strategy":"last_valid_answer"},"glpi-form-destination-commonitilfield-observerfield":{"strategies":["from_template"],"specific_question_ids":null,"specific_itilactors_ids":null},"glpi-form-destination-commonitilfield-templatefield":{"strategy":"default_template"},"glpi-form-destination-commonitilfield-requesterfield":{"strategies":["form_filler"],"specific_question_ids":null,"specific_itilactors_ids":null},"glpi-form-destination-commonitilfield-validationfield":{"strategy_configs":[{"strategy":"no_validation","specific_actors":[],"specific_question_ids":[],"specific_validation_step_id":null,"specific_validationtemplates_ids":[]}]},"glpi-form-destination-commonitilfield-requesttypefield":{"strategy":"specific_value","specific_request_type":"1"},"glpi-form-destination-commonitilfield-contentfield_auto":"1","glpi-form-destination-commonitilfield-itilcategoryfield":{"strategy":"specific_value","specific_itilcategory_id":"zzPagerduty"},"glpi-form-destination-commonitilfield-itilfollowupfield":{"strategy":"no_followup"},"glpi-form-destination-commonitilfield-requestsourcefield":{"strategy":"from_template"},"glpi-form-destination-commonitilfield-associateditemsfield":{"strategies":["last_valid_answer"],"specific_question_ids":null},"glpi-form-destination-commonitilfield-linkeditilobjectsfield":{"strategy_configs":[{"linktype":"1","strategy":null,"specific_itilobject":[],"specific_question_ids":[],"specific_destination_ids":[]}]}},"creation_strategy":"always_created","conditions":[]}],"translations":[],"data_requirements":[{"itemtype":"Entity","name":"xxx"},{"itemtype":"ITILCategory","name":"zzPagerduty"}]}]}
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

<details><summary>GLPI information</summary><pre>GLPI: 11.0.0 ( =&gt; E:\IIS Sites\GLPI\GLPI-IT)
Installation mode: TARBALL
Current language: en_US</pre></details><details><summary>Server</summary><pre>Operating system: Windows NT E1-GLPI-1 10.0 build 20348 (Windows Server 2022) AMD64

PHP: 8.3.21 cgi-fcgi

PHP extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection,
session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, xmlreader, xmlwriter, cgi-fcgi, openssl,
com_dotnet, curl, dba, dl_test, enchant, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, imap, intl, ldap, exif, mysqli, odbc,
Phar, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, shmop, snmp, sysvshm, sqlite3, zip, soap, sodium, sockets, xsl, tidy,
zend_test, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;300&quot; max_input_vars=&quot;2000&quot; memory_limit=&quot;1024M&quot; post_max_size=&quot;8M&quot;
session.cookie_secure=&quot;1&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;&quot; session.save_handler=&quot;files&quot;
upload_max_filesize=&quot;2M&quot; 

Web server: Microsoft-IIS/10.0 ()

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
Edg/140.0.0.0

Database:
   
Server Software: MySQL Community Server - GPL
   
Server Version: 8.4.6
   
Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
   
Parameters: 
   
Host info: 

Requirements:
PHP version (8.3.21) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader,
xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (8.4.6) is supported.
The log file has been created successfully.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_cache has been
validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_cron has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_graphs has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_lock has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_pictures has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_plugins has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_rss has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_sessions has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_tmp has been validated.
Write access to E:\IIS Sites\GLPI\GLPI-IT/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2,
Phar, zip.
Zend OPcache extension is installed
Following extensions are installed:
ctype, iconv, sodium.
Write access to
E:\IIS Sites\GLPI\GLPI-IT/marketplace has been validated.
Timezones seems loaded in database.</pre></details><details><summary>GLPI constants</summary><pre>GLPI_ROOT: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT&quot;
GLPI_VERSION: &quot;11.0.0&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.0@ea2dbba0e1edbf5128d73bdb23c2c9b9f68468ba&quot;
GLPI_FILES_VERSION: &quot;11.0.0-f682f73d&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2025&quot;
GLPI_I18N_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/locales&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_CONFIG_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/config&quot;
GLPI_VAR_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files&quot;
GLPI_MARKETPLACE_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                          
     # protocol\n                        (\n                            (?:\n                               
(?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                   
|\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain
name\n                                    |\n                                [a-z0-9\\-\\_]++                                   
          # a single-level domain name\n                            )\\.?\n                                |                    
                                      # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}               
              # an IP address\n                                |                                                           #
or\n                            \\[\n                               
(?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n
                           \\]                                                              # an IPv6 address\n                 
      )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n   
                    (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n   
                $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files&quot;
GLPI_CACHE_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_cache&quot;
GLPI_CRON_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_locales&quot;
GLPI_LOCK_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_lock&quot;
GLPI_LOG_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_log&quot;
GLPI_PICTURE_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_plugins&quot;
GLPI_RSS_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_rss&quot;
GLPI_SESSION_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_sessions&quot;
GLPI_TMP_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;E:\\IIS Sites\\GLPI\\GLPI-IT/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;E:\\IIS Sites\\GLPI\\GLPI-IT/marketplace&quot;,&quot;E:\\IIS
Sites\\GLPI\\GLPI-IT/plugins&quot;]
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;</pre></details><details><summary>LDAP Directories</summary><pre>Server: &#39;10.101.0.5&#39;, 
	Port: &#39;389&#39;, 
	
	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 
	RootDN: &#39;cjpony\srvc_glpi&#39;, 
	Use TLS: none

	Connection filter: &#39;(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))&#39;, 

	Use TLS: none</pre></details><details><summary>SQL Replicas</summary><pre>Not active</pre></details><details><summary>Notifications</summary><pre>Way of sending emails: Name: Additional fields              Version: 1.22.0     State: Enabled                                 
Install Method: Marketplace
news                 Name: Alerts                         Version: 1.13.0     State: Enabled                                 
Install Method: Marketplace
archisw              Name: Apps structures                Version: 3.0.20     State: Not Installed                           
Install Method: Marketplace
behaviors            Name: Behaviours                     Version: 3.0.1      State: Installed / Not Activated               
Install Method: Marketplace
archibp              Name: Business Processes             Version: 2.0.12     State: Installed / Not Activated               
Install Method: Marketplace
childticketmanager   Name: Child Tickets Manager          Version: 3.0.2      State: Not Installed                           
Install Method: Marketplace
consumables          Name: Consumable request             Version: 2.1.1      State: Enabled                                 
Install Method: Marketplace
datainjection        Name: Data injection                 Version: 2.15.0     State: Enabled                                 
Install Method: Marketplace
archimap             Name: Diagrams                       Version: 3.3.3      State: Installed / Not Activated               
Install Method: Marketplace
formcreator          Name: Formcreator End-of-Life Update Version: 3.0.0      State: Not Installed                           
Install Method: Marketplace
genericobject        Name: Generic Objects End-of-Life Up Version: 3.0.0      State: Not Installed                           
Install Method: Marketplace
glpiinventory        Name: GLPI Inventory                 Version: 1.6.0      State: Enabled                                 
Install Method: Marketplace
resources            Name: Human Resources                Version: 3.0.4      State: Not Installed                           
Install Method: Marketplace
addressing           Name: IP Addressing                  Version: 3.1.0      State: Enabled                                 
Install Method: Marketplace
uninstall            Name: Item&#39;s Lifecycle (uninstall)   Version: 2.10.0     State: Enabled                                 
Install Method: Marketplace
mailanalyzer         Name: Mail Analyzer                  Version: 3.2.2      State: Installed / Not Activated               
Install Method: Marketplace
metademands          Name: Meta-Demands                   Version: 3.5.3      State: Not Installed                           
Install Method: Marketplace
mreporting           Name: More Reporting                 Version: 1.9.0      State: Enabled                                 
Install Method: Marketplace
moreticket           Name: More ticket                    Version: 1.8.0      State: Enabled                                 
Install Method: Marketplace
oauthimap            Name: OAuth IMAP                     Version: 1.5.0      State: Enabled                                 
Install Method: Marketplace
order                Name: Orders management              Version: 2.12.0     State: Enabled                                 
Install Method: Marketplace
additionalalerts     Name: Others alerts                  Version: 3.0.1      State: Enabled                                 
Install Method: Marketplace
printercounters      Name: Printer counters               Version: 2.0.1      State: Installed / Not Activated               
Install Method: Marketplace
purchaserequest      Name: Purchase request               Version: 3.1.1      State: Installed / Not Activated               
Install Method: Marketplace
reports              Name: Reports                        Version: 1.16.0     State: Installed / Not Activated               
Install Method: Marketplace
screenshot           Name: Screenshot                     Version: 2.0.5      State: Installed / Not Activated               
Install Method: Marketplace
stab                 Name: Split Timeline Action Buttons  Version: 1.1.3      State: Installed / Not Activated               
Install Method: Marketplace
statecheck           Name: Statecheck Rules               Version: 2.4.4      State: Not Installed                           
Install Method: Marketplace
manufacturersimports Name: Suppliers imports              Version: 3.1.1      State: Installed / Not Activated               
Install Method: Marketplace
tag                  Name: Tag Management                 Version: 2.13.0     State: Enabled                                 
Install Method: Marketplace
ticketfilter         Name: Ticketfilter                   Version: 1.3.2      State: Installed / Not Activated               
Install Method: Marketplace
timelineticket       Name: Timeline of tickets            Version: 10.0+1.2   State: Installed / Not Activated               
Install Method: Marketplace
useditemsexport      Name: Used items export              Version: 2.5.2      State: Installed / Not Activated               
Install Method: Marketplace
webresources         Name: Web Resources                  Version: 2.0.3      State: Error / To Clean                        
Install Method: Manual
webhook              Name: Webhooks                       Version: 1.0.20     State: Installed / Not Activated               
Install Method: Marketplace
yagp                 Name: YAGP                           Version: 2.3.1      State: Installed / Not Activated               
Install Method: Marketplace</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrienClairembault**
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Adding a "NOW" predefined fields like this would lead to an SQL error when creating a ticket through an helpdesk form:

image

## References

Fix #21267

### CODE REVIEW

File: src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php [hunk 1]
```diff
@@ -406,10 +407,11 @@ final public static function prepareDynamicConfigDataForImport(
 
     private function applyPredefinedTemplateFields(array $input): array
     {
-        $itemtype = $this->getTarget();
+        /** @var DBmysql $DB */
+        global $DB;
 
-        /** @var CommonITILObject $itil */
-        $itil = new $itemtype();
+        $itil = $this->getTarget();
```
Comment (AdrienClairembault) [inline src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php:413]: Unrelated change, unsure how this code worked as $itemtype was already a CommonITIL object, not a string.
Somehow, calling new on an object is legal and did not break anything?

I still fixed it to be safe.

Comment (cedric-anne) [reply src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php:413]: It is legal in PHP to call new on an object instance.

**Review by cedric-anne — APPROVED** [review]

**Review by trasher — APPROVED** [review]

**Comment by LucasBERTHIER** [comment]
Hello,
Sorry to ask the question, but what changes do we need to make to allow ticket creation from native forms again?

Because I tried to take the content of the file src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, but I am still unable to create tickets

**Comment by AdrienClairembault** [comment]
> Because I tried to take the content of the file src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php, but I am still unable to create tickets

If this fix isn't enough for you, maybe you are suffering from a separate problem.
In this case, you'll need to open a dedicated issue.
