### PR TITLE
Fin unexpected translation in system information

### LINKED ISSUE #22608: "Enabled" (Plugin list) is being translated on Setup > General page
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.4

### Bug description

Similar to https://github.com/glpi-project/glpi/issues/22416, inside the "Plugin list" section, the "State" is being translated to the language that the user selected in GLPI:

Image

### Relevant log output

```shell

```

### Page URL

https://glpi.example.com/front/config.form.php

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by felipee-monteiro**
## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.

## Description

- It fixes #22608

Fix translated plugin information (No need to translate, this part should always display in english (for copy/paste to forum)

### CODE REVIEW

**Comment by felipee-monteiro** [comment]
image

I noticed that when a sub-menu is selected, is not showed on Breadcumbs. Can I enhance ?

File: src/Plugin.php [hunk 1]
```diff
@@ -2612,27 +2616,28 @@ public function getPhpVersion()
      */
     public static function getState($state = 0)
     {
+        // No need to translate, this part always display in english (for copy/paste to forum)
```
Comment (trasher) [inline src/Plugin.php]: This method is not only used in system information (see calls inside Plugin class).

File: src/Plugin.php [hunk 2]
```diff
@@ -1646,11 +1646,13 @@ public function getSystemInformation()
 
         $plug     = new Plugin();
         $pluglist = $plug->find([], "name, directory");
+
```
Comment (trasher) [inline src/Plugin.php]: Please avoid useless changes

**Review by trasher — CHANGES_REQUESTED** [review]

File: src/Plugin.php (hunk 1 above)
Comment (trasher) [reply src/Plugin.php]: I guess you can add a `bool $translate = true` parameter to the method, and set it to false on system information call.
Then you can do `return $translate ? _x('status', 'New') : 'New';` (or something like that).

**Comment by trasher** [comment]
> I noticed that when a sub-menu is selected, is not showed on Breadcumbs. Can I enhance ?

Not entirely sur what you talk about, but it's not related to current PR, so must be done in a different one.

File: src/Plugin.php (hunk 1 above)
Comment (felipee-monteiro) [reply src/Plugin.php]: I'm writing a new method specifically for this; I believe it will improve readability and make the code more testable. What do you think?

Comment (trasher) [reply src/Plugin.php]: That does not change much, but with 2 distinct methods, there are chances one is updated but not the other in the future.

Comment (felipee-monteiro) [reply src/Plugin.php]: Uh, sure. I think your solution is the best

File: src/Plugin.php (hunk 2 above)
Comment (trasher) [inline src/Plugin.php]:
```suggestion
```

File: src/Plugin.php [hunk 3]
```diff
@@ -1646,11 +1646,13 @@ public function getSystemInformation()
...
         foreach ($pluglist as $plugin) {
             $name = Toolbox::stripTags($plugin['name']);
             $version = Toolbox::stripTags($plugin['version']);
             $state = $plug->isLoadable($plugin['directory']) ? $plugin['state'] : self::TOBECLEANED;
-            $state = self::getState($state);
+            $state = self::getState($state, shouldTranslate: false);
+
```
Comment (trasher) [inline src/Plugin.php]:
```suggestion
```

File: src/Plugin.php [hunk 4]
```diff
@@ -1659,8 +1661,10 @@ public function getSystemInformation()
                  . " Version: " . str_pad($version, 10)
                  . " State: " . str_pad($state, 40)
                  . " Install Method: " . $install_method;
+
```
Comment (trasher) [inline src/Plugin.php]:
```suggestion
```

File: src/Plugin.php [hunk 5]
```diff
@@ -1659,8 +1661,10 @@ public function getSystemInformation()
...
             $content .= "\n" . $msg;
         }
+
```
Comment (trasher) [inline src/Plugin.php]:
```suggestion
```

**Review by trasher — APPROVED** [review]

File: src/Plugin.php [hunk 6]
```diff
@@ -2610,32 +2610,34 @@ public function getPhpVersion()
...
 
             case self::NOTACTIVATED:
-                return _x('plugin', 'Installed / not activated');
+                return $shouldTranslate ? _x('plugin', 'Installed / not activated') : 'Installed / not activated';
 
             case self::REPLACED:
-                return _x('plugin', 'Replaced');
+                return $shouldTranslate ? _x('plugin', 'Replaced') : 'Replaced';
+            default:
+                return 'State not available';
```
Comment (trasher) [inline src/Plugin.php]: Not required, will use "Error / to clean"
```suggestion
```

File: src/Plugin.php [hunk 7]
```diff
@@ -2610,32 +2610,34 @@ public function getPhpVersion()
...
         }
 
-        return __('Error / to clean');
+        return $shouldTranslate ?  __('Error / to clean') : 'Error / to clean';
```
Comment (trasher) [inline src/Plugin.php]: If you change all contexts to `plugin`, you should change this one too
```suggestion
        return $shouldTranslate ?  _x('plugin', 'Error / to clean') : 'Error / to clean';
```

**Review by trasher — CHANGES_REQUESTED** [review]
See comments

**Comment by felipee-monteiro** [comment]
Thanks for the review. 
I will pay attention to these details in future PRs.

**Review by cedric-anne — APPROVED** [review]

File: src/Plugin.php [hunk 8]
```diff
@@ -2610,32 +2610,32 @@ public function getPhpVersion()
...
-                return _x('plugin', 'Installed / not activated');
+                return $shouldTranslate ? _x('plugin', 'Installed / not activated') : 'Installed / not activated';
 
             case self::REPLACED:
-                return _x('plugin', 'Replaced');
+                return $shouldTranslate ? _x('plugin', 'Replaced') : 'Replaced';
         }
 
-        return __('Error / to clean');
+        return $shouldTranslate ?  _x('plugin', 'Error / to clean') : 'Error / to clean';
```
Comment (trasher) [inline src/Plugin.php]:
```suggestion
        return $shouldTranslate ? _x('plugin', 'Error / to clean') : 'Error / to clean';
```

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Internal note: translations must be extracted and sent to transifex after merging.
