### PR TITLE
fix returns on PHPDoc only

### LINKED ISSUE #21794: Add types on ITIL related classes
## Cron
- [x] CommonITILRecurrentCron
- [x] CommonITILValidationCron

## CommonITILObject
- [x] CommonITILObject
- [x] Problem
- [x] Ticket
- [x] Change

## CommonITILActor
- [x] CommonITILActor
- [x] Change_Group
- [x] Change_Supplier
- [x] Change_User
- [x] Group_Problem
- [x] Group_Ticket
- [x] Problem_Supplier
- [x] Problem_User
- [x] Supplier_Ticket
- [x] Ticket_User

## CommonITILCost
- [x] CommonITILCost
- [x] ChangeCost
- [x] ProblemCost
- [x] TicketCost

## CommonItilObject_Item
- [x] CommonItilObject_Item
- [x] Change_Item
- [x] Item_Problem
- [x] Item_Ticket
- [x] Item_TicketRecurrent

## CommonITILRecurrent
- [x] CommonITILRecurrent
- [x] RecurrentChange
- [x] TicketRecurrent

## CommonITILSatisfaction
- [x] CommonITILSatisfaction
- [x] ChangeSatisfaction
- [x] TicketSatisfaction

## CommonITILTask
- [x] CommonITILTask
- [x] ChangeTask
- [x] ProblemTask
- [x] TicketTask

## CommonITILValidation
- [x] CommonITILValidation
- [x] ChangeValidation
- [x] TicketValidation

## CommonITILObject_CommonITILObject
- [x] CommonITILObject_CommonITILObject
- [x] Ticket_Ticket
- [x] Change_Problem
- [x] Change_Ticket
- [x] Problem_Ticket
- [x] Problem_Problem
- [x] Change_Change

### PR DESCRIPTION
**Pull request by f2cmb**
This a rework on the declined previous PR : https://github.com/glpi-project/glpi/pull/22002

It fixes #21794 after creating a new branch based on up-to-date 11.0/bugfixes

Only PHPDoc annotations.

Got a doubt though on showFor* methods in `src/Change_Ticket.php` and `src/Change_Problem.php` : PHPStan accept ONLY `void|false` but adding a `return;` statement could be an option (`return` + `void` is rejected by PHPStan so i'm open to any suggestion on those cases).

### CODE REVIEW

**Comment by cedric-anne** [comment]
> Got a doubt though on showFor* methods

IMHO, you can replace `return false;` by `return;`. The return value of these methods is never used.

File: src/CommonITILRecurrent.php [hunk 1]
```diff
@@ -44,6 +44,7 @@
  */
 abstract class CommonITILRecurrent extends CommonDropdown
 {
+    /** @use Clonable<CommonITILRecurrent> */
```
Comment (trasher) [inline src/CommonITILRecurrent.php]:
```suggestion
    /** @use Clonable<static> */
```

**Comment by f2cmb** [comment]
Lint checks are broken ? Did the checks locally and no problems...

**Comment by trasher** [comment]
> Lint checks are broken ? Did the checks locally and no problems...

```
  curl error 28 while downloading https://repo.packagist.org/packages.json: R  
  ecv failure: Connection reset by peer  
```

There are network problems today with some services...  :/

**Review by froozeify — APPROVED** [review]

File: src/Change_Problem.php [hunk 2]
```diff
@@ -188,20 +189,22 @@ public static function showForProblem(Problem $problem)
                 'container'     => 'mass' . static::class . $rand,
             ],
         ]);
+
```
Comment (trasher) [inline src/Change_Problem.php]:
```suggestion
```

File: src/Change_Problem.php [hunk 3]
```diff
@@ -279,5 +282,6 @@ public static function showForChange(Change $change)
...
```
Comment (trasher) [inline src/Change_Problem.php]:
```suggestion
```

File: src/Problem_Ticket.php [hunk 4]
```diff
@@ -260,20 +261,22 @@ public static function showForProblem(Problem $problem)
                 'extraparams'      => ['problems_id' => $problem->getID()],
             ],
         ]);
+
```
Comment (trasher) [inline src/Problem_Ticket.php]:
```suggestion
```

File: src/Problem_Ticket.php [hunk 5]
```diff
@@ -331,6 +334,7 @@ public static function showForTicket(Ticket $ticket)
                 'container'     => 'mass' . static::class . $rand,
             ],
         ]);
+
```
Comment (trasher) [inline src/Problem_Ticket.php]:
```suggestion
```

**Review by trasher — APPROVED** [review]
Excepted useless changes (see comments), LGTM.

**Review by cedric-anne — APPROVED** [review]
