### PR TITLE
Check directory exist before creation; fix #21848

### LINKED ISSUE #21848: Picture upload fails if directory already exists
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0/bugfixes

### Bug description

I couldn't recreate the specific issue in #21841, but instead found:
```
[2025-11-07 00:10:08] glpi.CRITICAL:   *** Uncaught PHP Exception Safe\Exceptions\FilesystemException: "An error occurred" at FilesystemException.php line 9
  Backtrace :
  .../generated/Exceptions/FilesystemException.php:9 
  ...gmachine/safe/generated/8.4/filesystem.php:1241 Safe\Exceptions\FilesystemException::createFromPhpError()
  ./src/User.php:1072                                Safe\mkdir()
  ./src/CommonDBTM.php:1677                          User->prepareInputForUpdate()
  ./front/user.form.php:142                          CommonDBTM->update()
  ...Glpi/Controller/LegacyFileLoadController.php:64 require()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```
The use of the `Safe\mkdir` function throws an exception any time the PHP `mkdir` function returns false, which is expected when the directory already exists.

There may be other usages of `Safe\mkdir` that need checked.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

File: src/User.php [hunk 1]
```diff
@@ -1069,7 +1069,9 @@ public function prepareInputForUpdate($input)
                     $extension = strtolower(pathinfo($fullpath, PATHINFO_EXTENSION));
                     $extension = in_array($extension, ['png', 'gif']) ? 'png' : 'jpg';
 
-                    @mkdir(GLPI_PICTURE_DIR . "/$sub");
+                    if (!file_exists(GLPI_PICTURE_DIR . "/$sub"))  {
+                        @mkdir(GLPI_PICTURE_DIR . "/$sub");
```
Comment (trasher) [inline src/User.php]: Since we now rely on `Safe` lib; I guess this `@` is maybe no longer required... But I do not know why it's been added (present since the line has been added in e6d7f6d65b5b5f4b3a00806a17ad691f1960dd44).
I had first in mind to add a try/catch; but since the error is quite generic, I'm not sure it would be a good idea.

Comment (cedric-anne) [reply src/User.php]: IMHO, the `@` operator was present to prevent a warning to be emmited when the directory was already existing. We could remove it to have a clear warning in logs prior to the `Safe` exception that would probably give an imprecise error description.
```suggestion
                        mkdir(GLPI_PICTURE_DIR . "/$sub");
```
