### PR TITLE
Fix SQL errors when using "field=all" global search

### LINKED ISSUE #23132: Stored search leads to mysql error
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.5

### Bug description

Using the search `https://DOMAIN/front/project.php?is_deleted=0&as_map=0&browse=0&criteria[1][link]=AND&criteria[1][field]=all&criteria[1][searchtype]=contains&criteria[1][value]=file1` which was stored as link in a browser leads to

Image 
See 

[project_error.txt](https://github.com/user-attachments/files/25339680/project_error.txt)

The query used to work in glpi 10. 

Removing `&criteria[1][field]=all` ( making the link `https://DOMAIN/front/project.php?is_deleted=0&as_map=0&browse=0&criteria[1][link]=AND&criteria[1][searchtype]=contains&criteria[1][value]=file1` ) is leading to the expected result. 

Adding `&criteria[1][field]=all` into queries from other types also leads to unexpected results i.e `https://DOMAIN/front/ticket.php?criteria[1][link]=AND&criteria[1][field]=all` 

see [error_ticket.txt](https://github.com/user-attachments/files/25339504/error_ticket.txt)

### PR DESCRIPTION
**Pull request by f2cmb**
- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #23132 
- Here is a brief description of what this PR does

- **SQL syntax error** (`( OR ...`): search option section headers (no `table` key) caused `addWhere()` to return an empty string, prematurely flipping `$first2` and producing invalid SQL
- **Too many tables**: `all_search` flag was set even without a search value, triggering LEFT JOINs on all searchable tables and exceeding MariaDB's 61-table limit

- SQLProvider.php: skip entries without table key in the all/view loop + check `addWhere` returns a non-empty string before flipping `$first2`                                                  
- SearchEngine.php: only set `all_search = true` when the search value is non-empty

## Test plan

- Projects > search with field "All", value "test" > no SQL error
- Tickets > `criteria[1][field]=all` (no value) > no "too many tables" crash

### CODE REVIEW

File: tests/functional/SearchTest.php [hunk 1]
```diff
@@ -759,6 +759,89 @@ public function testViewCriterionNew(string $itemtype, array $criteria, int $exp
...
+            ],
+        ]);
+
+        $CFG_GLPI = $cfg_backup;
+
+        // SQL must not start with "( OR" (the original bug)
+        $this->assertDoesNotMatchRegularExpression(
+            '/\(\s*OR\s/',
+            $data['sql']['search']
+        );
```
Comment (cedric-anne) [inline tests/functional/SearchTest.php]: IMHO, this check is useless. A `MySQL query error xxx` exception is thrown when the query is invalid, so this piece of code will never be reached.

```suggestion
```

**Review by AdrienClairembault — APPROVED** [review]

**Review by cedric-anne — APPROVED** [review]
