### PR TITLE
Fix dropdown custom field search options

### LINKED ISSUE #21162: GLPI 11 - Error after creating asset definition view
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 11.0.0-rc5

### Bug description

After creating an asset definition and creating a view with a custom field on it I get the following error:

Error 500

### Relevant log output

```shell
[2025-09-26 10:01:34] glpi.CRITICAL:   *** Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("MySQL query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON), '$.\"2\"'))  WHERE (1) AND `glpi_assets_assets`.`is_deleted` = 0  AND ...' at line 2 (1064) in SQL query "SELECT DISTINCT `glpi_assets_assets`.`id` AS id, 'bmendes' AS currentuser,
                        `glpi_assets_assets`.`entities_id`, `glpi_assets_assets`.`is_recursive`, `glpi_assets_assets`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_1`, `glpi_assets_assets`.`id` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_1_id`, `glpi_assets_assettypes`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_4`, `glpi_assets_assetmodels`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_40`, `glpi_assets_assets`.`serial` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_5`, `glpi_manufacturers`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_23`, `glpi_states`.`completename` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_31`, `glpi_locations`.`completename` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_3`, `glpi_assets_assets`.`date_mod` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_19`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`name`, '$#$', `glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`id`) ORDER BY `glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`id` SEPARATOR '$$##$$') AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_45002` FROM `glpi_assets_assets`  LEFT JOIN `glpi_assets_assettypes` ON (`glpi_assets_assets`.`assets_assettypes_id` = `glpi_assets_assettypes`.`id`) LEFT JOIN `glpi_assets_assetmodels` ON (`glpi_assets_assets`.`assets_assetmodels_id` = `glpi_assets_assetmodels`.`id`)  LEFT JOIN `glpi_manufacturers` ON (`glpi_assets_assets`.`manufacturers_id` = `glpi_manufacturers`.`id`) LEFT JOIN `glpi_states` ON (`glpi_assets_assets`.`states_id` = `glpi_states`.`id`) LEFT JOIN `glpi_locations` ON (`glpi_assets_assets`.`locations_id` = `glpi_locations`.`id`)  LEFT JOIN `glpi_dropdowns_dropdowns` AS `glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929` ON (JSON_CONTAINS(`glpi_assets_assets`.`custom_fields`, CAST(`glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`id` AS JSON), '$.\"2\"'))  WHERE (1) AND `glpi_assets_assets`.`is_deleted` = 0  AND `glpi_assets_assets`.`is_template` = 0  AND (`glpi_assets_assets`.`assets_assetdefinitions_id` = '2') GROUP BY `glpi_assets_assets`.`id` LIMIT 0, 40".") in "pages/generic_list.html.twig" at line 37." at generic_list.html.twig line 37
  Backtrace :
  ./templates/pages/generic_list.html.twig:37
  ./vendor/twig/twig/src/Template.php:358            Twig\Template->yield()
  ./vendor/twig/twig/src/Template.php:373            Twig\Template->display()
  ./vendor/twig/twig/src/TemplateWrapper.php:51      Twig\Template->render()
  .../Glpi/Application/View/TemplateRenderer.php:170 Twig\TemplateWrapper->render()
  ./src/Glpi/Controller/AbstractController.php:68    Glpi\Application\View\TemplateRenderer->render()
  ./src/Glpi/Controller/GenericListController.php:51 Glpi\Controller\AbstractController->render()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\GenericListController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
  Previous: MySQL query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON), '$.\"2\"'))  WHERE (1) AND `glpi_assets_assets`.`is_deleted` = 0  AND ...' at line 2 (1064) in SQL query "SELECT DISTINCT `glpi_assets_assets`.`id` AS id, 'bmendes' AS currentuser,
                        `glpi_assets_assets`.`entities_id`, `glpi_assets_assets`.`is_recursive`, `glpi_assets_assets`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_1`, `glpi_assets_assets`.`id` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_1_id`, `glpi_assets_assettypes`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_4`, `glpi_assets_assetmodels`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_40`, `glpi_assets_assets`.`serial` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_5`, `glpi_manufacturers`.`name` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_23`, `glpi_states`.`completename` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_31`, `glpi_locations`.`completename` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_3`, `glpi_assets_assets`.`date_mod` AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_19`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`name`, '$#$', `glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`id`) ORDER BY `glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`id` SEPARATOR '$$##$$') AS `ITEM_Glpi\CustomAsset\NumeroMovelAsset_45002` FROM `glpi_assets_assets`  LEFT JOIN `glpi_assets_assettypes` ON (`glpi_assets_assets`.`assets_assettypes_id` = `glpi_assets_assettypes`.`id`) LEFT JOIN `glpi_assets_assetmodels` ON (`glpi_assets_assets`.`assets_assetmodels_id` = `glpi_assets_assetmodels`.`id`)  LEFT JOIN `glpi_manufacturers` ON (`glpi_assets_assets`.`manufacturers_id` = `glpi_manufacturers`.`id`) LEFT JOIN `glpi_states` ON (`glpi_assets_assets`.`states_id` = `glpi_states`.`id`) LEFT JOIN `glpi_locations` ON (`glpi_assets_assets`.`locations_id` = `glpi_locations`.`id`)  LEFT JOIN `glpi_dropdowns_dropdowns` AS `glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929` ON (JSON_CONTAINS(`glpi_assets_assets`.`custom_fields`, CAST(`glpi_dropdowns_dropdowns_custom_fields_22b71b877f8218e5eb326c37464b5929`.`id` AS JSON), '$.\"2\"'))  WHERE (1) AND `glpi_assets_assets`.`is_deleted` = 0  AND `glpi_assets_assets`.`is_template` = 0  AND (`glpi_assets_assets`.`assets_assetdefinitions_id` = '2') GROUP BY `glpi_assets_assets`.`id` LIMIT 0, 40".
  ./src/DBmysql.php:381
  ./src/Glpi/Search/Provider/SQLProvider.php:4910    DBmysql->doQuery()
  ./src/Glpi/Search/SearchEngine.php:654             Glpi\Search\Provider\SQLProvider::constructData()
  ./src/Glpi/Search/SearchEngine.php:669             Glpi\Search\SearchEngine::getData()
  ./src/Glpi/Search/SearchEngine.php:626             Glpi\Search\SearchEngine::showOutput()
  :                                                  Glpi\Search\SearchEngine::show()
  .../Application/View/Extension/PhpExtension.php:93 call_user_func_array()
  ...ates/d2/d2b37832bf51af0b62c74e19009d9f3a.php:55 Glpi\Application\View\Extension\PhpExtension->call()
  ./vendor/twig/twig/src/Template.php:402            __TwigTemplate_b40120a834b3391b61c2a12879a3687d->doDisplay()
  ./vendor/twig/twig/src/Template.php:358            Twig\Template->yield()
  ./vendor/twig/twig/src/Template.php:373            Twig\Template->display()
  ./vendor/twig/twig/src/TemplateWrapper.php:51      Twig\Template->render()
  .../Glpi/Application/View/TemplateRenderer.php:170 Twig\TemplateWrapper->render()
  ./src/Glpi/Controller/AbstractController.php:68    Glpi\Application\View\TemplateRenderer->render()
  ./src/Glpi/Controller/GenericListController.php:51 Glpi\Controller\AbstractController->render()
  ./vendor/symfony/http-kernel/HttpKernel.php:181    Glpi\Controller\GenericListController->__invoke()
  ./vendor/symfony/http-kernel/HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  ./vendor/symfony/http-kernel/Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  ./public/index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

Fixes #21162
Fix condition for dropdown custom field search option joins when multiple selection are allowed.
Fix usage of `glpi_assets_assets` table instead of `REFTABLE` in join conditions.
Add dropdown custom fields (single and multiple) to test dataset for automatic search tests to take them into account.

### CODE REVIEW

File: src/Glpi/Asset/CustomFieldType/DropdownType.php [hunk 1]
```diff
@@ -154,8 +154,8 @@ public function getSearchOption(): ?array
         } else {
             $opt['joinparams']['condition'] = [
                 QueryFunction::jsonContains([
-                    'glpi_assets_assets.custom_fields',
-                    QueryFunction::cast('NEWTABLE.id', 'JSON'),
```
Comment (cedric-anne) [inline src/Glpi/Asset/CustomFieldType/DropdownType.php:158]: Is this working in both MariaDB and MySQL ? Could you add a test case to validate that a search query using this search option works as expected on both of them ?

**Review by cedric-anne — DISMISSED** [review]

File: src/Glpi/Asset/CustomFieldType/DropdownType.php (hunk 1 above)
Comment (cedric-anne) [reply src/Glpi/Asset/CustomFieldType/DropdownType.php:158]: I had to put back this cast operation to prevent the following error on MySQL:
```
ySQL query error: Invalid data type for JSON data in argument 2 to function json_contains; a JSON string or JSON type is required. (3146)
```

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Tests are failing

**Comment by cconard96** [comment]
You cannot use CAST with JSON datatype. JSON is only a valid datatype in MySQL.

**Comment by cedric-anne** [comment]
> You cannot use CAST with JSON datatype. JSON is only a valid datatype in MySQL.

Indeed, there is something missing to make this code compatible with both MySQL and MariaDB.

**Comment by cconard96** [comment]
> > You cannot use CAST with JSON datatype. JSON is only a valid datatype in MySQL.
> 
> Indeed, there is something missing to make this code compatible with both MySQL and MariaDB.

The point of the QueryFunction class refactoring was to allow better compatibility between DBMS. Maybe calls to `cast` with JSON type should be transformed to a `JSON_EXTRACT` function when MariaDB is detected, if there is a way currently to detect that.

I don't know how useful I am going to be today. I haven't had much sleep.

**Review by trasher — APPROVED** [review]
