### PR TITLE
Restore LDAP replicate test

### LINKED ISSUE #23734: File ajax/ldap.php apparently missing from the repository
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Disable plugins

- [x] I reproduce the issue with all plugins disabled

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.6

### Bug description

After installing GLPI 11 in a test environment (pre-upgrade validation), testing an LDAP replica fails due to a call to a non-existent endpoint.
With debug enabled, I observed that the application attempts to send a POST request to the following endpoint:

/ajax/ldap.php

However, this file does not exist in the current installation. I also verified the official repository and could not find this file there either.

This suggests one of the following:

an incorrect or outdated endpoint is being called, or
the corresponding file has been removed without updating the related logic.

### Relevant log output

```shell
The requested item has not been found.
No route found for "POST https://glpi-11.comp.local/ajax/ldap.php" (from "https://glpi-11.comp.local/front/authldap.form.php?id=1")
In ./vendor/symfony/http-kernel/EventListener/RouterListener.php(127)
#0 ./vendor/symfony/event-dispatcher/EventDispatcher.php(260): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest()
#1 ./vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()
#2 ./vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#3 ./vendor/symfony/http-kernel/HttpKernel.php(157): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#4 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#5 ./vendor/symfony/http-kernel/Kernel.php(208): Symfony\Component\HttpKernel\HttpKernel->handle()
#6 ./public/index.php(71): Symfony\Component\HttpKernel\Kernel->handle()
#7 {main}

Previous: No routes found for "/ajax/ldap.php".
In ./vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php(70)
#0 ./vendor/symfony/routing/Matcher/UrlMatcher.php(98): Symfony\Component\Routing\Matcher\CompiledUrlMatcher->match()
#1 ./vendor/symfony/routing/Router.php(237): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest()
#2 ./vendor/symfony/http-kernel/EventListener/RouterListener.php(105): Symfony\Component\Routing\Router->matchRequest()
#3 ./vendor/symfony/event-dispatcher/EventDispatcher.php(260): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest()
#4 ./vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()
#5 ./vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#6 ./vendor/symfony/http-kernel/HttpKernel.php(157): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#7 ./vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#8 ./vendor/symfony/http-kernel/Kernel.php(208): Symfony\Component\HttpKernel\HttpKernel->handle()
#9 ./public/index.php(71): Symfony\Component\HttpKernel\Kernel->handle()
#10 {main}
```

### Page URL

/front/authldap.form.php?id=1

### Steps To reproduce

Install GLPI 11
Go to Setup > Authentication > LDAP directories
Configure a new LDAP directory
Navigate to the Replicates tab
Add a new replica
Click Test on the newly added replica (debug enabled will give you the missing endpoint information)

### Your GLPI setup information

<details><summary>
         GLPI information
      </summary><pre>
GLPI: 11.0.6 ( =&gt; /var/www/html/glpi-11/backend)
Installation mode: TARBALL
Current language: en_GB
Source Integrity: OK
</pre></details><details><summary>
         Server
      </summary><pre>
Operating system: Linux host-removed 6.8.0-106-generic #​106-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar  6 07:58:08 UTC 2026 x86_64

PHP: 8.2.30 apache2handler

PHP extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Setup: disable_functions=&quot;&quot; max_execution_time=&quot;300&quot; max_input_vars=&quot;1000&quot; memory_limit=&quot;256M&quot; post_max_size=&quot;50M&quot; session.cookie_secure=&quot;1&quot; session.cookie_httponly=&quot;1&quot; session.cookie_samesite=&quot;Lax&quot; session.save_handler=&quot;files&quot; upload_max_filesize=&quot;50M&quot; 

Web server: Apache/2.4.58 (Ubuntu) (Apache/2.4.58 (Ubuntu) Server at host Port 443)

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36

Database:
   
Server Software: Ubuntu 24.04
   
Server Version: 10.11.14-MariaDB-0ubuntu0.24.04.1-log
   
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
   
Parameters: glpi_11@host/glpi_11
   
Host info: host via TCP/IP

Requirements:
PHP version (8.2.30) is supported.
OS and PHP are relying on 64 bits integers.
Sessions configuration is OK.
Allocated memory is sufficient.
Following extensions are installed: dom, fileinfo, filter, libxml, simplexml, tokenizer, xmlreader, xmlwriter.
mysqli extension is installed
curl extension is installed
gd extension is installed
intl extension is installed
mbstring extension is installed
zlib extension is installed
bcmath extension is installed
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
openssl extension is installed
Database engine version (10.11.14) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi-11/backend/files/_cache has been validated.
Write access to /var/www/html/glpi-11/backend/files/_cron has been validated.
Write access to /var/www/html/glpi-11/backend/files has been validated.
Write access to /var/www/html/glpi-11/backend/files/_graphs has been validated.
Write access to /var/www/html/glpi-11/backend/files/_lock has been validated.
Write access to /var/www/html/glpi-11/backend/files/_pictures has been validated.
Write access to /var/www/html/glpi-11/backend/files/_plugins has been validated.
Write access to /var/www/html/glpi-11/backend/files/_rss has been validated.
Write access to /var/www/html/glpi-11/backend/files/_sessions has been validated.
Write access to /var/www/html/glpi-11/backend/files/_tmp has been validated.
Write access to /var/www/html/glpi-11/backend/files/_uploads has been validated.

Sessions configuration is secured.
exif extension is installed
ldap extension is installed
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed
Following extensions are installed: ctype, iconv, sodium.
Write access to /var/www/html/glpi-11/backend/marketplace has been validated.
Timezones seems loaded in database.
</pre></details><details><summary>
         GLPI constants
      </summary><pre>
GLPI_ROOT: &quot;/var/www/html/glpi-11/backend&quot;
GLPI_VERSION: &quot;11.0.6&quot;
GLPI_SCHEMA_VERSION: &quot;11.0.6@84160e91f70f353b33495a7928e5b1476d4b6d98&quot;
GLPI_FILES_VERSION: &quot;11.0.6-15c577a4&quot;
GLPI_MIN_PHP: &quot;8.2&quot;
GLPI_MAX_PHP: &quot;8.5&quot;
GLPI_YEAR: &quot;2026&quot;
GLPI_I18N_DIR: &quot;/var/www/html/glpi-11/backend/locales&quot;
GLPI_ENVIRONMENT_TYPE: &quot;production&quot;
GLPI_CONFIG_DIR: &quot;/var/www/html/glpi-11/backend/config&quot;
GLPI_VAR_DIR: &quot;/var/www/html/glpi-11/backend/files&quot;
GLPI_MARKETPLACE_DIR: &quot;/var/www/html/glpi-11/backend/marketplace&quot;
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: [&quot;~^\n                        (http|https|feed)://                                                # protocol\n                        (\n                            (?:\n                                (?:xn--[a-z0-9-]++\\.)*+xn--[a-z0-9-]++                      # a domain name using punycode\n                                    |\n                                (?:[\\pL\\pN\\pS\\pM\\-\\_]++\\.)+[\\pL\\pN\\pM]++                    # a multi-level domain name\n                                    |\n                                [a-z0-9\\-\\_]++                                              # a single-level domain name\n                            )\\.?\n                                |                                                           # or\n                            \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}                              # an IP address\n                                |                                                           # or\n                            \\[\n                                (?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::))))\n                            \\]                                                              # an IPv6 address\n                        )\n                        (?:/ (?:[\\pL\\pN\\pS\\pM\\-._\\~!$&amp;&#39;()*+,;=:@]|%[0-9A-Fa-f]{2})* )*     # a path\n                        (?:\\? (?:[\\pL\\pN\\-._\\~!$&amp;&#39;\\[\\]()*+,;=:@/?]|%[0-9A-Fa-f]{2})* )?    # a query (optional)\n                    $~ixuD&quot;]
GLPI_DISALLOWED_UPLOADS_PATTERN: &quot;/\\.(php\\d*|phar)$/i&quot;
GLPI_TELEMETRY_URI: &quot;https://telemetry.glpi-project.org&quot;
GLPI_INSTALL_MODE: &quot;TARBALL&quot;
GLPI_NETWORK_MAIL: &quot;glpi@teclib.com&quot;
GLPI_NETWORK_SERVICES: &quot;https://services.glpi-network.com&quot;
GLPI_MARKETPLACE_ENABLE: 3
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: &quot;&quot;
GLPI_DOCUMENTATION_ROOT_URL: &quot;https://links.glpi-project.org&quot;
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: &quot;1&quot;
GLPI_LOG_LVL: &quot;warning&quot;
GLPI_SKIP_UPDATES: false
GLPI_STRICT_ENV: false
GLPI_AJAX_DASHBOARD: &quot;1&quot;
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_CENTRAL_WARNINGS: &quot;1&quot;
GLPI_SYSTEM_CRON: false
GLPI_TEXT_MAXSIZE: &quot;4000&quot;
GLPI_WEBHOOK_ALLOW_RESPONSE_SAVING: &quot;0&quot;
GLPI_WEBHOOK_CRA_MANDATORY: false
GLPI_ALTCHA_MODE: &quot;interactive&quot;
GLPI_ALTCHA_MAX_NUMBER: 50000
GLPI_ALTCHA_EXPIRATION_INTERVAL: &quot;PT20M&quot;
GLPI_DOC_DIR: &quot;/var/www/html/glpi-11/backend/files&quot;
GLPI_CACHE_DIR: &quot;/var/www/html/glpi-11/backend/files/_cache&quot;
GLPI_CRON_DIR: &quot;/var/www/html/glpi-11/backend/files/_cron&quot;
GLPI_GRAPH_DIR: &quot;/var/www/html/glpi-11/backend/files/_graphs&quot;
GLPI_LOCAL_I18N_DIR: &quot;/var/www/html/glpi-11/backend/files/_locales&quot;
GLPI_LOCK_DIR: &quot;/var/www/html/glpi-11/backend/files/_lock&quot;
GLPI_LOG_DIR: &quot;/var/www/html/glpi-11/backend/files/_log&quot;
GLPI_PICTURE_DIR: &quot;/var/www/html/glpi-11/backend/files/_pictures&quot;
GLPI_PLUGIN_DOC_DIR: &quot;/var/www/html/glpi-11/backend/files/_plugins&quot;
GLPI_RSS_DIR: &quot;/var/www/html/glpi-11/backend/files/_rss&quot;
GLPI_SESSION_DIR: &quot;/var/www/html/glpi-11/backend/files/_sessions&quot;
GLPI_TMP_DIR: &quot;/var/www/html/glpi-11/backend/files/_tmp&quot;
GLPI_UPLOAD_DIR: &quot;/var/www/html/glpi-11/backend/files/_uploads&quot;
GLPI_INVENTORY_DIR: &quot;/var/www/html/glpi-11/backend/files/_inventories&quot;
GLPI_THEMES_DIR: &quot;/var/www/html/glpi-11/backend/files/_themes&quot;
GLPI_PLUGINS_DIRECTORIES: [&quot;/var/www/html/glpi-11/backend/marketplace&quot;,&quot;/var/www/html/glpi-11/backend/plugins&quot;]
GLPI_NETWORK_API_URL: &quot;https://services.glpi-network.com/api&quot;
GLPI_NETWORK_REGISTRATION_API_URL: &quot;https://services.glpi-network.com/api/registration/&quot;
GLPI_MARKETPLACE_PLUGINS_API_URI: &quot;https://services.glpi-network.com/api/marketplace/&quot;
</pre></details><details><summary>
         LDAP directories
      </summary><pre>
Server: &#39;dc.comp.local&#39;, 
	Port: &#39;389&#39;, 
	BaseDN: &#39;dc=comp,dc=local&#39;, 
	Connection filter:  removed
	RootDN: &#39;ad@comp.local&#39;, 
	Use TLS: none
</pre></details><details><summary>
         SQL replicas
      </summary><pre>
Not active
</pre></details><details><summary>
         Notifications
      </summary><pre>
Way of sending emails: PHP
</pre></details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

fixes #23734
The test was originally handled by the front script. My Twig rework of Auth code was supposed to move it to an AJAX script, but this file was missing from the pull request. This PR reimplements it in a controller.

### CODE REVIEW

**Review by trasher — APPROVED** [review]

File: src/Glpi/Controller/Config/LDAPController.php [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+    #[Route(
+        "/AuthLDAP/{authldaps_id}/Replica/{authldapreplicates_id}/Test",
+        name: "authldap_replica_status",
+        requirements: [
+            'authldaps_id' => '\d+',
+            'authldapreplicates_id' => '\d+',
+        ],
+        methods: ['POST'],
+    )]
+    public function testReplica(Request $request): Response
```
Comment (cedric-anne) [inline src/Glpi/Controller/Config/LDAPController.php:57]: IMHO, this endpoint should not be accessible to everyone. Rights checks should be added.

**Review by cedric-anne — CHANGES_REQUESTED** [review]

**Review by AdrienClairembault — APPROVED** [review]

**Review by AdrienClairembault — DISMISSED** [review]
See @cedric-anne comments.

**Review by cedric-anne — APPROVED** [review]
