### PR TITLE
Hide inactive suppliers in actor list

### LINKED ISSUE #19968: An inactive supplier is still present in "assigned to" dropdown
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

In GLPI when a supplier is set to inactive, it still appears in the dropdown list when assigning a supplier to a ticket.

Ideally, inactive suppliers should be excluded from selection to retain their history without being assigned to new tickets.

### Relevant log output

```shell

```

### Page URL

_No response_

### Steps To reproduce

1. Set Active = No in a supplier (Management > Supplier)
2. Select "assigned to" dropdown in a ticket
3. The inactive supplier is still visible and selectable

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cconard96**
## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Description

Fixes #19968

### CODE REVIEW

File: phpunit/functional/DropdownTest.php [hunk 1]
```diff
@@ -2038,4 +2038,44 @@ public function testFilterDisplayWithLoggedIn(): void
...
+            'is_recursive' => 1,
+        ]);
+        $inactive_supplier = $this->createItem('Supplier', [
+            'name' => __FUNCTION__ . '_inactive',
+            'is_active' => 0,
+            'entities_id' => $this->getTestRootEntity(true),
+            'is_recursive' => 1,
+        ]);
+        $params = [
+            'itemtype' => 'Ticket',
```
Comment (SebSept) [inline phpunit/functional/DropdownTest.php]: you can use Ticket::class instead of 'Ticket'

File: src/Dropdown.php [hunk 2]
```diff
@@ -4254,16 +4254,19 @@ public static function getDropdownActors($post, $json = true)
...
                 'searchText'          => $post['searchText'],
                 'entity_restrict'     => $entity_restrict,
-            ], false);
+                'condition'           => [],
+            ];
+            if (!$post['inactive_deleted']) {
+                $supplier_params['condition'] = static::addNewCondition(['is_active' => 1]);
+            }
+            // Bypass checks, idor token validation has already been made earlier in method
+            $supplier_idor = Session::getNewIDORToken('Supplier', ['entity_restrict' => $entity_restrict, 'condition' => $supplier_params['condition']]);
```
Comment (SebSept) [inline src/Dropdown.php]: same remark, use ::class constant

**Comment by trasher** [comment]
Tests are failing

File: src/Dropdown.php (hunk 2 above)
Comment (trasher) [inline src/Dropdown.php]:
```suggestion
            $supplier_idor = Session::getNewIDORToken(\Supplier::class, ['entity_restrict' => $entity_restrict, 'condition' => $supplier_params['condition']]);
```

File: src/Dropdown.php [hunk 3]
```diff
@@ -4254,16 +4254,19 @@ public static function getDropdownActors($post, $json = true)
             && !$template->isHiddenField("_suppliers_id_{$post['actortype']}")
             && in_array('Supplier', $post['returned_itemtypes'])
         ) {
-            // Bypass checks, idor token validation has already been made earlier in method
-            $supplier_idor = Session::getNewIDORToken('Supplier', ['entity_restrict' => $entity_restrict]);
-
-            $suppliers    = Dropdown::getDropdownValue([
+            $supplier_params = [
                 'itemtype'            => 'Supplier',
```
Comment (trasher) [inline src/Dropdown.php]:
```suggestion
                'itemtype'            => \Supplier::class,
```

File: src/Dropdown.php [hunk 4]
```diff
@@ -4254,16 +4254,19 @@ public static function getDropdownActors($post, $json = true)
             && !$template->isHiddenField("_suppliers_id_{$post['actortype']}")
             && in_array('Supplier', $post['returned_itemtypes'])
```
Comment (trasher) [inline src/Dropdown.php]:
```suggestion
            && in_array(\Supplier::class, $post['returned_itemtypes'])
```

**Review by SebSept — APPROVED** [review]
